tinymce/tinymce-docs

advanced-development-topics/index.md, editor-configuration-settings/advanced-editing-behaviors.md, editor-configuration-settings/content-appearance.md, editor-configuration-settings/content-filtering.md, editor-configuration-settings/editor-appearance.md, editor-configuration-settings/file-and-image-upload.md, editor-configuration-settings/index.md, editor-configuration-settings/integration-and-setup.md, editor-configuration-settings/internationalization.md, editor-configuration-settings/spelling.md, editor-configuration-settings/url-handling.md, getting-started/advanced-installation-options.md, getting-started/basic-configuration.md, getting-started/content-filtering.md, getting-started/getting-support.md, getting-started/image-uploading.md, getting-started/spell-checking-in-tinymce.md, getting-started/system-requirements.md, getting-started/themes-and-ui-customizations.md, getting-started/tinymce-in-your-language.md, getting-started/using-tinymce-inline.md, getting-started/working-with-plugins.md, integrations/index.md, plugins/index.md
Added content to meta description.
=> Getting started updates

_includes/install/bower.md, _includes/install/cdn.md, _includes/install/composer.md, _includes/install/custom.md, _includes/install/jquery.md, _includes/install/npm.md, _includes/install/nuget.md, _includes/install/sdk.md, getting-started/advanced-installation-options.md, getting-started/spell-checking-in-tinymce.md, getting-started/working-with-plugins.md, plugins/spell-checker.md
@kilianc 
* Updates to the getting started, spell checking page. While you're at it, please take a look at the page content. Thanks.
* Updates to _include install pages.
=> More getting started

_includes/configuration/directionality.md, _includes/configuration/language.md, _includes/install/bower.md, _includes/install/cdn.md, _includes/install/composer.md, _includes/install/custom.md, _includes/install/jquery.md, _includes/install/npm.md, _includes/install/nuget.md, _includes/install/sdk.md, getting-started/advanced-installation-options.md, getting-started/spell-checking-in-tinymce.md, getting-started/tinymce-in-your-language.md, getting-started/working-with-plugins.md
@kilianc content updates:
* added new content to directionality section in getting started
* added new content to spellcheckig section in getting started
* content updates to other getting started sections
* fixed title capitalization and removed code formatting from titles in all install pages
=> Still getting started

getting-started/getting-support.md, plugins/code-sample.md, plugins/moxiemanager.md, plugins/noneditable.md, plugins/powerpaste.md, plugins/spell-checker-pro.md
Added some info that I am aware of for 4.3.
Added information regarding premium features.
=> Premium features & 4.3 update

_data/nav.yml, advanced-development-topics/contributing-to-open-source.md, changelog.md
=> Added changelog

_includes/feedback.html, _layouts/default.html, _plugins/url_encode.rb
please @androb or @r12s merge :beers:
=> added github feedback snippet

_includes/configuration/formats.md, _includes/install/bower.md, _includes/install/cdn.md, _includes/install/composer.md, _includes/install/custom.md, _includes/install/jquery.md, _includes/install/npm.md, _includes/install/nuget.md, _includes/install/sdk.md, configure/content-filtering.md, configure/file-image-upload.md, configure/index.md, get-started/advanced-install.md, get-started/basic-setup.md, get-started/customize-ui.md, get-started/filter-content.md, get-started/first-steps.md, get-started/get-support.md, get-started/localize-your-language.md, get-started/spell-checking.md, get-started/system-requirements.md, get-started/upload-images.md, get-started/use-tinymce-inline.md, get-started/work-with-plugins.md
Updates and corrections to Get Started guide section.
=> Getting started edits

_layouts/default.html
please @androb or @r12s merge ;)
=> added contribute link to every page

_includes/top-menu.html
=> top-menu fixes

get-started/advanced-install.md, get-started/basic-setup.md, get-started/customize-ui.md, get-started/filter-content.md, get-started/first-steps.md, get-started/localize-your-language.md, get-started/spell-checking.md, get-started/system-requirements.md, get-started/upload-images.md, get-started/use-tinymce-inline.md, get-started/work-with-plugins.md
* Add new content to filter-content.md in Get Started guide
* Fix capitalization of next steps titles in Get Started guide
=> Filter content page

_includes/configuration/browser-spellcheck.md, advanced-development-topics/handling_asynchronous_image_uploads.md, changelog.md, enterprise/check-spelling/index.md, enterprise/check-spelling/server.md, enterprise/check-spelling/troubleshoot.md, enterprise/system-requirements.md, get-started/basic-setup.md, get-started/first-steps.md, get-started/spell-checking.md, get-started/upload-images.md, plugins/spellchecker.md, plugins/tinymcespellchecker.md
Spell check should be one word, it now is.
=> Fixed spellcheck typos

get-started/localize-your-language.md, get-started/work-with-plugins.md
Some instances of the old naming persisted. Fixed.
=> Change Getting Started to Get Started

_data/nav.yml, advanced-development-topics/index.md, configure/index.md, enterprise/index.md, integrations/index.md, plugins/index.md, view-examples/common-setup.md, view-examples/custom-toolbar-button.md, view-examples/custom-toolbar-listbox.md, view-examples/format-custom.md, view-examples/format-html5.md, view-examples/full-featured.md, view-examples/image-tools.md, view-examples/index.md, view-examples/inline.md, view-examples/url-conversion.md, view-examples/valid-elements.md
@kilianc @androb this update adds a new nav.yml item "Try TinyMCE", where we will put the example content from http://www.tinymce.com/tryit/
It changes the nav structure and the arrays in index.md
=> Create view examples

plugins/lists.md
* keyword meta is space separated ...
=> remove commas from keywords plugins/lists.md

_data/nav.yml, integrations/angularjs.md, integrations/knockout.md, integrations/react.md
They still need to be expanded.
=> Added VERY basic AngularJS, Knockout and React articles.

get-started/get-support.md
It is appropriate to mention Premium Support here with a link for more
info.
=> Closes #43

get-started/upload-images.md
Adds link to PowerPaste plugin
=> Link to PowerPaste

_data/nav.yml, demo/whats-new.md
* url previously new-in-4v3, now whats-new (much more flexi)
=> rename example url demo/whats-new example for future use

_data/nav.yml, _includes/configuration/toolbar-n.md, _includes/configuration/toolbar.md, _includes/nav.html, _includes/search-db.json, _plugins/anchor.rb
let's wait for stage build to come up and test it before merging it
=> changed toolbar<n> to toolbar(n)

_config.yml, _includes/install/cdn.md, get-started/basic-setup.md, get-started/first-steps.md, get-started/multiple-editors.md, get-started/use-tinymce-inline.md, get-started/work-with-plugins.md
=> updated and parameterized cdn url

_data/nav.yml, _includes/configuration/images-dataimg-filter.md, configure/file-image-upload.md
Added docs on the image-dataimg-filter config option. So could you @kilianc review that I did everything correctly when I added this option.
=> added images-dataimg-filter config option

README.md, _config-local.sample.yml, _layouts/default.html, _plugins/include_remote.rb, init.sh, serve.sh
@r12s this should also address some of your concerns about contribution bootstrapping and setup
=> Refactor init scripts

_includes/install/bower.md, _includes/install/cdn.md, _includes/install/composer.md, _includes/install/jquery.md, _includes/install/npm.md, _includes/install/nuget.md, _includes/install/sdk.md, advanced/creating-a-plugin.md, advanced/using-the-gzip-compressors.md, get-started/basic-setup.md, get-started/first-steps.md, get-started/localize-your-language.md, get-started/multiple-editors.md, get-started/use-tinymce-inline.md, get-started/work-with-plugins.md, plugins/compat3x.md
* revert incorrect single quote in html to double quote
* fix excessive indentation in snippets
* add "type" to html script tags where it met section style
=> revert incorrect single quote in html to double quote

_config.yml, _scripts/s3-cleanup.sh, wercker.yml
This will cleanup deleted PR branches from S3 on every deploy
=> cleanup old branches from s3 bucket

plugins/noneditable.md
Added some improvements to the docs to fix #232
=> Improved the noneditable_regexp option docs

_data/nav.yml, _includes/configuration/menu.md, _includes/configuration/toolbar.md, advanced/editor-control-identifiers.md
Re-added the control ids page and restructured it a bit also added references to it here and there.
=> Added control identifiers.

get-started/upload-images.md
Fix link for PHP Upload Handler on getting started / upload images page
=> Fix link for PHP Upload Handler on getting started / upload images page

advanced/editor-control-identifiers.md
We had a complain on the NPS survey about not being able to find any results for "superscript". Thought we could at least add some keywords here. Much more to be done to improve search!
=> Added toolbar and menu controls to keyword list.

advanced/editor-command-identifiers.md
=> Added command identifiers to keywords

_layouts/default.html
+ replaced compromised fonts.com public key with new key
=> update _layouts/default.html with new fonts.com key

_data/nav.yml, enterprise/server.md, plugins/imagetools.md, plugins/tinymcespellchecker.md
This PR documents the upcoming image proxy service included with TinyMCE Enterprise.
=> Image proxy

demo/whats-new.md
+ blog link pointed to generic url, not specific article
=> update blog link, points to correct url

advanced/editor-control-identifiers.md, plugins/mentions.md
will impact the current block level element
=> Blockquote effect

advanced/accessibility.md
=> Correct spelling

_includes/configuration/file-browser-callback.md
=> duplicate of word 'browser'

demo/full-featured.md, enterprise/paste-from-word.md
+ clarified the "full featured" demo to note that it doesn't include premium plugins
+ add missing content to enterprise/paste-from-word.md
=> fixed various typos and missing content

enterprise/server.md
Edited server types to include WebSphere, and added contact info for
additional Java application server support.
=> Changes to server.md adding Websphere server type

_data/nav.yml, advanced/index.md, configure/index.md, demo/index.md, enterprise/index.md, get-started-cloud/first-steps.md, get-started-cloud/index.md, get-started/index.md, integrations/index.md, plugins/index.md, themes/index.md
+ adds TinyMCE Cloud page, folder and nav structure
=> add TinyMCE Cloud page

get-started-cloud/index.md
+ minor update to cloud sdk webcopy
=> update cloud copy

plugins/moxiemanager.md
The description of MoxieManager pricing needed updating.
=> Update re pricing

enterprise/advcode.md, plugins/advcode.md
+ adds note to enterprise/advcode.md
+ adds note to plugins/advance.md
=> adds note that advcode is a premium plugin

.gitignore, plugins/spellchecker.md
=> fix spellchecker codesample

_includes/configuration/preview-styles.md
=> TINY-750: improve preview styles documentation

integrations/angularjs.md
=> fix #426, replace bower install --save-dev by --save

enterprise/server.md
We've not only improved how developers can specify their trusted domains, but this new process also resolves issues we've seen with TLS.
=> TLS Config Change

advanced/events.md
"that causes and undo" -> "that cause an undo"
=> Corrects typo

enterprise/advcode.md, get-started-cloud/editor-and-features.md, get-started-cloud/editor-plugin-version.md, get-started-cloud/features-only.md, get-started-cloud/plugin-editor-version-compatibility.md, plugins/advcode.md
[+] fixes typos for style in new Cloud docs
[+] fixes inconsistent naming of Advanced Code Editor
=> fixes typos for style in new Cloud docs, Advanced Code Editor 

advanced/cdn-details.md, enterprise/advcode.md, get-started-cloud/plugin-editor-version-compatibility.md, plugins/advcode.md
[+] fix Advanced Code naming issue in versions table
[+] update Advanced Code Editor page meta
[+] 	minor edits to advanced/cdn-details.md
=> content updates to Advanced Code Editor, CDN details

integrations/angular2.md, integrations/angularjs.md, integrations/bootstrap.md, integrations/dojo.md, integrations/jquery.md, integrations/knockout.md, integrations/rails.md, integrations/react.md, integrations/wordpress.md
[+] added a notice to the integrations docs to advise the reader to contact 3rd parties, or to sign up for the Community, for help with the integration
=> updates integrations pages to reference 3rd parties

advanced/usage-with-module-loaders.md
Addresses https://github.com/tinymce/tinymce/issues/3412
=> Document compatible uglify-js usage

get-started/basic-setup.md
=> Missing comma

get-started-cloud/editor-and-features.md, get-started-cloud/editor-plugin-version.md, get-started-cloud/features-only.md, get-started-cloud/plugin-editor-version-compatibility.md
Ensuring the Cloud documentation references the Enhanced Media Embed and Link Checker documentation.
=> Media / linkcheck for cloud

advanced/creating-custom-dialogs.md
=> minor typo

enterprise/embed-media/index.md, plugins/linkchecker.md, plugins/mediaembed.md
[+] fix a few minor typos
[+] started to remove “Enterprise” references, replace with premium plugin and subscription messaging
=> update content in Enhanced Media Embed and Link Checker

enterprise/index.md, integrations/wordpress.md
We are phasing out use of term "enterprise" in favor of premium features.
=> Change of title to Enterprise section

_config.yml, _data/nav.yml, _includes/install/cloud.md, advanced/cdn-details.md, demo/full-featured.md, get-started-cloud/editor-and-features.md, get-started/advanced-install.md, get-started/first-steps.md, get-started/work-with-plugins.md, integrations/react.md
[+] changes to various docs pages removing mention of CDN and replacing with TinyMCE Cloud
=> documentation changes for TinyMCE cloud transition

README.md
[+] corrects a minor structuring issue in the README
=> minor correction to README

get-started-cloud/editor-and-features.md
Also made heading a bit clearer
=> Fixed capitalization of PowerPaste

get-started-cloud/editor-and-features.md, get-started-cloud/features-only.md
Documentation changes to remind the user to configure forward proxies if using TinyMCE cloud.
=> Added doco for forward proxy considerations for TinyMCE cloud

plugins/codesample.md
[+] minor refresh to Code Sample plugin content. Removes ref to v4.3. Moves snippet above the fold.
=> minor update to plugins/codesample.md

enterprise/server/index.md
Documentation for new capability of adding wildcards in the allowed-origins settings.
=> Wildcard origins

plugins/image.md
[+] minor content restucture to the Image Plugin
=> restructure plugins/image.md

_data/nav.yml, demo/whats-new.md, get-started-cloud/index.md, get-started/index.md, plugins/imagetools.md
[+] minor updates improving docs
=> miscellaneous updates fixes what's new demo, nav ordering

get-started/work-with-plugins.md, plugins/charmap.md
[+] fixes snippet error in get-started/work-with-plugins
[+] minor text update to plugins/charmap.md
=> merge to master, fixes snippet error in get started

enterprise/paste-from-word.md, plugins/powerpaste.md
[+] fixes requirement to improve quality of content on PowerPaste marketing page in docs; adds links to Ephox store.
[+] updates purchase info on PowerPaste plugin page.
=> fix #538 PowerPaste marketing page

advanced/security.md
Added docs on how to enabled content security policy in 4.6.2.
=> added csp docs

demo/custom-toolbar-listbox.md
[+] fixes broken link from the custom listbox demo to the listbox API page, looks like the url path/s may have changed
=> fixes broken link to listbox api page

get-started-cloud/index.md
[+] remove the 5 minute promise
=> minor update to index page web copy

get-started-cloud/index.md
[+] minor webcopy change to make Cloud get started consistent with SDK
=> webcopy update to Cloud get started

plugins/a11ychecker.md, plugins/mediaembed.md, plugins/powerpaste.md
[+] minor updates to init statement quotes, adds missing closing semicolon to snippet, blog link update
=> minor updates for consistency

enterprise/check-spelling/custom.md, enterprise/check-spelling/index.md
[+] remove tabs from index table indentation
[+] remove hard returns from text
=> misc cleanup to custom dictionaries

_includes/configuration/allow-html-in-named-anchor.md
removing the "// confirmation required" text from the default value line.
=> Removed confirmation required text from the default value

changelog.md
[+] add links to relevant docs content
=> tidy 4.6.5 release changelog

changelog.md
[+] fix incorrectly formated markdown
=> fix broken link in changelog

_includes/configuration/inline-boundaries-selector.md
[+] minor fomatting update, adds backticks to several elements
=> minor update to style in inline_boundary_selector

plugins/powerpaste.md
Added to the sample code for paste_postprocess to show what you can do to modify the content.
=> Added code to postprocess example to clairfy usage

demo/full-featured.md
Adds premium features so we "lead with" the best
=> Update to fully featured example

_includes/configuration/language-url.md, _includes/install/custom.md, _includes/install/jquery.md, _includes/install/sdk.md, advanced/creating-a-plugin.md, enterprise/check-links.md, enterprise/check-spelling/index.md, enterprise/embed-media/index.md, enterprise/paste-from-word.md, enterprise/server/index.md, get-started-cloud/editor-and-features.md, get-started-cloud/editor-plugin-version.md, get-started/advanced-install.md, get-started/get-support.md, get-started/index.md, get-started/localize-your-language.md, get-started/spell-checking.md, integrations/wordpress.md, plugins/a11ychecker.md, plugins/image.md, plugins/imagetools.md, plugins/link.md, plugins/linkchecker.md, plugins/mediaembed.md, plugins/mentions.md, plugins/powerpaste.md, plugins/tinymcespellchecker.md
[+] replaces relevant webcopy instances of SDK with Self-hosted
[+] fixes minor typos, urls
=> update SDK to self-hosted, fixes typos, improve readability

mobile.md
[+] fixes link broken when url of mobile demo page changed
=> fix link to mobile demo page

mobile.md
[+] improve clarity of mobile webcopy
=> Mobile docs webcopy update

mobile.md
[+] page description now consistent with mobile beta messaging
=> update page description mobile.md

mobile.md
[+] adds https protocol to quick start snippet
=> add protocol to cloud snippet

mobile.md
[+] adds browser versioning to the mobile docs
[+] mobile is out of beta, removes these references
=> Mobile versioning

changelog.md
[+] adds links in the changelog to referenced docs
=> changelog adds internal ref links

demo/whats-new.md
[+] adds the new 4.7 Codepen to the What’s New demo
=> update what’s new demo

plugins/link.md
=> Added some missing commas in example codes of link plugin

_data/nav.yml, _includes/configuration/browser-spellcheck.md, _includes/configuration/spell-checker-pro.md, _includes/nav.html, configure/spelling.md
I figure that anyone who ends up in the Spelling config of our docco really should be told about our pro spell checker.
=> Feature Spell Checker Pro in Spelling configuration

advanced/keyboard-shortcuts.md
[+] adds link to Ryan Pollard’s post on the TinyMCE blog explaining how to create custom keyboard shortcuts
=> add link to custom shortcuts blog post

get-started/system-requirements.md
Added text to clarify our support position as browser's update their major versions over time.
=> Add statement on how long we support each browser major version

plugins/contextmenu.md
and its impact on TinyMCE.  This change was made at Tim's request and the text has been reviewed by Tim.
=> Added more explanation to the contextmenu configuration option

plugins/mentions.md
Per a request from Tim to improve this part of the documentation.
=> Improved example code for mentions_fetch

demo/custom-toolbar-menu-button.md, demo/custom-toolbar-split-button.md
[+] minor update to custom toolbars text
=> update custom toolbar text

advanced/usage-with-module-loaders.md
[+] add site.baseurl to link pointing to configure/editor-appearance/#skin_url
=> fix link in useage-with-module-loaders.md

_includes/configuration/custom-ui-selector.md
=> fix typo in custom_ui_selector.ms

mobile.md
[+] removes hyphen from any instances of rich-text
=> remove hyphen from rich-text

plugins/powerpaste.md
needed clarification based on a support ticket where this was brought up.
=> added note around Excel online not working with PowerPaste

integrations/angular2.md, integrations/angularjs.md
Modify the names for Angular 1 and Angular 2+ based on feedback from Tim and a confused prospect.
=> clarify angular version numbers

get-started-cloud/editor-and-features.md, get-started-cloud/editor-plugin-version.md
[+] clarifies that Image Tools is not a premium plugin
[+] minor fixes for clarity in Cloud editor versions doc
=> minor updates to Cloud Get Started

plugins/mentions.md
The current documentation is not clear on that requirement.
=> added note to clarify all values in mentions fetch user object are Strings

get-started-cloud/editor-plugin-version.md
[+] removes an unnecessary hard return in a code snippet
=> hotfix for nav refresh

changelog.md
[+] adds code style to latest release notes in changelog
=> minor style update to changelog

.gitignore, get-started-cloud/editor-and-features.md
Please review the changes in Step 3.
=> Add line space before Note in Step 3

get-started-cloud/editor-and-features.md
Please review the line space in Step 3 bullet points.
=> Fix the line space

get-started-cloud/editor-and-features.md
=> Fix spaces after admonitions, add appropraite admonition wherever necessary

advanced/events.md
Hi Mike,
I've made the changes to the ExecCommand section as per the request in https://ephocks.atlassian.net/browse/DX-535.
Please review the changes.
Regards,
Shikha
=> DX-535-Update the example in ExecCommand

enterprise/system-requirements.md
https://ephocks.atlassian.net/browse/DOC-46. Updated https://www.tinymce.com/docs/enterprise/system-requirements/#supportedtinymceversions. Please review.
Regards,
Shikha
=> Add new branch DOC-46

README.md, _scripts/api-reference-local.sh
This makes it easier to generate api docs from local files. Updated the readme so that the apollo team can generate docs locally.
=> fixed local api reference and updated readme.md

plugins/tinydrive.md
Just some extra details on why bulk copy isn't available requested by Tim T.
=> TINY-1839: added details of copy limitations

enterprise/moxiemanager.md, index.md, plugins/drive.md, quick-start.md
Added link regarding storage and bandwidth quotas.
=> Drive doc update re pricing

wercker.yml
DX-895 branch deployment configuration
=> DX-895 branch deployment configuration

wercker.yml
!note: don't merge until CI reconfigured
=> DX-929 add cache invalidation to deployment pipeline

advanced/cdn-details.md, ui-elements/contextmenu.md, ui-elements/contexttoolbar.md, ui-elements/dialog.md
Hi Ryan,
Please review.
Regards,
Shikha
=> DX-985/fix broken links

advanced/accessibility.md, advanced/security.md, advanced/usage-with-module-loaders.md, advanced/yeoman-generator.md
Hi Andrew,
This is the kind of line edits I will be performing to start with. Please review and if acceptable, then I will proceed doing some of this every day.
cheers,
Mike
=> Review edits

configure/editor-appearance.md
Hi Andy,
I have made the change requested in [DOC-131](https://ephocks.atlassian.net/browse/DOC-131). Please review.
Regards,
Shikha
=> Remove fixed-toolbar-container

_includes/codepens/custom-toolbar-menu-button/index.js, _includes/codepens/toolbar-button/index.js
We currently don't have any docs I could find that document the different menu items (which matches our discussion today). So for now I've just updated any thing that currently exists, which appears to only be the codepen examples.
Note: This JIRA is still on review, so we should hold off merging for now.
=> TINY-2230: Updated codepen examples for the new nested menu items type

_includes/codepens/codesample/index.html
The codepen wasn't rendering because the last paragraph wasn't being closed correctly.
=> DOC-201: Fixed the codesample codepen

configure/jwt-authentication.md, plugins/drive.md
Updated docs for custom root paths and image max size for drive.
=> TINY-1903: added docs on custom roots for drive

_config.yml
Updated the tinymce url for the codepens, to use the new cloud service for tinymce 5
=> Update TinyMCE codepen url for beta

_includes/release-notes/deleted.md, migration-from-4x.md
Hi Lee,
Please review the doc changes corresponding to https://ephocks.atlassian.net/browse/DOC-194.
Regards,
Shikha
=> Add removed feature 'insert'

_includes/release-notes/new-features.md
I've added a little summary on Permanent Pen, format Painter and Page Embed with an expected date of availability. Please review.
Regards,
Shikha
=> Add prem plugin to Rel Notes

_data/nav.yml, _includes/release-notes/known-issues.md, release-notes.md
I have removed everything except the github link from the known issues section :https://www.tiny.cloud/docs-beta/release-notes/#knownissues
2. Commented out bug fixes. We need to rework the bug fixes section after Jan 8 release.
Regards,
Shikha
=> Comment out the requested sections

plugins/charmap.md
Changed charmap code as per https://github.com/tinymce/tinymce-docs/pull/576. Please review.
Regards,
Shikha
=> Changes corresponding to PR#576

advanced/editor-command-identifiers.md
@blackcathikari These changes are corresponding to all the changes suggested in https://github.com/tinymce/tinymce-docs/pull/650. Please review.
Regards,
Shikha
=> Corresponding to PR#650

plugins/visualblocks.md, plugins/visualchars.md
`visualchars_default_state` for `visualchars` plugin inspired by `visualblocks_default_state` from `visualblocks`
=> #4643: Add visualchars_default_state option for visualchars plugin

advanced/security.md
This updated the csp headers to include *.tiny.cloud urls.
=> updated csp headers

_includes/configuration/formats.md, _includes/configuration/style-formats.md
This expands the docs on the various options for formats. Since I'm going away on vacation for about 6 weeks I won't be able to modify this PR much if it contains grammar issues etc. So I hope you @shikhanansi can massage this PR if needed.
=> TINY-2994: expanded the format options docs

_includes/configuration/contextmenu.md, _includes/release-notes/tech-preview.md, advanced/keyboard-shortcuts.md, demo/classic.md, demo/editor-dfree.md, demo/file-picker.md, demo/permanentpen.md, general-configuration-guide/basic-setup.md, general-configuration-guide/customize-ui.md, general-configuration-guide/get-support.md, general-configuration-guide/upload-images.md, general-configuration-guide/work-with-plugins.md
=> Minor docs edits

_includes/configuration/text-color.md
opening again as email wasn't public in order to get the CLA email
=> Custom colors

_config.yml, _includes/release-notes/overview.md, cloud-deployment-guide/editor-and-features.md, cloud-deployment-guide/editor-plugin-version.md, cloud-deployment-guide/features-only.md, enterprise/formatpainter.md, enterprise/pageembed.md, enterprise/permanentpen.md, enterprise/tiny-comments.md, migration-from-4x.md, plugins/pageembed.md, plugins/permanentpen.md, quick-start.md
@EkimChau Please review this PR. It has the version changes and few other GA related updates.
Regards,
Shikha
=> Version changes from 5-stable to /5

cloud-deployment-guide/editor-and-features.md, cloud-deployment-guide/editor-plugin-version.md, cloud-deployment-guide/features-only.md
@EkimChau please review this PR.
Regards,
Shikha
=> Update cloud deployment guide

ui-components/dialog.md
Reviewed the dialogs page and made any relevant updates/fixes to incorrect or out of date information. Please feel free to make any other additional changes you want :)
=> Dialogs review

_data/nav.yml, plugins/emoticons.md
To be honest I've largely just copied the charmap page and reworked it for emoticons, but feel free to make any changes as needed :smiley:
=> TINY-3088: Added new emoticons_append setting and added additional missing details

_includes/codepens/full-featured/index.js
I also noticed that mentions wasn't working, so I've added that to the demo as well.
=> TINY-2985: Added examples to the full featured demo for new premium plugins

_data/nav.yml, _includes/codepens/comments-2/index.html, _includes/codepens/comments-2/index.js, demo/comments-2.md, enterprise/tiny-comments.md, plugins/comments.md
=> Comments-demo

changelog.md
Also fixed a couple missing logs in 5.0.0
=> TINY-3372: Hotfix - Added 5.0.1 changelogs

_includes/codepen.html
If the file's not there, it omits the tab. 
Liquid is really not up to the task of rendering this page. Need something better. This works for now, though.
=> DOC-170: Make the Codepen CSS tab not show when there is no CSS content

advanced/configuring-comments-callbacks.md
@ephox-mogran, please review.
Regards,
Shikha
=> Fix wrong variable in Comments callback example

plugins/bbcode.md
I saw that there was a "/" too much in the [i] tag, so i removed it.
=> Removed a slash in the opening HTML tag of [i]

_plugins/pretty_changelog.rb, changelog.md
@lnewson please review and stamp.
=> Add styles to Changed class

_includes/codepens/drive-demo/index.html
=> Fix broken link inside demo content

_includes/codepens/annotations/index.html, _includes/codepens/basic-example/index.html, _includes/codepens/codesample/index.html, _includes/codepens/comments-2/index.html, _includes/codepens/context-menu/index.html, _includes/codepens/creating-a-custom-button-2/index.html, _includes/codepens/custom-menu-item/index.html, _includes/codepens/custom-toolbar-button/index.html, _includes/codepens/custom-toolbar-listbox/index.html, _includes/codepens/custom-toolbar-menu-button/index.html, _includes/codepens/custom-toolbar-split-button/index.html, _includes/codepens/custom-toolbar-toggle-button/index.html, _includes/codepens/drive/index.html, _includes/codepens/editor-dfree/index.html, _includes/codepens/format-custom/index.html, _includes/codepens/format-painter/index.html, _includes/codepens/full-featured/index.html, _includes/codepens/image-tools/index.html, _includes/codepens/page-embed/index.html, _includes/codepens/paste-from-word/index.html, _includes/codepens/permanent-pen/index.html, _includes/codepens/tinycomments-realtime/index.html, _includes/codepens/tinycomments-save/index.html, _includes/codepens/valid-elements/index.html
This ticket also involved doing the same thing in a whole heap of codepen pens
=> WEBSITE_1365 - Extra h1 headings reduced

Gemfile, Gemfile.lock, _config-local.sample.yml, _config.yml, robots.txt
- Changed URL, Origin properties from https://www.tinymce.com to correct URLs.
- Added jekyll-sitemap to local build for sitemap preview.
- Added last-modified-at for usage with sitemap.
- Added robots.txt to stop automatic robots.txt creation.
See PR https://github.com/tinymce/tinymce-docs/pull/972 for more details.
=> hotfix/WEBSITE-1358 - Implement better sitemaps

_includes/breadcrumbs.html, _includes/template/bodycontents.html
Related Ticket: [WEBSITE-1368](https://ephocks.atlassian.net/browse/WEBSITE-1368)
* Added structured markup data to breadcrumb elements.
* Tested in [Google Structured Data checker](https://search.google.com/structured-data/testing-tool).
=> WEBSITE-1368 - Breadcrumb Markup

mobile.md
Fixed mobile examples using v4 theme. @lnewson please review.
=> Fixed mobile examples using v4 theme

_includes/configuration/max-width.md, _includes/configuration/min-width.md, advanced/creating-a-custom-button.md, plugins/paste.md
JIRA Ticket: [WEBSITE-1370](https://ephocks.atlassian.net/browse/WEBSITE-1370)
Summary of Changes:
* Fixed missing variables from relative paths.
* Fixed broken link pointing to Git repository.
Other Notes:
* Broken links in API reference are being fixed by the Editor Team.
=> WEBSITE-1370 - Fix 404 errors in Documentation

mobile.md
Removed duplicate table. Please review.
=> Remove duplicate table

plugins/paste.md, plugins/powerpaste.md
@shikhanansi this just adds the new setting, so that we can at least communicate the change to the customer. Not sure how we want to go about documenting the other changes, so we'll still have to figure that out before closing DOC-242.
=> DOC-242: Added new paste_as_text setting to the powerpaste plugin page

plugins/link.md
@blackcathikari please review and stamp.
=> Removed sub-menu from list_link

_includes/template/bodycontents.html
Linked PR: https://github.com/tinymce/tinymce-website/pull/1169
=> WEBSITE-1356 - aside menu seo fix

plugins/comments.md
@ephox-mogran I have updated this section wrt https://ephocks.atlassian.net/browse/DOC-253. Please review.
=> Comments updates

README.md
Updated readme with correct Windows instructions and fixed a link typo.
=> Update readme, windows instructions

plugins/codesample.md
I've removed 'codesample_content_css' section. Please review.
=> removed codesample_content_css

release-notes/release-notes503.md
@blackcathikari I've made a few edits based on your feedback. Please review and stamp if everything's ok.
=> Millie's review

plugins/formatpainter.md
@EkimChau these are changes from https://github.com/tinymce/tinymce-docs/pull/1012. Please approve this PR.
=> Updated format painter formats

README.md, _includes/codepens/classic/index.js, _includes/codepens/format-custom/index.html, _includes/codepens/format-custom/index.js
Hotfixes for demonstrations on the live site; cannot include in `develop` as time-sensitive changes on branch.
* Added notes to readme regarding comments.
* Fixed issues with demonstrations due to comments.
=> HOTFIX/DOC-303 - Website issues with the Demos

README.md, _includes/codepens/basic-example/index.html, _includes/codepens/format-painter/index.html, _includes/codepens/image-tools/index.html, _includes/codepens/page-embed/index.html, _includes/codepens/permanent-pen/index.html, _includes/codepens/valid-elements/index.html, _includes/codepens/whats-new/index.html, _includes/codepens/whats-new/index.js, demo/custom-menu-item.md, demo/custom-toolbar-button.md, demo/custom-toolbar-menu-button.md, demo/custom-toolbar-split-button.md, demo/file-picker.md
@glennpenridge please review. Changes corresponding to DOC-303, and some other minor edits
=> Updated codepen to display the TinyMCE editor when the page is loaded

demo/tiny-drive-demo/demo_files_docs.json
=> WEBSITE-1558 fix for broken TinyDrive docs demo images/thumbnails

_data/nav.yml, changelog.md
Wasn't too sure who to set as a reviewer for this now, so sorry if I got this wrong :smiley:
=> TINY-3664: Added 5.0.6 changelog

_data/nav.yml, plugins/image.md
Noticed this was missing when trying to write up the internal R9 release notes, so just adding it to make sure it's not missed. If I've missed anything, or got something incorrect please feel free to change it.
=> TINY-3606: Added docs for the new image_uploadtab configuration option

_data/nav.yml, ui-components/urldialog.md
Fix #1057 and update URL dialogs page to match the new dialogs page. @lnewson please review. I tried not to touch the messaging section, and just updated other parts.
=> GH-1057 Fix buttons types and update URL dialog page

enterprise/premium-skins-and-icon-packs/bootstrap-demo.md, enterprise/premium-skins-and-icon-packs/borderless-demo.md, enterprise/premium-skins-and-icon-packs/fabric-demo.md, enterprise/premium-skins-and-icon-packs/index.md, enterprise/premium-skins-and-icon-packs/jam-demo.md, enterprise/premium-skins-and-icon-packs/material-classic-demo.md, enterprise/premium-skins-and-icon-packs/material-outline-demo.md, enterprise/premium-skins-and-icon-packs/small-demo.md
* Removed plugins and skins from sitemap for S9 release.
=> Removed Skins & Icons from documents sitemap

_data/nav.yml, plugins/comments.md, plugins/drive.md
* Changed Tiny Drive label in /plugins.
* Reordered nav.yml.
* Changed Comments label in /plugins.
=> DOC-319 - Minor updates to Docs nav items

plugins/link.md
tinymce/tinymce#5016 which fixes issue tinymce/tinymce#4335
=> Link: Document options 'http' and 'https' to link_assume_external_targets

_includes/configuration/toolbar-drawer.md, _includes/configuration/toolbar.md
Updated toolbar spec to include details on adding toolbar group labels and a note on using toolbar drawer with multiple toolbars
=> feature/DOC-324: Updated toolbar group labels spec and note for using Toolbar drawer with multiple toolbars

tinydrive/tinydrive-api/standalone.md
=> Some small capitalization suggestions

_data/nav.yml, changelog.md
Just merging my 5.0.9 changelog back into develop.
=> Merge master

advanced/configuring-comments-callbacks.md, plugins/comments.md
Note: Don't merge until TinyComments 2.1 is ready to be released.
=> TC-330: Added docs on new `tinycomments_author_name` setting

_scripts/deploy-production.sh, _scripts/deploy-staging.sh, wercker.yml
Get CSS/JS added to deploy step.
=> WEBSITE-1694 - Launcher v5 docs failing to load CSS/image/JS files

ui-components/dialogcomponents.md
=> TINY-3708: Added the new disabled property to the relevant dialog components

_includes/template/menu.html
Padding change to stop the button wrapping with the now longer text
=> WEBSITE-1730 - Optimize winner button text in place

_includes/codepens/full-featured/index.html, _includes/codepens/full-featured/index.js, _includes/codepens/full-featured/style.css, demo/full-featured.md
Updates to the Full-feature plugin demo:
- Add Tiny Drive
- Extend Mentions example to match the functionality in the Mentions codepen
=> Feature/doc 147: Updates to the Full-feature plugin demo

plugins/help.md
Don't merge until TINY-3603 is released
=> TINY-3603 Add new keyboardnav tab to help dialog docs

_includes/js/polyfill/promise-polyfill/polyfill.js, _includes/js/polyfill/whatwg-fetch/fetch.umd.js, _includes/js/store.js, _includes/template/bodycontents.html, _includes/template/menu.html, _includes/template/notification.html
Ported from develop
** accman additions needed before this
=> cart-yolo - show/hide store buttons based on cart status ported

general-configuration-guide/multiple-editors.md
fixing typo on multiple editors page
configuraiton -> configuration
=> fixing typo on multiple editors page

advanced/creating-a-skin.md
It was confusing to start with a warning that doesn't pertain to the rest of the document
=> Removed discussion of the skin creator

plugins/nonbreaking.md
Feel free to make additional changes as required.
=> TINY-3647: Added docs on new nonbreaking_wrap setting

ui-components/autocompleter.md
Note: I haven't included the mentions specific changes in this, as it might be released separately to 5.0.14.
=> MENTIONS-17: Added new autocompleter API details

_includes/js/notifications.js, _includes/template/notification.html
The contentful post can ignore the type, if so then docs needs to not default to blog no matter what
=> WEBSITE-1919 - News bar prefix is now optional

_data/nav.yml, release-notes/release-notes5014.md
5.0.14 Errata for updates to the premium plugins
=> 5.0.14 errata

general-configuration-guide/work-with-plugins.md
updated based on page views in the last 2 months
=> updating the list of "Top 10 plugins"

_includes/codepens/full-featured/index.js, _includes/codepens/full-featured/style.css, _includes/codepens/mentions/index.js, _includes/codepens/mentions/style.css
Please test in IE11. Both my parallels license and the virtual machine has expired 😞
=> Improved the visuals of the mentions plugins example

migration-from-4x.md
Adding info about WindowManager API changes for 5.0
updating description regarding CSS settings removal
=> Adding info about WindowManager API changes for 5.0

ui-components/dialog.md, ui-components/dialogcomponents.md
Note: I'm not 100% sure these are right, as they are just what I was able to find that had been added as part of the accessibility checker/search and replace dialog changes.
=> TINY-3054: Added new dialog details from changes done for search and replace

plugins/powerpaste.md
This contains new API stuff for PP 5.2, but also a general update to the Adv. Config. section
=> DOC-421 POW-155 POW-158 Update Advanced Configuration section for PowerPaste

_includes/integrations/angular-quick-start.md, _includes/integrations/react-quick-start.md, _includes/integrations/vue-quick-start.md
Links to basic example in integrations documentation are broken in production
=> (fix) demo links for integrations

advanced/creating-a-skin.md
=> fixing broken url 

_includes/configuration/height.md, _includes/release-notes/bugfixes.md, advanced/keyboard-shortcuts.md
Rebase and merge some suggested changes s/menubar/menu bar/
=> use of the term menubar/menu bar

advanced/handle-async-image-uploads.md, general-configuration-guide/upload-images.md
=> Minor fixes to the image upload docs

_includes/configuration/extended-valid-elements.md
=> adding information about allowing script elements

plugins/template.md
=> fixes for the template plugin page

general-configuration-guide/upload-images.md
Note: I'm not sure if this is right, but it seems like this is what they were trying to say.
Fixes: #734
=> fix incomplete sentence in upload-images

_includes/configuration/valid-styles.md
=> Improve the description of valid_styles

CODEOWNERS
=> updating codeowners file

_includes/integrations/angular-quick-start.md, _includes/integrations/react-quick-start.md, _includes/integrations/vue-quick-start.md, _includes/template/bodycontents.html, migration-from-4x.md
* Updated signup page paths to new location.
=> WEBSITE-1642 - Signup path updates for docs

_includes/template/bodycontents.html
=> fix the can't find what I'm looking for link

_includes/configuration/content-security-policy.md
=> Fixing issue #1360 incorrect quotes on CSP

_data/nav.yml, _includes/configuration/toolbar-location.md, configure/editor-appearance.md
Documentation for new `toolbar_location` option, for 5.2
=> TINY-4210: Add toolbar_location documentation

_includes/configuration/relative-urls.md, _includes/configuration/remove-script-host.md
And update the setting descriptions for relative_urls and remove_script_host
=> Remove references to MCFileManager

_data/nav.yml, release-notes/release-notes52.md
"premium plugin release" to "accompanying premium plugin release"
=> feat: premium plugin release to accompanying %1

LICENSE.txt
=> Add license file to repository

_config.yml, _data/nav.yml, release-notes/release-notes53.md
Related Ticket: DOC-530
* Adding skeleton release notes for 5.3 release
DOD:
- [N/A] file has been included where required if applicable
- [N/A] files removed have been deleted, not just excluded from the build if applicable
Review
- [N/A] Documentation Team Lead has reviewed
- [N/A] Product Manager has reviewed
=> skeleton of the 5.3 release notes

_includes/install/custom.md, general-configuration-guide/advanced-install.md, general-configuration-guide/localize-your-language.md
Related Ticket: DOC-228
* updated references to SDK installs to self-hosted installs
DOD:
Review
=> update s/sdk install/self-hosted install/g

cloud-deployment-guide/editor-plugin-version.md
Related Ticket: DOC-430
* update available cloud version links
DOD:
Review
=> update available cloud version links

release-notes/release-notes53.md
Related Ticket: DOC-541
* Adding 5.3 release note for comments 2.1.4
DOD:
Review
=> Comments 2.1.4 RN

plugins/powerpaste.md
Related Ticket: DOC-526
* add new PowerPaste pre-/post-process source - imagedrop
DOD:
Review
=> add new pre-/post-process source - imagedrop

advanced/creating-a-skin.md, general-configuration-guide/customize-ui.md
Related Ticket: DOC-503
* Update tinymce skin related pages to mention the updated tinymce 5 compatible skin tool and include links.
DOD:
Review
=> fix skin sections to mention the updated skin tool

_includes/codepens/emoticons/index.html, _includes/codepens/emoticons/index.js, plugins/emoticons.md
Related Ticket: DOC-435
* Add emoticon codepen to plugin page
* Add info on colon autocomplete functionality
* Convert double quotes to single quotes in code blocks
DOD:
Review
=> add emoticon codepen and add colon functionality

_includes/codepens/context-menu/index.js, _includes/configuration/available-context-menu-items.md, _includes/configuration/available-context-menu-sections.md, _includes/configuration/contextmenu.md, general-configuration-guide/spell-checking.md, plugins/table.md, ui-components/contextmenu.md
Related Ticket: DOC-532
* Added info about valid context menu options
* Additional tidy-up of context menu content
DOD:
Review
=> add available context menu items

release-notes/release-notes53.md
Related Ticket: DOC-540
* Release note for Spell Checker Pro 2.0.2 for TinyMCE 5.3 enterprise.
DOD:
Review
=> RN for spellcheckerpro 2.0.2

general-configuration-guide/upload-images.md
Apply fix provided by @JimRaleyTurbine on #1443
Related Ticket: DOC-256
* Fix image handler example
DOD:
Review
=> Fix image handler example

quick-start.md
Related Ticket: DOC-548
* update no-api-key warning on quick start
DOD:
Review
=> update no-api-key warning on quick start

plugins/drive.md
Related Ticket: #1511 
* Replacing premium plugin note for Tiny Drive plugin with note that it is only available on Tiny Cloud to reflect pricing changes
DOD:
Review
=> update premium plugin note

release-notes/release-notes53.md
Related Ticket: TINY-6034
* Adds an additional entry to the spellchecker 2.0.2 bug fixes for an issue found during QA
DOD:
Review
=> TINY-6034: Added additional spellchecker fix to the release notes

_data/nav.yml, changelog.md
Related Ticket: TINY-6029
* Adds TinyMCE 5.3.1 changelog
DOD:
Review
=> TINY-6029: Added 5.3.1 changelog

.github/CODEOWNERS
* Adding Neil to codeowners, removing newline that may have been preventing Hannes from showing in the reviewers list.
DOD:
Review
=> Adding Neil to codeowners file

enterprise/server/configure.md, release-notes/release-notes53.md
Related Ticket: DOC-523
* Document new Alternative http timeout settings
* Add 5.3 release note
DOD:
Review
=> new server-side http timeout settings

_includes/misc/supported_versions.md
Related Ticket: DOC-544
* Add 5.3 to supported versions list and add end of support dates for: 5.0, 5.1, and 5.2.
DOD:
Review
=> Update supported versions for 5.3

_includes/misc/supported_versions.md
* 5.3 enterprise release pushed back one day
DOD:
Review
=> Update release date for 5.3 enterprise

general-configuration-guide/multiple-editors.md
Related Ticket: #1519 
* Combining form elements
DOD:
Review
=> #1519 combining form elements on multiple editors examples

plugins/noneditable.md
Related Ticket: DOC-553
* Fixing the noneditable plugin example.
DOD:
Review
=> fixing noneditable example

_includes/misc/supported_versions.md
* Update 5.3 release date
DOD:
Review
=> update 5.3 release date due to delay

plugins/emoticons.md
Related Ticket: #1459 
* Fixes #1459 
Pre-checks:
Review:
=> Change from #1460

release-notes/release-notes53.md
Related Ticket: DOC-556
* Add the known issue for 5.3 release notes
Pre-checks:
Review:
=> add known issue to 53 RNs

_includes/codepens/page-embed/index.js
Related Ticket: DOC-485
* Add preview plugin to page embed codepen
Pre-checks:
Review:
=> add preview to page embed codepen

advanced/handle-async-image-uploads.md
Related Ticket: #1456 
* Fixes #1456 
Pre-checks:
Review:
=> fix roll your own image handler example

advanced/keyboard-shortcuts.md
Related Ticket: #1539 
* Updated the MacOS keyboard shortcuts reference
* Added missing shortcuts
* Formatted table markup
* Fixed incorrect shortcuts
* ~Moved accessibility shortcuts in the first table to the accessibility shortcut table~
* Updated shortcut descriptions to improve clarity
* fixes #1539 
Pre-checks:
Review:
=> Fixed MacOS keyboard shortcuts

_includes/configuration/language.md, release-notes/release-notes53.md
Related Ticket: DOC-560
* Add release note for new Greek lang pack
* Add Greek to supported premium lang packs list with version note
* Add A11ychecker release note for 2.2.1 (translations patch)
* Add known issue for missing Mexican Spanish translations for 5.2 and 5.3 features
Pre-checks:
Review:
=> Update 53RNs for translations

_data/nav.yml, changelog.md
Related Ticket: TINY-6086
* Adds the changelog for the 5.3.2 hotfix release
Pre-checks:
Review:
=> TINY-6086: Added 5.3.2 changelog

release-notes/release-notes53.md
* Minor link fixes
Pre-checks:
Review:
=> Minor fixes 5.3 release notes

_includes/index.html, index.md
Related Ticket: DOC-565
* Fixing the API docs namespace pages.
Pre-checks:
Review:
=> Fixing API docs namespace pages

_includes/index.html
Related Ticket: DOC-565
* remove hidden link on index pages
Pre-checks:
Review:
=> remove hidden link on index pages

_includes/codepens/full-featured/example.js, _includes/codepens/full-featured/index.js, _includes/codepens/open-source-plugins/index.js
* Removing duplicate height settings
Pre-checks:
Review:
=> remove duplicate heights on full-feature codepens

ui-components/dialogcomponents.md
* Fixed missing comma
Pre-checks:
Review:
=> Fixed missing comma in selectbox code demo

_includes/commands/table-cmds.md, release-notes/release-notes54.md
Related Ticket: DOC-573
* Update info on using `mceInsertTable` command
* Add related RN for 5.4 release
Pre-checks:
Review:
=> DOC-573: update mceInsertTable command usage

release-notes/release-notes54.md
Related Ticket: DOC-572
* Add 5.4 RN for spellcheckerpro dialog change
Pre-checks:
Review:
=> DOC-572: spellcheckpro 2.1.0 rn for 5.4 release

_includes/codepen.html
Related Ticket: DOC-597
* Adding comments to codepen.html file
* removing unused code - `script_tag` assigned but never called
Pre-checks:
Review:
=> DOC-597: comment on codepen.html, remove unused code

release-notes/release-notes54.md
Reverts tinymce/tinymce-docs#1571
=> Revert "DOC-572: spellcheckpro 2.1.0 rn for 5.4 release"

_data/nav.yml, changelog.md
Related Ticket: DOC-603
* Add TinyMCE 5.4.0 changelog
Pre-checks:
Review:
=> DOC-603: TinyMCE 5.4.0 Changelog

plugins/table.md, release-notes/release-notes54.md
Related Ticket: DOC-604
* Add changelog and deprecation notice to 5.4 Release Notes.
Pre-checks:
Review:
=> DOC-604: Add changelog & deprecation note to 54RN

_data/nav.yml, changelog.md
Related Ticket: TINY-6215
* Added 5.4.1 changelog for community release
Pre-checks:
Review:
=> TINY-6215: Added 5.4.1 changelog

_includes/codepens/checklist/style.css, plugins/checklist.md
Related Ticket: TINY-5139
* Updates the recommended content CSS for checklists to match the changes made in TINY-5139.
Pre-checks:
Review:
=> TINY-5139: Updated the recommended CSS for checklists

release-notes/release-notes54.md
Related Ticket: TINY-6215
* Add release note for powerpaste 5.3.1
Pre-checks:
Review:
=> TINY-6215: Powerpaste 5.3.1 release note

_includes/commands/nbsp-cmds.md, _includes/commands/pagebreak-cmds.md, _includes/configuration/formats.md, advanced/creating-a-skin.md, cloud-deployment-guide/editor-and-features.md, general-configuration-guide/basic-setup.md, plugins/a11ychecker.md, plugins/powerpaste.md, tinydrive/tinydrive-api/standalone.md
* Just some spelling fixes
Pre-checks:
Review:
=> Fixing some spelling and grammatical issues

release-notes/release-notes54.md
* Add 5.4.1 bug fixes to 5.4 release notes
Pre-checks:
Review:
=> Add 5.4.1 changelog

_data/nav.yml, _includes/misc/supported_versions.md, enterprise/system-requirements.md, release-notes/release-notes54.md
Related Ticket: DOC-611
* Update supported versions page
* Add server-side changes to 5.4 release notes
Pre-checks:
Review:
=> DOC-611: Update supported versions and server-side changes

_data/nav.yml, release-notes/release-notes54.md
Related Ticket: DOC-613
* Document 5.4 known issue regarding anchor_top and anchor_bottom options.
Pre-checks:
Review:
=> DOC-613: Anchor known issue in 5.4

advanced/editor-control-identifiers.md
Related Ticket: -
* Updated the description of the `aligncenter` toolbar control
Review:
=> Update `aligncenter` description

_scripts/icon_list_refresh.sh, advanced/editor-control-identifiers.md
* Improve icon listing script.
Pre-checks:
Review:
=> improved the icon listing script

_data/nav.yml, release-notes/release-notes54.md
* Moves the 5.4 security fix from general bug fixes to a proper security fixes section.
Pre-checks:
Review:
=> Added 5.4 security issue to the release notes

_data/nav.yml, plugins/table.md
* Add table_header_type to nav and add version note
Pre-checks:
Review:
=> Add table_header_type to nav and add version note

advanced/events.md
* Fixed description for `mce-tinycomments-update` event
Pre-checks:
Review:
=> Update the description on the tinycomments event

_data/nav.yml, _includes/integrations/expressjs-quick-start.md, integrations/expressjs.md
Related Ticket: https://github.com/tinymce/tinymce-docs/issues/531
* Add a walkthrough for creating a Node.js + Express app containing TinyMCE
* resolves #531
Pre-checks:
Review:
=> #531: Add Node.JS + Express integration documentation

_data/nav.yml, integrations/django.md
Related Ticket: #1588 
* Add documentation regarding third-party Django integration
Fixes #1588 
Pre-checks:
Review:
=> #1588: Add documentation regarding third-party django integration

migration-from-4x.md
* Fixing described change from 4 to 5 for removed plugins
Pre-checks:
Review:
=> Fixing described change from 4 to 5 for removed plugins

integrations/django.md
=> django typo

_data/nav.yml, release-notes/release-notes542.md
Related Ticket: DOC-620
* TinyMCE 5.4.2 Release Notes
Pre-checks:
Review:
=> DOC-620: 5.4.2 Release Notes

_data/nav.yml, release-notes/release-notes542.md
Related Ticket: DOC-621
* updating list of bug fixes for TinyMCE 5.4.2
Pre-checks:
Review:
=> DOC-621: updating list of bug fixes for TinyMCE 5.4.2

_config.yml, _includes/configuration/dockerized-hyperlinking-service.md, _includes/configuration/dockerized-image-proxy.md, _includes/configuration/dockerized-spelling-service.md, _includes/misc/supported_versions.md, _includes/release-notes/tech-preview.md, general-configuration-guide/attribution-requirements.md
to be clearer for self-hosted customers
Review:
=> DOC-622: Update attribution requirements

_includes/configuration/body-class.md
* Fixed `body_class` description
Pre-checks:
Review:
=> Update body_class description

general-configuration-guide/attribution-requirements.md
Related Ticket: #1640 
* Fixes #1640 
* Adjusts the attribution requirements to make them clearer for users with more than one editor per page/screen.
Pre-checks:
Review:
=> update attribution page for muli-editor applications

configure/url-handling.md
* Fixing some non-links
Pre-checks:
Review:
=> Update url-handling.md Fixing some non-links

integrations/swing.md
* Updated Java configuration example
* Added Javascript configuration example
* Replaced `setBody` (a deprecated method) with `setHtml`
* Mentioned change-log.md
* Added file-type annotation to code snippets for better highlighting
Pre-checks:
Review:
=> INT-2239: Update TinyMCE Swing documentation

_includes/configuration/fontsize-formats.md
* Update the default list of fontsize_formats and example
Pre-checks:
Review:
=> Update fontsize_format defaults and example

enterprise/premium-skins-and-icon-packs/index.md
Related Ticket: https://github.com/tinymce/tinymce-docs/pull/1666
* Fix from @dwahlqvist - Small detail in code, but when I was navigating the docs, it took me some time to figure that I was looking at the wrong skin :)
Pre-checks:
Review:
=> Fixed mixed up Material URLs

enterprise/embed-media/mediaembed-server-integration.md
* Fix ErrorObj code from 503 to 502
Pre-checks:
Review:
=> fix errorObj s/503/502/g

integrations/rails.md, release-notes/release-notes542.md
* Fixing some broken xrefs I found randomly
Pre-checks:
Review:
=> Fixing rails integration broken links

_config.yml, _data/nav.yml, release-notes/release-notes55.md
Related Ticket: DOC-644
* Add boilerplate release notes content and changes.
Pre-checks:
Review:
=> DOC-644: Adding tinymce 5.5 release notes

_config.yml, release-notes/release-notes55.md, ui-components/dialogcomponents.md
Related Ticket: DOC-643
* Adds documentation for the new `listbox` component.
Pre-checks:
Review:
=> DOC-643: Added documentation for new listbox dialog UI component

_data/nav.yml, _includes/configuration/toolbar-persist.md, configure/editor-appearance.md, release-notes/release-notes55.md
Related Ticket: TINY-4847
- Documented the new `toolbar_persist` setting added by TINY-4847.
Pre-checks:
Review:
=> DOC:642: Document new toolbar_persist setting

_data/nav.yml, changelog.md
Related Ticket: DOC-650
* TinyMCE 5.5.0 changelog
Pre-checks:
Review:
=> DOC-650: TinyMCE 5.5.0 changelog

_includes/configuration/images-upload-handler.md
Added the description for image_upload_handler
Pre-checks:
Review:
=> TINY-6268: Updated description of images_upload_handler.

_data/nav.yml, changelog.md
Related Ticket: DOC-676
* Adding 5.5.1 to the TinyMCE Changelog
Pre-checks:
Review:
=> DOC-676: add 5.5.1 changelog

release-notes/release-notes55.md
Related Ticket: DOC-661
* Adding advcode to 5.5 release notes. 
Pre-checks:
Review:
=> DOC-661: Add advcode 2.2.0 to release notes

_data/nav.yml, _includes/live-demos/template/index.html, _includes/live-demos/template/index.js, plugins/template.md
- adds template demo to docs page
- adds missing links from nav
- improves description of template_preview_replace_values
Pre-checks:
Review:
=> TINY-6434: Added demo to template docs page.

_data/nav.yml, _includes/live-demos/a11ychecker/index.html, _includes/live-demos/a11ychecker/index.js, plugins/a11ychecker.md, release-notes/release-notes55.md
Related Ticket: DOC-662 DOC-631 DOC-633 DOC-634 DOC-652 DOC-630
* DOC-630: Add rule ids and other details to rules
* DOC-633: Add id to getReport API output + minor edits
* DOC-634: Documented the `a11ychecker_ignored_rules` option
* DOC-631: Documented the `a11ychecker_issue_url_callback` option
* DOC-652: Documented the `a11ychecker_filter_issue` option + minor fixes
* DOC-662: A11ychecker change release notes for 5.5
* Re-wrote the A11ychecker plugin page
* Added a live demo for the A11ychecker page
Pre-checks:
Review:
=> DOC-662: TinyMCE 5.5 A11ychecker changes

.github/CODEOWNERS
* Fixing codeowners s/@tinymce/documentation-owners/@tinymce/documentation-team/g
Pre-checks:
Review:
=> Fix codeowner file, someone changed the team name

_includes/misc/supported_versions.md
Related Ticket: DOC-636
* Adding 5.4 and 5.5 support dates for TinyMCE 5.5 release
Pre-checks:
Review:
=> DOC-636: Adding support dates

release-notes/release-notes55.md
Related Ticket: DOC-636
* TinyMCE 5.5 known issue - table cell selection visability
Pre-checks:
Review:
=> DOC-636: Adding 5.5 known issue

plugins/advtable.md, release-notes/release-notes55.md
Related Ticket: DOC-636
* Advtables 1.0.1 release note
Pre-checks:
Review:
=> DOC-636: Advanced Tables 1.0.1 release note

release-notes/release-notes55.md
* Add beta note to 5.5 RNs for exports
Pre-checks:
Review:
=> Add beta note to 5.5 RNs for exports

_includes/misc/beta-note.md
* Update Beta Note
Pre-checks:
Review:
=> Update Beta Note

release-notes/release-notes55.md
Related Ticket: N/a
* fix broken links in 5.5 release notes
Pre-checks:
Review:
=> fix broken links in 5.5 release notes

plugins/textpattern.md
Related Ticket: TINY-6546
* Implemented some changes based on wendel's feedback to make certain parts of the examples more descriptive.
Pre-checks:
Review:
=> hotfix/TINY-6546: Wendel's feedback on text pattern

_includes/template/head.html
Related Ticket: N/a
* Add a folder indicator to nav
Pre-checks:
Review:
=> adding an arrow indicating folders in the nav

_includes/template/search.html
Related Ticket: WEBSITE-1884
* Update styles to allow search to appear on narrow viewports
Pre-checks:
Review:
=> WEBSITE-1884: Update styles to allow search on mobile

advanced/configuring-comments-callbacks.md, release-notes/release-notes56.md
Related Ticket: TINY-6345
Description of Changes: Documented new onError and onSuccess callbacks added to Comments.
Pre-checks:
Review:
=> Feature/doc-691: Document new Comments success and error callbacks

_includes/live-demos/classic/index.html, _includes/live-demos/comments-2/index.html, _includes/live-demos/full-featured/example.js, _includes/live-demos/full-featured/index.js, _includes/live-demos/open-source-plugins/index.js, _includes/live-demos/url-conversion-absolute-1/index.html, _includes/live-demos/url-conversion-absolute-2/index.html, _includes/live-demos/url-conversion-relative-1/index.html, _includes/live-demos/url-conversion-relative-2/index.html, _includes/live-demos/url-conversion-relative-2/index.js, _includes/template/head.html, integrations/bootstrap.md, integrations/jquery.md
* Quick fix to update the site name from "TinyMCE.com" to "TinyMCE Documentation" + other fixes
Pre-checks:
Review:
=> Fix site_name in metadata

_includes/configuration/branding.md
Related Ticket: DOC-710
* Update product attribution information on `branding` option.
Pre-checks:
Review:
=> DOC-710: Fix product attribution wording on branding option

_includes/misc/support-powerpaste.md, enterprise/system-requirements.md, plugins/powerpaste.md
Related Ticket: DOC-639
* DOC-639: Adding FAQs and support info to powerpaste docs
Pre-checks:
Review:
=> DOC-639: Adding FAQs to powerpaste docs

_data/nav.yml, plugins/emoticons.md, release-notes/release-notes56.md
Related Ticket: DOC-711
* Adds details about the new `emoticons_database` and `emoticons_images_url` settings.
* Adds details and legal notices about the new `emojiimages` database.
Pre-checks:
Review:
=> DOC-711: Added documentation and legal notices for the new emoticon image database

release-notes/release-notes56.md
Related Ticket: DOC-720
* Added release notes for advcode 2.3.0
Pre-checks:
Review:
=> DOC-720: Added advcode 2.3.0 release notes

advanced/php-upload-handler.md
Related Ticket: DOC-717
This just fixes some issues that @ShiridiGandham found while attempting to use this script from fiddle. The script previously had some logic to work for a CORS request, but it never actually worked, so this just adds the missing parts.
Pre-checks:
Review:
=> DOC-717: Improved the postAcceptor.php script to actually work for cross origin requests

_includes/live-demos/autocompleter/index.js, release-notes/release-notes56.md, ui-components/autocompleter.md
Related Ticket: TINY-6505
* DOC-709: Document new autocompleter item
Pre-checks:
Review:
=> DOC-709: Document new autocompleter item

release-notes/release-notes56.md
**Related Ticket:** DOC-714/TINY-6248
**Description of Changes:**
Documentation of changed behaviour in `readonly` mode.
**Pre-checks:**
**Review:**
=> DOC-714: New behaviour when clicking links in readonly mode

_data/nav.yml, changelog.md
Related Ticket: TINY-6658
* Added TinyMCE 5.6.0 changelog
Pre-checks:
Review:
=> TINY-6658: Added TinyMCE 5.6.0 changelog

plugins/table.md, release-notes/release-notes56.md
**Related Ticket:** 
DOC-713
TINY-6629
New `TableModified` event fired whenever a table is modified.
Pre-checks:
Review:
=> DOC-713: New TableModified event

README.md, _includes/configuration/valid-elements.md, _includes/feedback.html, _includes/live-demos/premiumskinsandicons-bootstrap/style.css, _includes/template/bodycontents.html, wercker.yml
Related Ticket: DOC-655
* switch from master to main branch
Pre-checks:
Review:
=> DOC-655: switch from master to main branch

_includes/misc/beta-note.md, enterprise/export.md, plugins/premium/export.md, release-notes/release-notes55.md
* Adjust beta note to allow for closed beta
Pre-checks:
Review:
=> Adjust beta note to allow for closed beta

_includes/configuration/table-column-resizing.md, _includes/live-demos/a11ychecker/index.html, _includes/live-demos/drive-demo-dropbox/index.html, _includes/live-demos/drive-demo-googledrive/index.html, _includes/live-demos/drive-demo/index.html, _includes/live-demos/full-featured/example.js, cloud-deployment-guide/editor-and-features.md, cloud-deployment-guide/editor-plugin-version.md, cloud-deployment-guide/features-only.md, demo/full-featured.md, enterprise/server/index.md, integrations/rails.md, plugins/opensource/table.md, plugins/premium/permanentpen.md, release-notes/release-notes503.md, release-notes/release-notes56.md
Related Ticket: DOC-685
*  Fix links broken by DOC-703
* Tidy up release notes
* Fixing some broken links 
Pre-checks:
Review:
=> DOC-685: Tidy up release notes

release-notes/release-notes56.md
Related Ticket: DOC-729
* Little tweak to spellchecker pro release notes
Pre-checks:
Review:
=> Doc 729 — spellchecker pro bugfix

_includes/live-demos/url-dialog/example.js
Related Ticket: #1785 
Fixes #1785 
Pre-checks:
Review:
=> #1785: Add example.js to url dialog demo to remove codepen link

_data/nav.yml, release-notes/release-notes56.md
* Removing deprecated features section references
Pre-checks:
Review:
=> Removing deprecated features section references

_data/nav.yml, changelog.md
Related Ticket: TINY-6783
* Added TinyMCE 5.6.2 changelog
Pre-checks:
Review:
=> TINY-6783: Added TinyMCE 5.6.2 changelog

_includes/integrations/angular-tech-ref.md, integrations/angular.md
* add supported versions to angular page
Pre-checks:
Review:
=> add supported versions to angular page

_includes/integrations/angular-quick-start.md, _includes/integrations/react-quick-start.md, _includes/integrations/vue-quick-start.md
Related Ticket: #1810 
Fixes #1810 
Pre-checks:
Review:
=> #1810: clarifying self-hosted options for key integrations

_new_content_templates/blank_releasenotes.md
* adding additional boilerplate text to premium plugin section of RN template
Pre-checks:
Review:
=> adding more boilerplate text to premium plugin section of RN template

release-notes/release-notes57.md
Related Ticket: DOC-743 & TINY-6664
Added release note for enhancement to table plugin when copy/pasting tables
Pre-checks:
Review:
=> DOC-743: Enhancement note for improved copy pasting of tables

_includes/configuration/formats.md
Resolves #556 
* Document the merge_siblings formats parameter
Pre-checks:
Review:
=> #556: document merge_siblings formats parameter

_includes/configuration/formats.md
Resolves #1444 
* Add `class` formats parameter and clarify `classes` description.
Pre-checks:
Review:
=> #1444: Add class param docs for format option

plugins/opensource/fullscreen.md
* quickfix for Fullscreen plugin intro
Pre-checks:
Review:
=> quickfix for Fullscreen plugin intro

_includes/live-demos/autocompleter/index.js
* Fixing the broken autocompleter demo.
Pre-checks:
Review:
=> fix the autocompleter demo

_config.yml, _includes/live-demos/editor-dfree/style.css, _includes/live-demos/inline/style.css, _includes/live-demos/premiumskinsandicons-fabric/style.css, _includes/live-demos/quickbars/style.css, _includes/template/bodycontents.html, _includes/template/head.html, _includes/template/notification.html
* Using variable for "Tiny Blue" on the docs site (where possible).
Pre-checks:
Review:
=> consistently tiny blue

_includes/configuration/table-column-resizing.md, release-notes/release-notes57.md
**Related Ticket:**
DOC-753
**Description of Changes:**
Documents new table resizing behaviour when using the `table_column_resizing` option.
Pre-checks:
Review:
=> DOC-753: Improved table resizing behaviour

_includes/events/table-events.md, release-notes/release-notes57.md
**Related Ticket:** 
DOC-731
**Description of Changes:**
Documents the `structure` and `style` variables in the `TableModified` event.
Pre-checks:
- ~~[ ] `_data/nav.yml` has been updated (if applicable)~~
- ~~[ ] Files has been included where required (if applicable)~~
- ~~[ ] Files removed have been deleted, not just excluded from the build (if applicable)~~
Review:
=> DOC-731: Document additional TableModified event data

_data/nav.yml, release-notes/release-notes57.md
Related Ticket: DOC-765
* Added release notes for the service changes included in the 5.7 release.
Pre-checks:
Review:
=> DOC-765: Added release notes for services updates

advanced/yeoman-generator.md
Related Ticket: DOC-767
* Updates the questions asked and the files output when building to match changes done in https://github.com/tinymce/generator-tinymce/pull/12
Pre-checks:
Review:
=> DOC-767: Updated the questions and generator output to reflect changes made

release-notes/release-notes57.md
Related Ticket: DOC-764
* Adds the release notes for the bug fixes done to the premium skins and icon packs (provided by @lostkeys and just reworded a little).
P.S. @lostkeys I didn't include the part about the variables as that's TinyMCE and was already included from the TinyMCE changelog.
Pre-checks:
Review:
=> DOC-764: Added premium skin/icon pack release notes

release-notes/release-notes57.md
Related Ticket: TINY-7043
* Add known issue for TinyMCE 5.7
Pre-checks:
Review:
=> TinyMCE 5.7 known issues

ui-components/contextmenu.md
**Related Ticket:** 
DOC-775
**Description of Changes:**
Adds missing `disabled` property to context menu item spec
Pre-checks:
Review:
=> DOC-775: Add disabled property to context menu item spec

_data/nav.yml, changelog.md
* 5.7.1 changelog for community release
Pre-checks:
Review:
=> 5.7.1 changelog

_includes/misc/supported_versions.md
Related Ticket: DOC-794
* Fixed the outdated supported versions page, as this was accidentally missed in the 5.7 release last month.
Pre-checks:
Review:
=> DOC-794: Fixed outdated supported versions page

_includes/live-demos/basic-conf/index.js, _includes/live-demos/premiumskinsandicons-fabric/index.js
* Removed visualchars plugin from selected demos
Pre-checks:
Review:
=> remove visualchars from selected plugins

release-notes/release-notes58.md, tinydrive/configuration.md, tinydrive/tinydrive-api/standalone.md
Related Ticket: DOC-804
* Document new skin settings
Pre-checks:
Review:
=> Doc-804: Document new skin settings

_config.yml
* Fixing some links that moved during product site refresh
Pre-checks:
Review:
=> fixing tiny.cloud urls that have changed

_includes/integrations/react-quick-start.md, _includes/integrations/react-tech-ref.md, _includes/misc/concept-dirty-state.md
See staging here:
http://docs-v5-hotfix-int-2490.staging.tiny.cloud/docs/integrations/react/
Added:
- scriptLoading
- uncontrolled component example
- prelude grouping options into categories
Changed
- Updated most examples to be current best practice
- Fixed some slightly odd English
Deprecated:
- outputFormat and documented alternative method
Pre-checks:
Review:
=> INT-2490: Updated react documentation

release-notes/release-notes571.md
Related Ticket: DOC-809
* Added attribution for the PowerPaste security issue release in the 5.7.1 patch
Pre-checks:
Review:
=> DOC-809: Added attribution for PowerPaste security issue

plugins/premium/rtc.md, rtc/beta-access.md, rtc/configuration.md, rtc/encryption.md, rtc/events.md, rtc/getting-started.md, rtc/index.md, rtc/introduction.md, rtc/jwt-authentication.md, rtc/rtc-troubleshooting.md
Staged preview: http://docs-v5-feature-rtc-expansion.staging.tiny.cloud/docs/
* Expanding RTC acronym to Real-Time Collaboration in selected cases to improve findability
Pre-checks:
Review:
=> Expanding rtc acronym in selected cases

_includes/template/bodycontents.html, release-notes/release-notes571.md, tinydrive/changelog.md
* Updating TD changelog to the new format and adding 1.4
Pre-checks:
Review:
=> Updating TD changelog to the new format and adding 1.4

_config.yml, _includes/configuration/branding.md, _includes/configuration/dockerized-hyperlinking-service.md, _includes/configuration/dockerized-image-proxy.md, _includes/configuration/dockerized-spelling-service.md, _includes/misc/admon_dont-push-docker-images.md, _includes/misc/beta-note.md, _includes/misc/supported_versions.md, _includes/release-notes/tech-preview.md, general-configuration-guide/attribution-requirements.md
Related Ticket: DOC-810
* Various changes to accompany website updates.
* Note: Changed links will not work until website changes are released.
Pre-checks:
Review:
=> DOC-810: Updating links for main site changes

changelog.md
Related Ticket: DOC-821
* removing jira id's from changelog
Pre-checks:
Review:
=> DOC-821: removing jira id's from changelog

_includes/configuration/formats.md, _includes/live-demos/format-custom/index.js, general-configuration-guide/filter-content.md
Related Ticket: DOC-800, TINY-6633
* Update some of the formatter code snippets to include the latest updates to the default formats
Pre-checks:
Review:
=> DOC-800: Document default format additions

_includes/configuration/resize.md, release-notes/release-notes58.md
Related Ticket: DOC-812
* Add a release note to describe how the resize handle can be controlled with the keyboard
Pre-checks:
Review:
=> DOC-812: Add release note for keyboard control of editor resizing

_includes/integrations/react-tech-ref.md
=> INT-2541: Documented using TinyMCE React in a bootstrap dialog

_includes/configuration/languages.md, plugins/premium/tinymcespellchecker.md, release-notes/release-notes58.md
Related Ticket: TINY-7431
* Added additional bug fixes to release notes
* Fixed various issues in the spellchecker docs (incorrect/inconsistent languages and default values)
Pre-checks:
Review:
=> TINY-7431: Added additional spellchecker release notes and fix issues with spellchecker docs

release-notes/release-notes58.md
Related Ticket: DOC-808
TinyMCE 5.8 Known issues
Pre-checks:
Review:
=> DOC-808: Add known issues to 5.8 release notes

release-notes/release-notes58.md, tinydrive/tinydrive-api/standalone.md
Related Ticket: DOC-826
* Removing Tiny Drive standalone `skin` setting docs
Pre-checks:
Review:
=> TD-296: removing broken skin TD setting

enterprise/server/configure.md
Related Ticket: DOC-777
* fixing incorrect details in allowed origin configuration
Pre-checks:
- [N/A] `_data/nav.yml` has been updated (if applicable)
- [N/A] Files has been included where required (if applicable)
- [N/A] Files removed have been deleted, not just excluded from the build (if applicable)
- [N/A] (New product features only) Release Note added
Review:
=> DOC-777: schemes and ports are ignored

Gemfile, Gemfile.lock, _includes/live-demos/comments-2/index.html, _includes/live-demos/comments-2/index.js
Related Ticket: DOC-769
* fixing the comments demo and adding resolve functionality
* locking bundler version to avoid future headaches
Pre-checks:
Review:
=> DOC-769: fixing the comments demo and adding resolve functionality

release-notes/release-notes581.md, tinydrive/changelog.md, tinydrive/tinydrive-api/standalone.md
Related Ticket: DOC-826
* Document TinyDrive skin setting
* Add TinyDrive release note
Pre-checks:
Review:
=> DOC-826: re-document TinyDrive skin setting and add release note

_data/nav.yml, release-notes/release-notes581.md
Related Ticket: DOC-803
* Added release notes for TinyMCE 5.8.1 release (as provided by @tylerkelly13)
Pre-checks:
Review:
=> DOC-803: Add release notes

_data/nav.yml, _includes/configuration/toolbar_sticky_offset.md, configure/editor-appearance.md, release-notes/release-notes59.md
Related Ticket: [DOC-829](https://ephocks.atlassian.net/secure/RapidBoard.jspa?rapidView=116&projectKey=TINY&modal=detail&selectedIssue=DOC-829)
Provide a quick description of "toolbar_sticky_offset" and what this change adds to "toolbar_sticky" functionality.
Pre-checks:
Review:
=> DOC-829: toolbar_sticky_offset

rtc/configuration.md
Related Ticket: TINY-7538
* update rtc plugin documentation for changed configuration parameter
Pre-checks:
- ~[ ] (New product features only) Release Note added~
Review:
=> TINY-7538: replace rtc_client_details with rtc_client_info

.gitignore, Gemfile, Gemfile.lock, docker/build/Dockerfile, wercker.yml
* CVE-2020-36327
Pre-checks:
Review:
=> Addressing CVE-2020-36327

_data/nav.yml, _includes/auth/gen-rsa-key-pairs.md, _includes/auth/passphrase-step-jwt.md, _includes/auth/recommend-passphrase.md
* Removing the passphrase part since that is not really needed to get things going.
* Tested these steps on linux, mac and windows.
Pre-checks:
Review:
=> DOC-831: removed passphrase since it makes it hard to be used with some of the JWT libraries

_includes/live-demos/full-featured/example.js, _includes/live-demos/full-featured/index.js
Related Ticket: DOC-832
* Add `export` for full-featured demo
Pre-checks:
Review:
=> DOC-832: add export to full-featured demo

_includes/live-demos/full-featured/example.js, _includes/live-demos/full-featured/index.js
[WSRF-244](https://ephocks.atlassian.net/browse/WSRF-244)
* Backporting DOC-832 to develop.
- [N/A] Branch prefixed with `feature/` or `hotfix/`
- [N/A] `_data/nav.yml` has been updated (if applicable)
- [N/A] Files has been included where required (if applicable)
- [N/A] Files removed have been deleted, not just excluded from the build (if applicable)
- [N/A] (New product features only) Release Note added
- [N/A] Product Manager has reviewed
=> WSRF-244 - Main -> Develop Backport

.gitignore, _includes/template/bodycontents.html, _includes/template/head.html, _scripts/build.sh
[WSRF-244](https://ephocks.atlassian.net/browse/WSRF-244)
* Fixed typo in build script.
* Added environment config file to .gitignore.
* Updated `_scripts/build.sh` with environment config for staging builds.
* Updated `include_remote` to insert entire template rather than specific elements.
* Small update to bash syntax (compatibility)
- [N/A] `_data/nav.yml` has been updated (if applicable)
- [N/A] Files has been included where required (if applicable)
- [N/A] Files removed have been deleted, not just excluded from the build (if applicable)
- [N/A] (New product features only) Release Note added
=> WSRF-244 - Staging environment fixes (Docs - General performance improvements)

.gitignore, _includes/template/bodycontents.html, _includes/template/head.html, _scripts/build.sh
This reverts commit 8e4fb76a618a0b96fcb45be4bf038f3e3b754901.Reverts tinymce/tinymce-docs#2018
=> Revert "WSRF-244 - Staging environment fixes (Docs - General performance improvements) (#2006)"

.gitignore, _includes/template/bodycontents.html, _includes/template/head.html, _scripts/build.sh
This reverts commit ebbfbd9870b40a3d0e9628f04cfe819eeda3bcb7.Reverts tinymce/tinymce-docs#2019
=> Revert "Revert "WSRF-244 - Main -> Develop Backport (#2005)""

_includes/configuration/entities.md
* Add default to entities option
Pre-checks:
Review:
=> update entities to add default value.

_data/nav.yml, _includes/configuration/iframe-aria-text.md, advanced/accessibility.md, configure/accessibility-options.md, configure/accessibility.md, release-notes/release-notes59.md
* Create a new section `Accessibility options` under `Configuration reference`
* Add `iframe_aria_text` configuration page
* Change `accessibility.md` page to include a link to `Accessibility options` page
Pre-checks:
Review:
=> DOC-852: New iframe_aria_text setting

_data/nav.yml, _includes/configuration/a11y_advanced_options.md, configure/accessibility.md
Related Ticket: DOC-854
* Add a11y_advanced_options to accessibility config page
Pre-checks:
Review:
=> DOC-854: Add a11y_advanced_options to accessibility config page

plugins/premium/rtc.md
Related Ticket: TINY-7318
* Fix breaking build error introduced by changes in TINY-7318/https://github.com/tinymce/tinymce-docs/pull/2021
Pre-checks:
Review:
=> Fix build error

rtc/introduction.md
* Setting no-longer not available
Pre-checks:
Review:
=> update RTC incompatible settings list

release-notes/release-notes59.md
Related Ticket: DOC-845
* Added release note for the UI performance improvements made in TinyMCE 5.9.
Pre-checks:
Review:
=> DOC-845: Added release note for improved rendering performance

advanced/editor-command-identifiers.md
Related Ticket: DOC-846
* Add `mceFocus` command to available commands page
Pre-checks:
Review:
=> DOC-846: Document new `mceFocus` command

release-notes/release-notes59.md
Related Ticket: DOC-866
Known issues for TinyMCE
Pre-checks:
Review:
=> DOC-866: Add known issues for 5.9

release-notes/release-notes59.md
Related Ticket: DOC-970
Known issues for RTC
Pre-checks:
Review:
=> DOC-970: Known issues for RTC

release-notes/release-notes59.md
* add notes
Pre-checks:
Review:
=> Add more notes

_includes/template/head.html
Current behavior: 
After Fix:
Pre-checks:
Review:
- [N/A] Product Manager has reviewed
=> Fix 'folder' highlighting on the nav

enterprise/server/configure.md
* Fix broken link
Pre-checks:
Review:
=> Fix broken link

plugins/opensource/emoticons.md, plugins/opensource/wordcount.md
Related Ticket: DOC-971
* Add missing cmd tables on plugin pgs
Pre-checks:
Review:
=> DOC-971: Add missing cmd tables on plugin pgs

_includes/configuration/rtc_client_connected.md, _includes/configuration/rtc_client_disconnected.md, _includes/configuration/rtc_server_disconnected.md, _includes/configuration/rtc_snapshot.md, release-notes/release-notes59.md
* Various minor hotfixes to RTC docs
Pre-checks:
Review:
=> rtc docs hotfixes

release-notes/release-notes59.md
Related Ticket: DOC-972
* Add 5.9 known issue for the reports we've received where customers followed tutorials suggesting that they override the `Event` global.
Pre-checks:
Review:
=> DOC-972: Add known issue for people reassigning the Event global

_includes/integrations/vue-tech-ref.md
Related Ticket: #2107 
* fix events list
Pre-checks:
Review:
=> #2107: fix events list

_data/nav.yml, cloud-deployment-guide/cloud-troubleshooting.md
Related Ticket: DOC-875
* troubleshooting guide for Tiny Cloud
---
I'll mark this is a draft because there are a few things to discuss
Pre-checks:
Review:
=> DOC-875: Adding information for causes and solutions of errors

wercker.yml
* wercker timeout change
Pre-checks:
Review:
=> increase timeout on linkchecker

wercker.yml
Fixes tinymce/tinymce-docs#2119
=> Fix increase timeout on linkchecker

_data/nav.yml, _new_content_templates/blank_releasenotes.md, release-notes/release-notes5101.md
Related Ticket: DOC-981 
* Adding Release notes for TinyMCE 5.10.1 Enterprise
Pre-checks:
Review:
=> DOC-981: 5.10.1 Release Notes

release-notes/release-notes5101.md
Related Ticket: DOC-981
* Fixed the missing release date in the 5.10.1 release notes
Pre-checks:
Review:
=> DOC-981: Fixed 5.10.1 release date

_config.yml, _includes/release-notes/51premium-plugins.md, advanced/creating-an-icon-pack.md, enterprise/paste-from-word.md, enterprise/server/dockerservices.md, integrations/wordpress.md, release-notes/release-notes503.md, release-notes/release-notes507.md
* Fixing some links to the product site
Pre-checks:
Review:
=> updating some links to the product site

_includes/toolbar-button-ids/tinymcespellchecker-toolbar-buttons.md
* broken link in spellchecker toolbar button section
Pre-checks:
Review:
=> broken link in spellchecker toolbar button section

modules/ROOT/partials/misc/ui-languages.adoc
Related Ticket: DOC-1552
* Add new languages to Supported Languages tables
Pre-checks:
Review:
=> DOC-1552: Document new languages

modules/ROOT/partials/plugin-files/plugin-file-list-a11ychecker.adoc, modules/ROOT/partials/plugin-files/plugin-file-list-editimage.adoc, modules/ROOT/partials/plugin-files/plugin-file-list-export.adoc, modules/ROOT/partials/plugin-files/plugin-file-list-powerpaste.adoc, modules/ROOT/partials/plugin-files/plugin-file-list-tableofcontents.adoc, modules/ROOT/partials/plugin-files/plugin-file-list-tinycomments.adoc, modules/ROOT/partials/plugin-files/plugin-file-list-tinymcespellchecker.adoc
Related Ticket: DOC-1552
* Add new languages to files missed in #2257
* Also add new languages to the new editimage and tableofcontents plugin-file-list- files
Pre-checks:
Review:
=> DOC-1552: Add new languages to plugin-file-list-<plugin> files

package.json, yarn.lock
Related Ticket: DOC-1585
* Upgrade to Antora 3 to get better error reporting and other new features
Pre-checks:
Review:
=> DOC-1585: Upgrade to antora 3

antora-playbook.yml
* Updated the UI bundle download URL to use the new location as provided in #docs
Pre-checks:
Review:
=> Update the UI bundle to use the new download URL

modules/ROOT/pages/available-menu-items.adoc, modules/ROOT/pages/available-toolbar-buttons.adoc, modules/ROOT/pages/content-localization.adoc, modules/ROOT/partials/configuration/toolbar_mode.adoc, modules/ROOT/partials/configuration/valid_elements.adoc, modules/ROOT/partials/misc/plugin-menu-item-id-boilerplate.adoc, modules/ROOT/partials/misc/plugin-toolbar-button-id-boilerplate.adoc, package.json, yarn.lock
Related Ticket: DOC-1585
* Upgrade to Antora 3
* Fixed broken xrefs reported after upgrading (these were broken before, they just weren't being flagged)
* Upgraded to the latest moxiedoc version
Pre-checks:
Review:
=> DOC-1585: Upgraded to Antora 3 and fixed some invalid xrefs

.github/workflows/feature_6_docs.yml, .github/workflows/release_6_docs.yml, .github/workflows/staging_6_docs.yml
* Added hotfixes CI and CI bucket name change
Pre-checks:
- [n/a] `_data/nav.yml` has been updated (if applicable)
- [n/a] Files has been included where required (if applicable)
- [n/a] Files removed have been deleted, not just excluded from the build (if applicable)
- [n/a] (New product features only) Release Note added
Review:
=> Hotfix-6 - Add hotfixes CI and CI bucket name change

antora.yml, modules/ROOT/partials/configuration/branding.adoc
* Update branding attribution admonition
Pre-checks:
Review:
=> DOC-1589: Update branding attribution admonition

modules/ROOT/partials/integrations/vue-tech-ref.adoc
Pre-checks:
- [-] `_data/nav.yml` has been updated (if applicable)
- [-] Files has been included where required (if applicable)
- [-] Files removed have been deleted, not just excluded from the build (if applicable)
- [-] (New product features only) Release Note added
Review:
=> Update vue integration docs

modules/ROOT/pages/changelog.adoc
Related Ticket: TINY-8555
* Added the changelog entries for 6.0.0 and 6.0.1
Pre-checks:
Review:
=> TINY-8555: Added changelog entries for TinyMCE 6.0.0 and 6.0.1

modules/ROOT/pages/tinymce-and-cors.adoc, modules/ROOT/partials/configuration/content_css_cors.adoc, modules/ROOT/partials/configuration/image_cors_hosts.adoc, modules/ROOT/partials/configuration/referrer_policy.adoc, modules/ROOT/partials/misc/general-csp.adoc
Related Ticket: DOC-1594
* Fixed some whitespace issues in the snippets
* Fixed incorrect ordering of some options
* Fixed a minor typo
Pre-checks:
Review:
=> DOC-1594: Updated the snippets and demos in the Security section

.github/workflows/feature_6_docs.yml, .github/workflows/release_6_docs.yml, .github/workflows/staging_6_docs.yml
* Fixed a bad path configuration that was causing workflows to not run when changes were made
Pre-checks:
Review:
=> Fixed bad path filtering on the GitHub action workflows

modules/ROOT/pages/plugins/premium/a11ychecker.adoc, modules/ROOT/partials/configuration/a11y_advanced_options.adoc, modules/ROOT/partials/configuration/a11ychecker_allow_decorative_images.adoc, modules/ROOT/partials/configuration/a11ychecker_filter_issue.adoc, modules/ROOT/partials/configuration/a11ychecker_html_version.adoc, modules/ROOT/partials/configuration/a11ychecker_issue_url_callback.adoc, modules/ROOT/partials/misc/premiumplugin.adoc
Related Ticket: TINY-8595
This PR updates the docs of the Plugins/Premium Plugins/a11ychecker page. It assumes The PR #2280 is going to merge first, so there might be broken links or missing ids because they are done in the another 
Pre-checks:
Review:
=> feature(Plugins/Premium Plugins/a11ychecker): Update docs of a11checker

modules/ROOT/pages/events.adoc
Related Ticket: DOC-1567
* Added the new Autocompleter events
* Added the new load error events
Pre-checks:
Review:
=> DOC-1567: Updated the editor events documentation

modules/ROOT/pages/plugins/premium/formatpainter.adoc, modules/ROOT/pages/plugins/premium/linkchecker.adoc, modules/ROOT/pages/plugins/premium/pageembed.adoc, modules/ROOT/pages/plugins/premium/permanentpen.adoc, modules/ROOT/pages/plugins/premium/powerpaste.adoc, modules/ROOT/partials/configuration/formatpainter_formats.adoc, modules/ROOT/partials/configuration/formats.adoc, modules/ROOT/partials/configuration/image_file_types.adoc, modules/ROOT/partials/configuration/linkchecker_content_css.adoc, modules/ROOT/partials/configuration/mentions_fetch.adoc, modules/ROOT/partials/configuration/mentions_item_type.adoc, modules/ROOT/partials/configuration/mentions_menu_hover.adoc, modules/ROOT/partials/configuration/mentions_select.adoc, modules/ROOT/partials/configuration/paste_block_drop.adoc, modules/ROOT/partials/configuration/paste_merge_formats.adoc, modules/ROOT/partials/configuration/paste_postprocess.adoc, modules/ROOT/partials/configuration/paste_preprocess.adoc, modules/ROOT/partials/configuration/paste_tab_spaces.adoc, modules/ROOT/partials/configuration/permanentpen_properties.adoc, modules/ROOT/partials/configuration/powerpaste_allow_local_images.adoc, modules/ROOT/partials/configuration/smart_paste.adoc, modules/ROOT/partials/configuration/tiny_pageembed_classes.adoc
Related Ticket: TINY-8595
This PR makes updates to premium plugins docs from format painter to power paste. This PR is a bit big, but it contains a lot of small changes to premium plugins that did not need much to update ( with the exception of power paste ).
Pre-checks:
Review:
=> feature(Plugins/Premium/Fromat Painter -> PowerPaste): Update docs for premium plugins section from formatpainter to powerpaste

package.json, yarn.lock
Related Ticket: DOC-1615
* Upgraded moxiedoc to pull in API doc fixes
Pre-checks:
Review:
=> DOC-1615: Upgraded moxiedoc to pull in API doc fixes

modules/ROOT/pages/plugins/premium/rtc.adoc, modules/ROOT/pages/plugins/premium/tinydrive.adoc, modules/ROOT/pages/plugins/premium/tinymcespellchecker.adoc, modules/ROOT/partials/configuration/spellchecker_active.adoc, modules/ROOT/partials/configuration/spellchecker_dialog.adoc, modules/ROOT/partials/configuration/spellchecker_ignore_list.adoc, modules/ROOT/partials/configuration/spellchecker_language.adoc, modules/ROOT/partials/configuration/spellchecker_languages.adoc, modules/ROOT/partials/configuration/spellchecker_on_load.adoc, modules/ROOT/partials/configuration/spellchecker_rpc_url.adoc, modules/ROOT/partials/configuration/spellchecker_select_languages.adoc, modules/ROOT/partials/plugin-apis/tinymcespellchecker-apis.adoc, modules/ROOT/partials/plugins/tinymcespellchecker-content-langs.adoc, modules/ROOT/partials/toolbar-button-ids/tinymcespellchecker-toolbar-buttons.adoc
…ellchecker pro premium plugin, tinydrive and rtc
Related Ticket: TINY-8595
This PR updates the docs for the Spellchecker pro premium plugin, the tiny drive premium plugin and etc premium plugin
Pre-checks:
Review:
=> feature(Plugins/Premium Plugins/Spellchecker pro): Update docs for Spellchecker pro premium plugin, tinydrive and rtc

modules/ROOT/pages/release-notes/release-notes52.adoc, modules/ROOT/pages/release-notes/release-notes521.adoc, modules/ROOT/pages/release-notes/release-notes522.adoc, modules/ROOT/pages/ui-components/typesoftoolbarbuttons.adoc, modules/ROOT/partials/configuration/a11y_advanced_options.adoc, modules/ROOT/partials/configuration/cache_suffix.adoc, modules/ROOT/partials/configuration/codesample_global_prismjs.adoc, modules/ROOT/partials/configuration/image_toolbar.adoc, modules/ROOT/partials/configuration/link_default_protocol.adoc, modules/ROOT/partials/configuration/linkchecker_preprocess.adoc, modules/ROOT/partials/configuration/tiny_pageembed_inline_styles.adoc, modules/ROOT/partials/configuration/toolbar_groups.adoc, modules/ROOT/partials/configuration/toolbar_location.adoc, modules/ROOT/partials/misc/releasenotes_for_stable.adoc
Description of Changes, it covers:
- Release TinyMCE 5.2.2
- Release TinyMCE 5.2.1
- Release TinyMCE 5.2
Pre-checks:
Review:
=> Feature/tinymce5update 3 releases 5.2.2 to 5.2

modules/ROOT/pages/general-configuration-guide/customize-ui.adoc, modules/ROOT/pages/mobile.adoc, modules/ROOT/pages/plugins/premium/powerpaste.adoc, modules/ROOT/pages/release-notes/release-notes51.adoc, modules/ROOT/pages/release-notes/release-notes514.adoc, modules/ROOT/pages/release-notes/release-notes515.adoc, modules/ROOT/pages/release-notes/release-notes516.adoc, modules/ROOT/pages/ui-components/typesoftoolbarbuttons.adoc, modules/ROOT/partials/configuration/automatic_uploads.adoc, modules/ROOT/partials/configuration/mediaembed_max_width.adoc, modules/ROOT/partials/configuration/mentions_fetch.adoc, modules/ROOT/partials/configuration/powerpaste_clean_filtered_inline_elements.adoc, modules/ROOT/partials/configuration/referrer_policy.adoc, modules/ROOT/partials/misc/releasenotes_for_stable.adoc, modules/ROOT/partials/release-notes/51deprecated.adoc, modules/ROOT/partials/release-notes/51known-issues.adoc, modules/ROOT/partials/release-notes/51new-features.adoc, modules/ROOT/partials/release-notes/51premium-plugins.adoc
Description of Changes, it covers:
- Release TinyMCE 5.1.6
- Release TinyMCE 5.1.5
- Release TinyMCE 5.1.4
- Release TinyMCE 5.1
Pre-checks:
Review:
=> Feature/tinymce5update 3 releases 5.1.6 to 5.1

modules/ROOT/pages/changelog.adoc, modules/ROOT/pages/migration-from-4x.adoc, modules/ROOT/pages/plugins/opensource/wordcount.adoc, modules/ROOT/pages/release-notes/release-notes501.adoc, modules/ROOT/pages/release-notes/release-notes5013.adoc, modules/ROOT/pages/release-notes/release-notes5014.adoc, modules/ROOT/pages/release-notes/release-notes502.adoc, modules/ROOT/pages/release-notes/release-notes503.adoc, modules/ROOT/pages/release-notes/release-notes504.adoc, modules/ROOT/pages/release-notes/release-notes505.adoc, modules/ROOT/pages/release-notes/release-notes506.adoc, modules/ROOT/pages/release-notes/release-notes507.adoc, modules/ROOT/pages/release-notes/release-notes509.adoc, modules/ROOT/pages/tinydrive/getting-started.adoc, modules/ROOT/pages/tinydrive/introduction.adoc, modules/ROOT/partials/configuration/base_url.adoc, modules/ROOT/partials/configuration/draggable_modal.adoc, modules/ROOT/partials/configuration/image_uploadtab.adoc, modules/ROOT/partials/configuration/imagetools_fetch_image.adoc, modules/ROOT/partials/configuration/link_assume_external_targets.adoc, modules/ROOT/partials/configuration/mediaembed_inline_styles.adoc, modules/ROOT/partials/configuration/nonbreaking_wrap.adoc, modules/ROOT/partials/configuration/suffix.adoc, modules/ROOT/partials/configuration/text_color.adoc, modules/ROOT/partials/configuration/toolbar.adoc, modules/ROOT/partials/release-notes/deleted.adoc, modules/ROOT/partials/release-notes/new-features.adoc, modules/ROOT/partials/release-notes/overview.adoc
Description of Changes, it covers:
- Release TinyMCE 5.0.14
- Release TinyMCE 5.0.13
- Release TinyMCE 5.0.9
- Release TinyMCE 5.0.7
- Release TinyMCE 5.0.6
- Release TinyMCE 5.0.5
- Release TinyMCE 5.0.4
- Release TinyMCE 5.0.3
- Release TinyMCE 5.0.2
- Release TinyMCE 5.0.1
- Release TinyMCE 5.0
Pre-checks:
Review:
=> Feature/tinymce5update 3 releases 5.0.14 to 5.0

modules/ROOT/pages/editimage.adoc, modules/ROOT/partials/configuration/editimage_upload_timeout.adoc, modules/ROOT/partials/configuration/image_proxy_service_url.adoc
Related Ticket: DOC-1574
* cleaned up editimage urls and pages
Pre-checks:
Review:
=> DOC-1574: cleaned up editimage docs and url clean up

antora.yml, modules/ROOT/pages/index.adoc
Related Ticket: DOC-1620
* The index page incorrectly showing `6.0` instead of `6`.
* Reverted https://github.com/tinymce/tinymce-docs/commit/c374d6fdf6d6a8daf2c6d245450ef1b194c4bf03 as that shouldn't have been removed yet.
Pre-checks:
Review:
=> DOC-1620: Minor fixes to prepare for releasing changes

.github/workflows/release_6_docs.yml
Related Ticket: DOC-1620
* Merge in changes that were incorrectly pushed straight to the release branch
Pre-checks:
Review:
Merging:
=> DOC-1620: Merge in changes from release/docs-6

modules/ROOT/partials/integrations/angular-tech-ref.adoc
Update Angular support table
Pre-checks:
- [-] `_data/nav.yml` has been updated (if applicable)
- [-] Files has been included where required (if applicable)
- [-] Files removed have been deleted, not just excluded from the build (if applicable)
- [-] (New product features only) Release Note added
Review:
=> INT-2814: Update Angular support table

modules/ROOT/partials/integrations/jquery-quick-start.adoc
=> DOC-1632: Fix path to tinymce-jquery in self-hosted example

modules/ROOT/examples/live-demos/comments-callback/index.js
* Fix for deleting the comments. I tested the other parts adding, editing, removing conversations it seems to all work. I think the intent here was to convert it to a string. I also fixed the if statement I guess the intent is to produce a 404 if you try to delete a comment that doesn't exist however don't think that scenario will be that likely in the demo but I thought I would fix that as well.
Pre-checks:
Review:
=> DOC-1626: fixed issue with deleting comments in callback demo

modules/ROOT/partials/integrations/angular-quick-start.adoc, modules/ROOT/partials/integrations/angular-tech-ref.adoc
=> DOC-1633: Use ts highlighting for Angular

modules/ROOT/pages/introduction-to-premium-selfhosted-services.adoc, modules/ROOT/partials/integrations/expressjs-quick-start.adoc, modules/ROOT/partials/integrations/webcomponent-quick-start.adoc
Related Ticket: DOC-1635
* upadated code snippet text to show correct productname
* fixed link
* fixed emal link
Pre-checks:
Review:
=> DOC-1635: Small fixes

modules/ROOT/partials/integrations/jquery-quick-start.adoc
Update the fiddle that shows how to make TinyMCE work in jQuery popups (which normally steal focus).
The previous fiddle was using an old version of jQuery and the jQuery integration from TinyMCE 4!
Pre-checks:
Review:
=> INT-2833: Update fiddle demonstrating jQuery dialogs

modules/ROOT/partials/integrations/angular-tech-ref.adoc, modules/ROOT/partials/integrations/blazor-tech-ref.adoc, modules/ROOT/partials/integrations/laravel-quick-start.adoc, modules/ROOT/partials/integrations/react-quick-start.adoc, modules/ROOT/partials/integrations/react-tech-ref.adoc, modules/ROOT/partials/integrations/svelte-quick-start.adoc, modules/ROOT/partials/integrations/svelte-tech-ref.adoc, modules/ROOT/partials/integrations/vue-tech-ref.adoc
- Remove repeated `code` plugin
- Fix Laravel syntax error
- Correct port for Svelte dev
- Set default channel for Svelte docs
- Add default channel to channel options
Pre-checks:
Review:
=> INT-2844: Misc fixes for integrations

modules/ROOT/partials/plugins/tinydrive-filetypeslist.adoc
* This adds more file extensions to the list of supported ones for tinydrive.
Pre-checks:
Review:
=> TINY-8605: Add new file extensions to TD docs

modules/ROOT/pages/rtc-supported-functionality.adoc
* Not sure how deep we should explain IMEs but people who care about that would know that it is. I don't want to list all the languages that uses IMEs.
Pre-checks:
Review:
=> DOC-1627: RTC does not support Input Method Editors

modules/ROOT/pages/tinydrive-changelog.adoc
* Updates the tinydrive changelog.
Pre-checks:
Review:
=> TD-315: Update changelog in docs

modules/ROOT/partials/integrations/blazor-postinstall.adoc
Add info for installing in Blazor WASM
Pre-checks:
Review:
=> INT-2843: Add info for Blazor WASM

modules/ROOT/partials/release-notes/6.0-release-notes-apis.adoc
Related Ticket: DOC-1559
Pre-checks:
Review:
=> DOC-1559: Fixes for core changes api section

modules/ROOT/partials/release-notes/6.0-release-notes-commands-and-queries.adoc, modules/ROOT/partials/release-notes/6.0-release-notes-events.adoc, modules/ROOT/partials/release-notes/6.0-release-notes-formatting.adoc
* Updated events, formatting and command and queries docs
Pre-checks:
Review:
=> DOC-1559: Updated events, formatting and command and queries docs

modules/ROOT/pages/6.0-release-notes-known-issues.adoc, modules/ROOT/pages/6.0-release-notes-overview.adoc, modules/ROOT/pages/6.0-release-notes-premium-changes.adoc, modules/ROOT/partials/release-notes/6.0-release-notes-plugins.adoc, modules/ROOT/partials/release-notes/6.0-release-notes-properties.adoc, modules/ROOT/partials/release-notes/6.0-release-notes-schema.adoc, modules/ROOT/partials/release-notes/6.0-release-notes-ui-and-ux-elements-and-components.adoc
Related Ticket: DOC-1559
This just tries to fix various issues found in the following sections of the release notes:
- Parsing and serialisation
- Plugins
- Properties
- Schema
- UI and UX elements and components
Pre-checks:
Review:
=> DOC-1559: Various minor 6.0 release note fixes and clarification

modules/ROOT/pages/migration-from-5x.adoc, modules/ROOT/partials/release-notes/6.0-release-notes-summary.adoc
Related Ticket: DOC-1559
* Just comments from the previous PR at this stage
Pre-checks:
Review:
=> DOC-1559: Updated migration guide

_includes/template/bodycontents.html
Related Ticket: https://ephocks.atlassian.net/browse/DOC-1622?atlOrigin=eyJpIjoiMjZhNzQ2Zjg5OGNkNGM3NzkzMjk1ZDExZTcyMjM5YmUiLCJwIjoiaiJ9
* Added version 6 in dropdown
Pre-checks:
- [n/a] `_data/nav.yml` has been updated (if applicable)
- [n/a] Files has been included where required (if applicable)
- [n/a] Files removed have been deleted, not just excluded from the build (if applicable)
- [n/a] (New product features only) Release Note added
Review:
=> DOCS-1622-v5 - add version 6 in dropdown

_new_content_templates/releasenotes_blank/x_y_z-release-notes-premium-changes.adoc, modules/ROOT/pages/6.0-release-notes-premium-changes.adoc, modules/ROOT/pages/migration-from-5x.adoc, modules/ROOT/partials/release-notes/6.0-release-notes-options.adoc, modules/ROOT/partials/release-notes/6.0-release-notes-summary.adoc, modules/ROOT/partials/release-notes/6.0-release-notes-ui-and-ux-elements-and-components.adoc
$title above is a (I hope) complete first draft.
=> Release Notes and misc improvements and corrections

modules/ROOT/pages/changelog.adoc
Related Ticket: DOC-1642
* Add [6.0.2 changelog](https://github.com/tinymce/tinymce/blob/master/modules/tinymce/CHANGELOG.md) entries
Pre-checks:
Review:
=> DOC-1642: 6.0.2 changelog

modules/ROOT/pages/emoticons.adoc, modules/ROOT/partials/commands/emoticons-cmds.adoc, modules/ROOT/partials/configuration/emoticons_database.adoc, modules/ROOT/partials/menu-item-ids/emoticons-menu-items.adoc, modules/ROOT/partials/toolbar-button-ids/emoticons-toolbar-buttons.adoc
Related Ticket: DOC-1496
* Updated the emoticons plugin docs to use the correct terms for Emoticon vs Emoji
* Fixed a couple of minor grammar or rendering issues
Pre-checks:
Review:
=> DOC-1496: Fix uses of emoticons and emojis

modules/ROOT/partials/integrations/jquery-quick-start.adoc
=> INT-2818: Re-order jQuery steps

package.json, yarn.lock
Related Ticket: DOC-1613
* Upgrade to the latest moxiedoc version to pull in fixes for API docs
Pre-checks:
Review:
=> DOC-1613: Upgrade to the latest moxiedoc version

modules/ROOT/pages/6.0-release-notes-known-issues.adoc
Related Ticket: DOC-1656
* Document new known issue for 6.0
I am not super confident about the wording but is just what I could come up with that seemed concise enough 
Pre-checks:
Review:
=> DOC-1656: Document TinyMCE 6.0 known issue

modules/ROOT/partials/integrations/vue-quick-start.adoc
Not needed for self-hosted
Redudndant information for cloud
Pre-checks:
Review:
=> INT-2873: Removed unused attributes

modules/ROOT/pages/changelog.adoc
Related Ticket: TINY-8643
* Copy across the changelog entries for the 6.0.3 community release
Pre-checks:
Review:
=> TINY-8643: Added 6.0.3 changelog

modules/ROOT/nav.adoc, modules/ROOT/pages/6.0.3-release-notes.adoc, modules/ROOT/pages/release-notes.adoc
1st draft of 6.0.3 release notes.
Pre-checks:
Review:
=> 6.0.3-release-notes.adoc

.github/workflows/release_6_docs.yml, .github/workflows/staging_6_docs.yml
Related Ticket: DOC-1724
* Update minimum plan tier for Table of Contents and Enhanced Image Editing premium plugins
Pre-checks:
- ~[x] `modules/ROOT/nav.adoc` has been updated (if applicable)~
- ~[x] Files has been included where required (if applicable)~
- ~[x] Files removed have been deleted, not just excluded from the build (if applicable)~
- ~[x] (New product features only) Release Note added~
Review:
=> DOC-1724: Updating Github workflow

.github/workflows/feature_6_docs.yml, .github/workflows/release_6_docs.yml, .github/workflows/staging_6_docs.yml
* change workflow config for AWS CLI for ec2
Pre-checks:
- [n/a] `modules/ROOT/nav.adoc` has been updated (if applicable)
- [n/a] (New product features only) Release Note added
Review:
=> Hotfix-6-aws cli fix

modules/ROOT/pages/changelog.adoc
* Added 6.1.0 community changelog
Pre-checks:
Review:
=> TINY-8099: Added changelog for TinyMCE 6.1.0 release

modules/ROOT/pages/changelog.adoc
Related Ticket: TINY-8876
* Add changelog for TinyMCE 6.1.2
Pre-checks:
Review:
=> TINY-8876: Add changelog for TinyMCE 6.1.2

package.json, yarn.lock
Related Ticket: TINY-8900
Second attempt
Pre-checks:
Review:
=> TINY-8900: Updated antora-extension-livedemos to a stable version

.github/pull_request_template.md
* As previously discussed, we don't need the review checkboxes anymore.
Pre-checks:
=> Remove review checkboxes from template

modules/ROOT/nav.adoc, modules/ROOT/pages/6.1-release-notes.adoc, modules/ROOT/pages/6.1.1-release-notes.adoc, modules/ROOT/pages/6.1.2-release-notes.adoc, modules/ROOT/pages/release-notes.adoc
* TinyMCE 6.1.2 Release Notes and associated changes to related files.
Pre-checks:
Review:
=> DOC-1770: TinyMCE 6.1.2 release notes

modules/ROOT/pages/media.adoc, modules/ROOT/partials/configuration/media_url_resolver.adoc
Copy edits and re-writes.
* Copy edits and re-writes
Pre-checks:
Review:
=> DOC-1784: media.adoc & media_url_resolver.adoc

modules/ROOT/pages/6.1-release-notes.adoc
* Fix variable error in release notes
Pre-checks:
Review:
=> HOTFIX: Fix `productname` variable error 6.1 release notes

modules/ROOT/pages/changelog.adoc
Related Ticket: TINY-8787
* Added the changelog for the 6.2 release
Pre-checks:
Review:
=> TINY-8787: Added 6.2.0 changelog

modules/ROOT/partials/configuration/premium-upgrade-promotion-option.adoc
Corrected xref: link now links.
* Corrected xref. Link now links.
Pre-checks:
Review:
=> DOC-1792: premium-upgrade-promotion-option.adoc

modules/ROOT/pages/content-behavior-options.adoc, modules/ROOT/partials/configuration/text_patterns_lookup.adoc
Related Ticket: DOC-1772
Pre-checks:
Review:
=> DOC-1772: Added doc for text_patterns_lookup

modules/ROOT/examples/live-demos/full-featured/example.js, modules/ROOT/examples/live-demos/full-featured/index.js
Related Ticket: DOC-1751
* Add `Merge Tags` functionality to full-featured demo
Pre-checks:
Review:
=> DOC-1751: Add `Merge Tags` functionality to full-featured demo

modules/ROOT/pages/autocorrect.adoc
Related Ticket: DOC-1753
* fixing duplicate (and incomplete) information
Pre-checks:
Review:
=> DOC-1753: Removing extra sentence

.github/workflows/feature_5_legacy_docs.yml, .github/workflows/release_5_legacy_docs.yml, .github/workflows/staging_5_legacy_docs.yml, _includes/js/notifications.js, _includes/template/notification.html
* Merge the changes from `develop` which includes the AWS fix to `main`. It also includes the `go.tiny.cloud` redirects, but they are already redirecting so this seems safe. FYI @ollyak
Pre-checks:
Review:
Merge:
=> Merge develop to main

modules/ROOT/nav.adoc
Related Ticket: DOC-1540
* Updated nav.doc file to read Using the Tiny Cloud.
- xref:laravel-tiny-cloud.adoc[Using the Tiny Cloud]
Updated the below as they where not consistent also.
- xref:blazor-cloud.adoc[Using the Tiny Cloud]
- xref:angular-cloud.adoc[Using the Tiny Cloud]
Pre-checks:
Review:
=> DOC-1540: Minor bug fixes

modules/ROOT/pages/changelog.adoc
Added all the 6.3 changes.
Related Ticket: [DOC-1863](https://ephocks.atlassian.net/browse/DOC-1863)
* Update `changelog.adoc` for the TinyMCE 6.3 Community Release
Pre-checks:
Review:
=> DOC-1863: changelog.adoc

modules/ROOT/pages/changelog.adoc
Related Ticket: [DOC-1868](https://ephocks.atlassian.net/browse/DOC-1868)
* Added ChangeLog entry for 6.3.1 community release noting the discovered and patched XSS vulnerability.
Pre-checks:
Review:
=> Added changelog entry for 6.3.1 community release

changelog.md
Related Ticket: [DOC-1869](https://ephocks.atlassian.net/browse/DOC-1869)
* Added ChangeLog entry for 5.10.7 community release noting the discovered and patched XSS vulnerability.
* Also corrected typos in old comment line.
Pre-checks:
Review:
=> Added changelog entry for 5.10.7 community release

_data/nav.yml, release-notes/release-notes5107.md
Related Ticket: [DOC-1872](https://ephocks.atlassian.net/browse/DOC-1872)
* add 5.10.7 Release Notes file and make associated updates to nav.yml.
Pre-checks:
Review:
=> DOC-1872: 5.10.7 Release Notes and related updates to nav.yml

modules/ROOT/pages/6.3-release-notes.adoc
Related Ticket: [DOC-1777](https://ephocks.atlassian.net/browse/DOC-1777)
* The *TinyMCE 6.3 Release Notes*.
* associated and required changes to `nav.adoc` and `release-notes.adoc`.
Pre-checks:
Review:
=> TinyMCE 6.3 Release Notes

modules/ROOT/nav.adoc, modules/ROOT/pages/6.3-release-notes.adoc, modules/ROOT/pages/advcode.adoc, modules/ROOT/pages/changelog.adoc, modules/ROOT/pages/release-notes.adoc
Related Ticket: TINY-8983
* Rebased on staging/docs-6 as 6.3 release note was merged into release/docs-6
Pre-checks:
Review:
=> TINY-8983: Prepare merging staging into release for TinyMCE 6.3.1 release

release-notes/release-notes5107.md
Related Ticket: [DOC-1876](https://ephocks.atlassian.net/browse/DOC-1876)
* added linked CVE number and attribution to _5.10.7 Release Notes_.
Pre-checks:
Review:
=> DOC-1876: added linked CVE number and attribution to 5.10.7 Release Notes.

modules/ROOT/pages/6.3-release-notes.adoc
Related Ticket: [DOC-1894](https://ephocks.atlassian.net/browse/DOC-1894).
* Documented the ‘infinite height increase’ bug dealt with in TINY-8872.
Pre-checks:
Review:
[DOC-1894]: https://ephocks.atlassian.net/browse/DOC-1894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-1894: Added missing documentation of the ‘infinite height increase’ bug (dealt with in TINY-8872) to the 6.3 Release Notes..

_includes/misc/supported_versions.md
Related Ticket: [DOC-1845](https://ephocks.atlassian.net/browse/DOC-1845)
* To improve readability the table columns displaying release and end-of-support dates are now left- or right-aligned, rather than centred.
Pre-checks:
Review:
[DOC-1845]: https://ephocks.atlassian.net/browse/DOC-1845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-1845: tweak the 5.x supported versions table to improve readability

.github/pull_request_template.md
Ticket: DOC-1897, minor edits to `pull_request_template.md` to better match current pull request norms
Changes:
* added placeholder text for copying-and-pasting the ticket’s title.
* also tweaked the Changes section boilerplate of `pull_request_template.md`.
Pre-checks:
Review:
=> DOC-1897: minor edits to `pull_request_template.md` to better match current pull request norms

modules/ROOT/pages/configure-required-services.adoc, modules/ROOT/pages/editimage.adoc, modules/ROOT/pages/export.adoc, modules/ROOT/pages/linkchecker.adoc, modules/ROOT/partials/configuration/automatic_uploads.adoc, modules/ROOT/partials/configuration/editimage_credentials_hosts.adoc, modules/ROOT/partials/configuration/image_cors_hosts.adoc, modules/ROOT/partials/configuration/image_proxy_service_url.adoc, modules/ROOT/partials/configuration/linkchecker_content_css.adoc, modules/ROOT/partials/configuration/linkchecker_service_url.adoc, modules/ROOT/partials/configuration/mediaembed_service_url.adoc, modules/ROOT/partials/index-pages/opensource-plugins.adoc, modules/ROOT/partials/index-pages/premium-plugins.adoc
Related Ticket: [DOC-1859](https://ephocks.atlassian.net/browse/DOC-1859).
* copy edits across a baker’s dozen files but mostly s/mydomain.com/example.com
Pre-checks:
Review:
[DOC-1859]: https://ephocks.atlassian.net/browse/DOC-1859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-1859: copy edits across a baker’s dozen files but mostly s/mydomain.com/example.com

.github/pull_request_template.md, changelog.md
Ticket: DOC-1898, Add a changelog file to the tinymce-docs project
Changes:
* Added new file to the project: `changelog.md`.
* Added entries for all docs changes back to 2022-12-08 to this file.
* Added *Unreleased* section to `changelog.md`.
* Added entry re this ticket and this file to *Unreleased* section.
Pre-checks:
Review:
=> DOC-1898: Add a changelog file to the tinymce-docs project

changelog.md, modules/ROOT/pages/changelog.adoc
Ticket: DOC-1930: Tiny 6.4 Community docs release.
Changes:
* added the TinyMCE 6.4-specific changes to `changelog.adoc`.
Pre-checks:
Review:
=> DOC-1930: changelog.adoc

changelog.md, modules/ROOT/pages/changelog.adoc
Ticket: DOC-1930: changelog updates for community 6.4 release
Changes:
* changelog updates for community 6.4 release
Pre-checks:
~- [ ] Branch prefixed with `feature/6/` or `hotfix/6/`~
Review:
=> DOC-1930: changelog updates for community 6.4 release

changelog.md, modules/ROOT/pages/changelog.adoc
Ticket: DOC-1939, TinyMCE 6.4.1 Community docs release
Changes:
* Added TinyMCE 6.4.1-specific changes to `changelog.adoc`.
* Also corrected typo and incorrect date in 6.4 sub-head.
Pre-checks:
Review:
=> DOC-1939: TinyMCE 6.4.1 Community docs release

changelog.md, modules/ROOT/examples/live-demos/ui-mode/index.html, modules/ROOT/examples/live-demos/ui-mode/index.js, modules/ROOT/examples/live-demos/ui-mode/style.css, modules/ROOT/nav.adoc, modules/ROOT/pages/ui-mode-configuration-options.adoc, modules/ROOT/partials/configuration/ui_mode.adoc, modules/ROOT/partials/misc/admon-requires-6.4v.adoc
Ticket: DOC-1902, TinyMCE within a Scrollable Container.
Changes:
* Documenting new `ui_mode` option
Pre-checks:
Review:
=> DOC-1902: TinyMCE within a Scrollable Container

changelog.md, modules/ROOT/pages/changelog.adoc
merging release to staging in prep for the 6.4.1 docs release
Changes:
* merging release to staging in prep for the 6.4.1 docs release
=> merging release to staging in prep for the 6.4.1 docs release

changelog.md, modules/ROOT/examples/live-demos/advcode/index.html, modules/ROOT/pages/advcode.adoc, modules/ROOT/partials/misc/advcode-shortcuts.adoc
Ticket: DOC-1907: update Advanced Code Editor documentation to cover new functionality.
Changes:
* Copy-edits to cater for documenting future, non-search-related keyboard chords.
* New Advanced Code Editor features now listed in both the intro paragraphs and the live demo.
Pre-checks:
Review:
=> DOC-1907: update Advanced Code Editor documentation to cover new functionality

changelog.md, modules/ROOT/pages/6.3.2-release-notes.adoc, modules/ROOT/partials/configuration/indentation.adoc, modules/ROOT/partials/configuration/invalid_styles.adoc, modules/ROOT/partials/configuration/schema.adoc, modules/ROOT/partials/configuration/spellchecker_dialog.adoc
Ticket: DOC-1927: copy edits and typos not otherwise ticketed
Changes:
* copy edits and typos not otherwise ticketed.
Pre-checks:
Review:
=> DOC-1927: copy edits and typos not otherwise ticketed

changelog.md, modules/ROOT/pages/dialog-components.adoc
Ticket: DOC-1914, document the tree dialog component
Changes:
* Added entry for tree component.
Pre-checks:
Review:
=> DOC-1914, document the tree dialog component

changelog.md, modules/ROOT/pages/accessibility.adoc, modules/ROOT/pages/content-appearance.adoc, modules/ROOT/pages/editor-important-options.adoc, modules/ROOT/partials/configuration/highlight_on_focus.adoc
Ticket: DOC-1893: New option highlight_on_focus and skin changes
Changes:
* new file added: `/modules/ROOT/partials/configuration/highlight_on_focus.adoc`.
* documentation of `highlight_on_focus` option added to new file.
* `include::` statements pointing to new file added
* `content-appearance.adoc`; and
* `accessibility.adoc`.
Pre-checks:
Review:
=> DOC-1893: New option highlight_on_focus and skin changes

modules/ROOT/pages/6.4.1-release-notes.adoc, modules/ROOT/pages/changelog.adoc
Ticket: DOC-1941: Copy edit changes to changelog.md 6.4.1.
Changes:
* `Hotfix` copy edit changes to changelog.md 6.4.1.
Pre-checks:
Review:
=> DOC-1941: Copy edit changes to changelog.md 6.4.1

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2044
Changes:
* Added TINY-9849 to the release notes.
Pre-checks:
Review:
=> DOC-2044: Added TINY-9849 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2048
Changes:
* Added TINY-9812 to the release notes.
Pre-checks:
Review:
=> DOC-2048: Added TINY-9812 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2047
Changes:
* Added TINY-9848 to the release notes.
Pre-checks:
Review:
=> DOC-2047: Added TINY-9848 to the release notes.

_config.yml, _includes/template/bodycontents.html
Ticket: [WSRF-1238](https://ephocks.atlassian.net/browse/WSRF-1238), SEO: Docs - Unification of signup paths.
Changes:
* Update banner's alt text
* Add slash to the signup URL
Pre-checks:
~- [ ] Branch prefixed with `feature/6/` or `hotfix/6/`~
~- [ ] Changelog entry added~
Review:
[WSRF-1238]: https://ephocks.atlassian.net/browse/WSRF-1238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WSRF-1238: Update banner's alt text and add slash to the URL

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2057
Changes:
* Added TINY-9830 to the release notes.
Pre-checks:
Review:
=> DOC-2057: Added TINY-9830 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2009
Changes:
* Added TINY-9688 to the release notes. (Real-time Collaboration (RTC) plugin notification regarding being deactivated)
Pre-checks:
Review:
=> DOC-2009: Added TINY-9688 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2053
Changes:
* Added TINY-9893 to the release notes.
Pre-checks:
Review:
=> DOC-2053: Added TINY-9893 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1986
Changes:
* Added TINY-9770 to the release notes.
Pre-checks:
Review:
=> DOC-1986: Added TINY-9770 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC:2041
Changes:
* Added TINY-9148 to the release notes.
Pre-checks:
Review:
=> DOC:2041: Added TINY-9148 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1997
Changes:
* Added TINY-9472 to the release notes.
Pre-checks:
Review:
=> DOC-1997: Added TINY-9472 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2005
Changes:
* Added TINY-9566 to the release notes.
Pre-checks:
Review:
=> DOC-2005: Added TINY-9566 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2018
Changes:
* Added TINY-9768 to the release notes.
Pre-checks:
Review:
=> DOC-2018: Added TINY-9768 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2019
Changes:
* Added TINY-9774 to the release notes.
Pre-checks:
Review:
=> DOC-2019: Added TINY-9774 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2036
Changes:
* Added TINY-9805 to the release notes.
Pre-checks:
Review:
=> DOC-2036: Added TINY-9805 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2056
Changes:
* Added TINY-9892 to the release notes.
Pre-checks:
Review:
=> DOC-2056: Added TINY-9892 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2010
Changes:
* Added TINY-9691 to the release notes
Pre-checks:
Review:
=> DOC-2010: Added TINY-9691 to the release notes

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2046
Changes:
* Added TINY-9743 to the release notes.
Pre-checks:
Review:
=> DOC-2046: Added TINY-9743 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2002
Changes:
* Added TINY-9510 to the release notes.
Pre-checks:
Review:
=> DOC-2002: Added TINY-9510 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2031
Changes:
* Added TINY-3909 to the release notes.
Pre-checks:
Review:
=> DOC-2031: Added TINY-3909 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2054
Changes:
* Added TINY-8297 to the release notes.
Pre-checks:
Review:
=> DOC-2054: Added TINY-8297 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2008
Changes:
* Added TINY-9680 to the release notes.
Pre-checks:
Review:
=> DOC-2008: Added TINY-9680 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2011
Changes:
* Added TINY-9694 to the release notes.
Pre-checks:
Review:
=> DOC-2011: Added TINY-9694 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2037
Changes:
* Added TINY-9794 to the release notes.
Pre-checks:
Review:
=> DOC-2037: Added TINY-9794 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2045
Changes:
* Added TINY-9280 to the release notes.
Pre-checks:
Review:
=> DOC-2045: Added TINY-9280 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2033
Changes:
* Added TINY-9813 to the release notes.
Pre-checks:
Review:
=> DOC-2033: Added TINY-9813 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2040
Changes:
* Added TINY-9696 to the release-notes
Pre-checks:
Review:
=> DOC-2040: Added TINY-9696 to the release-notes

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2013
Changes:
* Added TINY-9704 to the release notes.
Pre-checks:
Review:
=> DOC-2013: Added TINY-9704 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2012
Changes:
* Added TINY-9701 to the release notes.
Pre-checks:
Review:
=> DOC-2012: Added TINY-9701 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2014
Changes:
* Added TINY-9715 to the release notes.
Pre-checks:
Review:
=> DOC-2014: Added TINY-9715 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1977
Changes:
* Added TINY-9753 to the release notes.
Pre-checks:
Review:
=> DOC-1977: Added TINY-9753 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2059
Changes:
* Added TINY-9793 to the release notes.
Pre-checks:
Review:
=> DOC-2059: Added TINY-9793 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1978
Changes:
* Added TINY-9748 to the release notes.
Pre-checks:
Review:
=> DOC-1978: Added TINY-9748 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1984
Changes:
* Added TINY-9698 to the release notes.
Pre-checks:
Review:
=> DOC-1984: Added TINY-9698 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1979
Changes:
* Added TINY-9679 to the release notes.
Pre-checks:
Review:
=> DOC-1979: Added TINY-9679 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1993
Changes:
* Added TINY-9669 to the release notes.
Pre-checks:
Review:
=> DOC-1993: Added TINY-9669 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2035
Changes:
* Added TINY-9807 to the release notes.
Pre-checks:
Review:
=> DOC-2035: Added TINY-9807 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1988
Changes:
* Added TINY-9755 to the release notes.
Pre-checks:
Review:
=> DOC-1988: Added TINY-9755 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2063
Changes:
* Added TINY-9633 to the release notes.
Pre-checks:
Review:
=> DOC-2063: Added TINY-9633 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2066
Changes:
* Added TINY-9823 to the release notes.
Pre-checks:
Review:
=> DOC-2066: Added TINY-9823 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2064
Changes:
* Added TINY-9837 to the release notes.
Pre-checks:
Review:
=> DOC-2064: Added TINY-9837 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket:DOC-2055
Changes:
* Added TINY-9500 to the release notes.
Pre-checks:
Review:
=> DOC-2055: Added TINY-9500 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2062
Changes:
* Added TINY-9468 to the release notes.
Pre-checks:
Review:
=> DOC-2062: Added TINY-9468 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2060
Changes:
* Added TINY-9718 to the release notes.
Pre-checks:
Review:
=> DOC-2060: Added TINY-9718 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2007
Changes:
* Added TINY-9630 to the release notes.
Pre-checks:
Review:
=> DOC-2007: Added TINY-9630 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1976
Changes:
* Added TINY-8122 to the release notes.
Pre-checks:
Review:
=> DOC-1976: Added TINY-8122 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1982
Changes:
* Added TINY-9314 to the release notes.
Pre-checks:
Review:
=> DOC-1982: Added TINY-9314 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2039
Changes:
* Added TINY-9601 to the release notes.
Pre-checks:
Review:
=> DOC-2039: Added TINY-9601 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2050
Changes:
* Added TINY-9816 to the release notes.
Pre-checks:
Review:
=> DOC-2050: Added TINY-9816 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1994
Changes:
* Added TINY-9664 to the release notes.
Pre-checks:
Review:
=> DOC-1994: Added TINY-9664 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2021
Changes:
* Added TINY-9460 to the release notes.
Pre-checks:
Review:
=> DOC-2021: Added TINY-9460 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2003
Changes:
* Added TINY-9565 to the release notes.
Pre-checks:
Review:
=> DOC-2003: Added TINY-9565 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1995
Changes:
* Added TINY-9662 to the release notes.
Pre-checks:
Review:
=> DOC-1995: Added TINY-9662 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1998
Changes:
* Added TINY-9469 to the release notes.
Pre-checks:
Review:
=> DOC-1998: Added TINY-9469 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2034
Changes:
* Added TINY-9808 to the release notes.
Pre-checks:
Review:
=> DOC-2034: Added TINY-9808 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1990
Changes:
* Added TINY-9758 to the release notes.
Pre-checks:
Review:
=> DOC-1990: Added TINY-9758 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2032
Changes:
* Added TINY-9818 to the release notes.
Pre-checks:
Review:
=> DOC-2032: Added TINY-9818 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1991
Changes:
* Added TINY-9739 to the release notes.
Pre-checks:
Review:
=> DOC-1991: Added TINY-9739 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-1989
Changes:
* Added TINY-9761 to the release notes.
Pre-checks:
Review:
=> DOC-1989: Added TINY-9761 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2022
Changes:
*  Added TINY-9464 to the release notes.
Pre-checks:
Review:
=> DOC-2022: Added TINY-9464 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2016
Changes:
* Added TINY-9749 to the release notes.
Pre-checks:
Review:
=> DOC-2016: Added TINY-9749 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2023
Changes:
* Added TINY-9466 to the release notes.
Pre-checks:
Review:
=> DOC-2023: Added TINY-9466 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2017
Changes:
* Added TINY-9757 to the release notes.
Pre-checks:
Review:
=> DOC-2017: Added TINY-9757 to the release notes.

changelog.md, modules/ROOT/pages/6.5-release-notes.adoc
Ticket: DOC-2015
Changes:
* Added TINY-9735 to the release notes.
Pre-checks:
Review:
=> DOC-2015: Added TINY-9735 to the release notes.

changelog.md, modules/ROOT/examples/live-demos/accordion/index.html, modules/ROOT/examples/live-demos/accordion/index.js, modules/ROOT/nav.adoc, modules/ROOT/pages/accordion.adoc, modules/ROOT/pages/available-menu-items.adoc, modules/ROOT/pages/available-toolbar-buttons.adoc, modules/ROOT/partials/commands/accordion-cmds.adoc, modules/ROOT/partials/configuration/details_initial_state.adoc, modules/ROOT/partials/configuration/details_serialized_state.adoc, modules/ROOT/partials/events/accordion-events.adoc, modules/ROOT/partials/menu-item-ids/accordion-menu-items.adoc, modules/ROOT/partials/plugin-apis/accordion-apis.adoc, modules/ROOT/partials/toolbar-button-ids/accordion-toolbar-buttons.adoc
Ticket: DOC-2024, Document the new open source plugin, Accordion.
Changes:
* Added required files:
* `/modules/ROOT/partials/commands/accordion-cmds.adoc`.
* `/modules/ROOT/partials/events/accordion-events.adoc`.
* `/modules/ROOT/partials/menu-item-ids/accordion-menu-items.adoc`.
* `/modules/ROOT/partials/toolbar-button-ids/accordion-toolbar-buttons.adoc`.
* `/modules/ROOT/pages/accordion.adoc`.
* `/modules/ROOT/partials/configuration/details_initial_state.adoc`.
* `/modules/ROOT/partials/configuration/details_serialized_state.adoc`.
* `/modules/ROOT/examples/live-demos/accordion/index.html`.
* `/modules/ROOT/examples/live-demos/accordion/index.js`.
* Edited required files:
* `/modules/ROOT/nav.adoc`.
* `/modules/ROOT/pages/available-menu-items.adoc`.
* …
=> DOC-2024: Document the new open source plugin, Accordion.

changelog.md, modules/ROOT/pages/6.4.2-release-notes.adoc, modules/ROOT/pages/6.5.1-release-notes.adoc, modules/ROOT/partials/configuration/details_initial_state.adoc, modules/ROOT/partials/configuration/details_serialized_state.adoc
Ticket: DOC-2081
Changes:
* Updates to 6.5.1 release-notes and accordion.adoc file.
Pre-checks:
Review:
=> DOC-2081: Updates to 6.5.1 release-notes and accordion.adoc file.

changelog.md, modules/ROOT/partials/configuration/ai_shortcuts.adoc
DOC-2173: Update default ai_shortcuts values to match updates made in the plugin; also note the absence of translations
Changes:
* Updated the default value code sample to match the updated values included in the AI Assistant proper.
* Also re-wrote the following **Note** admonition to call-out the absence of any translations or alternative language versions of these default values.
Pre-checks:
Review:
=> DOC-2173: Update default ai_shortcuts values to match updates made in the plugin; also note the absence of translations

changelog.md, modules/ROOT/pages/6.7-release-notes.adoc
Ticket: DOC-2171: improvement documentation entry for TINY-10124 in the 6.7 Release Notes
Changes:
* added improvement documentation for `Improved the keyboard focus visibility for links inside dialogs`.
Pre-checks:
Review:
=> DOC-2171: improvement documentation entry for TINY-10124 in the 6.7 Release Notes

changelog.md, modules/ROOT/examples/live-demos/advtemplate-insertionpoint/index.html, modules/ROOT/examples/live-demos/advtemplate-insertionpoint/index.js, modules/ROOT/pages/6.4.1-release-notes.adoc, modules/ROOT/pages/6.4.2-release-notes.adoc, modules/ROOT/pages/6.7-release-notes.adoc, modules/ROOT/pages/advanced-templates.adoc, modules/ROOT/pages/mergetags.adoc, modules/ROOT/pages/tableofcontents.adoc, modules/ROOT/partials/commands/advtemplate-cmds.adoc, modules/ROOT/partials/configuration/tableofcontents_header.adoc, modules/ROOT/partials/configuration/tableofcontents_includeheader.adoc, modules/ROOT/partials/configuration/tableofcontents_orderedlist.adoc, modules/ROOT/partials/configuration/tableofcontents_orderedlist_type.adoc
DOC-2171: the TinyMCE 6.7 release notes plus 6.7-specific changes to the TinyMCE documentation
Changes:
* So many changes.
Pre-checks:
Review:
=> DOC-2171: the TinyMCE 6.7 release notes plus 6.7-specific changes to the TinyMCE documentation

.github/workflows/feature_5_legacy_docs.yml, .github/workflows/release_5_legacy_docs.yml, .github/workflows/staging_5_legacy_docs.yml
Ticket: DOC-2186, Add back workflow files.
Changes:
* Add back workflow files
Pre-checks:
Review:
=> DOC-2186: Add back workflow files

release-notes/release-notes5108.md
Ticket: DOC-2199
Changes:
* Add CVE numbers and links to 5108 release notes.
Pre-checks:
Review:
=> DOC-2199: Add CVE numbers and links to 5108 release notes.

changelog.md, modules/ROOT/pages/6.7.2-release-notes.adoc
Ticket: DOC-2194
Changes:
- add fix documentation for TINY-10213 in the 6.7.2 Release notes.
Pre-checks:
Review:
=> DOC-2194: fix documentation for TINY-10213 in the 6.7.2 Release notes.

changelog.md, modules/ROOT/pages/6.7.2-release-notes.adoc
Ticket: DOC-2194
Changes:
* added fix documentation for TINY-10154 in the 6.7.2 Release notes.
Pre-checks:
Review:
=> DOC-2194: fix documentation for TINY-10154 in the 6.7.2 Release notes.

changelog.md, modules/ROOT/pages/6.7.2-release-notes.adoc
Ticket: DOC-2194:
Changes:
* added fix documentation for TINY-10263 to the 6.7.2 Release notes
Pre-checks:
Review:
=> DOC-2194: added fix documentation for TINY-10263 to the 6.7.2 Release notes

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation to TINY-10154 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation to TINY-10154 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10133 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10133 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10254 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10254 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add `new feature` documentation for TINY-9974 in the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add addition `new feature` documentation for TINY-9974 in the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add improvement documentation for TINY-9963 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add improvement documentation for TINY-9963 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* added fix documentation for TINY-10209 in the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: fix documentation for TINY-10209 in the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10162 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10162 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add change documentation for TINY-10237 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add change documentation for TINY-10237 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10289 in the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10289 in the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add improvement documentation for TINY-10147 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add improvement documentation for TINY-10147 to the 6.8 release notes.

modules/ROOT/pages/ai.adoc, modules/ROOT/partials/configuration/ai_request.adoc
Ticket: DOC-2211
Changes:
* Modified `ai_request` examples to display errors in more situations
Pre-checks:
Review:
=> DOC-2211: Improve error handling in AI Assistant examples

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10177 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10177 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* added fix documentation for TINY-10178 to the release notes.
Pre-checks:
Review:
=> DOC-2181: fix documentation for TINY-10178 to the release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10139 to the release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10139 to the release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10132 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10132 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10118 to the release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10118 to the release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10285 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10285 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10316 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10316 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10173 to the 6.7 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10173 to the 6.7 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10330 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10330 to the 6.8 release notes.

modules/ROOT/pages/dialog-footer-buttons.adoc, modules/ROOT/partials/configuration/ai_request.adoc, modules/ROOT/partials/configuration/ai_shortcuts.adoc
Ticket: DOC-2217, TINY-10159
Changes:
* Updated default values for `ai_shortcuts`
* Added documentation of new `selection` property for shortcuts
* Fixed missing `async` in updated `ai_request` stream example
* Updated system messages in `ai_request` stream example for upcoming model update
Pre-checks:
Review:
=> DOC-2217: Update `ai_shortcut` documentation with `selection` property and changes to default value.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-9393 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-9393 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add documentation for TINY-10159 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add documentation for TINY-10159 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-9796 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-9796 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10172 to the 6.8 release notes.
* added small `note` for TINY-10154
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10172 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10174 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10174 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10343 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10343 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10291 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10291 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10292 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10292 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10241 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10241 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10282 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10282 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc, modules/ROOT/pages/content-formatting.adoc, modules/ROOT/partials/configuration/force_hex_color.adoc
Changes:
* add fix documentation for TINY-9819 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-9819 to the 6.8 release notes.

cloud-deployment-guide/cloud-troubleshooting.md
Ticket: DOC-2221 `v2-5x`
Changes:
* add new notification messages to `cloud-troubleshooting.adoc` file for `5x docs`.
Pre-checks:
Review:
=> DOC-2221: add new notification messages to `cloud-troubleshooting.adoc` file for 5x docs.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add improvement documentation for TINY-10141 to the 6.8.1 release notes.
Pre-checks:
Review:
=> DOC-2181: add improvement documentation for TINY-10141 to the 6.8.1 release notes.

changelog.md, modules/ROOT/pages/6.8.1-release-notes.adoc
Changes:
* add  `new feature` documentation for TINY-10290 to the 6.8.1 release notes.
Pre-checks:
Review:
=> DOC-2181: add  `new feature` documentation for TINY-10290 to the 6.8.1 release notes.

.github/workflows/feature_6_docs.yml, .github/workflows/release_6_docs.yml, .github/workflows/staging_6_docs.yml, antora.yml
Ticket: DOC-2234
Changes:
* Fix workflows to not overwrite 5 docs site
Pre-checks:
Review:
=> DOC-2234: Fix workflow to not overwrite 5 site

modules/ROOT/pages/creating-custom-notifications.adoc
Ticket: DOC-2288
Site: [DOC-2288 site](http://docs-feature-70-doc-2288tiny-10646.staging.tiny.cloud/docs/tinymce/latest/creating-custom-notifications/)
Changes:
* [DOC-2288 ](https://ephocks.atlassian.net/browse/DOC-2288) Remove closeButton in Notifications
* To support TINY-10646
Pre-checks:
Review:
=> DOC-2288_TINY-10646 Remove closeButton in Notifications

modules/ROOT/partials/configuration/media_url_resolver.adoc
Ticket: DOC-2301
Site: [DOC-2301 site](http://docs-feature-70-doc-2301.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
- Refactor media_url_resolver function to use a Promise in `media_url_resolver.adoc` to support TINY-9154
Pre-checks:
Review:
=> DOC-2301: Refactor media_url_resolver function to use a Promise

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270 site](http://docs-feature-70-doc-2270tiny-9637.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Release notes for TINY-9637
Pre-checks:
Review:
=> DOC-2270: Add improvement documentation for TINY-9637 to the TinyMCE 7.0 release notes

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270 site](http://docs-feature-70-doc-2270tiny-10487.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Add release notes for TINY-10487
Pre-checks:
Review:
=> DOC-2270: Add improved documentation for TINY-10487 to the TinyMCE 7.0 release notes

modules/ROOT/pages/7.0-release-notes.adoc
Ticket: DOC-10453
Site: [DOC-10453 site](http://docs-feature-70-doc-10453.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
*  Add release notes for TINY-10453
Pre-checks:
Review:
=> DOC-2270: Add improved documentation for TINY-10453 to the TinyMCE 7.0 release notes

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270 site](http://docs-feature-70-doc-2270tiny-10596.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#enhanced-code-editor)
Changes:
* Various improvements, fixes and changes for Enhanced Code Editor in the 7.0 release notes.
* Content for TINY-9205
* Content for TINY-10561
* Content for TINY-10596
* Content for TINY-10649
* Content for TINY-10651
Pre-checks:
Review:
=> DOC-2270: Various improvements, fixes and changes for Enhanced Code Editor in the 7.0 release notes.

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270 site](http://docs-feature-70-doc-2270.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Add release notes for TINY-10616 (combined to TINY-10453)
Pre-checks:
Review:
=> DOC-2270: Add improved documentation for TINY-10474 in TinyMCE 7.0 release notes

modules/ROOT/pages/changelog.adoc
Ticket: DOC-2317
Site: [DOC-2270_DOC-2317 site](http://docs-feature-70-doc-2270doc-2317.staging.tiny.cloud/docs/tinymce/latest/changelog/)
Changes:
* add changelog entries for TinyMCE 7.0 release project to reflect `tinymce/changelog.md`
Pre-checks:
Review:
=> DOC-2270: add changelog entries for TinyMCE 7.0 release project.

modules/ROOT/pages/7.0-release-notes.adoc
Ticket: DOC-2294
Site: [DOC-2270_DOC-2294 site](http://docs-feature-70-doc-2270doc-2294.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#accompanying-enhanced-skins-and-icon-packs-changes)
Changes:
* Add focus style changes to Accompanying Enhanced Skins & Icon Packs changes.
Pre-checks:
Review:
=> DOC-2270: Add focus style changes to Accompanying Enhanced Skins & Icon Packs changes.

modules/ROOT/nav.adoc, modules/ROOT/pages/license-key.adoc
Ticket: DOC-2319
Site: [DOC-2319 site](http://docs-feature-70-doc-2319.staging.tiny.cloud/docs/tinymce/latest/license-key/)
Changes:
* Updated TinyMCE License Configuration Guide with latest suggestions
Pre-checks:
Review:
=> Updated TinyMCE License Configuration Guide with latest suggestions

-new-material-templates/release-notes-template/antora.yml, antora.yml, modules/ROOT/examples/live-demos/full-featured/index.html
Ticket: DOC-2336
Site: [DOC-2336 site](http://docs-hotfix-7-doc-2336.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Fix incorrect url
Pre-checks:
Review:
=> DOC-2336: Fix demo version

modules/ROOT/partials/misc/supported-versions.adoc
Ticket: DOC-2337
Site: [DOC-2337 site](http://docs-hotfix-70-doc-2337.staging.tiny.cloud/docs/tinymce/latest/support/)
Changes:
* update the release and EOS date for TinyMCE 7.0.
Pre-checks:
Review:
=> DOC-2337: update TinyMCE 7.0 support date.

modules/ROOT/partials/install/upgrading-info.adoc
Ticket: DOC-2345
Site: [DOC-2345 site](http://docs-hotfix-7-doc-2345.staging.tiny.cloud/docs/tinymce/latest/upgrading)
Changes:
* DOC-2345 update `upgrading.adoc` page to reflect TinyMCE 7
Pre-checks:
Review:
=> DOC-2345 update `upgrading.adoc` page to reflect TinyMCE 7

modules/ROOT/partials/misc/supported-versions.adoc
Ticket: DOC-2344
Site: [DOC-2344 site](http://docs-hotfix-6-doc-2344.staging.tiny.cloud/docs/tinymce/6/support/)
Changes:
* DOC-2344 Add 6.8 EOS date to 6x branch.
Pre-checks:
Review:
=> DOC-2344 Add 6.8 EOS date to 6x branch.

modules/ROOT/partials/integrations/react-tech-ref.adoc
Ticket: DOC-2334
Site: [DOC-2334 site](http://docs-hotfix-70-doc-2334.staging.tiny.cloud/docs/tinymce/latest/react-ref/)
Changes:
* Added `licenseKey` to properties list
* Added `license_key` to list of overriden props in `init`
* Added `input` and `composition` related events to the available events list
Pre-checks:
Review:
=> DOC-2334: Update React Technical Reference

modules/ROOT/examples/live-demos/markdown/index.html, modules/ROOT/examples/live-demos/markdown/index.js
Ticket: DOC-2357
Site: [DOC-2357 site](http://docs-hotfix-7-doc-2357.staging.tiny.cloud/docs/tinymce/latest/markdown)
Changes:
* Update Markdown Premium Plugin demo with core basic plugins so it supports creation of `lists`.
Pre-checks:
Review:
=> DOC-2357: Update Markdown Premium Plugin demo with core basic plugins.

modules/ROOT/examples/live-demos/tiny-10682-after/index.html, modules/ROOT/examples/live-demos/tiny-10682-after/index.js, modules/ROOT/examples/live-demos/tiny-10682-before/index.html, modules/ROOT/examples/live-demos/tiny-10682-before/index.js, modules/ROOT/examples/live-demos/tiny-10682-initial/index.html, modules/ROOT/examples/live-demos/tiny-10682-initial/index.js, modules/ROOT/examples/live-demos/tiny-10789-after/index.html, modules/ROOT/examples/live-demos/tiny-10789-after/index.js, modules/ROOT/examples/live-demos/tiny-10789-before/index.html, modules/ROOT/examples/live-demos/tiny-10789-before/index.js, modules/ROOT/pages/7.0.1-release-notes.adoc
Entry: TINY-10682
Site: [Staging branch](http://docs-feature-7-doc-2354tiny-10682.staging.tiny.cloud/docs/tinymce/latest/7.0.1-release-notes/#table-of-contents)
Changes:
* DOC-2354: Add TINY-10682 release note entry
Pre-checks:
Review:
=> DOC-2354: Add TINY-10682 release note entry

.github/workflows/codeql.yml, .github/workflows/develop_6_docs.yml
Ticket: DOC-2324
Site: [Staging branch](http://docs-feature-6-doc-2324.staging.tiny.cloud/docs/tinymce/6/)
Changes:
* Added development and codeql workflows which apply to branches and PRs against tinymce/6 branch
Pre-checks:
Review:
=> DOC-2324: Add workflow for development on 6 docs branch

.github/workflows/codeql.yml, .github/workflows/develop_6_docs.yml
Ticket: DOC-2373
Site: [Staging branch](http://docs-feature-6-doc-2373.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Updated versions in workflows
* Add support for release and staging branches for development builds
Pre-checks:
Review:
=> DOC-2373: Update versions and branches within workflows

.github/pull_request_template.md, .github/workflows/codeql.yml, .github/workflows/deploy_docs.yml
Ticket: DOC-2373
Site: N/A
Changes:
* Updated versions in workflows
* Add support for release and staging branches for development builds
* Update PR template
Pre-checks:
Review:
=> DOC-2373: Update workflow versions for main branch

antora-playbook-local.yml, package.json
Ticket: DOC-2384
Changes:
* Added local playbook and dev scripts
Pre-checks:
Review:
=> DOC-2384: Added local playbook and dev scripts

modules/ROOT/pages/math.adoc, modules/ROOT/partials/commands/math-cmds.adoc
Ticket: DOC-2375
Changes:
* Fixed a couple errors from math plugin docs
Pre-checks:
Review:
=> DOC-2375: Fix errors in Math plugin docs

modules/ROOT/pages/usage-based-billing.adoc
Ticket: DOC-2417
Site: [Staging branch](http://docs-hotfix-7-doc-2417.staging.tiny.cloud/docs/tinymce/latest/usage-based-billing/#:~:text=We%20recommend%20that,or%20staff%20changes.)
Changes:
* Update domain link, and add missing parenthesis.
Pre-checks:
Review:
=> DOC-2417: Fix domain link and add closing parenthesis.

modules/ROOT/pages/7.1.1-release-notes.adoc, modules/ROOT/pages/changelog.adoc
Ticket: DOC-2426
Changes:
* copy edits to changelog.adoc and release notes 7.1.1 prior to release.
Pre-checks:
Review:
=> DOC-2426: copy edits to changelog.adoc and release notes 7.1.1.

modules/ROOT/pages/pageembed.adoc, modules/ROOT/pages/permanentpen.adoc, modules/ROOT/pages/tinydrive-dropbox-integration.adoc
Ticket: DOC-2432
Changes:
* remove missed `button` reference in previous DOC-2432 PR.
Pre-checks:
Review:
=> DOC-2432: Remove `button` text reference.

modules/ROOT/nav.adoc, modules/ROOT/pages/7.1.1-release-notes.adoc, modules/ROOT/pages/7.1.2-release-notes.adoc, modules/ROOT/pages/changelog.adoc, modules/ROOT/pages/release-notes.adoc
Ticket: DOC-2433
Site: [Staging branch](http://docs-release-712.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* TinyMCE `7.1.2` release documentation.
Pre-checks:
Review:
=> DOC-2433: TinyMCE `7.1.2` release documentation.

modules/ROOT/examples/live-demos/ai/example.js, modules/ROOT/examples/live-demos/ai/index.js, modules/ROOT/pages/ai-openai.adoc, modules/ROOT/partials/configuration/ai_request.adoc
Reverts tinymce/tinymce-docs#3324
=> Revert "DOC-2441: update ai assistant to use new GPT4o model."

modules/ROOT/examples/live-demos/ai/example.js, modules/ROOT/examples/live-demos/ai/index.js, modules/ROOT/pages/ai-openai.adoc, modules/ROOT/partials/configuration/ai_request.adoc
Ticket: DOC-2441
Site: [Staging branch](http://docs-hotfix-7-doc-2441.staging.tiny.cloud/docs/tinymce/latest/ai)
Changes:
* Change model in config from  “model: "gpt-3.5-turbo"  to “model: 'gpt-4o'“.
* Increase max_tokens from 800 to 4000 to match tiny.cloud AI demos.
* Add markdown fix to match tiny.cloud AI demos.
Pre-checks:
Review:
=> DOC-2441: update ai assistant to use new GPT4o model.

modules/ROOT/pages/7.1.2-release-notes.adoc, modules/ROOT/pages/changelog.adoc
Ticket: DOC-2449
Site: [Staging branch](http://docs-hotfix-7-doc-2449.staging.tiny.cloud/docs/tinymce/latest/7.1.2-release-notes)
**HOTFIX**
Changes:
* Fix spelling typo in changelog.
* Grammer improvements in the 7.1.2 release notes.
Pre-checks:
- [-] Files added for `New product features`, and included a `release note` entry.
Review:
=> DOC-2449: 7.1.2 Post Release Clean-Up

modules/ROOT/pages/7.2-release-notes.adoc
Site: [Staging branch](http://docs-feature-72-doc-2446tiny-10900.staging.tiny.cloud/docs/tinymce/latest/7.2-release-notes/#math)
Changes:
* DOC-2446: Add TINY-10900 release note entry
Pre-checks:
Review:
=> DOC-2446: Add TINY-10900 release note entry

modules/ROOT/pages/changelog.adoc
Site: [Staging branch](http://docs-feature-72-doc-24462.staging.tiny.cloud/docs/tinymce/latest/changelog)
**Need PR to fix merge conflict as `release/7.2` is a protected branch.**
Changes:
* Fix merge conflict in changelog.adoc
Pre-checks:
Review:
=> Fix merge conflict in changelog.adoc

modules/ROOT/pages/changelog.adoc
Changes:
* Attempt 2 at fixing merge conflict
Pre-checks:
Review:
=> Attempt 2 at fixing merge conflict

antora-playbook.yml
Ticket: DOC-2476
Changes:
* Fix url to point to production antora UI theme package
Pre-checks:
Review:
=> DOC-2476: Update theme URL

modules/ROOT/nav.adoc, modules/ROOT/pages/7.2.1-release-notes.adoc, modules/ROOT/pages/changelog.adoc
Ticket: DOC-2466
Site: [Release notes](http://docs-feature-721-doc-2466.staging.tiny.cloud/docs/tinymce/latest/7.2.1-release-notes/#overview)
Site: [Changelog](http://docs-feature-721-doc-2466.staging.tiny.cloud/docs/tinymce/latest/changelog/#7-2-1-2024-07-03)
Changes:
* Branch contains all individual release-note entries for TinyMCE 7.2.1 release documentation.
Pre-checks:
Review:
=> DOC-2466: TinyMCE 7.2.1 Release notes & community changelog

modules/ROOT/nav.adoc, modules/ROOT/pages/7.2.1-release-notes.adoc, modules/ROOT/pages/changelog.adoc, modules/ROOT/pages/release-notes.adoc
Ticket: DOC-2465
Site: [Staging branch](http://docs-release-721.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Finalised target branch containing all changes for TinyMCE `7.2.1` release.
Pre-checks:
Review:
=> DOC-2465: TinyMCE 7.2.1 Release Documentation

.github/pull_request_template.md
Ticket: DOC-2469
Changes:
* Update pull request template
Pre-checks:
Review:
=> DOC-2469: Update pull request template

antora.yml
Ticket: DOC-2477
Site: [Staging branch](http://docs-hotfix-7-doc-2477.staging.tiny.cloud/docs/tinymce/latest/ai)
Changes:
* Update OpenAI Proxy Token
Pre-checks:
Review:
=> DOC-2477: Update OpenAI Proxy Token

antora.yml
Ticket: DOC-2477
Site: [Staging branch](http://docs-hotfix-6-doc-2477.staging.tiny.cloud/docs/tinymce/6/ai)
Changes:
* (6 Docs) Update OpenAI Proxy Token
Pre-checks:
Review:
=> DOC-2477: (6 Docs) Update OpenAI Proxy Token

modules/ROOT/pages/importword.adoc
Ticket: DOC-2489
Changes:
* remove `code` from plugin and toolbar list.
Pre-checks:
Review:
=> DOC-2489: update code block for `importword` basic-setup.

modules/ROOT/nav.adoc, modules/ROOT/pages/7.1.1-release-notes.adoc, modules/ROOT/pages/docx-to-html-converter-api.adoc, modules/ROOT/pages/export-to-pdf-standalone-service.adoc, modules/ROOT/pages/export-to-word-standalone-service.adoc, modules/ROOT/pages/html-to-docx-converter-api.adoc, modules/ROOT/pages/html-to-pdf-converter-api.adoc, modules/ROOT/pages/import-from-word-standalone-service.adoc
Ticket: DOC-2440
Changes:
* [Export to PDF](http://docs-hotfix-7-doc-2440.staging.tiny.cloud/docs/tinymce/latest/html-to-pdf-converter-api/)
* [HTML to DOCX](http://docs-hotfix-7-doc-2440.staging.tiny.cloud/docs/tinymce/latest/html-to-docx-converter-api/)
* [DOCX to HTML](http://docs-hotfix-7-doc-2440.staging.tiny.cloud/docs/tinymce/latest/docx-to-html-converter-api/)
Pre-checks:
Review:
=> DOC-2440: Document Converters Self-Hosted Advert Pages.

modules/ROOT/pages/7.3-release-notes.adoc
Site: [Staging branch](http://docs-feature-73-doc-2463tiny-10999.staging.tiny.cloud/docs/tinymce/latest/7.3-release-notes/#added-success-notification-when-all-misspellings-are-resolved)
Changes:
* added fix documentation for TINY-10999
Pre-checks:
Review:
=> DOC-2463: Added success notification when all misspellings are resolved.

antora-playbook.yml
Ticket: DOC-2499
Test locally - change to main branch
Changes:
* UI Bundle will be fetched every time
Pre-checks:
Review:
=> DOC-2499: Remove UI Bundle Caching

modules/ROOT/pages/comments-commands-events-apis.adoc
Ticket: DOC-<num>
Site: [Staging branch](http://docs-feature-74-doc-2524doc-2535.staging.tiny.cloud/docs/tinymce/latest/comments-commands-events-apis/)
Changes:
* Updated: `pages/comments-commands-events-apis.adoc` to expand more details.
Pre-checks:
Review:
=> DOC-2524: Update: Commands, Events and APIs (Comments)

modules/ROOT/pages/comments-toolbars-menus.adoc, modules/ROOT/partials/toolbar-button-ids/comments-toolbar-buttons.adoc
Ticket: DOC-2524
Site: [Staging branch](http://docs-feature-74-doc-2524doc-2530.staging.tiny.cloud/docs/tinymce/latest/comments-toolbars-menus/)
Changes:
* minor updates to:
* `pages/comments-toolbars-menus.adoc`
* `partials/toolbar-button-ids/comments-toolbar-buttons.adoc`
Pre-checks:
Review:
=> DOC-2524: Update: Toolbar Buttons and Menu Items (Comments)

.github/CODEOWNERS
Ticket: DOC-2549
Changes:
* Include specific users to be added automatically when new pull request is opened.
Pre-checks:
Review:
=> DOC-2549: Update `tinymce/7` CODEOWNERS to include specific members from org for pull requests.

.github/CODEOWNERS
Ticket: DOC-2549
Changes:
* Include specific users to be added automatically when new pull request is opened.
Pre-checks:
Review:
=> DOC-2549_v6: Update `tinymce/6` CODEOWNERS to include specific members from org for pull requests.

modules/ROOT/partials/misc/supported-versions.adoc
Ticket: DOC-2571
Site: [Staging branch](http://docs-hotfix-7-doc-2571.staging.tiny.cloud/docs/tinymce/latest/support)
Changes:
* Changed the support information.
Pre-checks:
Review:
=> DOC-2571: Updated the support information.

modules/ROOT/partials/misc/supported-versions.adoc
Ticket: DOC-2571
Site: [Staging branch](http://docs-hotfix-6-doc-2571.staging.tiny.cloud/docs/tinymce/6/support)
Changes:
* Updated the content of the support information.
Pre-checks:
Review:
=> DOC-2571: Updated the support information for TinyMCE 6.

modules/ROOT/partials/configuration/mentions_fetch.adoc
Ticket: DOC-2579
Site: [Staging branch](http://docs-hotfix-7-doc-2579.staging.tiny.cloud/docs/tinymce/latest/mentions/#example-using-mentions_fetch)
Changes:
* update example to reflect changes made in [this demo](https://github.com/tinymce/tinymce-docs/pull/3511)
Pre-checks:
Review:
=> DOC-2579: Update the example using `mentions_fetch` to reflect demo changes.

modules/ROOT/pages/7.6.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11462.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#add-detailed-issue-description-to-accessibility-checker)
Changes:
* Documented the improvement for TINY-11462.
Pre-checks:
Review:
=> DOC-2578: Enhanced accessibility checker UI to display affected content

modules/ROOT/pages/7.6.1-release-notes.adoc
Ticket: DOC-3129
Site: [Staging branch](http://docs-hotfix-7-doc-3129.staging.tiny.cloud/docs/tinymce/latest/7.6.1-release-notes/#overview)
Changes:
* Fixed typo in 7.6.1 release documentation: DOC-3129
Pre-checks:
Review:
=> DOC-3129: Fixed typo.

modules/ROOT/pages/7.7.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11715.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#improved-visual-separation-of-comments-side-panel-header)
Changes:
* Documented the bug fix for TINY-11715.
Pre-checks:
Review:
=> DOC-3132: Improved visual separation of comments side panel header.

modules/ROOT/pages/creating-a-skin.adoc, modules/ROOT/pages/customize-ui.adoc
Ticket: DOC-3155
Site: [Staging branch](http://docs-hotfix-6-doc-3155v2.staging.tiny.cloud/docs/tinymce/6/creating-a-skin/)
Changes:
* <placeholder-text>
Pre-checks:
Review:
=> DOC-3155: Clarify skin creation instructions in UI customization documentation (TinyMCE v6).

modules/ROOT/partials/misc/admon-account-creation-and-social-option.adoc
Ticket: DOC-3168
Site: [Usage Based Billing](http://docs-hotfix-7-doc-3168.staging.tiny.cloud/docs/tinymce/latest/usage-based-billing/)
Site: [Getting Started](http://docs-hotfix-7-doc-3168.staging.tiny.cloud/docs/tinymce/latest/getting-started/)
Site: [Cloud Quick Start](http://docs-hotfix-7-doc-3168.staging.tiny.cloud/docs/tinymce/latest/cloud-quick-start/)
Site: [Introduction to Tinymce](http://docs-hotfix-7-doc-3168.staging.tiny.cloud/docs/tinymce/latest/introduction-to-tinymce/)
Site: [Invalid API Key](http://docs-hotfix-7-doc-3168.staging.tiny.cloud/docs/tinymce/latest/invalid-api-key/)
Site: [Latest](http://docs-hotfix-7-doc-3168.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Update the link in the widget (to the account creation) to include the UTM tracking.
Pre-checks: …
=> DOC-3168: Update the link in the widget (to the account creation) to include the UTM tracking.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-11757.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#accompanying-premium-plugin-changes)
Changes:
* Documented the improvement for TINY-11757.
Pre-checks:
Review:
=> DOC-3151: Adjusted spacing in accessibility checker component for better visual alignment

antora.yml
Ticket: DOC-3239
Changes:
* Port `openai_proxy_token` update to v6 docs.
Pre-checks:
Review:
=> DOC-3239: Port ai proxy update to v6 branch.
