_includes/configuration/block-formats.md

If there are spaces after the semicolon in the block_formats configuration the translation doesn't work.

Remove spaces after semicolon in block_formats configuration

---

get-started/filter-content.md

It throws an "red is not defined" error

Add quotes to literal on JS example

---

advanced/handle-async-image-uploads.md

The docs were not very clear on the fact that the name of the uploaded images are going to be repeated and that you need to come up with a unique name when you save the content. If you don't do this the second `blobid0` will overwrite the prior `blobid0`.

Added more details around image upload script requirements 

---

advanced/handle-async-image-uploads.md
get-started/upload-images.md

by adding a vaild file extension (png) to the file name.  This corrects the typo in two prior commits.

Fixed filename typos in two files 

---

_includes/configuration/language.md

The URL was pointing to a page on the old TinyMCE site.  I also removed Russian Petrine from language list as its not on the new language pack download page.

Fixed URL to language pack downloads

---

_includes/configuration/entity-encoding.md

The `&nsbp; `and `&#160;` entities were not seen on 
https://www.tinymce.com/docs/configure/content-filtering/#entity_encoding  page so modified the page to put them in code block. Also placed & < > " entities in code block

Modified the nonbreaking space entity and added block code on the entity encoding

---

plugins/tinymcespellchecker.md

Fixed the URL so that it points to the docs on the TinyMCE site for installing the server side components (as opposed to the old docs on docs.ephox.com).

Updated URL for server side component installation guide

---

plugins/tinymcespellchecker.md

Link to the toolbar config option pointed to the old site. It now refers to the current documentation.

Updated link to toolbar configuration

---

plugins/tinymcespellchecker.md

{{ site.baseurl }} as opposed to hard coding the domain and doc path.  (stick tap to r12s).

Updated URL for server side component installation guide to use

---

enterprise/paste-from-word.md

Added a note that larger images may fail to paste properly due to browser limitations.  Done at request of Tim.

Add message around larger images possibly failing to import 

---

plugins/tinymcespellchecker.md

The list of dictionaries does not reference the medical dictionaries we have for US or UK English.

Added reference to English medical dictionaries

---

_includes/configuration/automatic-uploads.md

...just cleaned up the markdown by removing a comment that was visible on the site.

Removed comment from automatic-uploads definition

---

enterprise/paste-from-word.md

by fixing the list formatting for merge as it was not setup as a list item.

Fixed typo in listing of options for powerpaste_html_import

---

plugins/code.md

I noticed that `code_dialog_width` and `code_dialog_height` were both listed as `string`s, when they should be `number`s. This PR fixes that.

Fix types of code_dialog_width and height

---

plugins/advlist.md

The decription regarding un orderd list (ul) is not correct. The list-style-type: circle, shall produce a hollow circle, where as for 'disc' it is filled.

Advlist plugin documentation mistakes

---

get-started/upload-images.md

+ fixes broken link in get-started/upload-images.md pointing to /advanced/php-upload-handler/ missing `{{ site.baseurl }}`

fix #341 get-started/upload-images.md

---

enterprise/paste-from-word.md

+ added a note regarding Word 2013 or later on Windows treatment of cut/paste content when in Protected View.

add note about Word >2013 Protected View in paste-from-word.md

---

enterprise/server.md

+ fixes commit 2c21b9 in file enterprise/server.md which reverted the file back to setting up spell check server-side components

fixes reversion to enterprise/server.md

---

get-started-cloud/index.md

fix typo in h1 of get-started-cloud/index.md

---

advanced/events.md

Obvious change in the provided example of 'Blur' event listener. It was faulty, probably due to c/p of the 'Focus' event listener example.

Changed the event type in the example of 'Blur' event listener

---

_includes/configuration/images-upload-handler.md

one of the references to `images_upload_handler` was called `image_upload_handler`.

Fix incorrect name of configuration option

---

get-started/spell-checking.md

Fixed a URL that was pointing to a now archived wiki on docs.ephox.com to a page on the TinyMCE.com documentation site.

Updated URL for documentation for Spelling link at bottom of page

---

get-started-cloud/editor-plugin-version.md
get-started-cloud/index.md

[+] the top level url for the updated Cloud docs at get-started-cloud/index.md was treated as a page, not a folder. It’s now a folder.
[+] fix minor typos in meta section of editor-plugin-version.md

Cloud Get Started index now treated as folder

---

get-started-cloud/editor-and-features.md
get-started-cloud/features-only.md
get-started-cloud/plugin-editor-version-compatibility.md

[+] `site.baseurl` = `tinymce.com/docs` and referencing this broke intended links to the download page. This should now be fixed.

fix incorrect baseurl refs

---

enterprise/advcode.md

It was out of date, referring to "TinyMCE Enterprise"

Updated link to pricing

---

enterprise/server/index.md

[+] fixes issue #521, where the link behind the text "Link Checker and Enhanced Media Embed" at the top of the page gives a 404.

fix #521 broken links on enterprise server setting

---

advanced/editor-control-identifiers.md

Per https://github.com/tinymce/tinymce/issues/3342 `bullist` and `numlist` have been moved to list plugin but docs still show core

Update documentation to reflect list plugin change

---

advanced/editor-control-identifiers.md

[+] updates href attribute text for `numlist` and `bullist` control identifiers

fixes typo in editor-control-identifiers

---

integrations/angular2.md

[+] the file system delimiter for the Windows example used slashes rather than backslashes. Fixed issue #514 from @markgoho

fixes path delimiter in integrations/angular2.md

---

plugins/autosave.md

[+] added the toolbar icon to the docs header section. Fixes #439 by @MichaelFromin.

add toolbar icon to plugins/autosave.md

---

plugins/autosave.md

[+] added webcopy noting that a toolbar button can be added (the doc previously required deduction to learn this).

add webcopy to plugins/autosave.md

---

_includes/configuration/style-formats.md
get-started/get-support.md
plugins/link.md

[+] fixes links pointing to interim forum url `tinymce.com/forum`, now points to https://community.tinymce.com/

fix links to Community

---

plugins/powerpaste.md

Fixed install SDK instructions to not reference the README file from the downloaded zip as a starting point.  Guessing this was a copy/paste from the README but that's not appropriate for the documentation site.

Fix SDK install details for PowerPaste

---

plugins/textcolor.md

Not sure what the exact type definition should be
- `List`
- `Array`
- `Array<String>`
- `String[]`
Or, even better,
- `Object<String, String>`

`textcolor_map` should be a list of strings, not a string itself

---

plugins/fullpage.md

Update the setting `fullpage_default_font_size` as it now has an underscore.
The parameter can be found on [this line in the plugin source.](https://github.com/tinymce/tinymce/blob/master/src/plugins/fullpage/src/main/js/api/Settings.js#L33)
This would clarify the docs and stop other users from making the same mistake I did.

Update fullpage_default_font_size setting

---

plugins/codesample.md

[+] adds a live Codepen to the Code Sample plugin page. Resolves GH-626. Helps explain how the plugin works for the end user.

add Codepen to plugins/codesample.md

---

plugins/advlist.md
plugins/lists.md

[+] lists.md explain that the `advlist` plugin is required to enable extended list types
[+] lists.md add link to `advlist` plugin
[+] advlist.md add link to `lists` plugin

improve lists and advlist plugins

---

_includes/configuration/allow-conditional-comments.md

Default value in docs for this property is not accurate. There is no defined value for `allow_conditional_comments` in the default settings, so default is false. https://github.com/tinymce/tinymce/blob/114e2d6878c58d6fe452db39353cc177f842d8bd/src/core/src/main/js/EditorSettings.js#L61
This causes confusion for users, ex https://github.com/tinymce/tinymce/issues/1620. And we can now remove the `// confirmation required` comment left by original contributor 😄 .

fix default value for allow_conditional_comments

---

advanced/creating-a-plugin.md

The getMetadata method should return a name and url property.
Fixes: #653

Fix documentation about exposing metadata

---

plugins/tinydrive.md

We changed the format of direct uploads to not have sub directories in a deep structure.

TINY-1848: changed date format to not have subdirs for direct upload

---

_plugins/headers_anchors.rb

Header anchors creation was removed with redcarpet.. :feelsbadman:
Restored with Kramdown
/cc @shikhanansi

DX-874 Restored linking headers anchors

---

plugins/textpattern.md

We're adding a "replacement pattern" feature to the text pattern plugin. For example - write "brb" and get "Be Right Back". This PR updates the text pattern docs page.
/ Simon Fjeldså

TINY-1908: add info about replacement patterns

---

migration-from-4x.md

Reworded the onpostrender -> onSetup details, to clarify that's for toolbar and menu components. Also expanded on some of the removed and new settings for dialogs.
@shikhanansi I think this should cover what we discussed for this, but more than happy to discuss and make any additional changes.

DOCINBOX-12: Added some more details about dialog migration from 4.x -> 5.x

---

migration-from-4x.md

@shikhanansi this is the part I mentioned I missed during standup. `onCancel` and `onTabChange` are new callbacks and previously changes were detected by an `onchange` callback on each component. However now there's just a single callback function with the change data.
If it helps, here's some examples (in case you want to reword or elaborate on what I added):
TinyMCE 4.x:
```
const config = {
title: 'Insert Link',
body: [
{
name: 'text',
type: 'textbox',
size: 40,
label: 'Text to display',
onchange () {
data.text = this.value();
}
}
]
};
```
TinyMCE 5.0:
```
const config = {
title: 'Insert Link',
body: {
type: 'panel',
items: [
{
name: 'text',
type: 'input',
label: 'Text to display'
}
]
},
onChange (api, changeData) {
if (changeData.name === 'text') {
// Do something with the text to …
```

DOCINBOX-12: Added details about onChange being merged into a single callback

---

plugins/autosave.md

The default value for `autosave_restore_when_empty` is `false`, according to:
https://github.com/tinymce/tinymce/blob/master/src/plugins/autosave/main/ts/api/Settings.ts#L29

Reflect correct default settings for autosave

---

migration-from-4x.md

Issue #869. Fixed three broken links in “Migration from V4” under the “Plugin” section.

Add forward slash to broken URLs

---

plugins/visualblocks.md
plugins/visualchars.md

Reverts tinymce/tinymce-docs#795
This shouldn't have been merged yet, so reverting it until we include the actual implementation in TinyMCE.

Revert "#4643: Add visualchars_default_state option for visualchars plugin"

---

_includes/codepens/drive-demo/example.js
_includes/codepens/drive-demo/index.html
_includes/codepens/drive-demo/index.js
_includes/codepens/drive/index.js
demo/drive.md
demo/tiny-drive-demo/demo_files.json

The drive demo was using an old version of TinyMCE, so moved it to being a codepen, so it'll use the same  TinyMCE version as the rest of the demos. Also fixed an issue where the images would 404 in the drive plugin demo, because the image paths needed to move up one more level.

TINY-3174: Fixed issues with Tiny Drive demos

---

plugins/visualblocks.md
plugins/visualchars.md

This reinstates the original version (https://github.com/tinymce/tinymce-docs/pull/795) that got reverted in commit 9af454417b7e361c168fb0dfe5f491f5ed05c617 due to it being merged ahead of time.

Re-add visualchars_default_state option for visualchars plugin

---

_includes/codepens/mentions/index.js
_includes/codepens/mentions/style.css
plugins/mentions.md

I've recently re-enabled the mentions APIs: `mentions_menu_hover`, `mentions_selector` and `mentions_select` so they will work with TinyMCE 5.
Note that the current public release of mentions has some known problems which have been fixed in the latest internal build so it might be sensible to wait for those to become public before merging this.

TINY-2911: Restored and improved the documentation for the reenabled mentions APIs

---

migration-from-4x.md

Tried to add some extra details about how to migrate from using `file_browser_callback` to `file_picker_callback` since the former was removed in 5.0. This is largely based on my experience migrating MoxieManager.

Migration from using `file_browser_callback` to `file_picker_callback`

---

_includes/configuration/formats.md

Was reviewing these docs, as I wanted to link them for another issue. However I noticed that a number of the examples aren't being formatted as examples, so this should fix that.

Fixed up issues found in the content formatting examples

---

plugins/tinymcespellchecker.md

I've also fixed a couple typos in the other existing event names.
Note: These two new events only exist in the v5 implementation.

TINY-3090: Added docs on new TinyMCE 5 spellchecker events

---

_data/nav.yml
_includes/codepens/autocompleter/index.html
_includes/codepens/autocompleter/index.js
migration-from-4x.md
ui-components/autocompleter.md

I should note that the autocompleter defaults in 5.0.0 are a little different, as we've just adjusted them a little different. For example the default `minChars` in 5.0.0 was 0 instead of 1 and the default `matches` predicate was just to always return true, instead of it matching at the start of a word. So I've targeted this more so at the 5.0.1 release.
As always, please feel free to change anything if you want :smiley:

DOC-182: Documented the autocompleter api

---

plugins/importcss.md

We recently had a customer confused on how this plugin works, not understanding that the importcss plugin only uses the css brought in by the content_css setting so I thought it would be better if the content_css setting is set on all of the examples.

add content_css setting to all examples

---

_includes/codepens/custom-menu-item/index.html
_includes/codepens/custom-menu-item/index.js

@shikhanansi noticed this demo wasn't working on the staging site. Turned out to be that the codepens don't seem to like the comments in the JS file. I also removed the style.css which got removed in DOC-170 (this was missed, as it was on review at the time).

DOC-112: Fixed the custom menu item codepen/example

---

configure/editor-appearance.md
migration-from-4x.md

This setting was added back in 5.0.2.

TINY-2712: Added `fixed_toolbar_container` back to the docs

---

changelog.md

@shikhanansi still not sure how we're handling changelogs in the docs, so not sure if we should merge this to master or to develop sorry :disappointed:. I know there was some talk of removing this page and changing it to "Release Notes" or something similar, but I'd have to follow up on that.

TINY-3433: Added changelogs for the 5.0.2 community release

---

_data/nav.yml

Missed this sorry @shikhanansi in the previous PR when bringing this setting back

TINY-2712: Added fixed_toolbar_container back to the nav

---

Gemfile
Gemfile.lock
_config-local.sample.yml
_config.yml
robots.txt

Related Ticket: [WEBSITE-1358](https://ephocks.atlassian.net/browse/WEBSITE-1358)
* Added last-modified-at plugin to Jekyll for use in sitemaps.
* Modified local configuration to output sitemap.xml for testing purposes.
* Added empty robots.txt to prevent sitemap generator from outputting misleading information for search bots.
* Updated site configuration with origin and URL to point to https://www.tiny.cloud instead of https://www.tinymce.com

WEBSITE-1358 - Add sitemap.xml

---

plugins/spellchecker.md

This doesn't include details about migration, etc... it's just updating the examples atm, so we'll still need to decide if and what we want to include in the migration guide. We could also probably make improvements to the docs to detail how the dictionary, etc... part works.

DOC-214: Updated example to work with TinyMCE 5 and included examples for the addToDictionary method

---

integrations/jquery.md

Just a very minor thing I noticed when double checking some changes I made yesterday. Sorry for not catching them yesterday :disappointed:

Fixed a minor spacing issue in the jQuery integration example

---

_data/nav.yml
_includes/codepens/url-dialog/index.html
_includes/codepens/url-dialog/index.js
demo/url-dialog-demo/external-page.html
migration-from-4x.md
ui-components/dialog.md
ui-components/urldialog.md

This is my initial draft for the URL dialog functionality that we are bringing back, though with a different/new API in comparison to v4. @shikhanansi let me know if you have any questions or want something clarified :smile: 
Note: I haven't been able to test the new example works correctly, as the new API isn't deployed to cloud yet.

TINY-3382: Added docs and examples for the new URL dialog functionality

---

ui-components/customsidebar.md

`Custom sidebar` section within `UI components`:
- Added a line within `Editor sidebar API` heading about how to create a sidebar toggle button in the toolbar.
- Added more information to the `icon` sub-heading.
- Replaced the `settings` icon with `comment` icon in the example code.

feature/DOC-305: Added information on how to create a sidebar toggle button in the toolbar

---

_includes/index.html
advanced/index.md
cloud-deployment-guide/index.md
configure/index.md
demo/index.md
enterprise/index.md
general-configuration-guide/index.md
integrations/index.md
plugins/index.md
release-notes/index.md
tinydrive/getting-started/index.md
tinydrive/index.md
tinydrive/integrations/index.md
tinydrive/introduction/index.md
ui-components/index.md

**JIRA Ticket Link:** [DOC-307](https://ephocks.atlassian.net/browse/DOC-307)
* Modified TD-209 changes to index.md paths for folders as was not displaying list of entries.
* **NOTE:** The changes for TD-209 should have worked according to Jekyll/Liquid documentation but weren't.
**Index Page checks:**
* /general-configuration-guide OK
* /cloud-deployment-guide OK
* /demo OK
* /configure OK
* /plugin OK
* /ui-components OK
* /enterprise OK
* /tinydrive OK
* /advanced OK
* /integrations OK
* /release-notes OK
* Changed index cards to use nav_title if present instead of title, or title otherwise.
* **REF:** S. Nansi requested.

DOC-307 - Category/product index cards are not visible

---

plugins/wordcount.md

Just some API documentation of the word count plugin for Tiny 5.0.6
/ Simon

TINY-3578: Add examples of new wordcount api

---

integrations/angular2.md
integrations/vue.md

This is 95% about synching the documentation we already have for our [tinymce-angular](https://github.com/tinymce/tinymce-angular) and [tinymce-vue](https://github.com/tinymce/tinymce-vue) components.
/ Simon

Tiny 3582: Update integration documentation

---

_data/nav.yml
_includes/configuration/icons_url.md
configure/editor-appearance.md

Added documentation for a new `icons_url` option to Tiny 5.0.6

TINY-3585: Add documentation for icons_url option

---

configure/contributing-docs.md

Both sides were spelled in the exact same way.

Improve contributing docs examples of US English

---

advanced/usage-with-module-loaders.md

According to the updated documentation for [inline](https://webpack.js.org/concepts/loaders/#inline) syntax of loaders, you now need to append `-loader` to the end of the desired webpack loader.

Update inline syntax for webpack loaders

---

integrations/bootstrap.md

Just happened to notice this, this morning when looking around. We fixed the jquery selector a while back, but missed updating the selectors for the bootstrap docs.

Fixed the bootstrap intergration docs using an incorrect selector

---

_config.yml
_includes/tinymce-script-tag.html

The premium skins/icons demos need dispenser to be able to load, so this updates the codepens to use the new cdn.tiny.cloud domain instead.

Use cdn.tiny.cloud domain for codepens, instead of the old cloud.tinymce.com domain

---

_includes/install/cloud.md
general-configuration-guide/basic-setup.md
general-configuration-guide/multiple-editors.md
general-configuration-guide/use-tinymce-inline.md
general-configuration-guide/work-with-plugins.md
integrations/react.md

* Removed code snippet from "Loading TinyMCE by yourself" as it wasn't useful in the context of the content.
* Fixed missing referrer tags in script loads.

Added missing referrerpolicy tags to scripts in documents

---

_includes/codepens/drive-demo-dropbox/index.html
_includes/codepens/drive-demo-googledrive/index.html
_includes/codepens/drive-demo/index.html
cloud-deployment-guide/editor-and-features.md
cloud-deployment-guide/editor-plugin-version.md
cloud-deployment-guide/features-only.md
cloud-deployment-guide/plugin-editor-version-compatibility.md

This fixes the links broken by changes made for DOC-319, since it changed back to using `drive` as the url instead of `tinydrive`.

DOC-327: Changed links back to using "drive" to reflect changes in DOC-319

---

_data/nav.yml
plugins/imagetools.md

Added this as I noticed it was missing when writing up the internal R10 release notes for Bart. @spocke feel free to change anything if I've got it wrong or if you want to word things differently.

TINY-3658: Added docs for new imagetools_fetch_image function

---

_includes/configuration/contextmenu.md

This adds details about disabling the context menu and using the CTRL key to bypass the editors context menu.
Note: Setting the context menu to false wasn't an offical way to disable it, but it just so happened to have worked since 5.0.0. I've also seen it mentioned elsewhere (eg [StackOverflow](https://stackoverflow.com/a/56168371) and [browser spellchecker docs](https://www.tiny.cloud/docs/general-configuration-guide/spell-checking/#browser-basedspellchecking)) so thought it'd be good to document it here and make the code actually respect it properly (which I've done as part of TINY-3392).

DOC-232: Added missing context menu details

---

plugins/help.md

We'd used arrow functions which don't work in IE 11 and missed the closing brackets.

Fixed broken help plugin example

---

_includes/template/bodycontents.html
_includes/template/head.html

Fixed CSS/JS loads in `_includes` directory missing required `/docs` slug when running in branch/staging/prod deploys.

WEBSITE-1694 - Launcher v5 docs failing to load CSS/image/JS files

---

_includes/configuration/draggable-modal.md
configure/editor-appearance.md

Documented the `draggable_modal` config option that can be used to enable or disable dragging of modal dialogs.

feature/TINY-3873: Added information about the draggable_modal config option

---

_includes/configuration/formats.md

remove duplicate `div` from built-in formats list

remove duplicate item from built-in formats list

---

_includes/configuration/toolbar-drawer.md

Just noticed a missing space in the toolbar drawer docs.

Fixed a minor typo in the toolbar drawer docs

---

_includes/template/head.html

Update the Open Graph image (og:image) for the Documentation site to match the OG image used for the parent site (tiny.cloud).

Update the Open Graph image (og:image)

---

quick-start.md

adding missing attribute to quickstart code example. See: #1135

adding missing attribute to quickstart example

---

_data/nav.yml

Noticed that we missed adding the nav menu item in https://github.com/tinymce/tinymce-docs/pull/1140

TINY-3873: Added missing draggable_modal nav menu item

---

plugins/link.md

Removing references to lightbox and toc on the link plugin page

Fix bug on link plugin page

---

integrations/angular.md

It's up for discussion if we should just link to the Docs instructions from the GitHub integration readme's so that we don't have to mirror everything, but for now, I'm updating it to lessen any confusion since they have diverged.

Mirror tinymce-angular Docs readme with tinymce-angular GitHub readme

---

_includes/release-notes/new-features.md
migration-from-4x.md

Fixing the migration from 4.x guide using bug info in the 5.0 release notes and fixing the 5.0 release notes

fixing migration 4.x guide

---

plugins/noneditable.md

Clarified the usage of noneditable_regexp in the noneditable plugin.

Clarify usage of noneditable_regexp

---

plugins/template.md

needs verification, uncertain of `template_cdate_classes` example removing the `template_cdate_classes` line

Adding missing info to the template plugin docs

---

_includes/integrations/angular-quick-start.md
_includes/integrations/react-quick-start.md
_includes/integrations/vue-quick-start.md
general-configuration-guide/advanced-install.md
integrations/bootstrap.md
integrations/jquery.md
integrations/knockout.md
integrations/rails.md
migration-from-froala.md
quick-start.md

Renaming the "Advanced installation choices" to "Installing TinyMCE"

"advanced install options" to "installing TinyMCE"

---

plugins/hr.md

The plugin description says that it adds a toolbar button, so it feels like it adds the button by default. Instead, we need to add the 'hr' string to `toolbar`

Updated hr.md

---

_config.yml
_data/nav.yml
_includes/configuration/image_toolbar.md
_includes/configuration/language.md
cloud-deployment-guide/editor-and-features.md
configure/editor-appearance.md
plugins/quickbars.md

Updated the cloud setup docs to mention that the languages can be loaded directly from the cloud now.
I wasn't sure if we should mention that only enterprise language packs are available? As the list available is really a subset of the community languages, so I figured if we did mention it, then we'd need to include a list which might be confusing or a bit too much for this page. So @tylerkelly13 (and anyone else who has an opinion) I wanted to get your take on what you think would be best?

TINY-3652: Cloud languages

---

advanced/creating-an-icon-pack.md

Having to install gulp globally causes instability and unpredictable builds, as users could be using varying different versions and as such is considered an antipattern. The icon template repo already has gulp pinned to a specific version, so we should use that instead of making the user install gulp globally, so this PR just changes the steps to use `npx gulp` instead of `gulp`.

Updated the icon pack docs to remove the need to install gulp globally

---

_includes/integrations/angular-quick-start.md
_includes/integrations/angular-tech-ref.md
_includes/integrations/react-quick-start.md
_includes/integrations/react-tech-ref.md
_includes/integrations/vue-quick-start.md
_includes/integrations/vue-tech-ref.md

Mostly various minor syntax fixes for the code examples for the React, Angular and Vue integrations

Fix minor syntax issues in integration code examples

---

_includes/configuration/urlconverter-callback.md

The string case actually works but is a legacy thing, no reason to recommend that now

Pass function instead of string

---

demo/file-picker.md

This function is supported in all TinyMCE-supported browsers.

Remove comment about createObjectURL browser support

---

plugins/template.md

These settings were removed in TinyMCE 5 and while the setting descriptions themselves were removed, they weren't removed from the other examples.
Fixes #1465

Cleaned up template example that had removed settings

---

_includes/configuration/dockerized-hyperlinking-service.md
_includes/configuration/dockerized-spelling-service.md

Related Ticket: DOC-543
* Update dockerized self-hosted services docs for individually licensed services to match the final file structure.
DOD:
Review

update selfhosted docker service to match packs

---

release-notes/release-notes53.md

Related Ticket: DOC-542
* Add a release note for the new `imagedrop` `source` for the PowerPaste `paste_preprocess` and `paste_postprocess` options.
DOD:
Review

RN powerpaste imagedrop source for pre/postprocess

---

_includes/configuration/dockerized-hyperlinking-service.md
_includes/configuration/dockerized-image-proxy.md
_includes/configuration/dockerized-spelling-service.md

Related Ticket: DOC-416
* reducing ambiguity about location of the origins.env file for docker deployments of the server-side components.
DOD:
Review

reducing ambiguity about location of origins.env

---

_config.yml
enterprise/moxiemanager.md
plugins/moxiemanager.md

Related Ticket: DOC-539
* add a note to emphasize that moxiemanager not provided by Tiny Cloud
DOD:
Review

add note: moxiemanager not on cloud

---

plugins/spellchecker.md

Related Ticket: DOC-221
* Added a note: community spellchecker is not available on cloud
* Added spellchecker_rpc_url: 'spellchecker.php' to the example to reinforce that it requires a self-hosted backend
DOD:
Review

Add note and fix example on spellchecker

---

tinydrive/jwt-authentication.md

I found knowing JWT stands for JSON Web Token made it slightly less mysterious and more modern. (I think there was some sort of JWT in Java.) It is also best practice to spell out acronyms on first use.
DOD:
- [ x] nav.yml has been updated if applicable
- [ x] file has been included where required if applicable
- [ x] files removed have been deleted, not just excluded from the build if applicable
Review

Spell out acronym on first use

---

_config.yml
_includes/configuration/menu.md
_includes/configuration/mobile.md

Related Ticket: DOC-465
* add menubar reference to mobile option
* add mobile differences note to menu option
* fix broken link in differs_for_mobile note
DOD:
Review

improve clarity about menubar on mobile

---

advanced/usage-with-module-loaders.md

Related Ticket: DOC-549
* Updated the module loader examples to include importing the default icon pack since it was split from core in 5.3.0.
DOD:
Review

DOC-549: Update module loader examples to include importing default icons

---

plugins/colorpicker.md

* Fixed a broken link on the color picker plugin page and updated the text.
DOD:
Review

Fix a broken link on color picker plugin

---

_includes/codepens/full-featured/example.js
_includes/codepens/full-featured/index.js

* Re-enable spell-checking-as-you-type on the full-featured demo
DOD:
Review

reenabling spellcheck-as-you-type on ff demo

---

enterprise/server/configure.md
release-notes/release-notes53.md

Related Ticket: DOC-522
* Added docs on using  regex for specifying allowed-origins for server-side components
* Added release note for regex allowed-origins support
DOD:
Review

regex allowed-origins docs and RN

---

enterprise/check-links.md
enterprise/server/configure.md
release-notes/release-notes53.md

Related Ticket: DOC-521
* Document new linkchecker server-side setting `fallback-to-get`
* Add release note and cross-ref premium plugin release notes to server-side changes
* Move linkchecker config setting to server-side component page and document undocumented `enabled` setting.
* Additional minor fixes.
DOD:
Review

Doc fallback-to-get for linkcheck and consolidate

---

.github/CODEOWNERS

* moving editor-core to the front (only first 12 codeowners are added to PRs)
Pre-checks:
Review:

re-order codeowners file

---

plugins/lists.md

Related Ticket: DOC-99
* Adding simple example for lists plugin `lists_indent_on_tab` option.
Pre-checks:
Review:

add example for lists_indent_on_tab

---

plugins/paste.md

Add documentation for the pastetext toolbar button for the Paste plugin
Pre-checks:
Review:

Add documentation for the pastetext toolbar button for the Paste plugin

---

_data/nav.yml
advanced/editor-context-menu-identifiers.md

Related Ticket: DOC-563
* Add a context menu id's page alongside other id pages
Pre-checks:
Review:

add context menu ids page

---

release-notes/release-notes54.md

Related Ticket: DOC-568
* Add TinyMCE 5.4 release note for changing icon lookup to case-insensitive (https://github.com/tinymce/tinymce/pull/5717).
Pre-checks:
Review:

DOC-568: 5.4 RN icon lookup case-insensitive

---

_includes/commands/table-cmds.md
release-notes/release-notes54.md

Related Ticket: DOC-570
* Add `mcetableapplycellstyle` cmd to table plugin cmds list
* Add 5.4 release note for `mcetableapplycellstyle` cmd
Pre-checks:
Review:

DOC-570: add mcetableapplycellstyle cmd

---

_data/nav.yml
_includes/configuration/ref-time-date-formats.md
plugins/insertdatetime.md
plugins/template.md

* Add time and date format reference to template plugin page.
Pre-checks:
Review:

Add time and date format reference to template pg

---

_includes/codepens/advcode/index.html
_includes/codepens/advcode/index.js
_includes/misc/advcode-shortcuts.md
advanced/keyboard-shortcuts.md
enterprise/advcode.md
plugins/advcode.md
release-notes/release-notes54.md

Related Ticket: DOC-601
* Document new `advcode` search and replace functionality.
* Add `advcode` demo to plugin and enterprise page.
* Add release note for TinyMCE 5.4 release.
Pre-checks:
Review:

DOC-601: advcode search and replace

---

_data/nav.yml
_includes/commands/table-cmds.md
plugins/table.md
release-notes/release-notes54.md

Related Ticket: DOC-599
* Added release note for the `table_sizing_mode` option and the `mceTableSizingMode` cmd.
* Added docs for, and examples of `table_sizing_mode` option and the `mceTableSizingMode` cmd.
* Converted all the double-quotes (`"`) in examples to single-quotes (`'`) on the table plugin page.
Pre-checks:
Review:

DOC-599: table_sizing_mode and mceTableSizingMode

---

_data/nav.yml
_includes/configuration/block-unsupported-drop.md
configure/file-image-upload.md
release-notes/release-notes53.md

Related Ticket: DOC-607
* Adds the new `block_unsuuported_drop` setting.
* This renames the `Image & File upload options" page to "Image & File options" so it's more generic. I haven't changed the URL/filename though as that'd break existing links (as discussed with Tyler).
Pre-checks:
Review:

DOC-607: Re-labeled "Image/File upload options" page and added "block_unsupported_drop" setting

---

_config.yml
_includes/codepens/basic-conf/index.js
_includes/configuration/contextmenu.md
_includes/configuration/contextmenu_never_use_native.md
advanced/editor-command-identifiers.md
advanced/events.md
general-configuration-guide/basic-setup.md
general-configuration-guide/spell-checking.md
migration-from-4x.md
plugins/spellchecker.md
release-notes/release-notes54.md

Related Ticket: DOC-606
* Add a deprecation notice to 5.4 release notes for the community spellchecker
* Add admonitions to docs about deprecation of the the spellchecker
* Tidy-up some misleading demos
* Fix some language around context menus
Pre-checks:
Review:

DOC-606: Spellchecker deprecation notices

---

_data/nav.yml
_includes/codepens/readonly-demo/index.html
_includes/codepens/readonly-demo/index.js
_includes/configuration/readonly.md
configure/integration-and-setup.md

Related Ticket: DOC-348
* Document `readonly` option
* Add codepen with `readonly` option and APIs to toggle readonly status
Pre-checks:
Review:

DOC-348: readonly option with codepen

---

plugins/linkchecker.md

Related Ticket: DOC-609
* The example for the `linkchecker_preprocess` had an additional `]` that shouldn't have been there.
Pre-checks:
Review:

DOC-609: Fixed broken linkchecker_preprocess example

---

_includes/configuration/toolbar-mode.md
_includes/configuration/toolbar.md

Related Ticket: DOC-612
* Add information on how the editor determines which toolbar buttons to move to the more drawer.
Pre-checks:
Review:

DOC-612: toolbar drawer content determination

---

_data/nav.yml
release-notes/release-notes54.md

Related Ticket: DOC-607
* Add `block_unsupported_drop` option release note
Pre-checks:
Review:

DOC-607: block_unsupported_drop option release note

---

_data/nav.yml
_includes/configuration/paste-tab-spaces.md
plugins/paste.md
plugins/powerpaste.md
release-notes/release-notes542.md

Related Ticket: DOC-619
* Added the relevant documentation for the new `paste_tab_spaces` setting in TinyMCE 5.4.2.
Pre-checks:
Review:

DOC-619: Added docs for the new paste_tab_spaces setting

---

_data/nav.yml
changelog.md

Related Ticket: DOC-621
* Adds TinyMCE 5.4.2 changelog
Pre-checks:
Review:

DOC-621: Adding TinyMCE 5.4.2 changelog

---

_config.yml
advanced/security.md
general-configuration-guide/upload-images.md
plugins/image.md
plugins/imagetools.md

Related Ticket: DOC-605
* Add a note indicating that SVGs are not supported for security purposes.
Pre-checks:
Review:

DOC-605: Add svgs unsupported note to docs

---

_includes/live-demos/custom-toolbar-menu-button/index.js

Related Ticket: DOC-629 
* Added a toggle menu item type to the menu button demo. The demo is the currently the only place where we let people know which types of menuitems are available.
Pre-checks:
Review:

Added toggle menu item example to the toolbar menu button demo

---

_includes/live-demo.html

Related Ticket: https://github.com/tinymce/tinymce-docs/issues/1654
* Show or hide live demos based on currently visible tab
Fixes #1654 
Pre-checks:
Review:

#1654: Show and Hide the live demos based on current tab

---

_config.yml
_data/nav.yml
_includes/configuration/contextmenu_avoid_overlap.md
configure/editor-appearance.md
release-notes/release-notes55.md

Related Ticket: DOC-638
* Adds documentation for the new `contextmenu_avoid_overlap` setting.
Pre-checks:
Review:

DOC-638: Added documentation for new contextmenu_avoid_overlap setting

---

_config.yml
_includes/configuration/block-unsupported-drop.md
_includes/configuration/paste-tab-spaces.md
_includes/configuration/referrer_policy.md
release-notes/release-notes51.md
release-notes/release-notes514.md
release-notes/release-notes515.md
release-notes/release-notes516.md
release-notes/release-notes52.md
release-notes/release-notes521.md
release-notes/release-notes522.md
release-notes/release-notes53.md
release-notes/release-notes54.md
release-notes/release-notes542.md

* Moving "requires version" notes to above setting descriptions for consistency
* Created variable for note indicating that release notes reflect the enterprise release, not community
Pre-checks:
Review:

Moving some notes for consistency, create var for RN ent/comm note

---

_config.yml
_includes/live-demos/annotations/index.html
_includes/live-demos/basic-example/index.html
_includes/live-demos/casechange/index.html
_includes/live-demos/context-menu/index.html
_includes/live-demos/custom-menu-item/index.html
_includes/live-demos/custom-toolbar-button/index.html
_includes/live-demos/custom-toolbar-split-button/index.html
_includes/live-demos/custom-toolbar-toggle-button/index.html
_includes/live-demos/dark-mode/index.html
_includes/live-demos/drive/index.html
_includes/live-demos/format-custom/index.html
_includes/live-demos/format-painter/index.html
_includes/live-demos/full-featured/index.html
_includes/live-demos/image-tools/index.html
_includes/live-demos/open-source-plugins/index.html
_includes/live-demos/page-embed/index.html
_includes/live-demos/paste-from-word/index.html
_includes/live-demos/permanent-pen/index.html
_includes/live-demos/valid-elements/index.html
_scripts/check-links-staging.sh
general-configuration-guide/get-support.md
integrations/bootstrap.md
integrations/jquery.md
integrations/swing.md

Related Ticket: DOC-654
* replacing forum links with stackoverflow
Pre-checks:
Review:

DOC-654: replacing forum links with stackoverflow

---

release-notes/release-notes55.md

Related Ticket: DOC-660
* Add powerpaste 5.3.3 to the 5.5 release notes
Pre-checks:
Review:

DOC-660: Add powerpaste 5.3.3 to release notes

---

_data/nav.yml
_includes/configuration/language.md
release-notes/release-notes55.md

Related Ticket: DOC-656
* Deprecated premium es_MX lang pack
Pre-checks:
Review:

DOC-656: Deprecated premium es_MX lang pack

---

plugins/media.md
plugins/table.md

Related Ticket: #1660 
* Fixes #1660 
* Fixes media template callback examples
* Quick fix regarding table plugin heading
Pre-checks:
Review:

#1660: fixing media callback examples

---

plugins/linkchecker.md

Related Ticket: DOC-693
* Clarify how link checker works and circumstances that may lead to false positives.
Pre-checks:
Review:

DOC-693: Linkchecker invalid responses are marked as broken

---

_data/nav.yml
_includes/configuration/format-empty-lines.md
configure/content-formatting.md
release-notes/release-notes56.md

Related Ticket: DOC-690, TINY-6483
* Document new `format_empty_lines` setting
Pre-checks:
Review:

DOC-690: Document new format_empty_lines option

---

_data/nav.yml
release-notes/release-notes55.md

Related Ticket: TINY-6510
* Added a note about the `a11ychecker` security fix released in 5.5
* Added missing "Deprecated features" in the release notes ToC
Pre-checks:
Review:

TINY-6510: Added missing security fixes section to 5.5 release notes

---

_includes/configuration/style-formats.md
release-notes/release-notes56.md

Related Ticket: DOC-692
* New feature to add fixed named to style formats separate form the title that is currently used to generate a format name.
Pre-checks:
Review:

DOC-692: Document new name property for style_formats

---

release-notes/release-notes56.md

Related Ticket: DOC-721
* Added release notes for PowerPaste 5.4.0
Pre-checks:
Review:

DOC-721: Added PowerPaste 5.4.0 release notes

---

_includes/configuration/image-file-types.md

Related Ticket: DOC-696
* We missed `jif` in the original list, so we've added it now and this is just a minor update to reflect that.
Pre-checks:
Review:

DOC-696: Added `jif` to image_file_types default extensions list

---

ui-components/autocompleter.md

Related Ticket: DOC-726
1. In order to activate the Autocompleter the user must precede the trigger character with some separator (tab, space, newline). This need some clarification in documentation.
2. Improve typing for trigger character. Now we have: String. Better it to be: String(of one character). Because TinyMCE currently doesn't  support multicharacter trigger
Pre-checks:
Review:

DOC-726: Clarify autocompleter trigger character documentation

---

enterprise/server/index.md

Related Ticket: DOC-727
* Export was missing in the list of details for what plugins use the image proxy.
Pre-checks:
Review:

DOC-727: Added missing export details for server-side components

---

release-notes/release-notes56.md

Related Ticket: DOC-723
* Add release notes for upcoming spell checker pro update
Pre-checks:
Review:

DOC-723: Add Spell Checker Pro release notes for 5.6

---

changelog.md
release-notes/release-notes56.md

* This adds a changelog/release note entry for the `codesample` ReDoS security issue discovered that we'd fixed in 5.6.0 by upgrading Prism.js.
Pre-checks:
Review:

Added security release note for the ReDoS fix we did in 5.6

---

release-notes/release-notes57.md

Related Ticket: DOC-739
* Adds a release note for the new audio/video live embeds enhancement. I didn't update the option, as it was already vague and never mentioned it only worked for iframes previously.
Pre-checks:
Review:

DOC-739: Added release notes for the media live embed enhancement

---

_data/nav.yml
_includes/integrations/webcomponent-tech-ref.md
_includes/live-demos/classic/index.js
_includes/live-demos/full-featured/example.js
_includes/live-demos/full-featured/index.js
_includes/plugin-apis/tinymcespellchecker-apis.md
plugins/premium/tinymcespellchecker.md
release-notes/release-notes57.md

Related Ticket: DOC-738
- Rename from `whitelist` to `ignorelist` (backwards compatible)
- Support multiple languages in `ignorelist`
- New `addIgnoredWords` API
Pre-checks:
Review:

DOC-738: Changes to spellchecker_whitelist/ignorelist option

---

release-notes/release-notes57.md

Related Ticket: DOC-742
Minor enhancement note for changes to `lists` plugin behaviour on selections across multiple text blocks.
Pre-checks:
Review:

DOC-742: Document changes to lists plugin with multiple text blocks selected

---

plugins/opensource/advlist.md
plugins/opensource/anchor.md
plugins/opensource/autoresize.md
plugins/opensource/bbcode.md
plugins/opensource/charmap.md
plugins/opensource/directionality.md
plugins/opensource/emoticons.md
plugins/opensource/fullpage.md
plugins/opensource/hr.md
plugins/opensource/image.md
plugins/opensource/importcss.md
plugins/opensource/insertdatetime.md
plugins/opensource/media.md
plugins/opensource/nonbreaking.md
plugins/opensource/noneditable.md
plugins/opensource/pagebreak.md
plugins/opensource/paste.md
plugins/opensource/preview.md
plugins/opensource/print.md
plugins/opensource/save.md
plugins/opensource/searchreplace.md
plugins/opensource/spellchecker.md
plugins/opensource/tabfocus.md
plugins/opensource/table.md
plugins/opensource/template.md
plugins/opensource/textpattern.md
plugins/opensource/toc.md
plugins/opensource/visualblocks.md
plugins/opensource/visualchars.md
plugins/opensource/wordcount.md

* removing confusing information from introduction on plugin pages
Pre-checks:
Review:

removing confusing information from introduction

---

_data/nav.yml
_includes/live-demos/premiumskinsandicons-bootstrap/index.js
enterprise/premium-skins-and-icon-packs/bootstrap-demo.md
enterprise/premium-skins-and-icon-packs/index.md
release-notes/release-notes57.md

Related Ticket: DOC-751
* Adds a release note for the new bootstrap icon pack.
* Updates the skin/icon compatibility matrix.
* Updates the bootstrap demo to use the bootstrap icon pack (won't work until it's on cloud though). Also fixed some mino syntax issues in the demo.
Pre-checks:
Review:

DOC-751: Added documentation for new bootstrap icon pack

---

_config.yml
_includes/configuration/image_toolbar.md
_includes/configuration/insert-toolbar.md
_includes/configuration/selection-toolbar.md
_includes/live-demos/autocompleter/index.js
_includes/live-demos/quickbars/index.html
_includes/live-demos/quickbars/index.js
_includes/live-demos/quickbars/style.css
plugins/opensource/quickbars.md

Related Ticket: DOC-752
* Remove inline references from quickbars page to reduce confusion about quickbars working in iframe and inline mode
Pre-checks:
Review:

DOC-752: Remove inline references from quickbars page

---

release-notes/release-notes57.md

Related Ticket: DOC-741
* Added release note for IPv6 parsing support
Pre-checks:
Review:

DOC-741: Added IPv6 support release note

---

release-notes/release-notes57.md

…in 5ef7191
Related Ticket: Don't really have a doc ticket, but it's TINY-6457
* Copied over a line from the changelog that wasn't added until after the big changelog-copy-over
Pre-checks:
- ~[ ] (New product features only) Release Note added~
Review:

TINY-6457: Copied over a line from the changelog that wasn't added until after the big changelog-copy-over

---

_data/nav.yml
_includes/commands/advtable-cmds.md
_includes/configuration/advtable-value-series.md
plugins/premium/advtable.md
release-notes/release-notes58.md

Related Ticket: TINY-6005
* Documentation for the current work that has been done for the (table row numbering)/(series column) feature in Advanced Tables. 
Pre-checks:
- ~~[ ] (New product features only) Release Note added~~
Review:

DOC-756: Document series column feature for the advtable plugin

---

_includes/misc/beta-note.md
_includes/misc/plugin_support_table.md
_includes/plugin-apis/export-apis.md
enterprise/export.md
plugins/premium/export.md
release-notes/release-notes58.md

Related Ticket: DOC-799
* Adds a release note entry for Export 1.0.0
* Updates the export plugin page to include changes made for Export 1.0.0
* Adds the export plugin to the supported plugins page (and fixes some minor formatting issues)
Pre-checks:
Review:

DOC-799: Updated export plugin details for 1.0.0 release

---

release-notes/release-notes58.md

Related Ticket: DOC-816
* Add release notes for a11ychecker 2.3.2.
* Fixed missing "see more" link in comments release notes
Pre-checks:
Review:

DOC-816: Added A11ychecker release notes

---

release-notes/release-notes58.md

Related Ticket: DOC-816
* Add release notes for spellchecker 2.3.1.
* Fixed missing "see more" link in export release notes
Pre-checks:
Review:

DOC-817: Added Spell Checker Pro release notes

---

_includes/configuration/skin.md

* It's possible to set the `skin` option to [`false` as well as a string value](https://github.com/tinymce/tinymce/blob/7966b8b3108d354a3400f92f761dba6144b5f81d/modules/tinymce/src/plugins/importcss/main/ts/api/Settings.ts#L24-L27) (also mentioned in the `tinymce-react` repo [here](https://github.com/tinymce/tinymce-react/issues/53)). This PR updates the docs to reflect this.
Pre-checks:
Review:

Update skin.md to include the ability to set the value to false

---

_includes/configuration/event-root.md
_includes/configuration/fixed-toolbar-container.md
_includes/configuration/hidden-input.md
_includes/configuration/toolbar-persist.md
release-notes/release-notes52.md

* changing selector for inline examples (textarea to div) 
Pre-checks:
Review:

textarea selector to div for inline examples

---

_includes/misc/support-powerpaste.md
plugins/premium/powerpaste.md
release-notes/release-notes58.md

Related Ticket: DOC-811
* Added new `powerpaste_googledocs_import` setting details
* Added PowerPaste 5.5.0 release notes
* Fixed some incorrect `setting` references (should be `option` in the docs)
**Note:** Known issues will be done in a separate PR.
Pre-checks:
Review:

DOC-811: Added PowerPaste release notes and documented gdocs support

---

_includes/template/menu.html

Related Ticket: WSRF-243
* Using **6 KB** SVG logo instead of **76 KB** PNG to reduce download size.
Pre-checks:
Review:

WSRF-243: Use .svg header logo instead of .png

---

rtc/jwt-authentication.md

Related Ticket: TINY-7537
* require exp to be the unix timestamp
Pre-checks:
- ~[ ] (New product features only) Release Note added~
Review:

TINY-7537: exp should be unix timestamp

---

_includes/template/head.html

Related Ticket: WSRF-244
* Removed Avenir font load from fonts.net in favor of locally hosted files
* Defer the loading of the third-party `docsearch.min.css`
* Remove the link to the `docs.min.css` since it’s contents are now inlined in the `_docs/head.html` partial
Pre-checks:
- [n/a] `_data/nav.yml` has been updated (if applicable)
- [n/a] Files has been included where required (if applicable)
- [n/a] Files removed have been deleted, not just excluded from the build (if applicable)
- [n/a] (New product features only) Release Note added
Review:
- [N/A] Product Manager has reviewed

WSRF-244: Docs performance tweaks

---

_data/nav.yml

* I noticed the autocompleter example nav link was broken due to a rename that happened ~9months ago. This fixes the 2 cases I found that were incorrect.
Pre-checks:
Review:

Fixed 2 broken nav links due to headings being renamed

---

enterprise/server/index.md
enterprise/system-requirements.md

Document changes to Tomcat and Jetty regarding the move from javax to jakarta
for servlets.
Related Ticket: DOC-849
* Update supported version of tomcat and jetty
* Added notes detailing how to use our applications with Tomcat 10
Pre-checks:
Review:

DOC-849: Add documentation about Jakarta servlet updates

---

_includes/configuration/table_background_color_map.md
_includes/configuration/table_border_color_map.md
release-notes/release-notes59.md

Related Ticket: DOC-864
* Clarify that the new table color map options do not apply to the table dialog
* Fix some missing full stops
Pre-checks:
Review:

DOC-864: Clarify that the new table color map options do not apply to the table dialog

---

_includes/configuration/language.md

* The URLs for : Using the premium language packs and : Using the community language packs got switched
* Changed the order of subsections
Pre-checks:
Review:

Fix language pack links and swapped lang pack sections

---

_includes/live-demos/autocompleter-autocompleteitem/index.html
_includes/live-demos/autocompleter-autocompleteitem/index.js
_includes/live-demos/comments-callback/example.js
_includes/live-demos/comments-callback/index.html
_includes/live-demos/comments-callback/index.js
_includes/live-demos/comments-embedded/index.html
_includes/live-demos/comments-embedded/index.js
_includes/live-demos/dialog-pet-machine/index.html
_includes/live-demos/dialog-pet-machine/index.js
_includes/live-demos/file-picker/index.html
_includes/live-demos/file-picker/index.js
_includes/live-demos/format-html5/index.html
_includes/live-demos/format-html5/index.js
_includes/live-demos/notifications/index.html
_includes/live-demos/notifications/index.js
_includes/live-demos/open-source-plugins/index.html
_includes/live-demos/open-source-plugins/index.js
_includes/live-demos/redial-demo/index.html
_includes/live-demos/redial-demo/index.js
_includes/live-demos/url-dialog/example.js
_includes/live-demos/url-dialog/index.html
_includes/live-demos/url-dialog/index.js
ui-components/dialog.md

Related Ticket: TINY-7894
The live demos for the docs requires the demo name and the id used for the editor to be the same. This is a bit of a flaw and it doesn't work with demos that have multiple editors (e.g. inline, distraction free, RTC, etc...). As such we probably need to look at changing how that logic works but I want to talk to @tylerkelly13 about that first. So for now this fixes a number of issues reported as side notes in TINY-7894, which was caused by the editor not being hidden when swapping tabs.
Pre-checks:
Review:

TINY-7894: Fixed incorrect live demo ids which caused the editor to not hide when swapping tabs

---

_includes/configuration/rtc_snapshot.md

The snapshot callback is not executed at regular intervals, but instead after edits are made to the document.
Snapshots are also stored on the server, but only as a editor checkpoint so operations do not need to be replayed from the beginning of the document editing session. By replacing "regular" with "HTML", the statement is more correct. There may be some HTML snapshots currently being sent to the server, but as legacy behaviour that is likely to be removed. (In all cases, these snapshots are encrypted before being sent to the server, and not readable without the client.)
Pre-checks:
Review:

Fix minor inaccuracies in RTC snapshot handling

---

_includes/integrations/angular-tech-ref.md
_includes/integrations/react-tech-ref.md
_includes/integrations/vue-tech-ref.md
cloud-deployment-guide/editor-plugin-version.md

Related Ticket: CLOUD-433
* restructured into a table to avoid duplication
* added information about new endpoint: cloud-plugins.min.js
* general restructuring
Pre-checks:
Review:

CLOUD-433: Updating specifying version documentation and documenting new endpoint

---

release-notes/release-notes5101.md

Related Ticket: DOC-981
* We're rolling back the mediaembed and pageembed releases due to an issue found in post-release checks, so this just removes the release notes for those 2 plugins.
Pre-checks:
Review:

DOC-981: Remove the mediaembed and pageembed releases notes

---

modules/ROOT/pages/editor-important-options.adoc
modules/ROOT/pages/editor-save-and-submit.adoc
modules/ROOT/pages/editor-size-options.adoc
modules/ROOT/partials/configuration/auto_focus.adoc
modules/ROOT/partials/configuration/base_url.adoc
modules/ROOT/partials/configuration/cache_suffix.adoc
modules/ROOT/partials/configuration/content_security_policy.adoc
modules/ROOT/partials/configuration/custom_ui_selector.adoc
modules/ROOT/partials/configuration/external_plugins.adoc
modules/ROOT/partials/configuration/height.adoc
modules/ROOT/partials/configuration/hidden_input.adoc
modules/ROOT/partials/configuration/init_instance_callback.adoc
modules/ROOT/partials/configuration/max_height.adoc
modules/ROOT/partials/configuration/max_width.adoc
modules/ROOT/partials/configuration/min_height.adoc
modules/ROOT/partials/configuration/min_width.adoc
modules/ROOT/partials/configuration/placeholder.adoc
modules/ROOT/partials/configuration/plugins.adoc
modules/ROOT/partials/configuration/readonly.adoc
modules/ROOT/partials/configuration/referrer_policy.adoc
modules/ROOT/partials/configuration/resize.adoc
modules/ROOT/partials/configuration/selector.adoc
modules/ROOT/partials/configuration/setup.adoc
modules/ROOT/partials/configuration/suffix.adoc
modules/ROOT/partials/configuration/taborder.adoc
modules/ROOT/partials/configuration/target.adoc
modules/ROOT/partials/configuration/width.adoc
modules/ROOT/partials/misc/admon_different_default_for_mobile.adoc

Related Ticket: DOC-1532
* Replace all liquid logic with asciidoc ifeval, etc... logic instead
* Fixed conversion issues with admonitions (these were converted to blockquotes since markdown doesn't have this concept)
* Fixed xref conversion issues (basically replace the legacy `<<id, title>>` format with `xref:id[title]`)
**Note:** I'd suggest running this locally instead of trying to review the actual markup here.
Pre-checks:
Review:

DOC-1532: Fixed markdown -> asciidoc conversion issue initial config docs

---

modules/ROOT/partials/configuration/a11ychecker_html_version.adoc
modules/ROOT/partials/configuration/element_format.adoc
modules/ROOT/partials/configuration/link_default_protocol.adoc
modules/ROOT/partials/configuration/table_style_by_css.adoc
modules/ROOT/partials/configuration/table_use_colgroups.adoc

Related Ticket:  DOC-1490
- Updated the default value of `a11ycheck_html_version`, `element_format`, `table_style_by_css`, `link_default_protocol` and `table_use_colgroups` settings. 
- Changed the wording in a few places
Pre-checks:
Review:

DOC-1490: Updated doc for default settings

---

modules/ROOT/live-demos/format-custom/index.js
modules/ROOT/live-demos/valid-elements/index.js
modules/ROOT/pages/editor-command-identifiers.adoc
modules/ROOT/partials/configuration/extended_valid_elements.adoc
modules/ROOT/partials/configuration/valid_elements.adoc

Related Ticket: DOC-987, DOC-1530, DOC-1543
* DOC-987: Document alignleft and alignright format change for tables
* DOC-1530: Document mceAddEditor and mceToggleEditor command value change
* DOC-1543: Update valid_elements documentation to replace : with ~
Pre-checks:
Review:

DOC-987/DOC-1530/DOC-1543: Document format, command, schema changes

---

modules/ROOT/pages/a11ychecker.adoc

Related Ticket: TINY-8559
* Added back the ids needed for the relevant a11ychecker rules so that links from the plugin will work
Pre-checks:
Review:

TINY-8559: Added back ids lost during conversion

---

modules/ROOT/pages/editimage.adoc
modules/ROOT/pages/editor-and-features.adoc
modules/ROOT/pages/export.adoc
modules/ROOT/pages/features-only.adoc
modules/ROOT/pages/introduction-to-premium-selfhosted-services.adoc
modules/ROOT/pages/tableofcontents.adoc
modules/ROOT/partials/configuration/image_proxy.adoc
modules/ROOT/partials/configuration/image_proxy_service_url.adoc

Related Ticket: DOC-1499
* Adds the documentation for the new `export_image_proxy_service_url` and `editimage_proxy_service_url` options
* Updates the existing `export_image_proxy` and `editimage_proxy` options to clarify they should only be used with third-party or custom proxy options.
* Removes the old example proxy.php script, as we'd prefer customers using the image proxy service we provide.
* Fixes an issue with the editimage and tableofcontents pages missing the premium include at the top to detail how to get it.
* Fixes an issue on the editmage page where the options where using the wrong heading levels.
Pre-checks:
Review:

DOC-1499: Added documentation for the new image proxy service url options

---

antora.yml

* Add [Beta] to the docs title, to make it clear this is not production grade docs
Pre-checks:
Review:

DOC-1587: Add beta prefix to docs title

---

modules/ROOT/pages/powerpaste-commands-events-apis.adoc
modules/ROOT/partials/commands/powerpaste-cmds.adoc

* Added mceInsertClipboardContent command to list of PowerPaste commands
* Updated command description to describe paste path for PowerPaste, and replaced term content with html
* Updated PowerPaste commands description to be plural
Pre-checks:
Review:

DOC-1573: Updated PowerPaste command documentation

---

.github/workflows/feature_6_docs.yml
package.json
yarn.lock

Related Ticket: DOC-1601
* Upgrade to the latest moxiedoc version to pull in the fix to use `xref` macros for linking
* Update the feature branch git workflow to upload to the `/docs/` prefix
Pre-checks:
Review:

DOC-1601: Upgrade to the latest moxiedoc version and fix the feature branch deploy paths

---

modules/ROOT/examples/live-demos/web-component/example.html
modules/ROOT/pages/editor-command-identifiers.adoc
modules/ROOT/partials/install/basic-quickstart-base.adoc
modules/ROOT/partials/install/upgrading-info.adoc
modules/ROOT/partials/integrations/bootstrap-quick-start.adoc
modules/ROOT/partials/integrations/expressjs-quick-start.adoc
modules/ROOT/partials/integrations/laravel-quick-start.adoc
modules/ROOT/partials/integrations/rails-quick-start.adoc
modules/ROOT/partials/integrations/svelte-quick-start.adoc
modules/ROOT/partials/integrations/swing-quick-start.adoc
modules/ROOT/partials/integrations/webcomponent-quick-start.adoc

Related Ticket: DOC-1579
This is largely just some further fixes/enhancements for things I found to what was already done in https://github.com/tinymce/tinymce-docs/pull/2292. It turns out the content used between the `Getting started` and `How-to guides` section is exactly the same as they both link to the same URLs.
Pre-checks:
Review:

DOC-1579: Updated the snippets and demos in the Getting started section

---

modules/ROOT/pages/events.adoc

Related Ticket: DOC-1550
Pre-checks:
Review:

DOC-1550: Add deprecation message to SetContent event

---

modules/ROOT/pages/editor-command-identifiers.adoc

Related Ticket: DOC-1567
* Added autocompleter commands
* Added native commands that were re-implemented in core
* Removed the `mceInsertRawHTML` command
Pre-checks:
Review:

DOC-1567: Updated the editor commands documentation

---

_new_content_templates/blank_releasenotes.adoc
modules/ROOT/pages/changelog.adoc
modules/ROOT/pages/enterprise/server/configure.adoc
modules/ROOT/pages/plugins/premium/tinymcespellchecker.adoc
modules/ROOT/pages/release-notes/6.0-upcoming-changes.adoc
modules/ROOT/pages/release-notes/release-notes510.adoc
modules/ROOT/pages/release-notes/release-notes5101.adoc
modules/ROOT/pages/release-notes/release-notes5102.adoc
modules/ROOT/pages/release-notes/release-notes53.adoc
modules/ROOT/pages/release-notes/release-notes59.adoc
modules/ROOT/partials/configuration/advtable_value_series.adoc
modules/ROOT/partials/configuration/autoresize_on_init.adoc
modules/ROOT/partials/configuration/convert_fonts_to_spans.adoc
modules/ROOT/partials/configuration/file_picker_types.adoc
modules/ROOT/partials/configuration/media_scripts.adoc
modules/ROOT/partials/configuration/paste_convert_word_fake_lists.adoc
modules/ROOT/partials/configuration/paste_retain_style_properties.adoc
modules/ROOT/partials/configuration/paste_word_valid_elements.adoc
modules/ROOT/partials/configuration/rtc_token_provider.adoc
modules/ROOT/partials/configuration/spellchecker_ignore_list.adoc
modules/ROOT/partials/configuration/spellchecker_select_languages.adoc
modules/ROOT/partials/configuration/tabfocus_elements.adoc
modules/ROOT/partials/configuration/target.adoc
modules/ROOT/partials/install/upgrading-info.adoc
modules/ROOT/partials/misc/releasenotes_for_stable.adoc

It covers:
- Changelog
- Release TinyMCE 6.0
- Release TinyMCE 5.10.2
- Release TinyMCE 5.10.1
- Release TinyMCE 5.10
Pre-checks:
Review:

Feature/tinymce5update 3 releases 6 to 5.10

---

modules/ROOT/pages/advanced/events.adoc
modules/ROOT/pages/plugins/opensource/table.adoc
modules/ROOT/pages/plugins/premium/tinymcespellchecker.adoc
modules/ROOT/pages/release-notes/release-notes56.adoc
modules/ROOT/pages/release-notes/release-notes562.adoc
modules/ROOT/pages/release-notes/release-notes57.adoc
modules/ROOT/pages/release-notes/release-notes571.adoc
modules/ROOT/pages/ui-components/autocompleter.adoc
modules/ROOT/partials/configuration/emoticons_database.adoc
modules/ROOT/partials/configuration/emoticons_images_url.adoc
modules/ROOT/partials/configuration/font_css.adoc
modules/ROOT/partials/configuration/images_file_types.adoc
modules/ROOT/partials/configuration/media_live_embeds.adoc
modules/ROOT/partials/configuration/spellchecker_ignore_list.adoc
modules/ROOT/partials/configuration/table_column_resizing.adoc
modules/ROOT/partials/misc/releasenotes_for_stable.adoc

Description of Changes, it covers:
- Release TinyMCE 5.7.1
- Release TinyMCE 5.7
- Release TinyMCE 5.6.2
- Release TinyMCE 5.6
Pre-checks:
Review:

Feature/tinymce5update 3 releases 5.7.1 to 5.6

---

antora.yml

Related Ticket: DOC-1619
* Renamed the `Tiny Cloud Community Plan` to `Tiny Cloud Core Plan
Pre-checks:
Review:

DOC-1619: Rename community plan to core plan

---

modules/ROOT/examples/live-demos/full-featured/example.js
modules/ROOT/examples/live-demos/full-featured/index.js
modules/ROOT/examples/live-demos/open-source-plugins/index.js

Related Ticket: DOC-1618
* Added the `toolbar_sticky_offset` configuration for the full featured demos.
* Note: It doesn't use advanced logic such as looking up the element and getting the exact bounding client rect or similar as this is meant to be a simple demo. This unfortunately however does mean it may overlap or have gaps should the UI change in the future.
* Enabled sticky toolbar on the premium full featured demo. This was done as it doesn't make sense to have it on the Opensource one but not the premium one.
Pre-checks:
Review:

DOC-1618: Fixed sticky toolbars on full featured demos

---

modules/ROOT/examples/live-demos/tableofcontents/index.html
modules/ROOT/examples/live-demos/tableofcontents/index.js
modules/ROOT/pages/tableofcontents.adoc

Related Ticket: DOC-1606
Adds a new Table of Contents demo based on our normal template just with some initial content to explain how it works.
Pre-checks:
Review:

DOC-1606: Added a demo for the table of contents plugin

---

modules/ROOT/pages/tinydrive-jwt-authentication.adoc
modules/ROOT/partials/configuration/custom_elements.adoc
modules/ROOT/partials/configuration/editimage_credentials_hosts.adoc
modules/ROOT/partials/configuration/filetypes.adoc
modules/ROOT/partials/configuration/image_cors_hosts.adoc
modules/ROOT/partials/configuration/importcss_file_filter.adoc
modules/ROOT/partials/configuration/importcss_groups.adoc
modules/ROOT/partials/configuration/importcss_selector_filter.adoc
modules/ROOT/partials/configuration/link_assume_external_targets.adoc
modules/ROOT/partials/configuration/menubar.adoc
modules/ROOT/partials/configuration/paste_block_drop.adoc
modules/ROOT/partials/configuration/powerpaste_allow_local_images.adoc
modules/ROOT/partials/configuration/powerpaste_clean_filtered_inline_elements.adoc
modules/ROOT/partials/configuration/powerpaste_keep_unsupported_src.adoc
modules/ROOT/partials/configuration/spellchecker_ignore_list.adoc
modules/ROOT/partials/configuration/spellchecker_languages.adoc
modules/ROOT/partials/configuration/table_clone_elements.adoc
modules/ROOT/partials/configuration/tinydrive_dropbox_app_key.adoc
modules/ROOT/partials/configuration/tinydrive_google_drive_client_id.adoc
modules/ROOT/partials/configuration/tinydrive_google_drive_key.adoc
modules/ROOT/partials/integrations/angular-tech-ref.adoc
modules/ROOT/partials/integrations/blazor-tech-ref.adoc
modules/ROOT/partials/integrations/react-tech-ref.adoc
modules/ROOT/partials/integrations/svelte-tech-ref.adoc
modules/ROOT/partials/integrations/vue-tech-ref.adoc

Related Ticket: DOC-1607
This just includes the various fixes for things regarding option inconsistencies that @ltrouton pointed out or that I found when looking further that weren't in the original scope:
- Cleanup the inconsistent ordering and markup in the integrations tech references
- Ensure consistent casing of `String`, etc...
- Ensure consistent use of `Array` since we had three variants in use: `Array`, `Array<string>` and `String[]`
- Fixed missing `Type` fields
- Removed the incorrect default for `custom_elements`
Pre-checks:
Review:

DOC-1607: Additional options cleanup fixes identified during review

---

modules/ROOT/examples/live-demos/open-source-plugins/index.html
modules/ROOT/pages/pagebreak.adoc
modules/ROOT/pages/release-notes.adoc
modules/ROOT/partials/configuration/images_reuse_filename.adoc
modules/ROOT/partials/configuration/images_upload_credentials.adoc

Related Ticket: DOC-1623
* Fixed a markup and minor content issue in the pagebreak docs
* Fixed other minor markup issues found on the Image and file options page
Pre-checks:
Review:

DOC-1623: Fixed more missed conversion issues

---

modules/ROOT/partials/configuration/link_default_protocol.adoc
modules/ROOT/partials/configuration/link_default_target.adoc

Related Ticket: DOC-1608
* Update `link_default_protocol` and `link_default_target` documentation to show correct plugin in admonition.
Pre-checks:
Review:

DOC-1608: Update admonitions for shared link and autolink options

---

.github/workflows/feature_5_legacy_docs.yml
.github/workflows/release_5_legacy_docs.yml
.github/workflows/staging_5_legacy_docs.yml

Related Ticket: DOC-1640
* Swap to using different AWS keys as the current ones only work for Antora buckets
Pre-checks:
Review:

DOC-1640: Use the legacy AWS secrets instead

---

.github/workflows/feature_6_docs.yml
.github/workflows/release_6_docs.yml
.github/workflows/staging_6_docs.yml

Related Ticket: DOC-1640
This just contains a couple fixes for things I found when creating the new worflows for the legacy docs:
* Replaces `6.0` references with just `6` to match what's published
* Fixes the S3_BUCKET warnings as they were always warning that they were too small (0 chars)
Pre-checks:
Review:

DOC-1640: Fixed minor issues with the workflow configuration

---

modules/ROOT/pages/configure-spelling-service.adoc
modules/ROOT/pages/introduction-to-tiny-spellchecker.adoc
modules/ROOT/partials/configuration/advtable_value_series.adoc
modules/ROOT/partials/configuration/rtc_token_provider.adoc
modules/ROOT/partials/events/tinymcespellchecker-events.adoc
modules/ROOT/partials/misc/num-incorrect-words-in-suggestions-request-limit.adoc

Related Ticket: DOC-1643
* There looks to have been an issue where some commits from the v5 docs branches were missed being included in the v6 docs branches. The main one missed was the file changes for the 5.10 docs release (#2145). Potentially other commits were missed- this has to be looked into separately. This PR adds back some of the files changes made in the 5.10 docs release.
Pre-checks:
Review:

DOC-1643: Add missing content changes from 5.10 release

---

modules/ROOT/examples/live-demos/basic-example/index.js
modules/ROOT/examples/live-demos/context-menu/index.js
modules/ROOT/examples/live-demos/edit-image/index.js
modules/ROOT/pages/basic-setup.adoc
modules/ROOT/partials/commands/editimage-cmds.adoc
modules/ROOT/partials/release-notes/6.0-release-notes-summary.adoc

Related Ticket: DOC-1651
* Fixed `code` duplicated in the basic example demo and removed the `menubar: false` which prevented some plugins being used.
* Removed the `insertfile` toolbar item from docs/demos where it couldn't be used.
* Fixed an incorrect option name in the migration guide.
* Removed `lists` from the contextmenu demo as it wasn't usable and isn't meant to be overly visible.
* Fixed some typos/grammar issues in the `editimage` commands.
Pre-checks:
Review:

DOC-1651: Various minor docs fixes

---

modules/ROOT/pages/changelog.adoc

Related Ticket: DOC-1642
* Merge release/docs-6 into staging/docs-6 which includes the changelog entries for TinyMCE 6.0.2
Pre-checks:
Review:
When merging:

DOC-1642: Merge release/docs-6 into staging/docs-6

---

modules/ROOT/nav.adoc
modules/ROOT/pages/changelog.adoc
modules/ROOT/pages/release-notes/release-notes5103.adoc

Related Ticket: DOC-1562
* Add missing changelog sections for 5.10.3 and 5.10.4
* Add and convert missing release notes files for 5.10.3 (I am not sure if this should be done separately so can remove it if necessary)
Pre-checks:
Review:

DOC-1562: Add latest TinyMCE changelog and release notes

---

modules/ROOT/pages/work-with-plugins.adoc

Related Ticket: DOC-1638
* Fixed the "Work with plugins to extend TinyMCE" page using advlist without the lists plugin
Pre-checks:
Review:

DOC-1638: Fixed working with plugins using advlist without the lists plugin

---

modules/ROOT/pages/rtc-jwt-authentication.adoc

Related Ticket: DOC-1641
* This line was designed to show customers the object structure required by the RTC plugin, but then we duplicated the server-side endpoint examples from Tiny Drive which already return the correct structure. So all this did was create `{ token: undefined }` objects.
* I don't like deleting it, but I can't reasonably change the server-side example. We want it to be easy to use both Tiny Drive and RTC.
Pre-checks:
Review:

DOC-1641: Remove incorrect line from JWT docs

---

modules/ROOT/partials/release-notes/6.0-release-notes-summary.adoc

Related Ticket: DOC-1664
* Fixed incorrect information around the `editimage_proxy` option.
* Added missing `Element` column values for various items.
* Removed references to `Sand` as that's an internal API and should not be mentioned in public docs.
* Messed with the table rendering a little to give columns with content more space.
Pre-checks:
Review:

DOC-1664: Fixed incorrect information in the things we renamed table

---

antora.yml
modules/ROOT/partials/integrations/jquery-quick-start.adoc

* Both jquery and webcomponent had an older version of the URLs linked.
Pre-checks:
Review:

INT-2850: Fixed the CDN URLs for jquery and webcomponent

---

modules/ROOT/partials/commands/advlist-cmds.adoc

Corrects error in example JavaScript in `advlist-cmds.adoc`.
Pre-checks:
Review:

DOC-1662: Fix incorrect advlist command examples

---

_data/nav.yml
release-notes/release-notes5105.md

Added Release Notes file for TinyMCE 5.10.5.
Pre-checks:
Review:

DOC-1673: Added Release Notes for TinyMCE 5.10.5

---

modules/ROOT/partials/misc/general-csp.adoc

The extant documentation infers that TinyMCE cannot be run from within a strict CSP environment. This edit makes the inference explicit: TinyMCE cannot, currently, run from within a strict CSP environment and this update adds a specific note to this effect.
Pre-checks:
Review:

DOC-1674: add note about strict CSP to `general-csp.adoc`

---

.github/workflows/feature_6_docs.yml
.github/workflows/release_6_docs.yml
.github/workflows/staging_6_docs.yml
modules/ROOT/pages/editimage.adoc
modules/ROOT/pages/tableofcontents.adoc

Related Ticket: DOC-1724
* Update minimum plan tier for Table of Contents and Enhanced Image Editing premium plugins
Pre-checks:
- ~[x] `modules/ROOT/nav.adoc` has been updated (if applicable)~
- ~[x] Files has been included where required (if applicable)~
- ~[x] Files removed have been deleted, not just excluded from the build (if applicable)~
- ~[x] (New product features only) Release Note added~
Review:

DOC-1724: Update ToC and EditImage minimum plans

---

modules/ROOT/pages/comments-embedded-mode.adoc
modules/ROOT/partials/configuration/tinycomments_author_avatar.adoc
modules/ROOT/partials/configuration/tinycomments_author_name.adoc
modules/ROOT/partials/configuration/tinycomments_lookup.adoc
modules/ROOT/partials/misc/admon-requires-6.1v.adoc

Related Ticket: DOC-1658
* Added the `tinycomments_author_avatar` option to the comments embedded page and added a note about the URL not being able to be changed once a comment is added.
* Added the `authorAvatar` property details to the `tinycomments_lookup` callback mode option. I didn't add the warning here as the avatar can safely be changed at anytime for callback mode.
* Removed a note about Comments 2.1 in `tinycomments_author_name` as that was only useful for the 5.x docs.
Pre-checks:
Review:

DOC-1658: Added documentation for the comments avatar changes

---

modules/ROOT/partials/configuration/end_container_on_empty_block.adoc

Related Ticket: DOC-1759
* Updated type and default value of `end_container_on_empty_block` option
Pre-checks:
Review:

DOC-1759: Updated end_container_on_empty_block

---

modules/ROOT/pages/dialog-components.adoc

Related Ticket: DOC-1760
* Document new `transparent` property for iframe UI component
Pre-checks:
Review:

DOC-1760: Document `transparent` prop for iframe UI component

---

modules/ROOT/pages/comments-using-comments.adoc
modules/ROOT/pages/customsidebar.adoc
modules/ROOT/partials/configuration/sidebar_show.adoc
modules/ROOT/partials/plugins/comments-open-sidebar.adoc

Related Ticket: DOC-1663
- Added option section to the custom sidebar page
- Updated the example of comments embedded mode to use `sidebar_show` option to show comments sidebar on load
Pre-checks:
Review:

DOC-1663: Add `sidebar_show` doc

---

modules/ROOT/pages/changelog.adoc

Related Ticket: TINY-8876
* Copy across the changelog entries for the 6.1.1 community release
Pre-checks:
Review:

TINY-8876: Add 6.1.1 changelog

---

modules/ROOT/partials/misc/supported-versions.adoc

Related Ticket: DOC-1783
* Added 6.1 to the supported versions list
* Added an End of Support date for 6.0
Pre-checks:
Review:

DOC-1783: Fixed supported versions page missing 6.1

---

modules/ROOT/pages/customsidebar.adoc

Edited javascript examples: onSetup now returns an empty function.
NB: `console.log` is still used despite it ‘not [being] a valid api function.’
* edited .js examples in customsidebar.adoc to ‘improve accuracy’.
Pre-checks:
Review:

DOC-1779: edited .js examples in customsidebar.adoc to ‘improve accuracy’.

---

modules/ROOT/pages/content-appearance.adoc
modules/ROOT/pages/customize-ui.adoc
modules/ROOT/pages/editor-premium-upgrade-promotion.adoc
modules/ROOT/partials/configuration/premium-upgrade-promotion-option.adoc
modules/ROOT/partials/configuration/promotion.adoc
modules/ROOT/partials/misc/premium-upgrade-promotion-option.adoc

* Typo fixed: s/disribution/distribution in `editor-premium-upgrade-promotion.adoc`.
* header level fixed in `premium-upgrade-promotion-option.adoc`.
Pre-checks:
Review:

Fix typos in `editor-premium-upgrade-promotion.adoc` and `premium-upgrade-promotion-option.adoc`.

---

modules/ROOT/pages/editor-premium-upgrade-promotion.adoc

Added ‘lightning bolt’ to document keywords field.
* Added ‘lightning bolt’ to keywords field.
Pre-checks:
Review:

DOC-1795: add ‘lightning bolt’ to keywords field of `editor-premium-upgrade-promotion.adoc`

---

modules/ROOT/pages/content-formatting.adoc
modules/ROOT/partials/configuration/format_noneditable_selector.adoc

Related Ticket: DOC-1768, TINY-8905
* Document new `format_noneditable_selector` option added as part of TinyMCE 6.2
Pre-checks:
Review:

DOC-1768: Document `format_noneditable_selector` option

---

modules/ROOT/pages/autocompleter.adoc
modules/ROOT/partials/misc/admon-deprecated-6.2v.adoc
modules/ROOT/partials/misc/admon-requires-6.2v.adoc

Related Ticket: DOC-1774
* Update name of `ch` single character trigger option to `trigger` option with multiple character (string) support
Pre-checks:
Review:

DOC-1774: Update autocompleter `trigger` option

---

modules/ROOT/pages/advlist.adoc
modules/ROOT/pages/lists.adoc
modules/ROOT/partials/misc/inline-formatting-of-list-bullets.adoc

* Document inline formatting’s new effect on list element (bullets and numbers).
Pre-checks:
Review:

DOC-1755: Document inline formatting’s new effect on list element (bullets and numbers)

---

antora-playbook-dev.yml
antora-playbook-staging.yml
modules/ROOT/examples/live-demos/custom-toolbar-menu-button-search/index.html
modules/ROOT/examples/live-demos/custom-toolbar-menu-button-search/index.js
modules/ROOT/pages/custom-menu-toolbar-button.adoc

Related Ticket: DOC-1782
* Added documentation and an example for the new searchable toolbar menu buttons
Pre-checks:
Review:

DOC-1782: API documentation for searchable menu buttons with new example

---

modules/ROOT/pages/mergetags.adoc

Related Ticket: DOC-1751
* Fix indentation of basic usage example
* Fix styling information showing in the incorrect position
Pre-checks:
Review:

DOC-1751: Further merge tag fixes

---

modules/ROOT/pages/release-notes.adoc

Removed inline comment pre-pending the closing table markup.
This, incorrectly applied, comment caused AsciiDoctor to produce an `unterminated table block` warning.
* markup correction in `release-notes.adoc` to end asciidoctor warnings
Pre-checks:
Review:

DOC-1816 markup correction in `release-notes.adoc` to end asciidoctor warnings

---

_new_content_templates/releasenotes_blank/x_y_z-release-notes-core-fixes.adoc
_new_content_templates/releasenotes_blank/x_y_z-release-notes-core-security-fixes.adoc
_new_content_templates/releasenotes_blank/x_y_z-release-notes-premium-changes.adoc
modules/ROOT/nav.adoc
modules/ROOT/pages/6.2-release-notes.adoc
modules/ROOT/partials/misc/inline-formatting-of-list-bullets.adoc
modules/ROOT/partials/misc/premium-upgrade-promotion-option.adoc

Related Ticket: DOC-1824
This copies the template and fills it out for the missing server side security fixes that were included in 6.2. @brian-forte please feel free to reword this however you see fit.
Note: I've also fixed other various issues I found while writing these.
Pre-checks:
Review:

DOC-1824: Added missing services releases information

---

modules/ROOT/pages/mergetags.adoc

Typo correction: s/tags/Tags/.
* typo correction in `mergtags.adoc`
Pre-checks:
Review:

DOC-1818: typo correction in `mergtags.adoc`

---

_includes/js/notifications.js
_includes/template/notification.html

Related Ticket:
WSRF-1003 - SEO: Remove go.tiny.cloud from the source code
* go.tiny.cloud urls replaced with the actual website url
Pre-checks:
~~- [ ] Branch prefixed with feature/5/ or hotfix/5/~~
~~- [ ] modules/ROOT/nav.adoc has been updated (if applicable)~~
~~- [ ] Files has been included where required (if applicable)~~
~~- [ ] Files removed have been deleted, not just excluded from the build (if applicable)~~
~~- [ ] (New product features only) Release Note added~~
Review:

WSRF-1003 - Replace go.tiny.cloud with the actual website url

---

modules/ROOT/partials/release-notes/6.0-release-notes-summary.adoc

In deprecated and removed table: added outbound links to browser-native APIs documentation that replaced two deprecated and removed TinyMCE APIs.
* Added outbound links to browser-native APIs documentation that replaced two deprecated and removed TinyMCE APIs.
Pre-checks:
Review:

DOC-1831: added outbound links to browser-native APIs documentation that replaced two deprecated and removed TinyMCE APIs.

---

modules/ROOT/pages/6.2-release-notes.adoc
modules/ROOT/partials/release-notes/6.2-release-notes-autocompleter-trigger-configuration-property.adoc

Added new partial — `6.2-release-notes-autocompleter-trigger-configuration-property.adoc` — and includes to said partial to two sections in `6.2-release-notes.adoc`.
* Edits to and restructuring of the autocompleter and `ch` deprecation sections of the 6.2 release notes to more explicitly note the new `trigger` property’s utility.
Pre-checks:
Review:

DOC-1834: 6.2-release-notes.adoc & 6.2-release-notes-autocompleter-trigger-configuration-property.adoc

---

_includes/misc/supported_versions.md

Related Ticket: [DOC-1835](https://ephocks.atlassian.net/browse/DOC-1835)
* Added end-of-support date to version 5.10 row of supported versions page. (Also added spaces to the Markdown table to clean up the table’s presentation when viewed as a plain text file.)
Pre-checks:
Review:

DOC-1835: added end-of-support date to version 5.10 row of supported versions page

---

modules/ROOT/pages/custom-basic-toolbar-button.adoc
modules/ROOT/pages/custom-toggle-toolbar-button.adoc

Related Ticket: DOC-1844
* Very minor change, just moved links to correct rows
Pre-checks:
Review:

DOC-1844: Move onSetup links to correct rows in buttons pages

---

release-notes/release-notes5106.md

Copy edits for the 5.10.6 release notes.
Related Ticket: [DOC-1851](https://ephocks.atlassian.net/browse/DOC-1851)
* Copy edits correcting two link errors in the 5.10.6 Release notes.
Pre-checks:
Review:

DOC-1851: release-notes5106.md

---

modules/ROOT/partials/index-pages/opensource-plugins.adoc

Related Ticket: [DOC-1850](https://ephocks.atlassian.net/jira/software/c/projects/DOC/boards/171/backlog?view=detail&selectedIssue=DOC-1850&issueLimit=100&assignee=63368ea08b75455be4572778)
Update incorrect xref link in adoc file.
* Affected file
/modules/ROOT/partials/index-pages/opensource-plugins.adoc
Fix
-xref:autoresize.adoc[Character Map]
+xref:charmap.adoc[Character Map]
Pre-checks:
Review:

DOC-1850: Fixed incorrect charmap xref

---

_includes/configuration/language.md

Related Ticket: [DOC-1540](https://ephocks.atlassian.net/jira/software/c/projects/DOC/boards/171?modal=detail&selectedIssue=DOC-1540&assignee=63368ea08b75455be4572778)
* [Using the premium language packs](https://www.tiny.cloud/docs/configure/localization/#usingthepremiumlanguagepacks) → replace the ‘premium’ keyword with ‘enterprise’ [Language Packages | Trusted Rich Text Editor | TinyMCE](https://www.tiny.cloud/get-tiny/language-packages/) )
Pre-checks:
Review:

DOC-1540: Replacing premium keyword >> enterprise

---

modules/ROOT/pages/comments-commands-events-apis.adoc

Related Ticket: DOC-1852
* Add description for the `'tinycomments'` annotator API
* Add example for displaying notification with `annotationChanged` method
* Add example for highlighting annotations with `getAll` method
Pre-checks:
Review:

DOC-1852: Add 'tinycomments' annotator

---

modules/ROOT/partials/integrations/vue-quick-start.adoc

Related Ticket: INT-3038
* Update Vue quick start to use create-vue instead of vue-cli
Pre-checks:
Review:

INT-3038: Update to use create vue instead of vue cli

---

modules/ROOT/partials/configuration/toolbar_mode.adoc
modules/ROOT/partials/misc/inline-formatting-of-list-bullets.adoc

Related Ticket: [DOC-1857](https://ephocks.atlassian.net/browse/DOC-1857)
Typo Tuesday 01: typo corrections and copy-edits.
Typo 1: `inline-formatting-of-list-bullets.adoc`: s/plugi]/plugin/.
Typo 2: `toolbar_mode.adoc`: s/`+'floating'+` or `+sliding+`/`+'floating'+` or `+'sliding'+`/.
Pre-checks:
Review:

DOC-1857: Typo Tuesday 01

---

release-notes/release-notes5107.md

Related Ticket: [DOC-1873](https://ephocks.atlassian.net/browse/DOC-1873)
* Remove extraneous ‘v’ from release-notes5107.md’s title_nav value
Pre-checks:
Review:

DOC-1873: Typo in 5.x docs navigation tree

---

modules/ROOT/partials/configuration/advlist_bullet_styles.adoc

Related ticket: [DOC-1886](https://ephocks.atlassian.net/browse/DOC-1886)
* corrected documented default values for advlist_bullet_styles.
* also a typographic copy-edit.
Pre-checks:
Review:

DOC-1886: corrected documented default values for advlist_bullet_styles

---

.github/workflows/feature_6_docs.yml
.github/workflows/release_6_docs.yml
.github/workflows/staging_6_docs.yml

Related Ticket: DOC-1883
* https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
Pre-checks:
Review:

DOC-1883: Updated the workflow runner to use ubuntu 20.04

---

modules/ROOT/pages/6.3-release-notes.adoc

Related ticket: [DOC-1875](https://ephocks.atlassian.net/browse/DOC-1875)
* Added linked CVE number and attribution to XSS vulnerability section of _6.3 Release Notes_.
Pre-checks:
Review:

DOC-1875: added linked CVE number and attribution to XSS vulnerability section of 6.3 Release Notes.

---

modules/ROOT/pages/changelog.adoc

Related Ticket: [DOC-1874](https://ephocks.atlassian.net/browse/DOC-1874)
The sub-section order in other 6.x releases not match 6.3 order.
Pre-checks:
Review:

DOC-1874: Structural ‘typo’ in 6.x Changelog as presented in the 6.x docs

---

modules/ROOT/pages/a11ychecker.adoc

Related ticket: [DOC-1890](https://ephocks.atlassian.net/browse/DOC-1890)
* Fixed two markup typos in a11ychecker.adoc
Pre-checks:
Review:

DOC-1890: fixed two markup typos in a11ychecker.adoc

---

modules/ROOT/pages/a11ychecker.adoc
modules/ROOT/pages/security.adoc

Related ticket: [DOC-1887](https://ephocks.atlassian.net/browse/DOC-1887)
* added material re responsible disclosure and reporter credit to Reporting TinyMCE security issues section.
* Also turned report e-mail address into e-mail macro so the text is now a clickable link.
* NB: added text is based on edits also supplied for updating `security.md` as per [TINY-9487](https://ephocks.atlassian.net/browse/TINY-9487).
Pre-checks:
Review:
[DOC-1887]: https://ephocks.atlassian.net/browse/DOC-1887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TINY-9487]: https://ephocks.atlassian.net/browse/TINY-9487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-1887: added material re responsible disclosure and reporter credit to Reporting TinyMCE security issues section.

---

modules/ROOT/pages/events.adoc
modules/ROOT/pages/fullscreen.adoc
modules/ROOT/partials/configuration/fullscreen_native.adoc

Added a NOTE admonition to `fullscreen.adoc` to keep this in sync with the equivalent admonition added to the 5.x docs consequent to the release of 5.10.6.
Plus a small copy-edit tweak to one of the bullet list items in the ‘Limitations of the fullscreen_native option’ section of `fullscreen_native.adoc`.
Said copy-edit was noted when trawling through looking for the right spot to add the NOTE above.
* NOTE admonition added to `fullscreen.adoc` and copy-edit applied to `fullscreen_native.adoc`.
Pre-checks:
Review:

DOC-1836: fullscreen.adoc & fullscreen_native.adoc

---

modules/ROOT/pages/advcode.adoc
modules/ROOT/partials/configuration/advcode.adoc

Ticket: DOC-1899. Add missing `include::` statement to `advcode.adoc`
Changes:
* `/tinymce-docs/modules/ROOT/partials/configuration/advcode.adoc` was added as part of the 6.3 docs.
* `include::partial$configuration/advcode.adoc[]` (pointing to the above) was not added to `/tinymce-docs/modules/ROOT/pages/advcode.adoc`.
* It has been now.
Pre-checks:
Review:

DOC-1899: Add missing `include::` statement to `advcode.adoc`

---

modules/ROOT/partials/configuration/mergetags_prefix.adoc
modules/ROOT/partials/configuration/mergetags_suffix.adoc

Ticket: DOC-1906, update Merge Tags docs to note prefix and suffix characters must be different.
Changes:
* Added IMPORTANT admonition to both partials regarding the necessity of Merge Tags prefixes and suffixes being different characters or strings.
* **Editorial note**
* A single partial, set to included in both files included in this edit, was abandoned as wordy and complicated.
* As presented, these two admonitions are nearly identical and very close to each other on the published page.
* The close focus most people have when reading documentation, however, justifies the near-repetition.
* Most people, when reading the material on suffixes will not, for example, pay any attention to the prefixes documentation even though it is only a few paragraphs above it on the screen.
Pre-checks: …

DOC-1906: update Merge Tags docs to note prefix and suffix characters must be different.

---

changelog.md
modules/ROOT/pages/changelog.adoc

Ticket: DOC-1918, Add the TinyMCE 6.3.2-specific changes to `changelog.adoc` so this file matches changelog.md on GitHub.
Changes:
* Added 6.3.2-specific change to changelog.adoc for the community release of 6.3.2.
* Also edited changelog.md (the docs-suite’s own changelog file) to note this addition.
Pre-checks:
Review:

DOC-1918: changelog.adoc

---

changelog.md
modules/ROOT/nav.adoc
modules/ROOT/pages/6.2-release-notes.adoc
modules/ROOT/pages/6.3.2-release-notes.adoc
modules/ROOT/pages/release-notes.adoc
modules/ROOT/partials/misc/admon-no-functionality-changes-in-updated-server-side-components.adoc

Ticket: DOC-1913, TinyMCE 6.3.2 Enterprise docs release
Changes:
* Added `6.3.2-release-notes.adoc`
* Added documentation of the single change to this.
* Added entries linking to 6.3.2 release notes sections to `nav.adoc`.
* Added table cell linking to 6.3.2 release notes to `release-notes.adoc`.
* Added entry for this work to tinymce-docs changelog file.
Pre-checks:
Review:

DOC-1913: 6.3.2-release-notes.adoc

---

modules/ROOT/partials/misc/spellchecker-languages.adoc

Ticket: DOC-1931, Missing space in "Supported languages" table heading on Spell Checker Pro page.
Changes:
* "withTinyMCE" -> "with TinyMCE"
Pre-checks:
Review:

DOC-1931: Add missing space in table column heading on Spell Checker Pro page

---

changelog.md
modules/ROOT/pages/custom-basic-toolbar-button.adoc
modules/ROOT/pages/custom-group-toolbar-button.adoc
modules/ROOT/pages/custom-menu-toolbar-button.adoc
modules/ROOT/pages/custom-split-toolbar-button.adoc
modules/ROOT/pages/custom-toggle-toolbar-button.adoc

Ticket: DOC-1900, document the new toolbar buttons api functions; setText and setIcon.
Changes:
* Added documentation of `setText` and `setIcon` functions to `custom-*-toolbar-button.adoc` files.
* Also added required include:: statement to `admon-requires-6.4v.adoc`.
Pre-checks:
Review:

Ticket: DOC-1900, document the new toolbar buttons api functions; setText and setIcon.

---

changelog.md
modules/ROOT/examples/live-demos/full-featured/index.js
modules/ROOT/pages/user-formatting-options.adoc
modules/ROOT/partials/configuration/font_size_input_default_unit.adoc
modules/ROOT/partials/toolbar-button-ids/core-toolbar-buttons.adoc

Ticket: DOC-1892: `fontsizeinput` and `font_size_input_default_unit` documentation
Changes:
* `fontsizeinput` and `font_size_input_default_unit` documentation
Pre-checks:
Review:

DOC-1892: `fontsizeinput` and `font_size_input_default_unit` documentation

---

changelog.md
modules/ROOT/pages/6.3-release-notes.adoc
modules/ROOT/partials/configuration/autoresize_bottom_margin.adoc

Ticket: DOC-1867: add notes re setting `autoresize_bottom_margin` in relation to `margin-bottom` values.
Changes:
* Typo correction in the 6.3 Release Notes: s/checkes/checks/.
* added notes regarding setting `autoresize_bottom_margin` in relation to values for `margin-bottom` to `autoresize_bottom_margin.adoc`.
Pre-checks:
Review:

DOC-1867: add notes re setting `autoresize_bottom_margin` in relation to `margin-bottom` values.

---

changelog.md
modules/ROOT/nav.adoc
modules/ROOT/pages/inline-css.adoc
modules/ROOT/pages/shadow-dom.adoc

Ticket: DOC-1889: restructure inline css documentation
Changes:
* Restructured inline css documentation.
Pre-checks:
Review:

DOC-1889: restructure inline css documentation

---

changelog.md
modules/ROOT/pages/how-the-rtc-plugin-encrypts-content.adoc
modules/ROOT/pages/rtc-encryption.adoc
modules/ROOT/pages/rtc-events.adoc
modules/ROOT/pages/rtc-getting-started.adoc
modules/ROOT/pages/rtc-introduction.adoc
modules/ROOT/pages/rtc-jwt-authentication.adoc
modules/ROOT/pages/rtc-options-optional.adoc
modules/ROOT/pages/rtc-options-overview.adoc
modules/ROOT/pages/rtc-options-required.adoc
modules/ROOT/pages/rtc-supported-functionality.adoc
modules/ROOT/pages/rtc-troubleshooting.adoc
modules/ROOT/partials/misc/admon-rtc-eol.adoc

Ticket: DOC-1929: Add an include file to `/partial/misc/` re RTC no longer being sold or supported and `include::` said file appropriately.
Changes:
* Added `admon-rtc-eol.adoc` to `/modules/partials/misc/`.
* Added draft copy to `admon-rtc-eol.adoc` re rtc being removed from sale.
* Added `include::` statements to all RTC-related docs pages.
Pre-checks:
Review:

DOC-1929: Add an include file to `/partial/misc/` re RTC no longer being sold or supported and `include::` said file appropriately

---

changelog.md
modules/ROOT/pages/advanced-typography.adoc

Ticket: DOC-1922, Add a list of the typograf’s typography rules subset that we, in fact, support to the Advanced Typography documentation.
Changes:
* Added new section:
* listing the specific sub-set of typograf rules used by the Advanced Typography plugin;
* noting that the Advanced Typography plugin cannot be configured to use any other rules; and 
* also noting the Advanced Typography plugin affects only text, and does not touch the underlying HTML markup.
Pre-checks:
Review:

DOC-1922, Add a list of the typograf’s typography rules subset that we, in fact, support to the Advanced Typography documentation.

---

changelog.md
modules/ROOT/partials/misc/mobile-platform-compatibility.adoc

Ticket: DOC-1909, Re-write Supported Mobile Platforms section to match the Browser Compatibility section approach.
Changes:
* Re-written to fulfill the brief. This PR presents two suggested re-writes.
* both use language that doesn’t require this page be constantly updated as new Android and iOS versions are released.
* The first ties our support to the versions the two vendors — Google and Apple, respectively — support.
* In particular, this ties our support to Google’s habit of supporting the current, penultimate and ante-penultimate versions of Android.
* The second re-write sets our support to the current and penultimate versions (which, without explicitly saying so, apes Apple’s approach for iOS).
* Choosing which is to be published is now a key aspect of any Pull Request reviews and …

DOC-1909: Re-write Supported Mobile Platforms section to match the Browser Compatibility section approach

---

_includes/configuration/indentation.md
_includes/rtc/admon-rtc-eol.md
rtc/configuration/index.md
rtc/configuration/rtc-options-overview.md
rtc/encryption.md
rtc/events.md
rtc/getting-started.md
rtc/how-the-rtc-plugin-encrypts-content.md
rtc/index.md
rtc/introduction.md
rtc/jwt-authentication.md
rtc/rtc-supported-functionality.md
rtc/rtc-troubleshooting.md

Ticket: DOC-1932: Add the RTC EOL message to RTC pages in the TinyMCE 5.x documentation
Changes:
* Added `admon-rtc-eol.md` to `/_includes/rtc/`.
* Added EOL announcement text to `admon-rtc-eol.md`.
* Added include statement pointing to `admon-rtc-eol.md` to every RTC-related file.
* Typo correction for an incorrect default value.
Pre-checks:
Review:

DOC-1932: Add the RTC EOL message to RTC pages in the TinyMCE 5.x documentation

---

changelog.md
modules/ROOT/examples/live-demos/autocompleter-autocompleteitem/index.js
modules/ROOT/examples/live-demos/autocompleter-cardmenuitem/index.js

DOC-1946: remove deprecated `ch` parameter and use `trigger` in autocompleter examples
Changes:
* Replaced soft-deprecated option with currently supported option in two index.js files.
* Change:
* s/ch/trigger/.
* Changed files:
1. `/modules/ROOT/examples/live-demos/autocompleter-autocompleteitem/index.js`
2. `/modules/ROOT/examples/live-demos/autocompleter-cardmenuitem/index.js`
Pre-checks:
Review:

DOC-1946: corrections to two demo index.js files

---

changelog.md
modules/ROOT/nav.adoc
modules/ROOT/pages/6.4.1-release-notes.adoc
modules/ROOT/pages/custom-basic-toolbar-button.adoc
modules/ROOT/pages/custom-group-toolbar-button.adoc
modules/ROOT/pages/custom-menu-toolbar-button.adoc
modules/ROOT/pages/custom-split-toolbar-button.adoc
modules/ROOT/pages/custom-toggle-toolbar-button.adoc
modules/ROOT/partials/configuration/highlight_on_focus.adoc
modules/ROOT/partials/misc/admon-requires-6.4v.adoc.

Ticket: DOC-1952
Changes:
* The partials weren't loading because they weren't being included on separate lines
* There was a duplicate partial with no file extension because it ended in `.adoc.`, so that was removed
* When building and testing there were a number of missing reference errors, so those have been fixed as well
* There was an unintentional `{pluginname}` in the 6.4.1 release notes, so that was removed.
Pre-checks:
Review:

DOC-1952: Fix incorrect include placement for partials

---

changelog.md
modules/ROOT/pages/6.3-release-notes.adoc
modules/ROOT/pages/6.4.1-release-notes.adoc
modules/ROOT/pages/changelog.adoc

Ticket: DOC-1948, 6.4.1 release notes post-release follow-up.
Changes:
Update release notes for:
* TINY-8872
* TINY-9364
* TINY-9459
Remove TINY-8872 entry from 6.3 release notes. Add changelog entry for TINY-8872 in changelog.adoc under 6.4.0.
Pre-checks:
Review:

DOC-1948: 6.4.1 release notes post-release follow-up

---

changelog.md
modules/ROOT/partials/configuration/language_url.adoc

DOC-1170, update `language_url` description and example. 
Changes:
* Re-write of both the description and example to
1. explicitly note that `language: ‘<language-file-pack-name>’` must be set; and
2. replace language that relied on common implication and assumption with language that sets out specifically and explicitly what we recommend.
Pre-checks:
Review:

DOC-1170: Update `language_url` description and example

---

changelog.md
modules/ROOT/pages/changelog.adoc

Ticket: DOC-1955, Tiny 6.4.2 Community docs release.
Changes:
* added the TinyMCE 6.4.2 specific changes to changelog.adoc.
Pre-checks:
Review:

DOC-1955: changelog.adoc

---

changelog.md
modules/ROOT/pages/6.4.2-release-notes.adoc

Ticket: DOC-1958: Tab navigation no longer incorrectly stops at menu buttons within toolbar groups.
Changes:
* added `DOC-1958: Tab navigation no longer incorrectly stops at menu buttons within toolbar groups.` to staging.
Pre-checks:
Review:

DOC-1958: Tab navigation no longer incorrectly stops at menu buttons within toolbar groups.

---

changelog.md
modules/ROOT/pages/6.4.2-release-notes.adoc

Ticket: DOC-1957: Selection was not correctly scrolled horizontally into view when using the  API.
Changes:
* added `DOC-1957: Selection was not correctly scrolled horizontally into view when using the  API.` to staging.
Pre-checks:
Review:

DOC-1957: Selection was not correctly scrolled horizontally into view when using the  API.

---

changelog.md
modules/ROOT/pages/6.4.2-release-notes.adoc

Ticket: DOC-1960: The `urlinput` dialog component would not open the type-ahead dropdown when the input value was reset to an empty string.
Changes:
* added `DOC-1960: The urlinput dialog component would not open the type-ahead dropdown when the input value was reset to an empty string.` to staging.
Pre-checks:
Review:

DOC-1960: The urlinput dialog component would not open the type-ahead dropdown when the input value was reset to an empty string.

---

changelog.md
modules/ROOT/pages/6.4.1-release-notes.adoc
modules/ROOT/pages/6.4.2-release-notes.adoc

Ticket: DOC-1959: Redial would, in some situations, cause select elements not to have an initial value selected when they should have.
Changes:
* added `DOC-1959: Redial would, in some situations, cause select elements not to have an initial value selected when they should have.` to staging.
Pre-checks:
Review:

DOC-1959: Redial would, in some situations, cause select elements not to have an initial value selected when they should have.

---

changelog.md
modules/ROOT/pages/6.4.2-release-notes.adoc

Ticket: DOC-1961: Enabled variant of toggleable `tox-button` and `tox-button—​secondary`: it now supports `hover/active/focus/disabled` states.
Changes:
* added `Enabled variant of toggleable `tox-button` and `tox-button—​secondary`: it now supports `hover/active/focus/disabled` states.` to staging.
Pre-checks:
Review:

DOC-1961: Enabled variant of toggleable `tox-button` and `tox-button—​secondary`: it now supports `hover/active/focus/disabled` states.

---

changelog.md
modules/ROOT/pages/6.4.2-release-notes.adoc

Ticket: DOC-1963: Setting an invalid unit in the  changed it to the default value instead of reverting it to the previous, and valid, value.
Changes:
* added `DOC-1963: Setting an invalid unit in the  changed it to the default value instead of reverting it to the previous, and valid, value.` to staging.
Pre-checks:
Review:

DOC-1963: Setting an invalid unit in the  changed it to the default value instead of reverting it to the previous, and valid, value.

---

changelog.md
modules/ROOT/pages/6.4.2-release-notes.adoc

Ticket: DOC-1964:  menu item was enabled before any comments were added.
Changes:
* added `DOC-1964:  menu item was enabled before any comments were added.` to staging.
Pre-checks:
Review:

DOC-1964:  menu item was enabled before any comments were added.

---

changelog.md
modules/ROOT/pages/6.4.2-release-notes.adoc

Ticket: DOC-1965: The editor displayed a notification error when it failed to retrieve a blob image uri.
Changes:
* Added `DOC-1965: The editor displayed a notification error when it failed to retrieve a blob image uri.` to staging.
* Reflective of `Replace error notification from promise rejection in unavailable blob images with exempt data attribute`
Pre-checks:
Review:

DOC-1965: The editor displayed a notification error when it failed to retrieve a blob image uri.

---

changelog.md
modules/ROOT/pages/6.4.2-release-notes.adoc

Ticket: DOC-1967: Fixed the mouse pointer style from a text cursor to a default arrow pointer when hovering over the tree dialog component items.
Changes:
* Added `DOC-1967: Fixed the mouse pointer style from a text cursor to a default arrow pointer when hovering over the tree dialog component items.` to staging.
Pre-checks:
Review:

DOC-1967: Fixed the mouse pointer style from a text cursor to a default arrow pointer when hovering over the tree dialog component items.

---

changelog.md
modules/ROOT/pages/6.4.2-release-notes.adoc

Ticket: DOC-1968: Enabled buttons in the quickbar menu is not shown as active
Changes:
* Added documentation to release-notes for `Enabled buttons in the quickbar menu is not shown as active`
Pre-checks:
Review:

DOC-1968: Enabled buttons in the quickbar menu is not shown as active

---

changelog.md
modules/ROOT/pages/6.4.2-release-notes.adoc

Ticket: DOC-1962: The image would not be inserted when the quickimage button was used on Chrome.
Changes:
* added `DOC-1962: The image would not be inserted when the quickimage button was used on Chrome.` to staging.
Pre-checks:
Review:

DOC-1962: The image would not be inserted when the quickimage button was used on Chrome.

---

changelog.md
modules/ROOT/nav.adoc
modules/ROOT/pages/6.5-release-notes.adoc
modules/ROOT/pages/release-notes.adoc

Ticket: DOC-2028: Adding release notes template to  for 6.5
Changes:
* Added release notes template to `staging` for 6.5
Pre-checks:
Review:

DOC-2028: Adding release notes template to  staging/doc-6  for 6.5

---

changelog.md
modules/ROOT/partials/configuration/language.adoc
modules/ROOT/partials/misc/using-community-lang-packs.adoc

Ticket: DOC-1980, Convert all mentions of Transifex to Crowdin for community translations.
Changes:
* Moved away from Transifex to Crowdin so converted mentions and URLs of Transifex to Crowdin
Pre-checks:
Review:

DOC-1980: Convert all mentions of Transifex to Crowdin

---

changelog.md
modules/ROOT/examples/live-demos/advtemplate-predefined/index.html
modules/ROOT/examples/live-demos/advtemplate-predefined/index.js
modules/ROOT/examples/live-demos/advtemplate/index.js
modules/ROOT/images/icons/template-add.svg
modules/ROOT/pages/advanced-templates.adoc
modules/ROOT/pages/template.adoc
modules/ROOT/partials/configuration/advtemplate_list.adoc
modules/ROOT/partials/configuration/advtemplate_templates.adoc

Ticket: DOC-1953, Advanced Template Docs update
Changes:
* Added documentation for the  new `advtemplate_templates` option.
* Interactive example of `advtemplate_templates` option usage.
* Interactive example of configuring the plugin for interacting with remote backend service.
* Deprecated the old Template plugin.
* Added plugin usage instructions.
Pre-checks:
Review:

DOC-1953: Docs for the new `advtemplate_templates` option.

---

changelog.md
modules/ROOT/partials/misc/admon-requires-6.5v.adoc
modules/ROOT/partials/misc/admon-requires-6.6v.adoc
modules/ROOT/partials/misc/admon-requires-6.7v.adoc
modules/ROOT/partials/misc/admon-requires-6.8v.adoc

Ticket: DOC-2049 create `/partial/misc/admon-requires-6.<x>v.adoc` for use as required by 6.5-and-later specific docs
Changes:
* Added multiple admon-requires files to /partials/misc/:
* admon-requires-6.5v.adoc
* admon-requires-6.6v.adoc
* admon-requires-6.7v.adoc
* admon-requires-6.8v.adoc
Pre-checks:
Review:

DOC-2049: create `/partial/misc/admon-requires-6.xv.adoc` for use as required by 6.5-and-later specific docs

---

changelog.md
modules/ROOT/partials/configuration/language.adoc

Ticket: DOC-2052, Incorrect default for language option.
Changes:
* Correct default value of `language` option to `en`
Pre-checks:
Review:

DOC-2052: Correct default value of `language` option to `en`

---

changelog.md
modules/ROOT/pages/content-behavior-options.adoc
modules/ROOT/partials/configuration/editable_root.adoc
modules/ROOT/partials/configuration/newdocument_content.adoc

Ticket: DOC-2029, Document new editable root APIs and options.
Changes:
* Added docs for the new `editable_root` and `newdocument_content` options unsure where to stick them none of the categories seems right to me. So I put both under `content-behavior-options.adoc`.
Pre-checks:
Review:

DOC-2029: Document new editable root APIs and options

---

changelog.md
modules/ROOT/pages/content-appearance.adoc
modules/ROOT/partials/configuration/init_content_sync.adoc

Ticket: DOC-2004, Document new `init_content_sync` option.
Changes:
* Added docs for the `init_content_sync` option
Pre-checks:
Review:

DOC-2004: Added docs for init_content_sync option

---

modules/ROOT/pages/changelog.adoc

DOC-2076: typo correction in changelog.adoc
Changes:
* s/6.5/6.5.0/
Pre-checks:
Review:

DOC-2076: typo correction in changelog.adoc

---

changelog.md
modules/ROOT/pages/6.5-release-notes.adoc

Ticket: DOC-2073
Changes:
* Added TINY-9947 to the release notes.
* Entry for `=== Dialog `tabpanel` tab labels are now allowed to word wrap for better readability with long labels.
TINY-9947` & `=== Help dialog was restored to `medium` width for better readability.
TINY-9947`
Pre-checks:
Review:

DOC-2073: Added TINY-9947 to the release notes.

---

changelog.md
modules/ROOT/pages/6.5-release-notes.adoc

Ticket: DOC-2000
Changes:
* Added 2x TINY-8910 entries to the release notes.
* Command + backspace would not add an undo level on Mac.
* Ctrl + backspace and Ctrl + delete would not restore correct caret position after redo.
Pre-checks:
Review:

DOC-2000: Added 2x TINY-8910 entries to the release notes.

---

changelog.md
modules/ROOT/pages/6.5-release-notes.adoc

Ticket: DOC-1992
Changes:
* Added TINY-9678 to the release notes.
This entry covers the below `changelog` entries.
- Formats were incorrectly applied to the closest editable element if the selection was in a noneditable context. #TINY-9678
- Formats were incorrectly removed to the closest editable element if the selection was in a noneditable context. #TINY-9678
- Formatter API `canApply` was not returning `false` when the selection was in a noneditable context. #TINY-9678
Pre-checks:
Review:

DOC-1992: Added TINY-9678 to the release notes.

---

changelog.md
modules/ROOT/nav.adoc
modules/ROOT/pages/6.5-release-notes.adoc

Ticket: DOC-2067
Changes:
* Added TINY-9730 Accordion plugin to the release-notes.adoc
Pre-checks:
Review:

DOC-2067: Added Accordion plugin to the release-notes.adoc

---

changelog.md
modules/ROOT/pages/table.adoc
modules/ROOT/partials/configuration/table_merge_content_on_paste.adoc

DOC-2025: Document new `table_merge_content_on_paste` option.
Changes:
* Added include statement pointing to new partial: /configuration/table_merge_content_on_paste.adoc.
* Added new partial: /configuration/table_merge_content_on_paste.adoc
* Documented new option, `table_merge_content_on_paste`, in this new file.
Pre-checks:
Review:

DOC-2025: Document new `table_merge_content_on_paste` option

---

changelog.md
modules/ROOT/pages/6.5.1-release-notes.adoc
modules/ROOT/pages/accordion.adoc

Ticket: DOC-2082
Changes:
* Various copy edits to TinyMCE 6.5.1 release-notes. 
* fixed semantic error in `modules/ROOT/pages/accordion.adoc`
Pre-checks:
Review:

DOC-2082: Copy edits to TinyMCE 6.5.1 release-notes.

---

changelog.md
modules/ROOT/pages/accordion.adoc

DOC-2083: boilerplate missing from `accordion.adoc`
Changes:
* Added back standard sentence inadvertently removed from `accordion.adoc`.
Pre-checks:
Review:

DOC-2083: boilerplate missing from `accordion.adoc`

---

changelog.md
modules/ROOT/pages/6.5.1-release-notes.adoc
modules/ROOT/partials/index-pages/opensource-plugins.adoc

Ticket: DOC-2068: typos and copy-edits found in docs: 2023-06-21 – 2023-06-30
Changes:
1. `opensource-plugins.adoc`
* Added accordions entry to open source plugins index page.
* Also commented out the empty cell since this addition makes the number of cells even.
* And applied a seen-in-passing copy-edit.
2. `6.5.1-release-notes.adoc`
* Removed comment from include adding `admon-releasenotes-for-stable.adoc` to the release notes.
Pre-checks:
Review:

DOC-2068: typos and copy-edits found in docs: 2023-06-21 – 2023-06-30

---

changelog.md
modules/ROOT/pages/release-notes.adoc

DOC-2095: Correct table mark-up in release-notes.adoc
Changes:
* Markup for an empty cell, required when the number of content-carrying cells is odd, was incorrectly commented out.
* It is now not so.
Pre-checks:
Review:

DOC-2095: Correct table mark-up in release-notes.adoc

---

changelog.md
modules/ROOT/partials/configuration/table_merge_content_on_paste.adoc

DOC-2098: Typo in include statement in `table_merge_content_on_paste.adoc`.
Changes:
* Corrected typo in include statement.
* s/partials/partial/.
Pre-checks:
Review:

DOC-2098: Typo in include statement in table_merge_content_on_paste.adoc

---

changelog.md
modules/ROOT/pages/ai-proxy.adoc
modules/ROOT/partials/misc/admon-ai-pricing.adoc

Changes:
* added link out to AI Assistant sign-up page on tiny.cloud to:
* `admon-ai-pricing.adoc`; and
* `ai-proxy.adoc`
* **NB:** the URL — https://www.tiny.cloud/tinymce/features/ai-integration/ — will not go live until ≅2023-07-25 20:00 AEST (2023-07-25 12:00 CEST).
Ticket: DOC-2108: add link to AI Assistant sign up page to admon-ai-pricing.adoc and `ai-proxy.adoc`
Pre-checks:
Review:

DOC-2108: add link to AI Assistant sign-up page to admon-ai-pricing.adoc and `ai-proxy.adoc`

---

changelog.md
modules/ROOT/pages/available-toolbar-buttons.adoc

Ticket: DOC-2133, In **Toolbar Buttons Available for TinyMCE**, the _For information_ links in `code` and `code sample` incorrectly point to Advanced Typography
Changes:
* Added :pluginpage: variables to entries as required.
Pre-checks:
Review:

DOC-2133: incorrect ‘For information’ links in `code` and `code sample` sections

---

changelog.md
modules/ROOT/examples/live-demos/mentions/index.html
modules/ROOT/partials/configuration/mentions_fetch.adoc

Ticket: DOC-2138, document the only-ten-users-present-to-the-end-user UI.
Changes:
* Added NOTE admonition to `mentions_fetch.adoc`, documenting the *only ten users present to the end user* UI.
* added paragraph to `examples/live-demos/mentions/index.html` noting the random nature of the photo-and-name pairing possible when using the *Mentions* live demo.
Pre-checks:
Review:

DOC-2138: document the only-ten-users-present-to-the-end-user UI.

---

changelog.md
modules/ROOT/pages/dialog-configuration.adoc
modules/ROOT/partials/configuration/mentions_fetch.adoc

Ticket:
* DOC-2092: Add xref, pointing to `apis/tinymce.windowmanager.adoc`, to *Dialog position* section of `dialog-configuration.adoc`.
Changes:
* Added xref, pointing to `apis/tinymce.windowmanager.adoc`, to *Dialog position* section of `dialog-configuration.adoc`.
Pre-checks:
Review:

DOC-2092: Add xref, pointing to `apis/tinymce.windowmanager.adoc`, to Dialog position section of dialog-configuration.adoc.

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2141: AI Assistant bug fix documentation entry for TINY-10077 (№1) in the 6.6.1 Release Notes
Changes:
* documentation of bug fix, _Toolbar buttons and menu items were enabled while the dialog was waiting for a final response_, added to **AI Assistant** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2141: AI Assistant bug fix documentation entry for TINY-10077 (№1) in the 6.6.1 Release Notes

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2142: AI Assistant bug fix documentation entry for TINY-10077 (№2) in the 6.6.1 Release Notes
Changes:
* documentation of bug fix, _Error events from streaming requests were included in seperate threads to the corresponding response event_, added to **AI Assistant** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2142: AI Assistant bug fix documentation entry for TINY-10077 (№2) in the 6.6.1 Release Notes

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2140: AI Assistant bug fix documentation entry for TINY-10096 in the 6.6.1 Release Notes
Changes:
* documentation of bug fix, _review content was removed when an error is encountered part way through a streaming response_, added to **AI Assistant** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2140: AI Assistant bug fix documentation entry for TINY-10096 in the 6.6.1 Release Notes

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2148: AI Assistant bug fix documentation entry for TINY-10102 in the 6.6.1 Release Notes
Changes:
* documentation of bug fix, _When a response from the AI Assistant dialog was inserted into a selection not in view, the content did not scroll into view_, added to **AI Assistant** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2148: AI Assistant bug fix documentation entry for TINY-10102 in the 6.6.1 Release Notes

---

changelog.md
modules/ROOT/nav.adoc
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2134: Improvement documentation entry for TINY-10097 in the 6.6.1 Release Notes
Changes:
* documentation of improvement, _When Safari is the host browser, content updates for iframe dialog components with `streamContent: true` set are now throttled to 500ms intervals_, added to **Improvement** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2134: 6.6.1-release-notes.adoc

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2149, change documentation entry for TINY-10073 in the 6.6.1 Release Notes
Changes:
* documentation of change, _API comments/documentation: a markup typo and run-on sentences both corrected_, added to **Change** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2149: change documentation entry for TINY-10073 in the 6.6.1 Release Notes

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2135, bug fix documentation entry for TINY-10078 in the 6.6.1 Release Notes
Changes:
* documentation of bug fix, _On Safari and Firefox browsers, scroll positions were not always maintained when updating the content of a `streamContent: true` iframe dialog component_, added to **Bug fix** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2135: bug fix documentation entry for TINY-10078 in the 6.6.1-release-notes.adoc

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2152, bug fix documentation entry for TINY-10109 in the 6.6.1 Release Notes
Changes:
* documentation of bug fix, _On Safari, iframe dialog components did not consistently autoscroll to the end of the scrollable area when `streamContent: true` was set_, added to **Bug fixes** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2152: bug fix documentation entry for TINY-10109 in the 6.6.1 Release Notes

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2139, bug fix documentation entry for TINY-10110 in the 6.6.1 Release Notes
Changes:
* documentation of bug fix, _Scrolling behavior was inconsistent when updating a `streamContent: true` iframe dialog component with content lacking an HTML document type declaration_, added to **Bug fixes** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2139: bug fix documentation entry for TINY-10110 in the 6.6.1 Release Notes

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2144, bug fix documentation entry for TINY-10070 in the 6.6.1 Release Notes
Changes:
* documentation of bug fix, _A warning message was sometimes printed to the browser console when closing a dialog that contained an iframe component_, added to **Bug fixes** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2144: bug fix documentation entry for TINY-10070 in the 6.6.1 Release Notes

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2147, bug fix documentation entry for TINY-10101 in the 6.6.1 Release Notes
Changes:
* documentation of bug fix, _On Safari and Firefox, the border around `iframe` dialog components did not highlight when focused_, added to **Bug fixes** section of `6.6.1-release-notes.adoc`.
Note for reviewers:
* This write-up makes no mention of the work done to deal with the issue of the highlighted border persisting in Safari and Firefox after focus has left the component. This issue presented internally and was fixed before the new code went public. So, effort and work to fix …

DOC-2147: bug fix documentation entry for TINY-10101 in the 6.6.1 Release Notes

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2156, bug fix documentation entry for TINY-10098 in the 6.6.1 Release Notes
Changes:
* documentation of bug fix, _The `color_cols` option was not respected when a custom `color_map` was defined_, added to **Bug fixes** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2156: bug fix documentation entry for TINY-10098 in the 6.6.1 Release Notes

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

* documentation of bug fix, _the `color_cols` options were were not rounded to the nearest number when set to a decimal number_, added to **Bug fixes** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2157: TINY-9737 write-up for the 6.6.1 Release Notes

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2131, bug fix documentation entry for TINY-10000 in the 6.6.1 Release Notes
Changes:
* documentation of bug fix, _Lists could not be created within editable areas nested inside non-editable areas_, added to **Bug fix** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2131: bug fix documentation entry for TINY-10000 in the 6.6.1 Release Notes

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2146, Addition documentation entry for TINY-9861 in the 6.6.1 Release Notes
Changes:
* DOC-2146: documentation of addition, _New filtering option: `pad_empty_with_br`_, added to **Addition** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2146: Addition documentation entry for TINY-9861 in the 6.6.1 Release Notes

---

changelog.md
modules/ROOT/pages/content-filtering.adoc
modules/ROOT/partials/configuration/pad_empty_with_br.adoc
modules/ROOT/partials/misc/admon-requires-6.6.1v.adoc
modules/ROOT/partials/release-notes/6.0-release-notes-summary.adoc

Ticket: DOC-2114, document the `pad_empty_with_br` option.
Changes:
* file, `pad_empty_with_br.adoc`, added to `/partials/configuration/`.
* documentation of option, `pad_empty_with_br`, added to file.
* `pad_empty_with_br.adoc` added to `content-filtering.adoc` with `include` statement.
* This option’s existence added to table in `6.0-release-notes-summary.adoc` noting the removal of equivalent previous option, `padd_empty_with_br`.
Pre-checks:
Review:

DOC-2114: Document the `pad_empty_with_br` option

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2155, bug fix documentation entry for TINY-10016 in the 6.6.1 Release Notes №2
Changes:
* documentation of bug fix, _Right-clicking on an image that was in a non-editable area would open the Image plugin’s context menu_, added to **Bug fixes** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2155: bug fix documentation entry for TINY-10016 in the 6.6.1 Release Notes №2

---

changelog.md
modules/ROOT/pages/6.6.1-release-notes.adoc

Ticket: DOC-2143: Enhanced Image Editor bug fix documentation entry for TINY-10016 in the 6.6.1 Release Notes
Changes:
* documentation of bug fix, _Context menu and context toolbar no longer show when the selected image is in a non-editable context_ added to **Enhanced Image Editing** section of `6.6.1-release-notes.adoc`.
Pre-checks:
Review:

DOC-2143: Enhanced Image Editor bug fix documentation entry for TINY-10016 in the 6.6.1 Release Notes

---

changelog.md
modules/ROOT/examples/live-demos/linkchecker/index.html

Ticket: DOC-2150: correct the example URLs used in the Link Checker plugin live-demo
Changes:
* Re-wrote live-demo html: it is now an actual interactive example.
* Used canonically invalid domain names for the invalid domain-name strings and in-house domain names for the valid domain name strings.
Pre-checks:
Review:

DOC-2150: correct the example URLs used in the Link Checker plugin live-demo

---

changelog.md
modules/ROOT/partials/configuration/powerpaste_html_import.adoc
modules/ROOT/partials/plugins/powerpaste_import_types.adoc

Ticket: DOC-2107: replace mis-leading explanatory text in powerpaste_html_import.adoc
Changes:
1. Removed misleading sentence from introductory paragraph.
2. Re-structured value behaviour documentation from list to table for greater readability and pars-ability.
3. Copy-edits to the behaviour documentation to further improve readability and pars-ability.
4. Added NOTE admonition documenting what is done when pasting from a TinyMCE instance to a TinyMCE instance.
5. Edited `powerpaste_import_types.adoc` so the equivalent material in this partial presents in the *powerpaste_googledocs_import* and *powerpaste_word_import* sections equivalently to the presentation in the *powerpaste_html_import* section.
Pre-checks:
Review:

DOC-2107: replace mis-leading explanatory text in powerpaste_html_import.adoc

---

changelog.md
modules/ROOT/pages/wordcount.adoc

DOC-1956: more thoroughly document the Word Count open source plugin’s count logic and UX
Changes:
* Re-wrote introductory text.
* Added tables of word boundary characters and not-word boundary characters.
* Added examples of character count logic.
Pre-checks:
Review:

DOC-1956: more thoroughly document the Word Count open source plugin’s count logic and UX

---

release-notes/6.0-upcoming-changes.md

DOC-2153: add note re pad_empty_with_br to 5.x docs note re removal of padd_empty_with_br.
Changes:
Added **Note** re `pad_empty_with_br` being:
1. available as part of TinyMCE 6.6.2; and
2. providing equivalent functionality to the deprecated `padd_empty_with_br` option.
to `6.0-upcoming-changes.md`.
Pre-checks:
Review:

DOC-2153: add note re pad_empty_with_br to 5.x docs note re removal of padd_empty_with_br

---

changelog.md
modules/ROOT/pages/advcode.adoc
modules/ROOT/pages/code.adoc
modules/ROOT/partials/misc/code-dialog-and-selection-state.adoc

DOC-2165: add notes re selection state and switching from rich-text to code-view
Changes:
1. Added file, `code-dialog-and-selection-state.adoc`, to `/partials/misc/`.
2. Added documentation of selection state behaviour when switching from rich-text to code-view dialog.
3. *include::* statements, pointing to `/partials/misc/code-dialog-and-selection-state.adoc`, added to `code.adoc` & `advcode.adoc`.
Pre-checks:
Review:

DOC-2165: add notes re selection state and switching from rich-text to code-view

---

changelog.md
modules/ROOT/pages/changelog.adoc

DOC-2169: TinyMCE 6.7 Community docs release
Changes:
* Added 6.7-specific changelog entries to `changelog.adoc`.
Pre-checks:
Review:

DOC-2169: TinyMCE 6.7 Community docs release

---

changelog.md
modules/ROOT/examples/live-demos/full-featured/example.js
modules/ROOT/examples/live-demos/full-featured/index.js
modules/ROOT/examples/live-demos/open-source-plugins/index.js

DOC-2167: sync the full-featured demo toolbar to the tiny.cloud home page demo toolbar
Changes:
1. Brought _Full-featured demo with Premium plugins_ demo toolbar into sync with the TinyMCE instance presented on Tiny home page.
2. Added comment to this configuration noting a toolbar item will not load if it relies on a plugin that is not loaded.
3. Brought _Full-featured demo with open source plugins only_ demo toolbar as into sync with the TinyMCE instance presented on Tiny home page as is possible.
Pre-checks:
Review:

DOC-2167: sync the full-featured demo toolbar to the tiny.cloud home page demo toolbar

---

integrations/jquery.md

DOC-2170: correct link pointing to official TinyMCE 5.x jQuery component in TinyMCE 5.x jQuery component docs
Changes:
* URL pointing to Official jQuery component changed. It now points to the file in the `/release/5.10` branch of TinyMCE, where the 5.x-specific jQuery component still exists. It no longer points to the `master` branch, which does not have this file in that spot at all.
Pre-checks:
Review:

DOC-2170: correct link pointing to official TinyMCE 5.x jQuery component in TinyMCE 5.x jQuery component docs

---

.github/CODEOWNERS
changelog.md

Ticket: DOC-2175: Update CODEOWNERS automatic reviewers upon opening new DOC- PRs
Changes:
* Update CODEOWNERS list to disable automatically adding the entire `editorTeam` and `other` reviewers to every DOCs ticket PR when they are created.
Pre-checks:
Review:

DOC-2175: Update CODEOWNERS automatic reviewers upon opening new DOC- PRs

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-10123 in the 6.7 Release Notes
Changes:
* Documentation entry for `In Safari on macOS, deleting backwards within a `summary` element removed the entire `details` element if it had no other content`
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-10123 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-10126 in the 6.7 Release Notes
Changes:
* Documentation entry for `The `color_cols` option was not respected when set to the value 5 with a custom `color_map` specified`
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-10126 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-9827 in the 6.7 Release Notes
Changes:
* add fix documentation for `Fixed the inability to insert content next to the `details` element when it is the first or last content element. Pressing the **Up** or **Down** arrow key now inserts a block element before or after the `details` element`
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-9827 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-10011 in the 6.7 Release Notes
Changes:
* added documentation bugfix for `An empty element with a `contenteditable="true"` attribute within a noneditable root was deleted when the Backspace key was pressed`
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-10011 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-10071 in the 6.7 Release Notes
Changes:
* added bugfix documentation for `Links in **Help → Help → Plugins** and **Help → Help → Version** were not navigable by keyboard`
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-10071 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-9965 in the 6.7 Release Notes.
Changes:
* added bugfix documentation entry for `It was possible to delete the sole empty block immediately before a `details` element if it was nested within another `details` element`
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-9965 in the 6.7 Release Notes.

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-6888 in the Release Notes.
Changes:
* added bugfix documentation for `Deleting <li> elements that only contained <br> tags sometimes caused a crash`
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-6888 in the Release Notes.

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc
modules/ROOT/pages/editor-command-identifiers.adoc

Ticket: DOC-2171: addition documentation entry for TINY-10022 in the 6.7 Release Notes
Changes:
* addition documentation entry for TINY-10022 in the 6.7 Release Notes;
* added entries for two new commands, InsertNewBlockBefore and InsertNewBlockAfter to `editor-command-identifiers.adoc`;
* organised Miscellaneous Core command and example tables into alphabetical order.
Pre-checks:
Review:

DOC-2171: addition documentation entry for TINY-10022 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

…tes.
Ticket: DOC-2171: fix documentation entry for TINY-9828 in the 6.7 Release Notes
Changes:
* added bugfix documentation for `In some circumstances, pressing the **Enter** key scrolled the entire page`
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-9828 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

DOC-2171: bug-fix documentation entry for TINY-10046 in `6.7-release-notes.adoc`
Changes:
* Added bug-fix documentation entry for TINY-10046, _Editing the data before switching theme would mean a loss of edited data_.
Pre-checks:
Review:

DOC-2171: bug-fix documentation entry for TINY-10046 in `6.7-release-notes.adoc`

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-9815 in the 6.7 Release Notes.
Changes:
* added bugfix documentation for `Tab navigation incorrectly stopped around iframe dialog components`.
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-9815 in the 6.7 Release Notes.

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-10054 in the 6.7 Release Notes
Changes:
* added bugfix documentation for `The Quick Toolbars plugin showed text alignment buttons on pagebreaks`
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-10054 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-9843 in the 6.7 Release Notes
Changes:
* added bugfix documentation for `The border styles of a table were incorrectly split into a longhand form after table dialog updates`.
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-9843 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

DOC-2171: bug-fix documentation entry for TINY-10053 in `6.7-release-notes.adoc`
Changes:
* Added bugfix documentation for TINY-10053, *Translation was missing for paragraph used as heading text*.
Pre-checks:
Review:

DOC-2171: bug-fix documentation entry for TINY-10053 in `6.7-release-notes.adoc`

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-10129 in the 6.7 Release Notes.
Changes:
* added bugfix documentation for `Numeric input in toolbar items did not disable when a switching from edit to read-only mode`
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-10129 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

DOC-2171: bug-fix documentation entry for TINY-10089 in `6.7-release-notes.adoc`.
Changes:
* added entry for TINY-10089, *Change event did not fire upon adding a reply*, to Comments section of `6.7-release-notes.adoc`.
Pre-checks:
Review:

DOC-2171: bug-fix documentation entry for TINY-10089 in `6.7-release-notes.adoc`

---

changelog.md
modules/ROOT/pages/6.4.1-release-notes.adoc
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-10136 in the 6.7 Release Notes
Changes:
* added bugfix documentation for `Creating lists in empty blocks sometimes, and incorrectly, converted adjacent block elements into list items`.
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-10136 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-10007 in the 6.7 Release Notes
Changes:
* added bugfix documentation for `Using the Media plugin unexpectedly changed `<script>` tags in the editor body to `<image>` tags`
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-10007 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-9975 (x2), TINY-9998 in the 6.7 Release Notes.
Changes:
* added fix documentation for the below
* `Applying checklist on a list with nested lists turned only the outer list into a checklist` to `checklist` subsection.
* `Stopped pasting comments from word documents.` to `powerpaste` subsection.
* `Applying an ordered or unordered list to a selected checklist incorrectly turned the list into paragraphs`
* `Removed error condition, error message, and error message translations for an error which no longer occurs.` into `powerpaste` subsection.
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-9975 (x2), TINY-9998 in the 6.7 Release Notes.

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: improvement documentation entry for TINY-9629 in the Release Notes
Changes:
* added improvement documentation for `Updated **More** toolbar button tooltip text from *More...* to *Reveal or hide additional toolbar items*`
Pre-checks:
Review:

DOC-2171: improvement documentation entry for TINY-9629 in the Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: improvement documentation entry for TINY-10115 in the 6.7 Release Notes
Changes:
* added improvement documentation for `Where multiple case sensitive variants of a translation key are provided, they will now all be preserved in the translation object instead of just the lowercase variant`.
Pre-checks:
Review:

DOC-2171: improvement documentation entry for TINY-10115 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc
modules/ROOT/pages/tableofcontents.adoc
modules/ROOT/partials/configuration/tableofcontents_header.adoc
modules/ROOT/partials/configuration/tableofcontents_includeheader.adoc
modules/ROOT/partials/configuration/tableofcontents_orderedlist.adoc
modules/ROOT/partials/configuration/tableofcontents_orderedlist_type.adoc

Ticket: DOC-2171: new options for TINY-9970, TINY-9968 and TINY-9969 in the 6.7 Release Notes.
Changes:
* added new option documentation for `Added new option tableofcontents_orderedlist_type to set a specific type of ordered list, defaulting to a numeric ordered list.`
* added new option documenation for `Added new boolean option tableofcontents_orderedlist to use ordered lists instead of unordered lists in the table of contents.`
* added new improvement documentation for `Added new boolean option tableofcontents_includeheader to control whether a header is included in the table of contents. Defaults to true.`.
Pre-checks:
Review:

DOC-2171: new options for TINY-9970, TINY-9968 and TINY-9969 for TOC in the 6.7 Release Notes.

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: change documentation entry for TINY-10008 in the 6.7 Release Notes.
Changes:
* added change documentation for `If loading content CSS takes more than 500ms, the editor will be set to an *in progress* state until the CSS is ready`
Pre-checks:
Review:

DOC-2171: change documentation entry for TINY-10008 in the 6.7 Release Notes.

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation (3) entries for TINY-9960 in the 6.7 Release Notes.
Changes:
* added bugfix documentation for `It was possible to remove the `summary` element from a `details` element by dragging and dropping`.
* added bugfix documentation for `It was possible to break `summary` elements if content containing block elements was dragged-and-dropped inside them`.
* added bugfix documentation for `Contents were not removed from the drag start source if dragging and dropping internally into a transparent block element`.
Pre-checks:
Review:

DOC-2171: fix documentation (3) entries for TINY-9960 in the 6.7 Release Notes

---

-new-material-templates/plugin-documentation-templates/ROOT/pages/pluginpage.adoc
changelog.md
modules/ROOT/pages/a11ychecker.adoc
modules/ROOT/pages/advcode.adoc
modules/ROOT/pages/advtable.adoc
modules/ROOT/pages/autocorrect.adoc
modules/ROOT/pages/casechange.adoc
modules/ROOT/pages/checklist.adoc
modules/ROOT/pages/editimage.adoc
modules/ROOT/pages/export.adoc
modules/ROOT/pages/footnotes.adoc
modules/ROOT/pages/formatpainter.adoc
modules/ROOT/pages/introduction-to-mediaembed.adoc
modules/ROOT/pages/introduction-to-powerpaste.adoc
modules/ROOT/pages/introduction-to-tiny-comments.adoc
modules/ROOT/pages/introduction-to-tiny-spellchecker.adoc
modules/ROOT/pages/linkchecker.adoc
modules/ROOT/pages/mentions.adoc
modules/ROOT/pages/mergetags.adoc
modules/ROOT/pages/pageembed.adoc
modules/ROOT/pages/permanentpen.adoc
modules/ROOT/pages/premium-skins-and-icons.adoc
modules/ROOT/pages/tableofcontents.adoc
modules/ROOT/pages/tinydrive-introduction.adoc
modules/ROOT/partials/misc/purchase-premium-plugins.adoc

Ticket: DOC-2176: Remove references to what plans Premium plugins are available with
Changes:
1. Commented out include statement adding `misc/purchase-premium-plugins.adoc` to almost every Premium plugin page.
2. Added notes to `pluginpage.adoc` in `-new-material-templates/plugin-documentation-templates/ROOT/pages/` regarding the need to update the logic in purchase-premium-plugins.adoc.
3. Added a NOTE to `premium-skins-and-icons.adoc` about premium skins only being available with a TinyMCE subscription.
4. Placed include statement pointing to `misc/purchase-premium-plugins.adoc`, and surrounding variables, in a comment block.
5. Added comment to head of `misc/purchase-premium-plugins.adoc` regarding the need to update the logic therein.
Pre-checks:
Review:

DOC-2176: Remove references to what plans Premium plugins are available with

---

changelog.md
modules/ROOT/pages/accessibility.adoc
modules/ROOT/pages/help.adoc
modules/ROOT/pages/keyboard-shortcuts.adoc
modules/ROOT/pages/tinymce-and-screenreaders.adoc
modules/ROOT/partials/configuration/help_accessibility.adoc

DOC-2027: document `help_accessibility` option and related updates
Changes:
* `keyboard-shortcuts.adoc` copy-edits:
1. s/Option/⌥/
2. s/Command/⌘/
3. s/Mac/macOS
4. s/PC/Windows or Linux/
5. s/TinyMCE/{productname}/
* `tinymce-and-screenreaders.adoc` copy-edits:
1. s/Option/⌥/
2. s/Mac/macOS
3. s/PC/Windows or Linux/
4. s/TinyMCE/{productname}/
5. added help-dialog keyboard shortcut to the keyboard shortcuts table.
6. added ‘(or *⌥+Fx*)’ to sections that only had the Windows/Linux shortcut listed.
* `help_accessibility.adoc`
1. Added `help_accessibility.adoc` to `/modules/ROOT/partials/configuration/`.
2. Added documentation of the `help_accessibility` option to `help_accessibility.adoc`.
* `help.adoc`
1. re-structured introductory text from bulleted list to table.
2. added documentation …

DOC-2027: document `help_accessibility` option and related updates

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: improvement documentation for TINY-10003 and TINY-10165 in the 6.7 Release Notes.
Changes:
* added improvement documentation for `Going back from a view to the editor in mobile caused an error.` and `Going back from a view to the editor in mobile visualization on browser caused an error.` for TINY-10165.
* `merged` the two tickets under the same heading.
Pre-checks:
Review:

DOC-2171: improvement documentation for TINY-10003 and TINY-10165 in the 6.7 Release Notes.

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-10017 in the 6.7 Release Notes.
Changes:
* added bugfix documentation for `For sufficiently long URLs and sufficiently wide windows, URL autocompletion hid middle portions of the URL from view`
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-10017 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-9872 in the 6.7 Release Notes.
Changes:
* added bugfix documentation for `Creating a list from multiple `<div>` elements only created a partial list`.
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-9872 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: improvement documentation entry for TINY-9978 in the Release Notes
Changes:
* added improvement documentation for `Menus now have a slight margin at the top and bottom to more clearly separate them from the frame edge`.
Pre-checks:
Review:

DOC-2171: improvement documentation entry for TINY-9978 in the Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: improvement documentation entry for TINY-9863 in the 6.7 Release Notes
Changes:
* added improvement documentation for `Adding a newline after a table would, in some specific cases, not work`.
Pre-checks:
Review:

DOC-2171: improvement documentation entry for TINY-9863 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

DOC-2171 for TINY-9943, TINY-10104, TINY-10099, and TINY-10114.
Changes:
* added entry for TINY-9943, *new UI string translations*, to AI Assistant section of `6.7-release-notes.adoc`.
* added entry for TINY-10104, *the generate button is now disabled when input field is empty, rather than displaying an alert*, to AI Assistant section of `6.7-release-notes.adoc`.
* added entry for TINY-10099, *the default prompts in the `ai_shortcuts` option have been improved for better results*, to AI Assistant section of `6.7-release-notes.adoc`.
* NB: documentation of these new prompts is already in `staging/docs-6`.
* added entry for TINY-10114, *the dialog sometimes unblocked and showed the preview component too early when a response is streamed*, to AI Assistant section of `6.7-release-notes.adoc`. …

DOC-2171_TINY-9943_10104_10099_10114: AI Assistant

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

DOC-2171: bug-fix documentation entry for TINY-10060 in `6.7-release-notes.adoc`
Changes:
* added entry for TINY-10060, *Automatic media embed would not work as expected if the link was pasted into a `<div>` element*, to Enhanced Media Embed section of `6.7-release-notes.adoc`.
Pre-checks:
Review:

DOC-2171: bug-fix documentation entry for TINY-10060 in `6.7-release-notes.adoc`

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: addition documentation entry for TINY-9379 in the 6.7 Release Notes.
Changes:
* added `additions` documentation entry for `New `help_accessibility` option displays the keyboard shortcut to open the in-application help in the status bar`.
* NB: documentation of this new option has been added to the docs-proper via DOC-2027.
Pre-checks:
Review:

DOC-2171: addition documentation entry for TINY-9379 in the 6.7 Release Notes.

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-9842 in the 6.7 Release Notes
Changes:
* added bugfix documentation for `Returning an empty string in a custom context menu update function resulted in a small white line appearing on right-click and the browser-native context menu would not present`.
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-9842 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

DOC-2171, bug fix entry for TINY-9894 in `6.7-release-notes.adoc`.
Changes:
* Entry for TINY-9894, Tiny Drive toolbar button and menu item are now disabled when the selection is not editable, added to Tiny Drive section of `6.7-release-notes.adoc`.
* Also a typo correction.
Pre-checks:
Review:

DOC-2171: bug fix entry for TINY-9894 in `6.7-release-notes.adoc`

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

[DOC-2171](https://ephocks.atlassian.net/browse/DOC-2171), bug fix entry for [TINY-9889](https://ephocks.atlassian.net/browse/TINY-9889) in `6.7-release-notes.adoc`.
Changes:
* Entry for [TINY-9889](https://ephocks.atlassian.net/browse/TINY-9889), *Page Embed toolbar button and menu item are now disabled when the selection is not editable*, added to Page Embed section of 6.7-release-notes.adoc.
Pre-checks:
Review:
[DOC-2171]: https://ephocks.atlassian.net/browse/DOC-2171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TINY-9889]: https://ephocks.atlassian.net/browse/TINY-9889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TINY-9889]: https://ephocks.atlassian.net/browse/TINY-9889?atlOrigin=eyJpIjoi …

DOC-2171: bug fix entry for TINY-9889 in `6.7-release-notes.adoc`

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

DOC-2171 bug fix entries for TINY-9891 in `6.7-release-notes.adoc`
Changes:
* Entry for TINY-9891, *The Footnotes toolbar button and menu item are now disabled when the selection is not editable*
* Entry for TINY-9891, *Calling the `mceInsertFootnote` command now does nothing when the selection is non-editable*
* both added to `6.7-release-notes.adoc`.
Pre-checks:
Review:

DOC-2171 bug fix entries for TINY-9891 in `6.7-release-notes.adoc`

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

DOC-2171: bug fix documentation entry for TINY-9776 in `6.7-release-notes.adoc`.
Changes:
* Entry for TINY-9776, *PowerPaste prevented uploaded images from using their original file-name*, added to PowerPaste section of `6.7-release-notes.adoc`.
Pre-checks:
Review:

DOC-2171: bug fix documentation entry for TINY-9776 in `6.7-release-notes.adoc`

---

changelog.md
modules/ROOT/pages/6.7-release-notes.adoc

Ticket: DOC-2171: fix documentation entry for TINY-9860 in the 6.7 Release Notes
Changes:
* added fix documentation for `Removed attribute from being added to `<br>` in empty table cells`.
Pre-checks:
Review:

DOC-2171: fix documentation entry for TINY-9860 in the 6.7 Release Notes

---

changelog.md
modules/ROOT/examples/live-demos/classic/index.js
modules/ROOT/examples/live-demos/full-featured/example.js
modules/ROOT/examples/live-demos/full-featured/index.js
modules/ROOT/examples/live-demos/open-source-plugins/index.js

Ticket: DOC-2191: updated both `premium`, `non-premium` and `classic` feature demo UI issues.
Changes:
* Hotfix to revert changes made in [DOC-1618](https://github.com/tinymce/tinymce-docs/pull/2325/files) files updated:
* `modules/ROOT/examples/live-demos/full-featured/example.js`
*  `modules/ROOT/examples/live-demos/full-featured/index.js`
*  `modules/ROOT/examples/live-demos/open-source-plugins/index.js`
* Additional `fix` added for `modules/ROOT/examples/live-demos/classic/index.js` to correct width breaking `<div class="tox-editor-container">` editor bounds.
Pre-checks:
Review:
[DOC-1618]: https://ephocks.atlassian.net/browse/DOC-1618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-2191: updated both `premium`, `non-premium` and `classic` feature demo UI issues.

---

changelog.md
modules/ROOT/pages/dialog-components.adoc

DOC-2177: document `picker_text` property for `urlinput` dialog component
Changes:
* Added documentation of the `picker_text` property to the `urlinput` dialog section of `dialog-components.adoc`.
Pre-checks:
Review:

DOC-2177: document `picker_text` property for `urlinput` dialog component

---

_includes/template/bodycontents.html

Ticket: DOC-2190: Add message notification banner to Tinymce 5x docs for LTS.
Changes:
* Add message notification banner to `bodycontent.html` for Tinymce 5x docs LTS.
Pre-checks:
Review:

DOC-2190: Add message notification banner to Tinymce 5x docs for LTS.

---

changelog.md
modules/ROOT/pages/6.7.1-release-notes.adoc

Ticket: DOC-2200
Changes:
* DOC-2200: Add CVE numbers and links to 6.7.1 release notes.
Pre-checks:
Review:

DOC-2200: Add CVE numbers and links to 6.7.1 release notes.

---

changelog.md
modules/ROOT/pages/6.7.2-release-notes.adoc

Ticket: DOC-2194
Changes:
* add fix documentation for TINY-10268 in the 6.7.2 Release notes.
Pre-checks:
Review:

DOC-2194: add fix documentation for TINY-10268 in the 6.7.2 Release notes

---

changelog.md
modules/ROOT/pages/6.7.2-release-notes.adoc

Ticket: DOC-2194
Changes:
* add bugfix documentation for TINY-10249 in the 6.7.2 release notes.
Pre-checks:
Review:

DOC-2194: fix documentation for TINY-10249 in the 6.7.2 release notes.
