tinymce/tinymce-docs

changelog.md, modules/ROOT/pages/6.7.2-release-notes.adoc
Ticket: DOC-2207
Changes:
* fix heading lvl in 6.7.2 release notes for fixes.
Pre-checks:
Review:
=> DOC-2194: fix heading lvl in 6.7.2 release notes for fixes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add fix documentation for TINY-10088 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: add fix documentation for TINY-10088 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* fix documentation for TINY-10153 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: fix documentation for TINY-10153 to the 6.8 release notes.

modules/ROOT/pages/6.7.3-release-notes.adoc
Ticket: DOC-2212
Changes:
* Typo correction for missing space in 6.7.3 docs.
Pre-checks:
Review:
=> DOC-2212: Typo correction for missing space in 6.7.3 docs.

modules/ROOT/pages/tinymce-for-mobile.adoc, modules/ROOT/partials/configuration/contextmenu.adoc, modules/ROOT/partials/misc/admon-mobile-context-menus.adoc, modules/ROOT/partials/misc/mobile-context-menus.adoc
Ticket: DOC-461
Changes:
* Added note which describes accessing the TinyMCE context menu/toolbar on a mobile device
* Added note which describes accessing the native context menu on a mobile device, when a TinyMCE context menu is configured
* Added new notes to context menu and tinymce for mobile pages.
Pre-checks:
Review:
=> DOC-461: Add documentation for accessing TinyMCE and native context menus on mobile devices

modules/ROOT/pages/6.7.3-release-notes.adoc
Ticket: DOC-2213
Changes:
* add CVE ref to 6.7.3 release notes.
Pre-checks:
Review:
=> DOC-2213: add CVE ref to 6.7.3 release notes.

changelog.md, modules/ROOT/pages/user-formatting-options.adoc, modules/ROOT/partials/configuration/default_font_stack.adoc
Ticket: DOC-2209, Document new `default_font_stack` option.
Changes:
* Added docs for the `default_font_stack` option.
Pre-checks:
Review:
=> DOC-2209: Added docs for the new default_font_size option

changelog.md, modules/ROOT/pages/changelog.adoc
Ticket: DOC-2219
Changes:
* TinyMCE 6.8 community release typo and corrections to heading levels.
Pre-checks:
Review:
=> DOC-2219: TinyMCE 6.8 community release typo and corrections.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* added fix documentation for TINY-10229 to the 6.8 release notes.
Pre-checks:
Review:
=> DOC-2181: added fix documentation for TINY-10229 to the 6.8 release notes.

changelog.md, modules/ROOT/pages/events.adoc
Ticket: DOC-2202
Changes:
* add new `bespoke` button text updates to `events.adoc` file.
Pre-checks:
Review:
=> DOC-2202: add new `bespoke` button text updates to `events.adoc` file.

changelog.md, modules/ROOT/pages/cloud-troubleshooting.adoc
Ticket: DOC-2221
Changes:
* add new notification messages to `cloud-troubleshooting.adoc` file.
Pre-checks:
Review:
=> DOC-2221: add new notification messages to `cloud-troubleshooting.adoc` file.

changelog.md, modules/ROOT/pages/6.8-release-notes.adoc
Changes:
* add improvement documentation for TINY-9287 to the 6.8.1 release notes.
Pre-checks:
Review:
=> DOC-2181: add improvement documentation for TINY-9287 to the 6.8 release notes.

antora.yml, modules/ROOT/examples/live-demos/advtemplate-insertionpoint/index.html, modules/ROOT/examples/live-demos/advtemplate-insertionpoint/index.js, modules/ROOT/examples/live-demos/advtemplate-predefined/index.js, modules/ROOT/examples/live-demos/advtemplate/index.js, modules/ROOT/pages/6.3-release-notes.adoc, modules/ROOT/pages/6.7-release-notes.adoc, modules/ROOT/pages/6.7.2-release-notes.adoc, modules/ROOT/pages/accordion.adoc, modules/ROOT/pages/ai-proxy.adoc, modules/ROOT/pages/ai.adoc, modules/ROOT/pages/full-featured-open-source-demo.adoc, modules/ROOT/pages/full-featured-premium-demo.adoc, modules/ROOT/partials/configuration/dialog_persistent.adoc, modules/ROOT/partials/release-notes/6.0-release-notes-apis.adoc, modules/ROOT/partials/release-notes/6.0-release-notes-summary.adoc
Ticket: DOC-2222
Changes:
* Fixed missing content wrapped in double curly brackets
* Fixed all current warnings and errors in local builds
Pre-checks:
Review:
=> DOC-2222: Fix broken mergetags in demos, warnings and errors

modules/ROOT/partials/module-loading/admon-bundling-plugin-langs.adoc
Ticket: DOC-2229
Changes:
* fix single `typo` for admon note include for `building-plugins.adoc` to replace `prefer` with `refer`.
* no-changelog required.
Pre-checks:
Review:
=> DOC-2229: typo correction for admon note include for `building-plugins.adoc`.

changelog.md, modules/ROOT/nav.adoc, modules/ROOT/pages/6.8.1-release-notes.adoc, modules/ROOT/pages/cloud-troubleshooting.adoc, modules/ROOT/pages/invalid-api-key.adoc
Ticket: DOC-2230
Changes:
* add new FAQ tree to tinymce-docs project that contains `Invalid API Key` page.
* small `typo` correction for tinymce 6.8.1 docs
Pre-checks:
Review:
=> DOC-2230: add new `How to fix invalid API key in TinyMCE` page to `tinymce/docs` project.

cloud-deployment-guide/cloud-troubleshooting.md
Ticket: DOC-2231
Changes:
* add `invalid-api-link` in the `cloud-troubleshooting.md` file within the `5x/docs` project, to link back to the newly added `invalid-api-key` page added to the `6x` docs project.
Pre-checks:
Review:
=> DOC-2231: add invalid api link to `cloud-troubleshooting.md` file.

changelog.md, modules/ROOT/nav.adoc, modules/ROOT/pages/6.8.2-release-notes.adoc, modules/ROOT/pages/changelog.adoc, modules/ROOT/pages/release-notes.adoc
Ticket: DOC-2225
Changes:
* added `6.8.2-release-notes.adoc` to project; updated `changelog.adoc`, `nav.adoc` and `release-notes.adoc` for the TinyMCE 6.8.2 release.
* removal of `duplication` entry notes in the `changelog.adoc` for `6.7.2` release.
Pre-checks:
Review:
=> DOC-2225: TinyMCE 6.8.2 release notes.

changelog.md, modules/ROOT/nav.adoc, modules/ROOT/pages/6.8.2-release-notes.adoc, modules/ROOT/pages/changelog.adoc, modules/ROOT/pages/release-notes.adoc
Ticket: DOC-2226
Changes:
* TinyMCE 6.8.2 Enterprise Docs Release.
Pre-checks:
Review:
=> DOC-2226: TinyMCE 6.8.2 Enterprise Docs Release.

changelog.md, modules/ROOT/examples/live-demos/full-featured/index.js
Ticket: DOC-2178
Changes:
* add hotfix to `live-demos/full-featured/index.js` for `advtemplate` when inserting template.
Pre-checks:
Review:
=> DOC-2178: add fix to `live-demos/full-featured/index.js` for `advtemplate` when inserting template.

changelog.md, modules/ROOT/examples/live-demos/full-featured/index.js, modules/ROOT/pages/ai.adoc
Ticket: DOC-2201
Changes:
* Added link to `ai.adoc` to direct users to the AI Assistant demo.
Pre-checks:
Review:
=> DOC-2201: Added link to `ai.adoc` to direct users to the AI Assistant demo.

.github/workflows/feature_6_docs.yml, .github/workflows/release_6_docs.yml, .github/workflows/staging_6_docs.yml
Ticket: DOC-2234
Changes:
* Site build sync won't interfere with new 5 docs site
Pre-checks:
Review:
=> DOC-2234: Modify workflow to not overwrite 5 docs

changelog.md, modules/ROOT/pages/invalid-api-key.adoc
Ticket: DOC-2235
Changes:
* changes and updates to `invalid-api-key.adoc` page, which include updating initial content, links.
Pre-checks:
Review:
=> DOC-2235: changes and updates to `invalid-api-key.adoc` page.

changelog.md, modules/ROOT/nav.adoc, modules/ROOT/pages/examples.adoc, modules/ROOT/partials/index-pages/skins-and-icons-examples.adoc
Ticket: DOC-1925
Changes:
* Added Skins and Icons examples section to the index page
Pre-checks:
Review:
=> DOC-1925: Add Skins and Icons examples to examples.adoc index page

changelog.md, modules/ROOT/nav.adoc, modules/ROOT/pages/understanding-editor-loads.adoc
Ticket: DOC-2240
Changes:
* added new `understanding-editor-loads.adoc` to `how-to-guide` section.
Pre-checks:
Review:
=> DOC-2240: add new `understanding-editor-loads.adoc` to `how-to-guide` section

changelog.md, modules/ROOT/pages/cloud-troubleshooting.adoc
Ticket: DOC-2275
Changes:
* updates to `cloud-troubleshooting.adoc` with new links to `invalid-api-key.adoc` page.
Pre-checks:
Review:
=> DOC-2275: updates to `cloud-troubleshooting.adoc` with new links to `invalid-api-key.adoc` page.

changelog.md, modules/ROOT/pages/cloud-troubleshooting.adoc
Ticket: DOC-2276
Changes:
* DOC-2276: updates to `cloud-troubleshooting.adoc` with new `read-only` ref and links to `invalid-api-key.adoc` page.
Pre-checks:
Review:
=> DOC-2276: updates to `cloud-troubleshooting.adoc` with new `read-only` ref and links to `invalid-api-key.adoc` page.

changelog.md, modules/ROOT/nav.adoc, modules/ROOT/pages/6.8.3-release-notes.adoc, modules/ROOT/pages/release-notes.adoc
Ticket: DOC-2241
Changes:
* added `6.8.3-release-notes.adoc` to project; updated `changelog.adoc`, `nav.adoc` and `release-notes.adoc` for the TinyMCE 6.8.3 release.
Pre-checks:
Review:
=> DOC-2241: TinyMCE 6.8.3 release notes

modules/ROOT/partials/configuration/highlight_on_focus.adoc
Ticket: DOC-2245
Site: [DOC-2245 site](http://docs-feature-70-doc-2245.staging.tiny.cloud/docs/tinymce/latest/accessibility/#highlight_on_focus)
Changes:
* DOC-2245 update docs to reflect new highlight_on_focus default being true
Pre-checks:
Review:
=> DOC-2245: now `highlight_on_focus`'s default is `true`

modules/ROOT/pages/7.0-release-notes.adoc
Release notes entry for: TINY-10433
Site: [DOC-2270_TINY-10433 site](http://docs-feature-70-doc-2270tiny-10433.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#fixed-incorrect-object-processor-for-event_root-option)
Changes:
* DOC-2270_TINY-10433: Fixed incorrect object processor for `event_root` option.
Pre-checks:
Review:
=> DOC-2270_TINY-10433: Fixed incorrect object processor for `event_root` option.

modules/ROOT/pages/autocompleter.adoc
Ticket: DOC-2293
Site: [DOC-2293 site](http://docs-feature-70-doc-2293.staging.tiny.cloud/docs/tinymce/latest/autocompleter/#options)
Changes:
* DOC-2293: Remove `ch` option from `Autocompleter.adoc` page
Pre-checks:
Review:
=> DOC-2293: Remove `ch` option from `Autocompleter.adoc` page

modules/ROOT/pages/7.0-release-notes.adoc
Release notes entry for: TINY-10581
Site: [DOC-2270_TINY-10581 site](http://docs-feature-70-doc-2270tiny-10581.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#the-toolbar-width-was-miscalculated-for-the-inline-editor-positioned-inside-a-scrollable-container)
Changes:
* DOC-2270_TINY-10581: The toolbar width was miscalculated for the inline editor positioned inside a scrollable container.
Pre-checks:
Review:
=> DOC-2270_TINY-10581: The toolbar width was miscalculated for the inline editor positioned inside a scrollable container.

modules/ROOT/pages/7.0-release-notes.adoc
Release notes entry for: TINY-10439
Site: [DOC-2270_TINY-10439 site](http://docs-feature-70-doc-2270tiny-10439.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#the-link_default_target-option-wasnt-considered-when-inserting-a-link-via-quicklink-toolbar)
Changes:
* DOC-2270: add release notes entry for TINY-10439
Pre-checks:
Review:
=> DOC-2270_TINY-10439 release notes entry: The `link_default_target` option wasn't considered when inserting a link via `quicklink` toolbar.

modules/ROOT/pages/7.0-release-notes.adoc
Release notes entry for: TINY-10580
Site: [DOC-2270_TINY-10580 site](http://docs-feature-70-doc-2270tiny-10580.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#when-inline-editor-toolbar-wrapped-to-multiple-lines-the-top-wasnt-always-calculated)
Changes:
* DOC-2270_TINY-10580 release notes entry: When inline editor toolbar wrapped to multiple lines the top wasn't always calculated.
Pre-checks:
Review:
=> DOC-2270_TINY-10580 release notes entry: When inline editor toolbar wrapped to multiple lines the top wasn't always calculated.

modules/ROOT/pages/7.0-release-notes.adoc
Release notes entry for: TINY-10482
Site: [DOC-2270_TINY-10482 site](http://docs-feature-70-doc-2270tiny-10482.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#inline-mode-with-persisted-toolbar-would-show-regardless-of-the-skin-being-loaded-causing-css-issues)
Changes:
* DOC-2270_TINY-10482 release notes entry: Inline mode with persisted toolbar would show regardless of the skin being loaded, causing css issues.
Pre-checks:
Review:
=> DOC-2270_TINY-10482 release notes entry: Inline mode with persisted toolbar would show regardless of the skin being loaded, causing css issues.

modules/ROOT/pages/7.0-release-notes.adoc
Release notes entry for: TINY-10459
Site: [DOC-2270_TINY-10459 site](http://docs-feature-70-doc-2270tiny-10459.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#the-domutils-isempty-api-function-has-been-modified-to-consider-nodes-containing-only-comments-as-empty)
Changes:
* DOC-2270_TINY-10459 release notes entry: The `DOMUtils.isEmpty` API function has been modified to consider nodes containing only comments as empty.
Pre-checks:
Review:
=> DOC-2270_TINY-10459 release notes entry: The `DOMUtils.isEmpty` API function has been modified to consider nodes containing only comments as empty.

modules/ROOT/partials/misc/supported-versions.adoc
Ticket: DOC-2290
Site: [DOC-2290 site](http://docs-feature-70-doc-2290.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
*  add EOSA for v6.8 to `support.adoc` page, to support [Github User Issue 3033](https://github.com/tinymce/tinymce-docs/issues/3033).
Pre-checks:
Review:
=> DOC-2290: add EOSA for v6.8 to `support.adoc` page.

modules/ROOT/pages/7.0-release-notes.adoc, modules/ROOT/partials/configuration/text_patterns.adoc
- Release notes entry for: DOC-2250 and relates to TINY-10324
Site: [DOC-2270_TINY-10324 site](http://docs-feature-70-doc-2270tiny-10324.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#a-new-trigger-property-for-block-text-pattern-configurations-allowing-pattern-activation-with-either-space-or-enter-keys)
Site: [text_pattern default changes](http://docs-feature-70-doc-2270tiny-10324.staging.tiny.cloud/docs/tinymce/latest/content-behavior-options/#text_patterns) and linked back to release notes entry.
Changes:
* add `new feature` documentation for TINY-10324 in the TinyMCE release notes.
* updated `text_patterns.adoc` to support incoming core changes for `space` trigger.
Pre-checks:
Review:
=> DOC-2270: add `new feature` documentation for TINY-10324 in the TinyMCE release notes.

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270 site](http://docs-feature-70-doc-2270tiny-6309.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#tableoperations-operaserows-did-not-calculate-the-correct-row-index-for-colgroup-tables)
Changes:
* add fix documentation for TINY-6309 to the release notes.
Pre-checks:
Review:
=> DOC-2270: add fix documentation for TINY-6309 to the release notes.

modules/ROOT/nav.adoc, modules/ROOT/pages/advlist.adoc, modules/ROOT/pages/basic-setup.adoc, modules/ROOT/pages/editor-command-identifiers.adoc, modules/ROOT/pages/lists.adoc, modules/ROOT/pages/work-with-plugins.adoc, modules/ROOT/partials/index-pages/opensource-plugins.adoc, modules/ROOT/partials/module-loading/bundling-plugin-files.adoc
Ticket: DOC-2300
Site: [DOC-2300_DOC-2305 site](http://docs-feature-70-doc-2300doc-2305.staging.tiny.cloud/docs/tinymce/latest/advlist/)
Changes:
* Rename Advanced Lists plugin to List Styles for TinyMCE 7.0.
Pre-checks:
Review:
=> DOC-2300: Rename Advanced Lists plugin to List Styles for TinyMCE 7.0.

-new-material-templates/release-notes-template/ROOT/nav.adoc, -new-material-templates/release-notes-template/ROOT/pages/<x.y[.z]>-release-notes.adoc, -new-material-templates/release-notes-template/antora.yml, antora.yml, modules/ROOT/nav.adoc, modules/ROOT/pages/7.0-release-notes.adoc, modules/ROOT/pages/creating-an-icon-pack.adoc, modules/ROOT/pages/enhanced-skins-and-icon-packs.adoc, modules/ROOT/partials/integrations/webcomponent-tech-ref.adoc, modules/ROOT/partials/misc/plugin-support-table.adoc, modules/ROOT/partials/misc/shipped-content-css.adoc, modules/ROOT/partials/module-loading/bundling-content-css-files.adoc, modules/ROOT/partials/module-loading/bundling-icon-files.adoc, modules/ROOT/partials/module-loading/bundling-next-steps.adoc, modules/ROOT/partials/module-loading/bundling-skin-files.adoc
Ticket: DOC-2300
Site: [DOC-2300_2311 site](http://docs-feature-70-doc-2300doc-2311.staging.tiny.cloud/docs/tinymce/latest/enhanced-skins-and-icon-packs/)
Changes:
* Replace `Skins & Icons Packs` with `Enhanced Skins & Icon Packs` in 7x docs.
* Update some ref to `Tiny Skins & Icons Packs` and removal of `Premium`/ replace with `Enhanced`.
Pre-checks:
Review:
=> DOC-2300: Replace `Skins & Icons Packs` with `Enhanced Skins & Icon Packs` in 7x docs.

modules/ROOT/pages/7.0-release-notes.adoc, modules/ROOT/partials/misc/admon-paid-addon-pricing.adoc
Ticket: DOC-2299
Site: [DOC-2299 site](http://docs-feature-70-doc-2270doc-2299.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#new-premium-plugins)
Changes:
* Add new plugin documentation for `importWord`, `exportWord` & `exportPDF` to 7.0 release notes.
* Create new `admon` for paid add-ons.
Pre-checks:
Review:
=> DOC-2299: Add new plugin documentation for `importWord`, `exportWord` & `exportPDF` to 7.0 release notes.

modules/ROOT/pages/7.0-release-notes.adoc, modules/ROOT/partials/configuration/sandbox_iframes.adoc
Ticket: DOC-2303
Site: [DOC-2303 site](http://docs-feature-70-doc-2303.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#sandbox_iframes-editor-option-is-now-defaulted-to-true)
Changes:
* add sandbox_iframes breaking changes to 7.0 release notes.
* update default `value` based on change made in 7.0
* added changes/improvements made by @MitchC1999
Pre-checks:
Review:
=> DOC-2303: add sandbox_iframes breaking changes to 7.0 release notes.

modules/ROOT/nav.adoc, modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270_TINY-10644 site](http://docs-feature-70-doc-2270tiny-10644.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#removedinsertorderedlistandinsertunorderedlistcommands-from-core)
Changes:
* Removed `InsertOrderedList` and `InsertUnorderedList` commands from core.
Pre-checks:
Review:
=> DOC-2270: Removed `InsertOrderedList` and `InsertUnorderedList` commands from core.

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270_TINY-10617 site](http://docs-feature-70-doc-2270tiny-10617.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#remove-the-height-field-from-the-table-plugin-cell-dialog-the-table-plugin-row-dialog-now-controls-the-row-height-by-setting-the-height-on-the-tr-element-not-the-td-elements)
Changes:
* add change documentation for TINY-10617 to the TinyMCE 7.0 release notes.
Pre-checks:
Review:
=> DOC-2270: add change documentation for TINY-10617 to the TinyMCE 7.0 release notes.

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270_TINY site](http://docs-feature-70-doc-2270tiny-10658.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#make-table-ghost-element-better-reflect-height-changes-when-resizing)
Changes:
* add improvement documentation for TINY-10658 to the release notes for 7.0
Pre-checks:
Review:
=> DOC-2270: add improvement documentation for TINY-10658 to the release notes for 7.0

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270_TINY-10589 site](http://docs-feature-70-doc-2270tiny-10589.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#change-table-height-resizing-handling-to-remove-heights-from-tdth-elements-and-only-apply-to-tr-elements)
Changes:
* add improvement documentation for TINY-10589 to the TinyMCE 7.0 release notes.
Pre-checks:
Review:
=> DOC-2270: add improvement documentation for TINY-10589 to the TinyMCE 7.0 release notes.

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270_TINY-10570 site](http://docs-feature-70-doc-2270tiny-10570.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#floating-toolbar-buttons-in-inline-editor-incorrectly-wrapped-into-multiple-rows-on-window-resizing-or-zooming)
Changes:
* add fix documentation for TINY-10570 to the TinyMCE 7.0 release notes.
Pre-checks:
Review:
=> DOC-2270: add fix documentation for TINY-10570 to the TinyMCE 7.0 release notes.

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270 site](http://docs-feature-70-doc-2270tiny-10615.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#advanced-templates)
Changes:
* Add tooltip release notes for `advtemplate`
Pre-checks:
Review:
=> DOC-2270: Add `advtemplate` documentation for TINY-10615 to the TinyMCE 7.0 release notes

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270_TINY-10308 site](http://docs-feature-70-doc-2270tiny-10308.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#when-setting-table-border-width-and-table_style_by_css-is-true-only-the-border-attribute-is-set-to-0-and-border-width-styling-is-no-longer-used)
Changes:
* add fix documentation for TINY-10308 to the TinyMCE 7.0 release notes.
Pre-checks:
Review:
=> DOC-2270: add fix documentation for TINY-10308 to the TinyMCE 7.0 release notes.

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270 site](http://docs-feature-70-doc-2270.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Add release notes for TINY-10672
Pre-checks:
Review:
=> DOC-2270: Add improved documentation for TINY-10672 in TinyMCE 7.0 release notes

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270 site](http://docs-feature-70-doc-2270.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Add release notes entry for TINY-10611
Pre-checks:
Review:
=> DOC-2270: Add improved documentation for TINY-10611 to the TinyMCE release notes

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270_TINY-9641 site](http://docs-feature-70-doc-2270tiny-9641.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#added-tooltips-to-click-for-more-info-button-in-the-accessibility-checker-dialog)
Changes:
* add improvement documentation for TINY-9641 to the TinyMCE 7.0 release notes.
Pre-checks:
Review:
=> DOC-2270: add improvement documentation for TINY-9641 to the TinyMCE 7.0 release notes.

modules/ROOT/pages/7.0-release-notes.adoc
Ticket: DOC-2320
Release note entry for: TINY-8929
Related: DOC-2270
Site: [DOC-2320 site](http://docs-feature-70-doc-2320.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#the-autocompleter-ch-configuration-property-has-been-removed-use-the-trigger-property-instead)
Changes:
* add release note entry for TINY-8929: The autocompleter `ch` configuration property has been removed. Use the `trigger` property instead.
Pre-checks:
Review:
=> add release note entry for TINY-8929: The autocompleter `ch` configuration property has been removed. Use the `trigger` property instead.

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270 site](http://docs-feature-70-doc-2270.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Add release notes for TINY-10603
Pre-checks:
Review:
=> DOC-2270: Add improved documentation for TINY-10603 to the TinyMCE 7.0 release notes

antora-playbook-dev.yml, antora-playbook-staging.yml, modules/ROOT/examples/live-demos/full-featured/index.js
Ticket: DOC-2321
Site: [DOC-2321 site to test markdown on paste](http://docs-feature-70-doc-2321.staging.tiny.cloud/docs/tinymce/latest/full-featured-premium-demo/)
Changes:
* update `tinymce_live_demo_url` to use v7, and update full feature demo for `markdown` plugin.
Pre-checks:
Review:
=> DOC-2321: update `tinymce_live_demo_url` to use v7, and update full feature demo for `markdown` plugin.

modules/ROOT/pages/7.0-release-notes.adoc
Ticket: DOC-2270 and DOC-2322
Site: [DOC-2270_DOC-2322 site](http://docs-feature-70-doc-2270doc-2322.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#enhanced-code-editor-search-and-replace-keyboard-shortcuts)
Changes:
* Add entry to the 7.0 release notes for new `CM6 shortcuts`.
Pre-checks:
Review:
=> DOC-2270: Add entry to the release notes for new CM6 shortcuts.

modules/ROOT/pages/7.0-release-notes.adoc
Release notes entry for: TINY-10310
Site: [DOC-2270_TINY-10310 site](http://docs-feature-70-doc-2270tiny-10310.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#moving-focus-to-the-outside-of-the-editor-after-having-clicked-a-menu-would-not-fire-a-blur-event-as-expected)
Changes:
* DOC-2270_TINY-10310: Moving focus to the outside of the editor after having clicked a menu would not fire a `blur` event as expected.
Pre-checks:
Review:
=> DOC-2270_TINY-10310: Moving focus to the outside of the editor after having clicked a menu would not fire a `blur` event as expected.

modules/ROOT/nav.adoc, modules/ROOT/pages/7.0-release-notes.adoc
Ticket: DOC-2315
Site: [DOC-2315 site](http://docs-feature-70-doc-2315.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#tinymce-7-0-plugin-naming-unification)
Changes:
* add TinyMCE 7.0 plugin naming unification to release notes, to support DOC-2230
* removed some `template-placeholders` for new `open-source-plugins`
Pre-checks:
Review:
=> DOC-2315: add TinyMCE 7.0 plugin naming unification to release notes.

modules/ROOT/pages/content-filtering.adoc, modules/ROOT/partials/configuration/sandbox_iframes.adoc, modules/ROOT/partials/configuration/sandbox_iframes_exclusions.adoc
Ticket: DOC-<num>
Site: [DOC-2325 new options added](http://docs-feature-70-doc-2325.staging.tiny.cloud/docs/tinymce/latest/content-filtering/#sandbox-iframes-exclusions)
Site: [DOC-2325 release notes link](http://docs-feature-70-doc-2325.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#sandbox_iframes-editor-option-is-now-defaulted-to-true:~:text=sandbox_iframes_exclusions)
Changes:
* New `sandbox_iframes_exclusions` option to `content-filtering.adoc
* Remove string `option` ref in the title for `content-filtering/#sandbox-iframes-option` 
Pre-checks:
Review:
=> DOC-2325: Add new `sandbox_iframes_exclusions` option to `content-filtering.adoc` to support `sandbox_iframes`.

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270_TINY-10654 site](http://docs-feature-70-doc-2270tiny-10654.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#the-open-source-template-plugin-has-been-removed)
Changes:
* added entry to `release notes` mentioning removal of open source Template plugin from TinyMCE 7.0
Pre-checks:
Review:
=> DOC-2270: add entry to `release notes` mentioning removal of open source Template plugin from TinyMCE 7.0

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270_TINY-10436 site](http://docs-feature-70-doc-2270tiny-10436.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#removed-force_hex_color-option-with-the-default-now-being-all-colors-are-forced-to-hex-format-and-as-lower-case)
Changes:
* add entry to `TinyMCE 7.0 release notes` for mention of removal of `force_hex_color`.
Pre-checks:
Review:
=> DOC-2270: add entry to `TinyMCE 7.0 release notes` for mention of removal of `force_hex_color`.

modules/ROOT/pages/7.0-release-notes.adoc
Ticket: DOC-2329
Site: [DOC-2329 site](http://docs-feature-70-doc-2329.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#new-premium-plugins)
Changes:
* DOC-2329 removed the paid addon admonitions for `Import from Word`, `Export to Word`, and `Export to PDF`.
Pre-checks:
Review:
=> DOC-2329 removed the paid addon admonitions for `Import from Word`, `Export to Word`, and `Export to PDF`.

modules/ROOT/pages/7.0-release-notes.adoc
Site: [DOC-2270_DOC-2328 site](http://docs-feature-70-doc-2270doc-2328.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#overview:~:text=TinyMCE%207.0%20is%20licensed%20under%20GPL%20Version%202%20or%20later.%20This%20version%20introduces%20a%20new%20license_key%20configuration%20setting%20that%20gives%20self%2Dhosted%20users%20the%20ability%20to%20select%20a%20usage%20under%20the%20GPL%20or%20to%20authenticate%20their%20paid%20license%20with%20Tiny.)
Changes:
* Add notification to the top of TinyMCE 7.0 release notes for `GPL` licence
* Add message below `Overview` section to introduce TinyMCE 7.0 focus plugins.
Pre-checks:
Review:
=> DOC-2270: Add notification to the top of TinyMCE 7.0 release notes for `GPL` licence and `new` plugins mentions.

modules/ROOT/partials/configuration/markdown.adoc
Ticket: DOC-2330
Site: [DOC-2330 site](http://docs-feature-70-doc-2330.staging.tiny.cloud/docs/tinymce/latest/markdown/#example-using-markdown_symbols)
Changes:
* update code sample for `markdown_symbols` as it was missing the `markdown` plugin and we want users to be able to copy and paste these code samples.
Pre-checks:
Review:
=> DOC-2330: update code sample for `markdown_symbols` example.

modules/ROOT/pages/advanced/index.adoc, modules/ROOT/pages/configure/index.adoc, modules/ROOT/pages/enterprise/index.adoc, modules/ROOT/pages/index.adoc, modules/ROOT/pages/integrations/index.adoc, modules/ROOT/pages/plugins/index.adoc, modules/ROOT/pages/plugins/opensource/index.adoc, modules/ROOT/pages/plugins/premium/index.adoc, modules/ROOT/pages/release-notes/index.adoc, modules/ROOT/pages/ui-components/index.adoc
Ticket: DOC-2289
Site: [DOC-2289 site](http://docs-feature-5-doc-2289.staging.tiny.cloud/docs/tinymce/5/)
Changes:
* Filled out empty index pages with tables containing links and descriptions to children pages, similar to how current prod 5 docs does.
Pre-checks:
Review:
=> DOC-2289: Add link tables to empty index pages

modules/ROOT/pages/advanced/index.adoc, modules/ROOT/pages/configure/index.adoc, modules/ROOT/pages/enterprise/index.adoc, modules/ROOT/pages/index.adoc, modules/ROOT/pages/integrations/index.adoc, modules/ROOT/pages/plugins/index.adoc, modules/ROOT/pages/plugins/opensource/index.adoc, modules/ROOT/pages/plugins/premium/index.adoc, modules/ROOT/pages/release-notes/index.adoc, modules/ROOT/pages/ui-components/index.adoc
Ticket: DOC-2289
Site: [Staging site](http://staging.tiny.cloud/docs/tinymce/5/)
Changes:
* Updating index page link tables
Review:
=> DOC-2289: Add link tables to empty index pages (#3154)

modules/ROOT/pages/export.adoc
Ticket: DOC-2313
Site: [DOC-2313 site](http://docs-hotfix-6-doc-2313.staging.tiny.cloud/docs/tinymce/6/export/)
Changes:
* add note to `export.adoc` in `tinymce 6x docs` to inform users about plugin name change in v7.
Pre-checks:
Review:
=> DOC-2313: add note to `export.adoc` to inform users about plugin name change in v7.

modules/ROOT/pages/7.0-release-notes.adoc
Ticket: DOC-2338
Ticket: TINY-10784
Site: [DOC-2338 site](http://docs-hotfix-70-doc-2338.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#incorrect-text-color-display-with-tinymce-skin-oxide-dark)
Changes:
* added known issue for advcode text-color not displaying correctly when `skin: 'oxide-dark'` is set.
Pre-checks:
Review:
=> DOC-2338: added known issue for advcode text-color not displaying correctly when `skin: 'oxide-dark'` is set.

modules/ROOT/pages/index.adoc
Ticket: DOC-2348
Site: [DOC-2348 site](http://docs-hotfix-6-doc-2348.staging.tiny.cloud/docs/tinymce/6/)
Changes:
* DOC-2348 add note to 6.x docs `index.adoc` pointing to latest TinyMCE docs
Pre-checks:
Review:
=> DOC-2348 add note to 6.x docs `index.adoc` pointing to latest TinyMCE docs

modules/ROOT/examples/live-demos/comments-callback/index.js, modules/ROOT/examples/live-demos/comments-embedded/index.js, modules/ROOT/pages/6.1-release-notes.adoc, modules/ROOT/pages/6.4.1-release-notes.adoc, modules/ROOT/pages/6.5.1-release-notes.adoc, modules/ROOT/pages/changelog.adoc
Ticket: DOC-2318
Site: [DOC-2318 site](http://docs-hotfix-641-doc-2318.staging.tiny.cloud/docs/tinymce/6/6.4.1-release-notes/#overview)
Changes:
* ~Remove `skip_focus` check to the `ToggleToolbarDrawer` command from 6.4.1 release notes.~
* the `skipFocus` argument was incorrectly documented. One [review comment](https://github.com/tinymce/tinymce-docs/pull/2655#discussion_r1162183137) accidentally changed the argument from `skipFocus` to `skip_focus`.
* Update the release notes entry rather than removing it, as the argument still works correctly.
* Update the wording to use "the toolbar is now not focused" instead of "the toolbar now avoids stealing focus" to avoid confusion about retaining focus, since focus outside the editor is lost when the command is run.
Pre-checks:
Review:
=> DOC-2318: Fix `skip_focus` check to the `ToggleToolbarDrawer` command from 6.4.1 release notes.

modules/ROOT/partials/configuration/sandbox_iframes.adoc, modules/ROOT/partials/configuration/sandbox_iframes_exclusions.adoc
Ticket: DOC-2356
Site: [DOC-2356 site](http://docs-hotfix-70-doc-2356.staging.tiny.cloud/docs/tinymce/latest/content-filtering/#sandbox-iframes)
Changes:
* fix broken links in `sandbox-iframes.adoc` and `sandbox-iframe-exclusions.adoc`.
Pre-checks:
Review:
=> DOC-2356: fix broken links in `sandbox-iframes.adoc` and `sandbox-iframe-exclusions.adoc`.

modules/ROOT/nav.adoc, modules/ROOT/pages/7.0-release-notes.adoc
Ticket: DOC-2333
Site: [DOC-2333 site](http://docs-hotfix-70-doc-2333.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#security-fixes)
Changes:
* Add Cross-Site Scripting (XSS) vulnerability's to TinyMCE `7.0.0` release notes.
Pre-checks:
Review:
=> DOC-2333: Add Cross-Site Scripting (XSS) vulnerability's to TinyMCE `7.0.0` release notes.

modules/ROOT/pages/7.0.1-release-notes.adoc
Entry: TINY-10789
Site: [Staging branch](http://docs-feature-7-doc-2354tiny-10789.staging.tiny.cloud/docs/tinymce/latest/7.0.1-release-notes/#table-of-contents)
Changes:
* DOC-2354: Add TINY-10789 release note entry
Pre-checks:
Review:
=> DOC-2354: Add TINY-10789 release note entry

modules/ROOT/pages/bower-projects.adoc, modules/ROOT/pages/cloud-quick-start.adoc, modules/ROOT/pages/dotnet-projects.adoc, modules/ROOT/pages/license-key.adoc, modules/ROOT/pages/npm-projects.adoc, modules/ROOT/pages/php-projects.adoc, modules/ROOT/pages/zip-install.adoc, modules/ROOT/partials/install/basic-quickstart-base.adoc, modules/ROOT/partials/misc/setting-the-license.adoc
Ticket: DOC-2355
Site Pages (same file change affects all these pages):
- [DOC-2355 npm site](http://docs-hotfix-7-doc-2355.staging.tiny.cloud/docs/tinymce/latest/npm-projects)
- [DOC-2355 php site](http://docs-hotfix-7-doc-2355.staging.tiny.cloud/docs/tinymce/latest/php-projects)
- [DOC-2355 dotnet site](http://docs-hotfix-7-doc-2355.staging.tiny.cloud/docs/tinymce/latest/dotnet-projects)
- [DOC-2355 bower site](http://docs-hotfix-7-doc-2355.staging.tiny.cloud/docs/tinymce/latest/bower-projects)
- [DOC-2355 zip site](http://docs-hotfix-7-doc-2355.staging.tiny.cloud/docs/tinymce/latest/zip-install)
Changes:
* update quickstart self-hosted pages (the five pages linked above) to include "Setting the license" information
* extract the "Setting the license" section of `license-key.adoc` into …
=> DOC-2355 add "Setting the license" information to quickstart self-hosted documents

modules/ROOT/pages/7.0.1-release-notes.adoc
Entry: TINY-10760
Site: [Staging branch](http://docs-feature-7-doc-2354tiny-10760.staging.tiny.cloud/docs/tinymce/latest/7.0.1-release-notes/#light-mode-background-with-advcode_inline-true-had-the-wrong-color-when-tinymce-was-used-with-a-dark-skin)
Changes:
* DOC-2354: Add TINY-10760 release note entry
Pre-checks:
Review:
=> DOC-2354: Add TINY-10760 release note entry

modules/ROOT/pages/7.0.1-release-notes.adoc
Entry: TINY-10784
Site: [Staging branch](http://docs-feature-7-doc-2354tiny-10784.staging.tiny.cloud/docs/tinymce/latest/7.0.1-release-notes/#text-inside-code-editor-was-not-properly-rendered-when-using-a-dark-tinymce-skin)
Changes:
* DOC-2354: Add TINY-10784 release note entry
Pre-checks:
Review:
=> DOC-2354: Add TINY-10784 release note entry

modules/ROOT/pages/7.0.1-release-notes.adoc
Entry: TINY-10684
Site: [Staging branch](http://docs-feature-7-doc-2354tiny-10684.staging.tiny.cloud/docs/tinymce/latest/7.0.1-release-notes/#an-inline-editor-toolbar-now-behaves-correctly-in-horizontally-scrolled-containers)
Changes:
* DOC-2354: Add TINY-10684 release note entry
Pre-checks:
Review:
=> DOC-2354: Add TINY-10684 release note entry

modules/ROOT/pages/7.0.1-release-notes.adoc
Entry: TINY-10747
Site: [Staging branch](http://docs-feature-7-doc-2354tiny-10747.staging.tiny.cloud/docs/tinymce/latest/7.0.1-release-notes/#pasting-markdown-then-pressing-undo-resulted-in-incorrect-text-layout)
Changes:
* DOC-2354: Add TINY-10747 release note entry
Pre-checks:
Review:
=> DOC-2354: Add TINY-10747 release note entry

modules/ROOT/nav.adoc, modules/ROOT/pages/creating-a-skin.adoc
Ticket: DOC-2367
Site: [DOC-2367 site](http://docs-hotfix-7-doc-23672.staging.tiny.cloud/docs/tinymce/latest/creating-a-skin)
There was an error made in the previous hotfix. The intended change is to just remove the link to the Skin Tool which is only available in TinyMCE 5. Users can still create custom skins in later versions.
Changes:
* DOC-2367 restore creating-a-skin.adoc and only remove link to the Skin Tool
Pre-checks:
- [-] Files added for `New product features`, and included a `release note` entry.
Review:
=> DOC-2367 restore creating-a-skin.adoc and only remove link to the Skin Tool

modules/ROOT/partials/integrations/react-tech-ref.adoc
Ticket: DOC-2369
Site: [Staging branch](http://docs-feature-7-doc-2369.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
- Updated _react-tech-ref.adoc_ to include the `tabIndex` prop that was added.
Pre-checks:
Review:
=> DOC-2369: Added `tabIndex` prop to React's tech ref

.github/workflows/codeql.yml, .github/workflows/develop_7_docs.yml
Ticket: DOC-2324
Site: [Staging branch](http://docs-feature-7-doc-2324.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Added development and codeql workflows which apply to branches and PRs against tinymce/7 branch
Pre-checks:
Review:
=> DOC-2324: Add workflows for development on 7 docs branch

.github/pull_request_template.md, .github/workflows/codeql.yml, .github/workflows/develop_5_docs.yml
Ticket: DOC-2324
Site: [Staging branch](http://docs-feature-5-doc-2324.staging.tiny.cloud/docs/tinymce/5/)
Changes:
* Added development and codeql workflows which apply to branches and PRs against tinymce/5 branch
Pre-checks:
Review:
=> DOC-2324: Add workflows for development on 5 docs branch

antora.yml, modules/ROOT/nav.adoc, modules/ROOT/pages/individual-export-to-word-on-premises.adoc, modules/ROOT/pages/individual-import-from-word-and-export-to-word-on-premises.adoc, modules/ROOT/pages/individual-import-from-word-on-premises.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-api-usage-on-premises.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-autorization-on-premises.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-installation-on-premises.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-logs-on-premises.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-overview-on-premises.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-requirements-on-premises.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-ssl-communication-on-premises.adoc
Ticket: DOC-2352
Site: [DOC-2339_DOC-2352 site](http://docs-hotfix-7-doc-2339doc-2352.staging.tiny.cloud/docs/tinymce/latest/individual-import-from-word-and-export-to-word-on-premises/)
Changes:
* Add On-premises `Import from Word and Export to Word` documentation.
Pre-checks:
Review:
=> DOC-2352: On-premises `Import from Word and Export to Word` documentation.

modules/ROOT/nav.adoc, modules/ROOT/pages/cloud-deployment-guide.adoc, modules/ROOT/pages/demo-tinydrive.adoc, modules/ROOT/pages/editor-and-features.adoc, modules/ROOT/pages/enterprise-tinydrive.adoc, modules/ROOT/pages/examples.adoc, modules/ROOT/pages/general-configuration-guide.adoc, modules/ROOT/pages/getting-started.adoc, modules/ROOT/pages/release-notes504.adoc, modules/ROOT/pages/release-notes505.adoc, modules/ROOT/pages/release-notes507.adoc, modules/ROOT/pages/release-notes58.adoc, modules/ROOT/pages/release-notes581.adoc, modules/ROOT/pages/tinydrive-api.adoc, modules/ROOT/pages/tinydrive.adoc, modules/ROOT/partials/misc/plugin-menu-item-id-boilerplate.adoc, modules/ROOT/partials/misc/plugin-toolbar-button-id-boilerplate.adoc
Ticket: DOC-2372
Site: [Staging branch](http://docs-feature-doc-2372.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Renamed some index files to match 6/7 docs
* Populated some index files
* Removed links of unnecessary index files
Pre-checks:
Review:
=> DOC-2372: Rename and populate index files to match latest

.github/workflows/codeql.yml, .github/workflows/develop_5_docs.yml
Ticket: DOC-2373
Site: [Staging branch](http://docs-feature-5-doc-2373.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Updated versions in workflows
* Add support for release and staging branches for development builds
Pre-checks:
Review:
=> DOC-2373: Update workflow versions and branches

.github/workflows/codeql.yml, .github/workflows/develop_7_docs.yml
Ticket: DOC-2373
Site: [Staging branch](http://docs-feature-7-doc-2373.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Updated versions in workflows
* Add support for `release` and `staging` branches for development builds
Pre-checks:
Review:
=> DOC-2373: Update versions and branches within workflows

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-10778.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#new-index-js-file-that-includes-all-plugin-resources)
Changes:
* New `index.js` file that includes all plugin resources.
* include link back to the newly update bundling page.
Pre-checks:
Review:
=> DOC-2363: New `index.js` file that includes all plugin resources.

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-10795.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#removed-aria-pressed-from-the-more-button-in-sliding-toolbar-mode-and-replaced-it-with-aria-expanded)
Changes:
* added fix documentation for Removed `aria-pressed` from the `More` button in sliding toolbar mode and replaced it with `aria-expanded`.
Pre-checks:
Review:
=> DOC-2363: Removed `aria-pressed` from the `More` button in sliding toolbar mode and replaced it with `aria-expanded`

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-6925.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#notification-accessibility-improvements-added-tooltips-keyboard-navigation-and-shortcut-to-focus-on-notifications)
Changes:
* added `Notification accessibility improvements: added tooltips, keyboard navigation and shortcut to focus on notifications` to the release notes.
Pre-checks:
Review:
=> DOC-2363: Notification accessibility improvements: added tooltips, keyboard navigation and shortcut to focus on notifications.

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-10597.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#fullscreen-mode-now-prevents-focus-from-leaving-the-editor)
Changes:
* DOC-2363: Add TINY-10597 release note entry
Pre-checks:
Review:
=> DOC-2363: Add TINY-10597 release note entry

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-10800.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#dialog-title-markup-changed-to-use-an-h1-element-instead-of-div)
Changes:
* DOC-2363: Add TINY-10800 release note entry
Pre-checks:
Review:
=> DOC-2363: Add TINY-10800 release note entry

modules/ROOT/pages/keyboard-shortcuts.adoc, modules/ROOT/pages/tinymce-and-screenreaders.adoc
Ticket: DOC-2388
Site: [Staging branch](http://docs-feature-71-doc-2388.staging.tiny.cloud/docs/tinymce/latest/tinymce-and-screenreaders/)
[Staging branch](http://docs-feature-71-doc-2388.staging.tiny.cloud/docs/tinymce/latest/keyboard-shortcuts/)
Changes:
* Added documentation for shortcut to navigate to notifications and across multiple notifications
Pre-checks:
Review:
=> DOC-2388: Documenting notification keyboard navigation

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-10808.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#dialog-title-was-not-announced-in-macos-voiceover-dialogs-now-use-aria-label-instead-of-aria-labelledby-on-macos)
Changes:
* added fix documentation for Dialog title was not announced in macOS VoiceOver, dialogs now use `aria-label` instead of `aria-labelledby` on macOS.
Pre-checks:
Review:
=> DOC-2363: Dialog title was not announced in macOS VoiceOver, dialogs now use `aria-label` instead of `aria-labelledby` on macOS.

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-10726.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#toggletoolbardrawer-command-did-not-toggle-the-toolbar-in-sliding-mode-when-skipfocus-true-parameter-was-passed)
Changes:
* Add `ToggleToolbarDrawer` command did not toggle the toolbar in `sliding` mode when `{skipFocus: true}` parameter was passed to the release notes.
Pre-checks:
Review:
=> DOC-2363: `ToggleToolbarDrawer` command did not toggle the toolbar in `sliding` mode when `{skipFocus: true}` parameter was passed.

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-10718.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#firefox-not-announcing-the-iframe-title-when-iframe_aria_text-was-set)
Changes:
* added fix documentation for Firefox not announcing the iframe title when `iframe_aria_text` was set.
Pre-checks:
Review:
=> DOC-2363: Firefox not announcing the iframe title when `iframe_aria_text` was set.

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-10725.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#mentions)
Changes:
* DOC-2363: release note entry for TINY-10725
Pre-checks:
Review:
=> DOC-2363: release note entry for TINY-10725

modules/ROOT/pages/7.1-release-notes.adoc
Release notes ticket ref: DOC-2363
Ticket: DOC-2396
Site: [Staging branch](http://docs-feature-71-doc-2396.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#windows-high-contrast-mode-is-now-supported-in-tinymce)
Changes:
* DOC-2396: add Windows High Contrast mode support to 7.1 release notes
Pre-checks:
Review:
=> DOC-2396: add Windows High Contrast mode support to 7.1 release notes

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-10780.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#enhanced-code-editor)
Changes:
* DOC-2363: Add TINY-10780 release note entry
Pre-checks:
Review:
=> DOC-2363: Add TINY-10780 release note entry

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-9932.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#included-itemprop-itemscope-itemtype-as-valid-html5-attributes-in-the-core-schema)
Changes:
* Added improvement documentation for: Included `itemprop`, `itemscope`, `itemtype` as valid HTML5 attributes in the core schema.
Pre-checks:
Review:
=> DOC-2363: Included `itemprop`, `itemscope`, `itemtype` as valid HTML5 attributes in the core schema.

modules/ROOT/nav.adoc, modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tcloud-4278.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#accompanying-premium-self-hosted-server-side-component-changes)
Changes:
* `ephox-hyperlinking.war`: 2.105.25
* `ephox-image-proxy.war`: 2.106.12
* `ephox-spelling.war`: 2.118.21
Pre-checks:
Review:
=> DOC-2363: Accompanying Premium self-hosted server-side component changes in TinyMCE 7.1

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-10391.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* add fix documentation for `Open link context menu action was not enabled for links on images.`
Pre-checks:
Review:
=> DOC-2363: Open link context menu action was not enabled for links on images.

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-10886.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#notification-width-was-not-constrained-to-the-width-of-the-editor)
Changes:
* added fix documentation for `Notification width was not constrained to the width of the editor.`
Pre-checks:
Review:
=> DOC-2363: Notification width was not constrained to the width of the editor.

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-10774.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#video-and-audio-elements-could-not-be-played-on-safari)
Changes:
* added `Video and audio elements could not be played on Safari` to TinyMCE 7.1 release notes.
Pre-checks:
Review:
=> DOC-2363: Video and audio elements could not be played on Safari.

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-10741.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#in-the-custom-view-the-scrollbar-of-the-container-were-not-visible-if-its-height-was-greater-than-the-editor)
Changes:
* added improvement docs for `In the custom view, the scrollbar of the container were not visible if its height was greater than the editor.`
Pre-checks:
Review:
=> DOC-2363: In the custom view, the scrollbar of the container were not visible if its height was greater than the editor.

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-10837.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#styles-were-not-retained-when-toggling-a-list-on-and-off)
Changes:
* added fix for `Styles were not retained when toggling a list on and off.`
Pre-checks:
Review:
=> DOC-2363: Styles were not retained when toggling a list on and off.

modules/ROOT/pages/7.1-release-notes.adoc, modules/ROOT/pages/a11ychecker.adoc, modules/ROOT/pages/events.adoc, modules/ROOT/partials/events/a11ychecker-events.adoc
Site: [Staging branch- Release notes](http://docs-feature-71-doc-2363tiny-10777.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#added-new-a11ycheckstart-a11ycheckstop-a11ycheckignore-a11ycheckrepair-and-a11ycheckshowdetails-events)
Site: [Staging branch- Events](http://docs-feature-71-doc-2363tiny-10777.staging.tiny.cloud/docs/tinymce/latest/a11ychecker/#events)
Changes:
* Added new A11ycheckStart, A11ycheckStop, A11ycheckIgnore, A11ycheckRepair and A11ycheckShowDetails events to `a11ychecker.adoc`, and added release notes entry for new added events.
Pre-checks:
Review:
=> DOC-2363: Added new `A11ycheckStart`, `A11ycheckStop`, `A11ycheckIgnore`, `A11ycheckRepair` and `A11ycheckShowDetails` events..

modules/ROOT/pages/7.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-71-doc-2363tiny-10813.staging.tiny.cloud/docs/tinymce/latest/7.1-release-notes/#custom-block-elements-with-colon-characters-would-throw-errors)
Changes:
* add `Custom block elements with colon characters would throw errors.` to TinyMCE 7.1 release notes.
Pre-checks:
Review:
=> DOC-2363: Custom block elements with colon characters would throw errors.

modules/ROOT/pages/ai.adoc
Ticket: DOC-2399
Site: [Staging branch](http://docs-hotfix-7-doc-23992.staging.tiny.cloud/docs/tinymce/latest/ai/#basic-setup)
Hotfix - I forgot to update the "Basic setup" section with the initial pull request.
Changes:
* DOC-2399: Update Basic Setup section in AI Assistant plugin page
Pre-checks:
- [-] Files added for `New product features`, and included a `release note` entry.
Review:
=> DOC-2399: Update Basic Setup section in AI Assistant plugin page

modules/ROOT/pages/migration-from-6x.adoc
Ticket: DOC-2418
Site: [Staging branch](http://docs-hotfix-7-doc-2418.staging.tiny.cloud/docs/tinymce/latest/migration-from-6x/#:~:text=This%20documentation%20details%20the%20changes%20in%20TinyMCE%207.0%20that%20integrators%20using%20TinyMCE%206%20should%20consider%20when%20upgrading.)
Changes:
* Copy edits to `migration-from-6x.adoc`
* Replaced version (num) with variable.
Pre-checks:
Review:
=> DOC-2418: Copy edits to `migration-from-6x.adoc`, and replaced version (num) with variable.

modules/ROOT/nav.adoc, modules/ROOT/pages/cloud-deployment-guide.adoc, modules/ROOT/pages/editor-plugin-version.adoc, modules/ROOT/partials/misc/admon-script-tag-placement.adoc
Ticket: DOC-2392
Site: [Staging branch](http://docs-hotfix-7-doc-2392.staging.tiny.cloud/docs/tinymce/latest/editor-plugin-version/)
Changes:
* Remove list of plugins versions from document.
* Remove mention of the ability to specify plugin versions when loading from Cloud.
* Added new `admon` for `important` message for placement of script tags.
Pre-checks:
Review:
=> DOC-2392: Re-write of `editor-plugin-version.adoc` page.

modules/ROOT/pages/7.1.1-release-notes.adoc, modules/ROOT/partials/configuration/emoticons_images_url.adoc
Site: [Staging branch: release notes entry](http://docs-feature-711-doc-2411tiny-10878.staging.tiny.cloud/docs/tinymce/latest/7.1.1-release-notes/#resolved-an-issue-where-emojis-were-not-loading-correctly-due-to-a-broken-cdn)
Site: [Staging branch: emoticons_images_url](http://docs-feature-711-doc-2411tiny-10878.staging.tiny.cloud/docs/tinymce/latest/emoticons/#emoticons_images_url)
Changes:
* Added fix for TINY-10878 and included changes to `emoticons#emoticons_images_url` for DOC-2406.
Pre-checks:
Review:
=> DOC-2411: Resolved an issue where emojis were not loading correctly due to a broken CDN

modules/ROOT/pages/7.1.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-711-doc-2411tiny-10892.staging.tiny.cloud/docs/tinymce/latest/7.1.1-release-notes/#deleting-into-a-list-from-a-paragraph-that-has-an-img-tag-could-cause-extra-inline-styles-to-be-added)
Changes:
* DOC-2411: Add TINY-10892 release note entry
Pre-checks:
Review:
=> DOC-2411: Add TINY-10892 release note entry

modules/ROOT/pages/7.1.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-711-doc-2411tiny-10898.staging.tiny.cloud/docs/tinymce/latest/7.1.1-release-notes/#math-plugin)
Changes:
* add fix documentation for TINY-10898 to the release notes.
Pre-checks:
Review:
=> DOC-2411: Clearing the formula input and then saving didn't remove the element

modules/ROOT/pages/7.1.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-711-doc-2411tiny-10421.staging.tiny.cloud/docs/tinymce/latest/7.1.1-release-notes/#the-sort-algorithm-would-sometimes-incorrectly-compare-words-that-start-with-a-digit)
Changes:
* DOC-2411: Add TINY-10421 release note entry
Pre-checks:
Review:
=> DOC-2411: Add TINY-10421 release note entry

modules/ROOT/pages/7.1.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-711-doc-2411tiny-10885.staging.tiny.cloud/docs/tinymce/latest/7.1.1-release-notes/#insertedit-image-dialog-lost-focus-after-the-image-upload-completed)
Changes:
* DOC-2411: Add TINY-10885 release note entry
Pre-checks:
Review:
=> DOC-2411: Add TINY-10885 release note entry

modules/ROOT/pages/7.1.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-711-doc-2411tiny-10901.staging.tiny.cloud/docs/tinymce/latest/7.1.1-release-notes/#iframes-in-dialogs-were-not-rendering-rounded-borders-correctly)
Changes:
* added fix documentation for TINY-10901 to the release notes.
Pre-checks:
Review:
=> DOC-2411: Iframes in dialogs were not rendering rounded borders correctly.

modules/ROOT/pages/7.1.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-711-doc-2411tiny-10942.staging.tiny.cloud/docs/tinymce/latest/7.1.1-release-notes/#autocompleter-possible-values-are-no-longer-capped-at-a-length-of-10)
Changes:
* DOC-2411: Add TINY-10942 release note entry
Pre-checks:
Review:
=> DOC-2411: Add TINY-10942 release note entry

modules/ROOT/partials/configuration/advtemplate_list.adoc
Site: [Staging branch](http://docs-hotfix-7-template-wording.staging.tiny.cloud/docs/tinymce/latest/advanced-templates/#advtemplate_list)
Changes:
* [Previously](https://www.tiny.cloud/docs/tinymce/latest/advanced-templates/#advtemplate_list) it could appear at first glance like the value of the config was an array - arguably a bit misleading.
* I rearranged the section to put the code example first, then a description of the response, then the response block.
* I renamed the response block to a _sample_, rather than an _example_.
* No other content changes were made.
I suspect we might need a wider effort to change the statement that "return value is array" - it's really a promise containing an array - but that's happened on every section of the template docs so I don't want to do that …
=> Rearrange advtemplate_list docs to make the example clearer

modules/ROOT/pages/7.1.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-711-doc-2411tiny-10585.staging.tiny.cloud/docs/tinymce/latest/7.1.1-release-notes/#powerpaste)
Changes:
* add fix for TINY-10585 to the release notes.
Pre-checks:
Review:
=> DOC-2411: List with start attribute separated by  tags resulted in wrong numbering of the lists.

modules/ROOT/pages/7.1.2-release-notes.adoc
Ticket: DOC-2419
Site: [Spell Checker entry](http://docs-feature-712-doc-2419tiny-10904.staging.tiny.cloud/docs/tinymce/latest/7.1.2-release-notes/#spell-checker)
Site: [Core entry](http://docs-feature-712-doc-2419tiny-10904.staging.tiny.cloud/docs/tinymce/latest/7.1.2-release-notes/#acronyms-were-not-managed-correctly)
Changes:
* added fix documentation for TINY-10904
* included both release note entry to support fix for `acronyms` and premium plugin change as we added `new handling` logic for `acronyms`.
Pre-checks:
Review:
=> DOC-2419: Acronyms were not managed correctly.

modules/ROOT/pages/7.1.2-release-notes.adoc
Ticket: DOC-2419
Site: [Staging branch](http://docs-feature-712-doc-2419tiny-10916.staging.tiny.cloud/docs/tinymce/latest/7.1.2-release-notes/#css-color-values-set-to-transparent-were-incorrectly-converted-to-000000)
Changes:
* add fix documentation for TINY-10916.
Pre-checks:
Review:
=> DOC-2419: CSS color values set to `transparent` were incorrectly converted to `#000000`.

modules/ROOT/pages/7.1.2-release-notes.adoc
Ticket: DOC-2419
Site: [Staging branch](http://docs-feature-712-doc-2419tiny-10931.staging.tiny.cloud/docs/tinymce/latest/7.1.2-release-notes/#math-icon-state-was-not-set-to-active-on-math-element-selection)
Changes:
* Add fix documentation for TINY-10931
Pre-checks:
Review:
=> DOC-2419: Math icon state was not set to `active` on math element selection.

modules/ROOT/partials/integrations/angular-tech-ref.adoc
Ticket: DOC-2346
Site: [Staging branch](http://docs-feature-7-doc-2346.staging.tiny.cloud/docs/tinymce/7/)
Changes:
- Added `licenseKey` info
- Updated Angular version table to match what is in `tinymce-angular`'s _README.md_
- Updated event list to include the new events in v8
Pre-checks:
Review:
=> DOC-2346: Updated Angular technical reference page to support tinymce-angular v8 changes

modules/ROOT/partials/integrations/svelte-tech-ref.adoc
Ticket: DOC-2383
Site: [Staging branch](http://docs-hotfix-7-doc-2383.staging.tiny.cloud/docs/tinymce/latest/svelte-ref/)
Changes:
* Added `licenseKey` info
* Updated Svelte version table to match what is in `tinymce-svelte README.md`
* Updated event list to include the new events in `v7`.
Pre-checks:
Review:
=> DOC-2383: Update Svelte Integration's Technical Reference page for TinyMCE V7 release.

modules/ROOT/partials/integrations/vue-tech-ref.adoc
Ticket: DOC-2382
Site: [Staging branch: Vue-tech-ref](http://docs-hotfix-7-doc-2382.staging.tiny.cloud/docs/tinymce/latest/vue-ref/)
Changes:
* Add `licenseKey` documentation to Vue integration guide and missing Events.
Pre-checks:
Review:
=> DOC-2382: Add `licenseKey` documentation to Vue integration guide.

modules/ROOT/pages/pageembed.adoc, modules/ROOT/pages/permanentpen.adoc, modules/ROOT/pages/tinydrive-dropbox-integration.adoc, modules/ROOT/pages/tinydrive-googledrive-integration.adoc
Ticket: DOC-2432
- Site: [permanentpen/#using-the-ui](http://docs-hotfix-7-doc-2432.staging.tiny.cloud/docs/tinymce/latest/permanentpen/#using-the-ui)
- Site: [pageembed/#using-page-embed](http://docs-hotfix-7-doc-2432.staging.tiny.cloud/docs/tinymce/latest/pageembed/#using-page-embed)
Changes:
* replace mentions of `radio` buttons to render `checkbox` in all documentation pages.
Pre-checks:
Review:
=> DOC-2432: Update mention text of `radio` buttons to read `checkbox` instead.

modules/ROOT/examples/live-demos/ai/example.js, modules/ROOT/examples/live-demos/ai/index.js, modules/ROOT/pages/ai-openai.adoc, modules/ROOT/partials/configuration/ai_request.adoc
Ticket: DOC-2441
Site: [Staging branch](http://docs-hotfix-7-doc-2441.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Change model in config from  “model: "gpt-3.5-turbo"  to “model: 'gpt-4o'“.
Pre-checks:
Review:
=> DOC-2441: update ai assistant to use new GPT4o model.

modules/ROOT/pages/7.2-release-notes.adoc
Site: [Staging branch](http://docs-feature-72-doc-2446tiny-104282.staging.tiny.cloud/docs/tinymce/latest/7.2-release-notes/#image-editing)
Changes:
* DOC-2446: Add TINY-10428 release note entry
Pre-checks:
Review:
=> DOC-2446: Add TINY-10428 release note entry

modules/ROOT/pages/7.2-release-notes.adoc
Site: [Staging branch](http://docs-feature-72-doc-2446tiny-10374.staging.tiny.cloud/docs/tinymce/latest/7.2-release-notes/#added-referrerpolicy-as-a-valid-attribute-for-an-iframe-element)
Changes:
* DOC-2446: Add TINY-10374 release note entry
Pre-checks:
Review:
=> DOC-2446: Add TINY-10374 release note entry

modules/ROOT/pages/7.2-release-notes.adoc
Site: [Staging branch](http://docs-feature-72-doc-2446tiny-10605.staging.tiny.cloud/docs/tinymce/latest/7.2-release-notes/#added-options-debug-api-that-logs-the-initial-raw-editor-options-to-console)
Changes:
* DOC-2446: Add TINY-10605 release note entry
Pre-checks:
Review:
=> DOC-2446: Add TINY-10605 release note entry

modules/ROOT/pages/editor-plugin-version.adoc
Ticket: DOC-2450
Site: [Staging branch](http://docs-hotfix-6-doc-2450.staging.tiny.cloud/docs/tinymce/6/editor-plugin-version)
**HOTFIX: same changes as [hotfix/7/DOC-2450](https://github.com/tinymce/tinymce-docs/pull/3331) but for 6 Docs**
Changes:
* Add examples of specifying minor and patch versions
* Move the "Difference between using TinyMCE 6, 6-Testing, and 6-Dev release channels" section to the top of the document so that information about specifying editor version is all in one place.
Pre-checks:
- [-] Files added for `New product features`, and included a `release …
=> Port changes from 7x Docs for restructure of editor-plugin-version.adoc

modules/ROOT/nav.adoc, modules/ROOT/pages/editor-plugin-version.adoc
Ticket: DOC-2450
Site: [Staging branch](http://docs-hotfix-7-doc-2450.staging.tiny.cloud/docs/tinymce/latest/editor-plugin-version)
**HOTFIX**
Changes:
* Add examples of specifying minor and patch versions
* Move the "Difference between using TinyMCE 7, 7-Testing, and 7-Dev release channels" section to the top of the document so that information about specifying editor version is all in one place.
Pre-checks:
- [-] Files added for `New product features`, and included a `release note` entry.
Review:
=> DOC-2450: Restructure editor-plugin-version.adoc

modules/ROOT/pages/7.2-release-notes.adoc
Site: [Staging branch](http://docs-feature-72-doc-2446tiny-10820.staging.tiny.cloud/docs/tinymce/latest/7.2-release-notes/#focusing-on-contenteditabletrue-element-when-using-editable_root-false-and-inline-mode-caused-selection-to-be-shifted)
Changes:
* Add TINY-10820 release note entry: Focusing on `contenteditable="true"` element when using `editable_root: false` and inline mode caused selection to be shifted.
Pre-checks:
Review:
=> DOC-2446: Add TINY-10820 release note entry

modules/ROOT/pages/7.2-release-notes.adoc
Site: [Staging branch](http://docs-feature-72-doc-2446tiny-11001.staging.tiny.cloud/docs/tinymce/latest/7.2-release-notes/#replaced-tiny-branding-logo-with-build-with-tinymce-text-and-logo)
Changes:
* DOC-2446: Add TINY-11001 release note entry: Replaced tiny branding logo with `Build with TinyMCE` text and logo.
Pre-checks:
Review:
=> DOC-2446: Add TINY-11001 release note entry

modules/ROOT/pages/7.2-release-notes.adoc
Site: [Staging branch](http://docs-feature-72-doc-2446tiny-10869.staging.tiny.cloud/docs/tinymce/latest/7.2-release-notes/#improve-merging-of-inserted-inline-elements-by-removing-nodes-with-redundant-inheritable-styles)
Changes:
* Add TINY-10869 release note entry: Improve merging of inserted inline elements by removing nodes with redundant inheritable styles.
Pre-checks:
Review:
=> DOC-2446: Add TINY-10869 release note entry

modules/ROOT/pages/7.2-release-notes.adoc, modules/ROOT/pages/powerpaste-options.adoc, modules/ROOT/partials/configuration/powerpaste_autolink_urls.adoc, modules/ROOT/partials/configuration/smart_paste.adoc
Site: [Staging branch](http://docs-feature-72-doc-2446tiny-10962.staging.tiny.cloud/docs/tinymce/latest/7.2-release-notes/#new-option-to-disable-the-auto-linking-feature-in-powerpaste)
Site: [New powerpaste_autolink_urls  option](http://docs-feature-72-doc-2446tiny-10962.staging.tiny.cloud/docs/tinymce/latest/powerpaste-options/#powerpaste_autolink_urls)
Changes:
* Add TINY-10962 release note entry: New option to disable the auto-linking feature in PowerPaste. **(@kemister85 the heading has been modified form the [original changie title](https://github.com/tinymce/tinymce-premium/pull/214/files#diff-f0abfed8886d754d30efb422a296814751436924a360100cb10a6371a5f96c94))**
* New `powerpaste_autolink_urls.adoc` option page
* Add link to new option in `powerpaste-options.adoc` …
=> DOC-2446: Add TINY-10962 release note entry

modules/ROOT/pages/7.2-release-notes.adoc
Site: [Staging branch](http://docs-feature-72-doc-2446tiny-10871.staging.tiny.cloud/docs/tinymce/latest/7.2-release-notes/#improved-find-replace-dialog-accessibility-by-changing-placeholders-to-labels)
Changes:
* add improvement fix for TINY-10871
Pre-checks:
Review:
=> DOC-2446: Improved `Search & Replace` dialog accessibility by changing placeholders to labels.

modules/ROOT/pages/7.2-release-notes.adoc
Site: [Staging branch](http://docs-feature-72-doc-2446tiny-10384.staging.tiny.cloud/docs/tinymce/latest/7.2-release-notes/#fixed-cases-where-adding-a-newline-around-a-br-table-or-img-would-not-move-the-cursor-to-a-new-line)
Changes:
* add fix documentation for TINY-10384
Pre-checks:
Review:
=> DOC-2446: Fixed cases where adding a newline around a `br`, `table` or `img` would not move the cursor to a new line.

modules/ROOT/pages/7.2-release-notes.adoc
Site: [Staging branch](http://docs-feature-72-doc-2446tiny-10891.staging.tiny.cloud/docs/tinymce/latest/7.2-release-notes/#accessibility-for-element-path-buttons-added-tooltip-to-describe-the-button-and-removed-incorrect-aria-level-attribute)
Changes:
* Add TINY-10891 release note entry: Accessibility for element path buttons, added tooltip to describe the button and removed incorrect `aria-level` attribute.
Pre-checks:
Review:
=> DOC-2446: Add TINY-10891 release note entry

modules/ROOT/pages/dialog-components.adoc
Site: [Staging branch](http://docs-feature-72-doc-2446tiny-10971.staging.tiny.cloud/docs/tinymce/latest/dialog-components/#label)
Changes:
* Add `for` attribute to label component in `dialog-components.adoc` to support TINY-10971
Pre-checks:
Review:
=> DOC-2446: Add `for` attribute to label component in `dialog-components.adoc`.

modules/ROOT/pages/7.2-release-notes.adoc, modules/ROOT/pages/editor-command-identifiers.adoc
Site: [Staging branch](http://docs-feature-72-doc-2446tiny-tiny-10938.staging.tiny.cloud/docs/tinymce/latest/7.2-release-notes/#added-support-for-querying-the-state-of-the-mcetoggleplaintextpaste-command)
Changes:
* TINY-10938 Release Note Entry: Added support for querying the state of the `mceTogglePlainTextPaste` command.
* Add `mceTogglePlainTextPaste` command to `editor-command-identifiers.adoc`
Pre-checks:
Review:
=> DOC-2446: Added support for querying the state of the `mceTogglePlainTextPaste` command.

modules/ROOT/partials/security/sanitizing-html-input-and-protecting-against-xss-attacks-dom-parser-and-dom-purify.adoc
Ticket: DOC-2456
Site: [Staging branch](http://docs-hotfix-6-doc-2456.staging.tiny.cloud/docs/tinymce/6/security/#sanitizing-html-input-to-protect-against-xss-attacks)
**The version of DOMPurify used in TinyMCE was updated to 3.x in [this commit](https://github.com/tinymce/tinymce/pull/9020/files) which was released with TinyMCE 6.8.0, however, the documentation was never updated to match this.**
Changes:
* Update DOMPurify version in security guide to explain version change from DOMPurify 2.x to 3.x in TinyMCE 6.8.0
* Replace some TinyMCE 6 references with Antora attributes
Pre-checks:
- [-] Files removed have been deleted, not just excluded from the build `(if …
=> DOC-2456: Docs 6 - Update DOMPurify version in security guide

modules/ROOT/partials/security/sanitizing-html-input-and-protecting-against-xss-attacks-dom-parser-and-dom-purify.adoc
Ticket: DOC-2456
Site: [Staging branch](http://docs-hotfix-7-doc-2456.staging.tiny.cloud/docs/tinymce/latest/security/#sanitizing-html-input-to-protect-against-xss-attacks)
**The version of DOMPurify used in TinyMCE was updated to 3.x in [this commit](https://github.com/tinymce/tinymce/pull/9020/files) which was released with TinyMCE 6.8.0, however, the documentation was never updated to match this.**
Changes:
* Update DOMPurify version in security guide
* Update some TinyMCE 6 references with TinyMCE 7
Pre-checks:
- [-] Files added for `New product features`, and included a …
=> DOC-2456: Docs 7 - Update DOMPurify version in security guide

modules/ROOT/nav.adoc, modules/ROOT/pages/7.2-release-notes.adoc, modules/ROOT/pages/changelog.adoc
Ticket: DOC-2457
Site: [Changelog Update](http://docs-hotfix-72-doc-24572.staging.tiny.cloud/docs/tinymce/latest/changelog/#7-2-0-2024-06-19:~:text=HTML%20entities%20that,the%20noneditable_regexp%20option.)
Site: [Security Fixes](http://docs-hotfix-72-doc-24572.staging.tiny.cloud/docs/tinymce/latest/7.2-release-notes/#security-fixes)
Changes:
* TinyMCE Cross-Site Scripting (XSS) vulnerability using `noneditable_regexp` option
* TinyMCE Cross-Site Scripting (XSS) vulnerability using `noscript` elements
Pre-checks:
Review:
=> DOC-2457: TinyMCE 7.2 Security Patch.

modules/ROOT/nav.adoc, modules/ROOT/pages/6.8.4-release-notes.adoc, modules/ROOT/pages/changelog.adoc, modules/ROOT/pages/release-notes.adoc
Ticket: DOC-2457
Site: [Staging branch](http://docs-hotfix-684-doc-2457.staging.tiny.cloud/docs/tinymce/6/6.8.4-release-notes/#overview)
Site: [Staging branch](http://docs-hotfix-684-doc-2457.staging.tiny.cloud/docs/tinymce/6/changelog/#6-8-4-2024-06-19)
Changes:
* TinyMCE Cross-Site Scripting (XSS) vulnerability using `noneditable_regexp` option
* TinyMCE Cross-Site Scripting (XSS) vulnerability using `noscript` elements
Pre-checks:
Review:
=> DOC-2457: TinyMCE 6.8.4 Security Patch.

modules/ROOT/pages/7.2-release-notes.adoc
Ticket: DOC-2461
Site: [Staging branch](http://docs-hotfix-72-doc-24612.staging.tiny.cloud/docs/tinymce/latest/7.2-release-notes/#security-fixes)
Changes:
* add CVE for: HTML entities that were double decoded in noscript elements caused an XSS vulnerability.0
* add CVE for: It was possible to inject XSS HTML that was not matching the regexp when using the noneditable_regexp option.
Pre-checks:
Review:
=> DOC-2461_2: Add CVE's for TinyMCE 7.2 release notes.

modules/ROOT/pages/6.8.4-release-notes.adoc
Ticket: DOC-2461
Site: [Staging branch](http://docs-hotfix-684-doc-2461.staging.tiny.cloud/docs/tinymce/6/6.8.4-release-notes/#security-fixes)
Changes:
* add CVE for: HTML entities that were double decoded in `noscript` elements caused an XSS vulnerability. 
* add CVE for: It was possible to inject XSS HTML that was not matching the regexp when using the `noneditable_regexp` option.
Pre-checks:
Review:
=> DOC-2461: Add CVE's to the TinyMCE 6.8.4 release notes.

modules/ROOT/partials/integrations/angular-quick-start.adoc
Ticket: DOC-2435
Site: [Staging branch](http://docs-feature-doc-2435.staging.tiny.cloud/docs/tinymce/latest/angular-cloud/)
Changes:
- Updated _angular.io_ links to point to new Angular docs at _angular.dev_.
- Using standalone components are now the default for Angular projects, so this is now reflected in the docs. This simplified some sections as most changes are made to a single component. 
- Added an Angular modules note at the bottom. This mentions the use of `EditorModule`.
This was tested with Angular v18 CLI.
Pre-checks:
Review:
=> DOC-2435: Updated Angular quick start guides

modules/ROOT/partials/misc/supported-versions.adoc
Ticket: DOC-2460
Site: [Staging branch](http://docs-hotfix-6-doc-24602.staging.tiny.cloud/docs/tinymce/6/support/)
Changes:
* Update the supported versions table in `misc/supported-versions.adoc` to reflect 7x changes.
Pre-checks:
Review:
=> DOC-2460_2: Update the supported versions table in `misc/supported-versions.adoc` to reflect 7x changes.

modules/ROOT/pages/wordpress.adoc
Ticket: DOC-2475
Site: [Staging branch](http://docs-hotfix-7-doc-2475.staging.tiny.cloud/docs/tinymce/latest/wordpress/)
Changes:
* Remove old blog link to `How to use TinyMCE premium plugins in WordPress 5.` in 7x docs.
Pre-checks:
Review:
=> DOC-2475: Remove old link to Tiny Blog - How to use TinyMCE premium plugins in WordPress 5.

modules/ROOT/examples/live-demos/inline/index.js
Ticket: DOC-2471
Site: [Staging branch](http://docs-hotfix-7-doc-2471.staging.tiny.cloud/docs/tinymce/latest/inline-demo/)
Changes:
* Add `toolbar_sticky_offset`, to correct visual UI issue with inline-demos in docs.
Pre-checks:
Review:
=> DOC-2471: Update inline-demo to support `toolbar_sticky_offset`, to correct visual UI issue.

modules/ROOT/pages/7.2.1-release-notes.adoc
Site: [Staging branch](http://docs-feature-721-doc-2466tiny-10127.staging.tiny.cloud/docs/tinymce/latest/7.2.1-release-notes/#cursor-would-shift-to-the-start-of-the-editor-body-when-focus-was-shifted-to-a-noneditable-cell-of-a-table)
Changes:
* DOC-2466: Add TINY-10127 release note entry
Pre-checks:
Review:
=> DOC-2466: Cursor would shift to the start of the editor body when focus was shifted to a noneditable cell of a table.

modules/ROOT/pages/7.2.1-release-notes.adoc
Ticket: DOC-2466
Site: [Staging branch](http://docs-feature-721-doc-2466tiny-11009.staging.tiny.cloud/docs/tinymce/latest/7.2.1-release-notes/#open-link-button-was-disabled-when-selection-partially-covered-a-link-or-when-multiple-links-were-selected)
Changes:
* added fix documentation for TINY-11009
Pre-checks:
Review:
=> DOC-2466: `Open Link` button was disabled when selection partially covered a link or when multiple links were selected.

modules/ROOT/pages/7.2.1-release-notes.adoc
Ticket: DOC-2466
Site: [Staging branch](http://docs-feature-721-doc-2466tiny-10961.staging.tiny.cloud/docs/tinymce/latest/7.2.1-release-notes/#long-translations-of-the-bottom-help-text-would-cause-minor-graphical-issues)
Changes:
* add fix documentation for TINY-10961
Pre-checks:
Review:
=> DOC-2466: Long translations of the bottom help text would cause minor graphical issues.

modules/ROOT/pages/7.2.1-release-notes.adoc
Ticket: DOC-2466
Site: [Staging branch](http://docs-feature-721-doc-2466tiny-10590.staging.tiny.cloud/docs/tinymce/latest/7.2.1-release-notes/#text-content-could-move-unexpectedly-when-deleting-a-paragraph)
Changes:
* Add fix documentation for TINY-10590
Pre-checks:
Review:
=> DOC-2466: Text content could move unexpectedly when deleting a paragraph.

modules/ROOT/pages/release-notes.adoc
Ticket: DOC-2469
Site: [Staging branch](http://docs-hotfix-7-doc-24692.staging.tiny.cloud/docs/tinymce/latest/release-notes)
Changes:
* Fix release-notes.adoc table to show to final entry.
Pre-checks:
Review:
=> DOC-2469: Fix release-notes.adoc table

modules/ROOT/partials/plugin-apis/revisionhistory-apis.adoc
Ticket: DOC-2486
Site: [Staging branch](http://docs-hotfix-7-doc-2486.staging.tiny.cloud/docs/tinymce/latest/revisionhistory/#diff)
Changes:
* Add requires 7.1v admon to Revision History Diff API
Pre-checks:
Review:
=> DOC-2486: Add requires 7.1v admon to Revision History Diff API

modules/ROOT/partials/integrations/svelte-quick-start.adoc
Ticket: DOC-2480
6 Port: https://github.com/tinymce/tinymce-docs/pull/3389
Site: [Svelte Cloud](http://docs-hotfix-7-doc-2480.staging.tiny.cloud/docs/tinymce/latest/svelte-cloud/)
Site: [Svelte Package Manager](http://docs-hotfix-7-doc-2480.staging.tiny.cloud/docs/tinymce/latest/svelte-pm/)
Site: [Svelte Zip](http://docs-hotfix-7-doc-2480.staging.tiny.cloud/docs/tinymce/latest/svelte-zip/)
Changes:
* Update `svelte-quick-start.adoc` to use Vite 5 instead of the previous sveltejs/template repo which is no longer maintained.
* Replace `rollup-plugin-copy` with the Vite equivalent `vite-plugin-static-copy` for copying `tinymce` npm package to build directory in self-hosted PM setup.
* Expand the editor setup to showcase more properties such as specifying `channel`, initial `value`, and …
=> DOC-2480: Update `svelte-quick-start.adoc` to use Vite v5

modules/ROOT/partials/integrations/svelte-quick-start.adoc
Ticket: DOC-2480
Site: [Svelte Cloud](http://docs-hotfix-6-doc-2480.staging.tiny.cloud/docs/tinymce/6/svelte-cloud/)
Site: [Svelte Package Manager](http://docs-hotfix-6-doc-2480.staging.tiny.cloud/docs/tinymce/6/svelte-pm/)
Site: [Svelte Zip](http://docs-hotfix-6-doc-2480.staging.tiny.cloud/docs/tinymce/6/svelte-zip/)
Changes:
* Changes are **identical** to https://github.com/tinymce/tinymce-docs/pull/3388. Please write any suggested changes on that PR and they will be cherry-picked to here.
Pre-checks:
- [-] If this is a minor release, updated `productminorversion` in `antora.yml` and added new supported versions entry in …
=> DOC-2480: Port to 6 Docs - Update `svelte-quick-start.adoc` to use Vite v5

modules/ROOT/examples/live-demos/spellchecker/index.js, modules/ROOT/pages/introduction-to-tiny-spellchecker.adoc
Ticket: DOC-2487
6 Docs: https://github.com/tinymce/tinymce-docs/pull/3393
Site: [Spellchecker demo](http://docs-hotfix-7-doc-2487.staging.tiny.cloud/docs/tinymce/latest/introduction-to-tiny-spellchecker/#interactive-example) (see JS tab)
Site: [Spellchecker docs](http://docs-hotfix-7-doc-2487.staging.tiny.cloud/docs/tinymce/latest/introduction-to-tiny-spellchecker/#cloud-installation)
Search terms used to find any occurences of 'en':
- `spellchecker_language:`
- `spellchecker_languages:`
- `'en'`
Changes:
* Replace 'en' with 'en_US' in Spellchecker docs and demo
Pre-checks:
- [-] If this is a minor release, updated `productminorversion` in `antora.yml` …
=> DOC-2487: Replace 'en' with 'en_US' in Spellchecker docs and demo

modules/ROOT/pages/exportpdf.adoc, modules/ROOT/pages/exportword.adoc, modules/ROOT/partials/configuration/exportpdf.adoc, modules/ROOT/partials/configuration/exportword.adoc, modules/ROOT/partials/configuration/importword.adoc
Ticket: DOC-2488
Site: [ExportPDF](http://docs-hotfix-7-doc-2488.staging.tiny.cloud/docs/tinymce/latest/exportpdf/#:~:text=The%20Export%20to%20PDF%20uses%20the%20TinyMCE%20HTML%20to%20PDF%20converter%20service%20to%20generate%20the%20document%2Dname.pdf%20files.)
Site: [ExportPDF#intro](http://docs-hotfix-7-doc-2488.staging.tiny.cloud/docs/tinymce/latest/exportpdf/#:~:text=This%20data%20is%20transmitted%20to%20the%20TinyMCE%20HTML%20to%20PDF%20converter%20service.)
Site: [ExportWord](http://docs-hotfix-7-doc-2488.staging.tiny.cloud/docs/tinymce/latest/exportword/#:~:text=The%20Export%20to%20Word%20uses%20the%20TinyMCE%20HTML%20to%20DOCX%20converter%20service%20to%20generate%20the%20Word%20files.)
Site: [ExportWord#intro](http://docs-hotfix-7-doc-2488.staging.tiny.cloud/docs/tinymce/latest/ …
=> DOC-2488: Remove reference of `Cloud Service` from various plugin pages.

modules/ROOT/examples/live-demos/spellcheckerpro/index.js, modules/ROOT/pages/introduction-to-tiny-spellchecker.adoc
Ticket: DOC-2487
7 Docs: https://github.com/tinymce/tinymce-docs/pull/3392
Site: [Spellchecker demo](http://docs-hotfix-6-doc-2487.staging.tiny.cloud/docs/tinymce/6/introduction-to-tiny-spellchecker/#interactive-example) (see JS tab)
Site: [Spellchecker docs](http://docs-hotfix-6-doc-2487.staging.tiny.cloud/docs/tinymce/6/introduction-to-tiny-spellchecker/#cloud-installation)
Search terms used to find any occurences of 'en':
- `spellchecker_language:`
- `spellchecker_languages:`
- `'en'`
Changes:
* Replace 'en' with 'en_US' in Spellchecker docs and demo
Pre-checks:
- [-] If this is a minor release, updated `productminorversion` in `antora.yml` and added …
=> DOC-2487: (6 Docs) Replace 'en' with 'en_US' in Spellchecker docs and demo

modules/ROOT/pages/mergetags.adoc, modules/ROOT/partials/configuration/mergetags_prefix.adoc, modules/ROOT/partials/configuration/mergetags_suffix.adoc
Ticket: DOC-2492
Site: [Staging branch](http://docs-hotfix-7-doc-2492.staging.tiny.cloud/docs/tinymce/latest/mergetags/#mergetags_prefix)
Changes:
* hotfix to remove mention that the prefix and suffix cannot match, to support issue `25402`.
* fix spelling errors.
Pre-checks:
Review:
=> DOC-2492: Remove IMPORTANT mention regarding prefix and suffix cannot match in editor config.

modules/ROOT/pages/mergetags.adoc, modules/ROOT/partials/configuration/mergetags_prefix.adoc, modules/ROOT/partials/configuration/mergetags_suffix.adoc
Ticket: DOC-2492
Site: [Staging branch](http://docs-hotfix-6-doc-2492v6.staging.tiny.cloud/docs/tinymce/6/mergetags/#mergetags_prefix)
Changes:
* hotfix to remove mention that the prefix and suffix cannot match, to support issue 25402.
* fix spelling errors.
Pre-checks:
Review:
=> DOC-2492_v6: Remove IMPORTANT mention regarding prefix and suffix cannot match in the editor config.

modules/ROOT/pages/7.3-release-notes.adoc, modules/ROOT/partials/configuration/advcode.adoc
Site: [Staging branch- release notes](http://docs-feature-73-doc-2463tiny-11018.staging.tiny.cloud/docs/tinymce/latest/7.3-release-notes/#by-default-code-is-now-formatted-automatically-when-the-enhanced-code-editor-view-is-opened)
Site: [Staging branch- new option](http://docs-feature-73-doc-2463tiny-11018.staging.tiny.cloud/docs/tinymce/latest/advcode/#advcode_prettify_editor)
Changes:
* add new option to support TINY-11018
Pre-checks:
Review:
=> By default, code is now formatted automatically when the Enhanced Code Editor view is opened.

modules/ROOT/pages/7.3-release-notes.adoc
Site: [Staging branch](http://docs-feature-73-doc-2463tiny-10894.staging.tiny.cloud/docs/tinymce/latest/7.3-release-notes/#notifications-didnt-position-and-resize-properly-when-resizing-the-editor-or-toggling-views)
Changes:
* adding fix for TINY-10894
Pre-checks:
Review:
=> DOC-2463: Notifications didn't position and resize properly when resizing the editor or toggling views.

modules/ROOT/pages/7.3-release-notes.adoc
Site: [Staging branch](http://docs-feature-73-doc-2463tiny-10854.staging.tiny.cloud/docs/tinymce/latest/7.3-release-notes/#unnecessary-nbsp-entities-were-inserted-when-typing-at-the-edges-of-inline-elements)
Changes:
* add improvement for TINY-10854
Pre-checks:
Review:
=> DOC-2463: Unnecessary `nbsp` entities were inserted when typing at the edges of inline elements.

modules/ROOT/pages/events.adoc
Ticket: DOC-2151
7 Docs: https://github.com/tinymce/tinymce-docs/pull/3394
Site: [Staging branch](http://docs-hotfix-6-doc-2151.staging.tiny.cloud/docs/tinymce/6/events/#handling-editor-events)
Changes:
* Improve events.adoc explanation event handling
Pre-checks:
Review:
=> DOC-2151: (6 Docs) Improve events.adoc explanation event handling

modules/ROOT/pages/events.adoc
Ticket: DOC-2151
6 Docs: https://github.com/tinymce/tinymce-docs/pull/3395
Site: [Staging branch](http://docs-hotfix-7-doc-2151.staging.tiny.cloud/docs/tinymce/latest/events/#handling-editor-events)
Changes:
* Improve events.adoc explanation event handling
Pre-checks:
Review:
=> DOC-2151: Improve events.adoc explanation event handling

modules/ROOT/pages/7.3-release-notes.adoc
Site: [Staging branch](http://docs-feature-73-doc-2463tiny-10964.staging.tiny.cloud/docs/tinymce/latest/7.3-release-notes/#double-clicking-on-a-math-element-now-opens-the-edit-math-dialog)
Changes:
* add fix for TINY-10964
Pre-checks:
Review:
=> DOC-2463: Double-clicking on a math element now opens the `Math` dialog.

modules/ROOT/pages/7.3-release-notes.adoc, modules/ROOT/partials/configuration/advcode.adoc, modules/ROOT/partials/misc/admon-requires-7.3v.adoc
Site: [Staging branch- release notes](http://docs-feature-73-doc-2463tiny-11054.staging.tiny.cloud/docs/tinymce/latest/7.3-release-notes/#added-new-option-advcode_prettify_getcontent-to-enhanced-code-editor)
[Staging branch- new option](http://docs-feature-73-doc-2463tiny-11054.staging.tiny.cloud/docs/tinymce/latest/advcode/#advcode_prettify_getcontent)
Changes:
* added new option for TINY-11054
Pre-checks:
Review:
=> DOC-2463: Added new option `advcode_prettify_getcontent` to Enhanced Code Editor.

modules/ROOT/pages/7.3-release-notes.adoc
Site: [Staging branch](http://docs-feature-73-doc-2463tiny-10973.staging.tiny.cloud/docs/tinymce/latest/7.3-release-notes/#split-button-popups-were-incorrectly-positioned-when-switching-to-fullscreen-mode-if-the-editor-was-inside-a-scrollable-container)
Changes:
* TINY-10973 Split button popup positioning in fullscreen
Pre-checks:
Review:
=> DOC-2463: TINY-10973 Split button popup positioning in fullscreen

modules/ROOT/pages/7.3-release-notes.adoc
Site: [Staging branch](http://docs-feature-73-doc-2463tiny-10994.staging.tiny.cloud/docs/tinymce/latest/7.3-release-notes/#the-pattern-commands-would-execute-even-if-the-command-was-not-enabled)
Changes:
* DOC-2463: The pattern commands would execute even if the command was not enabled.
Pre-checks:
Review:
=> DOC-2463: The pattern commands would execute even if the command was not enabled

modules/ROOT/pages/7.3-release-notes.adoc, modules/ROOT/partials/configuration/ai_shortcuts.adoc
Site: [Staging branch](http://docs-feature-73-doc-2463tiny-11013.staging.tiny.cloud/docs/tinymce/latest/7.3-release-notes/#ai-assistant)
Changes:
* add Addition to AI Assistant for TINY-11013
Pre-checks:
Review:
=> DOC-2463:Add Translate options to AI Assistant default shortcuts.

modules/ROOT/pages/7.3-release-notes.adoc
Site: [Staging branch](http://docs-feature-73-doc-2463tiny-6887.staging.tiny.cloud/docs/tinymce/latest/7.3-release-notes/#fixed-javascript-error-when-inserting-a-table-using-the-context-menu-by-adjusting-the-event-order-in-renderinserttablemenuitem)
Changes:
* Add fix for TINY-6887
Pre-checks:
Review:
=> DOC-2463: Fixed JavaScript error when inserting a table using the context menu by adjusting the event order in `renderInsertTableMenuItem`.

modules/ROOT/pages/7.3-release-notes.adoc
Site: [Staging branch](http://docs-feature-73-doc-2463tiny-10939.staging.tiny.cloud/docs/tinymce/latest/7.3-release-notes/#markdown-will-now-respect-the-paste-as-text-menu-option)
Changes:
* added `improvement` for TINY-10939
Pre-checks:
Review:
=> DOC-2463: Markdown will now respect the `Paste as Text` menu option.

modules/ROOT/pages/7.3-release-notes.adoc
Site: [Staging branch](http://docs-feature-73-doc-2463tiny-11085.staging.tiny.cloud/docs/tinymce/latest/7.3-release-notes/#attempting-to-use-focus-commands-on-an-editor-where-the-cursor-had-last-been-in-certain-contenteditabletrue-elements-would-fail)
Changes:
* add fix documentation for TINY-11085
Pre-checks:
Review:
=> DOC-2463: Attempting to use focus commands on an editor where the cursor had last been in certain `contentEditable="true"` elements would fail.

modules/ROOT/pages/7.3-release-notes.adoc
Site: [Staging branch](http://docs-feature-73-doc-2463tiny-10884.staging.tiny.cloud/docs/tinymce/latest/7.3-release-notes/#the-listbox-component-had-a-fixed-width-and-was-not-a-responsive-ui-element)
Changes:
* fix documentation for TINY-10884
Pre-checks:
Review:
=> DOC-2463: The listbox component had a fixed width and was not a responsive ui element.

antora-playbook-local.yml, antora-playbook.yml
Ticket: DOC-2499
Site: [Staging branch](http://docs-feature-5-doc-2499.staging.tiny.cloud/docs/tinymce/5/)
Changes:
* Always fetch new UI Bundle
Pre-checks:
Review:
=> DOC-2499: 5x Remove UI Bundle Cache

antora-playbook-local.yml, antora-playbook.yml
Ticket: DOC-2499
Site: [Staging branch](http://docs-feature-6-doc-2499.staging.tiny.cloud/docs/tinymce/6/)
Changes:
* Always fetch new UI Bundle
Pre-checks:
Review:
=> DOC-2499: 6x Remove UI bundle cache

antora-playbook-local.yml, antora-playbook.yml
Ticket: DOC-2499
Site: [Staging branch](http://docs-feature-7-doc-2499.staging.tiny.cloud/docs/tinymce/7/)
Changes:
* Always fetch new UI Bundle
Pre-checks:
Review:
=> DOC-2499: 7x Remove UI Bundle Cache

modules/ROOT/pages/exportpdf.adoc, modules/ROOT/pages/exportword.adoc, modules/ROOT/pages/importword.adoc, modules/ROOT/partials/configuration/exportword.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-api-usage-on-premises.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-autorization-on-premises.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-installation-on-premises.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-logs-on-premises.adoc
Ticket: DOC-2482
Site: [Staging branch](http://docs-feature-73-doc-2482.staging.tiny.cloud/docs/tinymce/latest/exportword/)
Site: [Staging branch](http://docs-feature-73-doc-2482.staging.tiny.cloud/docs/tinymce/latest/exportpdf/#:~:text=The%20Export%20to,disk%20or%20drive.)
Site: [Docker changes to support v2](http://docs-feature-73-doc-2482.staging.tiny.cloud/docs/tinymce/latest/individual-import-from-word-and-export-to-word-on-premises/)
Changes:
* Preparation for updating `tinymce/exportword` plugin documentation for incoming changes for `v2`.
* update includes, improving `code` block examples for `exportword_converter_options` and `exportword_converter_style` due to `option` name changes.
* In addition updates to `exportword` plugin description and `improved` wording to `exportPDF` …
=> Update export to  Word config options to support v2 improved flexibility, and plugin descriptions.

modules/ROOT/pages/importword.adoc
Ticket: DOC-2510
Site: [Staging branch](http://docs-hotfix-7-doc-2510.staging.tiny.cloud/docs/tinymce/latest/importword)
Changes:
* Temporarily remove api-ref link from `importword` plugin documentation until the configuration option is implemented.
Pre-checks:
Review:
=> DOC-2510: Temporarily remove api-ref link from `importword` plugin documentation.

modules/ROOT/examples/live-demos/comments-embedded/index.js, modules/ROOT/pages/comments-embedded-mode.adoc, modules/ROOT/partials/configuration/tinycomments_author.adoc, modules/ROOT/partials/configuration/tinycomments_author_avatar.adoc, modules/ROOT/partials/configuration/tinycomments_author_name.adoc, modules/ROOT/partials/configuration/tinycomments_can_delete.adoc, modules/ROOT/partials/configuration/tinycomments_can_delete_comment.adoc, modules/ROOT/partials/configuration/tinycomments_can_edit_comment.adoc, modules/ROOT/partials/configuration/tinycomments_can_resolve.adoc
Ticket: DOC-2524
Site: [Staging branch](http://docs-feature-74-doc-2524doc-2529.staging.tiny.cloud/docs/tinymce/latest/comments-embedded-mode/)
Changes:
Updated Live demo `examples/live-demos/comments-embedded/index.js` to:
* remove hacky `showsidebar` on load, and add comments and show comments to toolbar.
Updated:
* pages/comments-embedded-mode.adoc
* partials/configuration/tinycomments_author.adoc
* partials/configuration/tinycomments_author_avatar.adoc
* partials/configuration/tinycomments_author_name.adoc
* partials/configuration/tinycomments_can_delete.adoc
* partials/configuration/tinycomments_can_delete_comment.adoc
* partials/configuration/tinycomments_can_edit_comment.adoc
* partials/configuration/tinycomments_can_resolve.adoc
Pre-checks:
Review:
=> DOC-2524: Update: Embedded Mode (Comments).

modules/ROOT/pages/introduction-to-tiny-comments.adoc, modules/ROOT/partials/misc/annotation-supported-content.adoc
Ticket: DOC-2526 linked to DOC-2524
Site: [Update: Introduction to Tiny Comments](http://docs-feature-74-doc-2524doc-2526.staging.tiny.cloud/docs/tinymce/latest/introduction-to-tiny-comments/)
Changes:
* Update content
* Remove duplicated demo for embedded mode from intro page.
* Updated: `annotation-supported-content.adoc` to improve admon note thats these features are only supported from `6.1 and later`.
Pre-checks:
Review:
=> DOC-2524: Update: Introduction (Comments)

modules/ROOT/pages/7.4-release-notes.adoc, modules/ROOT/pages/content-filtering.adoc, modules/ROOT/partials/configuration/allow_mathml_annotation_encodings.adoc
Site: [Staging branch](http://docs-feature-74-doc-2513tiny-11166.staging.tiny.cloud/docs/tinymce/latest/7.4-release-notes/#new-option-allow_mathml_annotation_encodings-to-opt-in-to-keep-math-annotations-with-specific-encodings)
Site: [content-filtering/#allow-mathml-annotation-encoding](http://docs-feature-74-doc-2513tiny-11166.staging.tiny.cloud/docs/tinymce/latest/content-filtering/#allow-mathml-annotation-encodings)
Changes:
* add addition entry for TINY-11166
* add new option to custom filtering `partials/configuration/allow_mathml_annotation_encodings.adoc`
Pre-checks:
Review:
=> DOC-2513: New option  to opt-in to keep math annotations with specific encodings.

modules/ROOT/pages/7.4-release-notes.adoc
Site: [Staging branch](http://docs-feature-74-doc-2513tiny-11123.staging.tiny.cloud/docs/tinymce/latest/7.4-release-notes/#dialog-list-dropdown-menus-now-close-when-the-browser-window-resizes)
Changes:
* added fix documentation for TINY-11123
Pre-checks:
Review:
=> DOC-2513: Dialog list dropdown menus now close when the browser window resizes.

modules/ROOT/pages/7.4-release-notes.adoc
Site: [Staging branch](http://docs-feature-74-doc-2513tiny-11146.staging.tiny.cloud/docs/tinymce/latest/7.4-release-notes/#formatter-would-not-remove-empty-lines)
Changes:
* ass fix documentation for TINY-11146
Pre-checks:
Review:
=> DOC-2513: Formatter would not remove empty lines.

modules/ROOT/pages/7.4-release-notes.adoc
Site: [Staging branch](http://docs-feature-74-doc-2513tiny-11150.staging.tiny.cloud/docs/tinymce/latest/7.4-release-notes/#formatting-indent-size-would-be-different-than-codemirror-indent-size)
Changes:
* add fix documentation for TINY-11150
Pre-checks:
Review:
=> DOC-2513: Formatting indent size would be different than CodeMirror indent size.

modules/ROOT/pages/7.4-release-notes.adoc
Site: [Staging branch](http://docs-feature-74-doc-2513tiny-11077.staging.tiny.cloud/docs/tinymce/latest/7.4-release-notes/#caret-would-unexpectedly-shift-to-the-non-editable-table-row-above-when-pressing-enter)
Changes:
* bug fix documentation for TINY-11077
Pre-checks:
Review:
=> DOC-2513: Caret would unexpectedly shift to the `non-editable` table row above when pressing Enter.

modules/ROOT/pages/7.4-release-notes.adoc
Site: [Staging branch](http://docs-feature-74-doc-2513tiny-9915.staging.tiny.cloud/docs/tinymce/latest/7.4-release-notes/#mouse-hover-on-partially-visible-dialog-collection-elements-no-longer-scrolls)
Changes:
* bug fix documentation for TINY-9915
Pre-checks:
Review:
=> DOC-2513: Mouse hover on partially visible dialog collection elements no longer scrolls.

modules/ROOT/pages/7.4-release-notes.adoc
Site: [Staging branch](http://docs-feature-74-doc-2513tiny-11082.staging.tiny.cloud/docs/tinymce/latest/7.4-release-notes/#pasting-a-table-now-places-the-cursor-after-the-table-instead-of-into-the-last-table-cell)
Changes:
* add improvements change for TINY-11082
Pre-checks:
Review:
=> DOC-2513: Pasting a table now places the cursor after the table instead of into the last table cell.

modules/ROOT/pages/7.4-release-notes.adoc
Site: [Staging branch](http://docs-feature-74-doc-2513tiny-11122.staging.tiny.cloud/docs/tinymce/latest/7.4-release-notes/#format-button-would-lose-focus-after-action-while-navigating-through-keyboard)
Changes:
* added fix documentation for TINY-11122
Pre-checks:
Review:
=> DOC-2513: Format button would lose focus after action while navigating through keyboard.

modules/ROOT/pages/7.4-release-notes.adoc
Site: [Staging branch](http://docs-feature-74-doc-2513tiny-10847.staging.tiny.cloud/docs/tinymce/latest/7.4-release-notes/#copying-tables-to-the-clipboard-did-not-correctly-separate-cells-and-rows-for-the-textplain-mime-type)
Changes:
* add fix documentation for TINY-10847
Pre-checks:
Review:
=> DOC-2513: Copying tables to the clipboard did not correctly separate cells and rows for the "text/plain" MIME type.

modules/ROOT/pages/7.4-release-notes.adoc
Site: [Staging branch](http://docs-feature-74-doc-2513tiny-11257.staging.tiny.cloud/docs/tinymce/latest/7.4-release-notes/#the-editor-resize-handle-was-incorrectly-rendered-when-all-components-were-removed-from-the-status-bar)
Changes:
* Add TINY-11257 release note entry
Pre-checks:
Review:
=> DOC-2513: The editor resize handle was incorrectly rendered when all components were removed from the status bar.

modules/ROOT/pages/7.4-release-notes.adoc
Site: [Staging branch](http://docs-feature-74-doc-2513tiny-10920.staging.tiny.cloud/docs/tinymce/latest/7.4-release-notes/#insert-lists-will-no-longer-unexpectedly-generate-indented-lists)
Changes:
* added fix documentation for TINY-10920
Pre-checks:
Review:
=> DOC-2513: Insert lists will no longer unexpectedly generate indented lists.

antora.yml, modules/ROOT/examples/live-demos/comments-callback/example.js, modules/ROOT/examples/live-demos/comments-callback/index.html, modules/ROOT/examples/live-demos/comments-callback/index.js, modules/ROOT/pages/comments-callback-mode.adoc, modules/ROOT/partials/configuration/tinycomments_create.adoc, modules/ROOT/partials/configuration/tinycomments_delete.adoc, modules/ROOT/partials/configuration/tinycomments_delete_all.adoc, modules/ROOT/partials/configuration/tinycomments_delete_comment.adoc, modules/ROOT/partials/configuration/tinycomments_edit_comment.adoc, modules/ROOT/partials/configuration/tinycomments_fetch.adoc, modules/ROOT/partials/configuration/tinycomments_lookup.adoc, modules/ROOT/partials/configuration/tinycomments_reply.adoc, modules/ROOT/partials/configuration/tinycomments_resolve.adoc, modules/ROOT/partials/plugins/comments-highlighting-css.adoc, modules/ROOT/partials/plugins/comments-open-sidebar.adoc
Ticket: DOC-2524
Site: [Staging branch](http://docs-feature-74-doc-2524doc-2528.staging.tiny.cloud/docs/tinymce/latest/comments-callback-mode/)
Changes:
* Update live demo to include `tinycomment_fetch`
* live-demos/comments-callback/example.js
* live-demos/comments-callback/index.js
Updates to:
* pages/comments-callback-mode.adoc
* partials/configuration/tinycomments_create.adoc
* partials/configuration/tinycomments_delete.adoc
* partials/configuration/tinycomments_delete_all.adoc
* partials/configuration/tinycomments_delete_comment.adoc
* partials/configuration/tinycomments_edit_comment.adoc
* partials/configuration/tinycomments_fetch.adoc
* partials/configuration/tinycomments_lookup.adoc
* partials/configuration/tinycomments_reply.adoc
* partials/configuration/tinycomments_resolve.adoc …
=> DOC-2524: Update: Callback Mode (Comments)

modules/ROOT/examples/live-demos/advtemplate-readonly-template/example.js, modules/ROOT/examples/live-demos/advtemplate-readonly-template/index.html, modules/ROOT/examples/live-demos/advtemplate-readonly-template/index.js, modules/ROOT/pages/7.4-release-notes.adoc, modules/ROOT/pages/advanced-templates.adoc, modules/ROOT/pages/editor-command-identifiers.adoc
Site: [Release notes](http://docs-feature-74-doc-2513tiny-11117.staging.tiny.cloud/docs/tinymce/latest/7.4-release-notes/#categories-can-now-be-declared-as-locked-making-them-readonly)
Site: [readonly templates option and demo](http://docs-feature-74-doc-2513tiny-11117.staging.tiny.cloud/docs/tinymce/latest/advanced-templates/#read-only-templates)
Changes:
* Added new option to support TINY-11117
Pre-checks:
Review:
=> DOC-2513: Categories can now be declared as `locked`, making them readonly.

modules/ROOT/pages/comments-access-options.adoc, modules/ROOT/partials/configuration/comments-tinycomments_access.adoc
Ticket: DOC-2543
Site: [Staging branch](http://docs-hotfix-74-doc-2543.staging.tiny.cloud/docs/tinymce/latest/comments-access-options/)
Changes:
* Fixed page `Title` is coming up as "untitled"
* Updated code snippet `comments-access-options`.
Pre-checks:
Review:
=> DOC-2543: Add title to `comments-tinycomments_access.adoc`.

modules/ROOT/nav.adoc, modules/ROOT/pages/7.4.1-release-notes.adoc, modules/ROOT/pages/changelog.adoc, modules/ROOT/pages/filter-content.adoc, modules/ROOT/pages/release-notes.adoc, modules/ROOT/partials/misc/supported-versions.adoc
Ticket: DOC-2545
Site: [Changelog](http://docs-hotfix-741-doc-2545.staging.tiny.cloud/docs/tinymce/latest/changelog/#7-4-1-2024-10-10)
Site: [Release notes 7.4.1](http://docs-hotfix-741-doc-2545.staging.tiny.cloud/docs/tinymce/latest/7.4.1-release-notes/#overview)
Changes:
* DOMPurify bump which caused `Invalid HTML elements within SVG elements were not removed`.
* Updates to supported-versions and typo fixes.
Pre-checks:
Review:
=> DOC-2545: TinyMCE 7.4.1 Documentation Release.

modules/ROOT/examples/live-demos/full-featured/example.js, modules/ROOT/examples/live-demos/full-featured/index.js, modules/ROOT/examples/live-demos/revisionhistory/index.js
Ticket: DOC-2534
Site: [Staging branch](http://docs-<hotfix|feature>-<version>-doc-<num>.staging.tiny.cloud/docs/tinymce/<version>/)
Changes:
* Updated the example to throw an error when the revision being fetched is not found 
* Updated the example.js of full feature to correctly reflect the revisions being shown
Pre-checks:
Review:
=> DOC-2534: Update the example for lazy loading a revision

modules/ROOT/nav.adoc, modules/ROOT/pages/6.8.5-release-notes.adoc, modules/ROOT/pages/changelog.adoc, modules/ROOT/pages/release-notes.adoc
Ticket: DOC-2544
Site: [Changelog](http://docs-hotfix-685-doc-2544.staging.tiny.cloud/docs/tinymce/6/changelog/#6-8-5-2024-10-10)
Site: [Release notes 6.8.5](http://docs-hotfix-685-doc-2544.staging.tiny.cloud/docs/tinymce/6/6.8.5-release-notes/#overview)
Changes:
* DOMPurify bump which caused `Invalid HTML elements within SVG elements were not removed`.
Pre-checks:
Review:
=> DOC-2544: TinyMCE 6.8.5 Documentation Release.

modules/ROOT/pages/comments-callback-mode.adoc, modules/ROOT/pages/comments-embedded-mode.adoc, modules/ROOT/pages/introduction-to-tiny-comments.adoc
Ticket: DOC-2548
Site: [Staging branch](http://docs-hotfix-7-doc-2548.staging.tiny.cloud/docs/tinymce/latest/introduction-to-tiny-comments/#interactive-examples)
Changes:
* add live-demo link for both `callback-mode` and `embedded-mode` to  `introduction-to-tiny-comments` page.
Pre-checks:
Review:
=> DOC-2548: Add live-demo links to `Introduction to Tiny Comments` page.

modules/ROOT/partials/configuration/exportpdf.adoc, modules/ROOT/partials/configuration/exportword.adoc, modules/ROOT/partials/configuration/importword-service-url.adoc
Ticket: DOC-2547
Site: [Staging branch: exportword](http://docs-hotfix-7-doc-2547.staging.tiny.cloud/docs/tinymce/latest/exportword/#exportword-service-url)
Site: [Staging branch: importword](http://docs-hotfix-7-doc-2547.staging.tiny.cloud/docs/tinymce/latest/importword/#importword-service-url)
Site: [Staging branch: exportpdf](http://docs-hotfix-7-doc-2547.staging.tiny.cloud/docs/tinymce/latest/exportpdf/#exportpdf-service-urll)
Changes:
* Update `TIP` for `<pluginname>_service_url` setting as it now appends `v2/convert/...` for example automatically when configured with a custom host in {productname} config.
Pre-checks:
Review:
=> DOC-2547: update documentation for Doc Converters service url's.

modules/ROOT/partials/configuration/inline-css.adoc
Ticket: DOC-2556
Site: [Staging branch](http://docs-hotfix-7-doc-2556.staging.tiny.cloud/docs/tinymce/latest/inline-css/#inlinecss_selector_filter)
Changes:
* update titles for `inlinecss_selector_filter` and `inlinecss_file_filter`
Pre-checks:
Review:
=> DOC-2556: Update titles from `inline_` to `inlinecss_` for inline-css.adoc

modules/ROOT/pages/7.5-release-notes.adoc
Site: [Staging branch](http://docs-feature-75-doc-2498tiny-11381.staging.tiny.cloud/docs/tinymce/latest/7.5-release-notes/#corrected-focus-highlight-visibility-in-statusbar-path)
Changes:
* fix documentation for TINY-11381
Pre-checks:
Review:
=> DOC-2498: Corrected focus highlight visibility in statusbar path.

modules/ROOT/pages/7.5-release-notes.adoc
Site: [Staging branch](http://docs-feature-75-doc-2498tiny-11352.staging.tiny.cloud/docs/tinymce/latest/7.5-release-notes/#the-conversationauthor-property-was-missing-from-create-conversation-events-in-the-eventlog-api)
Changes:
* fix documentation for TINY-11352
Pre-checks:
Review:
=> DOC-2498: The `conversationAuthor` property was missing from create conversation events in the EventLog API.

modules/ROOT/pages/7.5-release-notes.adoc
Site: [Staging branch](http://docs-feature-75-doc-2498tiny-11291.staging.tiny.cloud/docs/tinymce/latest/7.5-release-notes/#improved-color-picker-aria-support)
Changes:
*  fix documentation for TINY-11291
Pre-checks:
Review:
=> DOC-2498: Improved color picker aria support.

modules/ROOT/pages/7.5-release-notes.adoc
Site: [Staging branch](http://docs-feature-75-doc-2498tiny-11313.staging.tiny.cloud/docs/tinymce/latest/7.5-release-notes/#forecolor-and-backcolor-toolbar-buttons-were-not-completely-greyed-out-while-in-readonly-mode)
Changes:
* Fix documentation for TINY-11313
Pre-checks:
Review:
=> DOC-2498: `Forecolor` and `backcolor` toolbar buttons were not completely greyed out while in readonly mode.

modules/ROOT/pages/7.5-release-notes.adoc
Site: [Staging branch](http://docs-feature-75-doc-2498tiny-11395.staging.tiny.cloud/docs/tinymce/latest/7.5-release-notes/#inability-to-type-character-on-german-keyboard-layouts)
Changes:
* fix documentation for TINY-11395
Pre-checks:
Review:
=> DOC-2498: Inability to type { character on German keyboard layouts.

antora.yml, modules/ROOT/partials/integrations/swing-quick-start.adoc
Ticket: DOC-2498 & DOC-2563
Site: [Staging branch](http://docs-feature-75-doc-2498doc-2563.staging.tiny.cloud/docs/tinymce/latest/swing/#getting-the-tinymce-for-swing-integration)
Changes:
* Update text from `Contact Tiny Support` to `Contact sales`
* Add new global variable to `antora.yml` to include this new link.
Pre-checks:
Review:
=> DOC-2498: Update TinyMCE for Java Swing `Contact sales` link.

modules/ROOT/pages/7.5-release-notes.adoc
Site: [Staging branch](http://docs-feature-75-doc-2498tiny-11217.staging.tiny.cloud/docs/tinymce/latest/7.5-release-notes/#added-new-default-li-element-styles-to-the-content-css-to-prevent-child-list-elements-from-inheriting-certain-parent-list-item-styles)
Changes:
* fix documentation for TINY-11217
Pre-checks:
Review:
=> DOC-2498: Added new default `li` element styles to the content CSS to prevent child list elements from inheriting certain parent list item styles.

modules/ROOT/pages/7.4-release-notes.adoc, modules/ROOT/pages/7.5-release-notes.adoc
Site: [Staging branch](http://docs-feature-75-doc-2498tiny-11323.staging.tiny.cloud/docs/tinymce/latest/7.5-release-notes#use-default-anon-value-for-tinycomments_author-and-tinycomments_author_name-options-when-the-provided-value-is-an-empty-string)
Site: [Known issue](http://docs-feature-75-doc-2498tiny-11323.staging.tiny.cloud/docs/tinymce/latest/7.4-release-notes/#comments-not-functional-with-empty-tinycomments_author-and-tinycomments_author_name)
Changes:
* fix for TINY-11323
* update 7.4 release notes - known issues
Pre-checks: …
=> DOC-2498: Default values for tinycomments_author and tinycomments_author_name when empty string provided

modules/ROOT/pages/7.4-release-notes.adoc, modules/ROOT/pages/7.5-release-notes.adoc
Site: [Staging branch](http://docs-feature-75-doc-2498tiny-11366.staging.tiny.cloud/docs/tinymce/latest/7.5-release-notes/#removing-annotated-content-now-removes-associated-conversation-card-from-the-sidebar)
Changes:
* Fix documentation for TINY-11366
Pre-checks:
Review:
=> DOC-2498: Removing annotated content, now, removes associated conversation card from the sidebar.

modules/ROOT/pages/7.5-release-notes.adoc
Site: [Staging branch](http://docs-feature-75-doc-2498tiny-11273.staging.tiny.cloud/docs/tinymce/latest/7.5-release-notes/#autocompleter-would-not-activate-after-applying-an-inline-format-like-font-size-in-some-cases)
Changes:
* fix documentation for TINY-11273
Pre-checks:
Review:
=> DOC-2498: Autocompleter would not activate after applying an inline format like font size in some cases.

modules/ROOT/pages/7.5-release-notes.adoc
Site: [Staging branch](http://docs-feature-75-doc-2498tiny-11153.staging.tiny.cloud/docs/tinymce/latest/7.5-release-notes/#closing-a-nested-modal-dialog-would-lose-focus-from-the-editor)
Changes:
* fix documentation for TINY-11153
Pre-checks:
Review:
=> DOC-2498: Closing a nested modal dialog would lose focus from the editor.

modules/ROOT/examples/live-demos/exportpdf/index.html, modules/ROOT/examples/live-demos/exportpdf/index.js, modules/ROOT/examples/live-demos/exportword/index.html, modules/ROOT/examples/live-demos/exportword/index.js, modules/ROOT/examples/live-demos/full-featured/example.js, modules/ROOT/examples/live-demos/full-featured/index.js, modules/ROOT/examples/live-demos/importword/index.html, modules/ROOT/examples/live-demos/importword/index.js, modules/ROOT/pages/exportpdf.adoc, modules/ROOT/pages/exportword.adoc, modules/ROOT/pages/full-featured-premium-demo.adoc, modules/ROOT/pages/importword.adoc
Ticket: DOC-2562
Site: [Full Feature Demo](http://docs-hotfix-7-doc-2562.staging.tiny.cloud/docs/tinymce/latest/full-featured-premium-demo/)
Site: [ExportWord](http://docs-hotfix-7-doc-2562.staging.tiny.cloud/docs/tinymce/latest/exportword/)
Site: [ExportPDF](http://docs-hotfix-7-doc-2562.staging.tiny.cloud/docs/tinymce/latest/exportpdf/)
Site: [ImportWord](http://docs-hotfix-7-doc-2562.staging.tiny.cloud/docs/tinymce/latest/importword/)
Changes:
* add new demos to plugin pages.
Pre-checks:
Review:
=> DOC-2562: Add live-demo for document converters and full feature demo pages.

modules/ROOT/pages/7.5-release-notes.adoc, modules/ROOT/partials/configuration/exportpdf.adoc, modules/ROOT/partials/configuration/exportword.adoc, modules/ROOT/partials/configuration/importword-converter-options.adoc
Site: [Release notes Export to PDF](http://docs-feature-75-doc-2498tiny-11396.staging.tiny.cloud/docs/tinymce/latest/7.5-release-notes/#export-to-pdf)
Site: [Release notes Export to Word](http://docs-feature-75-doc-2498tiny-11396.staging.tiny.cloud/docs/tinymce/latest/7.5-release-notes/#export-to-word)
Site: [Release notes Import from Word](http://docs-feature-75-doc-2498tiny-11396.staging.tiny.cloud/docs/tinymce/latest/7.5-release-notes/#import-from-word)
Site: [Default value change: Export to PDF](http://docs-feature-75-doc-2498tiny-11396.staging.tiny.cloud/docs/tinymce/latest/exportpdf/#exportpdf-converter-options)
Site: [Default value change: Export from Word](http://docs-feature-75-doc-2498tiny-11396.staging.tiny.cloud/docs/tinymce/latest/exportword/#exportword-conver …
=> DOC-2498: Improve Document Converter default value for `<pluginname>converter-options`

modules/ROOT/pages/7.5-release-notes.adoc
Ticket: DOC-2564
Site: [Staging branch](http://docs-feature-75-doc-2564.staging.tiny.cloud/docs/tinymce/latest/7.5-release-notes/#comments-with-mentions)
Changes:
* DOC-2564: Release Note Entry for Mentions in Comments
Pre-checks:
Review:
=> DOC-2564: Release Note Entry for Mentions in Comments

modules/ROOT/pages/7.5-release-notes.adoc, modules/ROOT/partials/configuration/text_color.adoc
Ticket: DOC-2557
Support: TINY-11385
Site: [Release notes](http://docs-feature-75-doc-2498tiny-11385.staging.tiny.cloud/docs/tinymce/latest/7.5-release-notes/#added-support-for-using-raw-css-in-the-list-of-possible-colours-using-the-color_map_raw-property)
Site: [color_map_raw](http://docs-feature-75-doc-2498tiny-11385.staging.tiny.cloud/docs/tinymce/latest/user-formatting-options/#color_map_raw)
Changes:
* Added addition, and new option for `color_map_raw` option.
Pre-checks:
Review:
=> DOC-2498: Added support for using raw CSS in the list of possible colours, using the `color_map_raw` property.

modules/ROOT/examples/live-demos/comments-callback-with-mentions/index.html, modules/ROOT/examples/live-demos/comments-callback-with-mentions/index.js, modules/ROOT/examples/live-demos/comments-embedded-with-mentions/index.html, modules/ROOT/examples/live-demos/comments-embedded-with-mentions/index.js
Ticket: DOC-2565
Site: [Staging branch](http://docs-feature-doc-2565.staging.tiny.cloud/docs/tinymce/latest/comments-with-mentions/)
Changes:
* Update mentions to use blue text in comments with mentions demos
Pre-checks:
Review:
=> DOC-2565: Update comments with mentions demos to use blue mentions

modules/ROOT/examples/live-demos/comments-callback-with-mentions/index.js, modules/ROOT/examples/live-demos/comments-callback/example.js, modules/ROOT/examples/live-demos/comments-callback/index.js, modules/ROOT/examples/live-demos/comments-embedded-with-mentions/index.js, modules/ROOT/examples/live-demos/comments-embedded/index.js, modules/ROOT/examples/live-demos/comments-readonly-mode/index.js, modules/ROOT/examples/live-demos/comments-ui-mode/index.js, modules/ROOT/pages/7.5-release-notes.adoc, modules/ROOT/partials/misc/supported-versions.adoc
Ticket: DOC-2566
Site: [Staging branch](http://docs-hotfix-7-doc-2566.staging.tiny.cloud/docs/tinymce/latest/)
Site: [Demo:#comments-callback-live-demo](http://docs-hotfix-7-doc-2566.staging.tiny.cloud/docs/tinymce/latest/comments-callback-mode/#comments-callback-live-demo)
Site: [Demo:#comments-embedded-live-demo](http://docs-hotfix-7-doc-2566.staging.tiny.cloud/docs/tinymce/latest/comments-embedded-mode/#comments-embedded-live-demo)
Site: [Demo:#comments-with-tinycomments_access-set-to-comment](http://docs-hotfix-7-doc-2566.staging.tiny.cloud/docs/tinymce/latest/comments-access-options/#comments-with-tinycomments_access-set-to-comment)
Site: [Demo:#comments-with-readonly-set-to-true](http://docs-hotfix-7-doc-2566.staging.tiny.cloud/docs/tinymce/latest/comments-access-options/#comments-wi …
=> DOC-2566: Add `sidebar_show: 'showcomments'` to the Comments Demos, and quickbars.

modules/ROOT/pages/changelog.adoc
Ticket: DOC-2573
Site: [Staging branch](http://docs-hotfix-7-doc-2573.staging.tiny.cloud/docs/tinymce/latest/changelog)
Changes:
* Converted the headings in the changelog page to be xref links instead.
Pre-checks:
Review:
[DOC-2573]: https://ephocks.atlassian.net/browse/DOC-2573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-2573: Convert headings in changelog to xref links that point to their respective release notes.

modules/ROOT/examples/live-demos/mentions/index.js
Ticket: n/a, discovered by @lostkeys in slack
Site: [Staging branch](http://docs-hotfix-7-mentions-demo-fix.staging.tiny.cloud/docs/tinymce/latest/mentions/)
Changes:
* Sort the list of usernames on load. This doesn't guarantee a sorted result, because we use an object store, but I don't really want to sort on every search
* Fix the case insensitive name match code, which was only lowercasing the query term. The result was what a user would consider completely unpredictable behaviour
Pre-checks:
Review:
=> Fix mentions demo to behave more consistently

modules/ROOT/pages/7.6.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11455.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#pressing-shiftenter-in-mentions-in-comments-dropdown-should-accept-the-active-menu-item)
Changes:
* Documented the improvement for TINY-11455.
Pre-checks:
Review:
=> DOC-2578: Pressing `Shift + Enter` in the comment textarea now selects the highlighted user.

modules/ROOT/pages/7.6.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11383.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#numbered-table-context-menu-not-properly-applying-changes)
Changes:
* Documented the bug fix for TINY-11383.
Pre-checks:
Review:
=> DOC-2578: Changing the table row type when a `contentEditable="false"` cell was selected would not work as expected.

.github/workflows/codeql.yml
Ticket: DOC-2589
Support: TINY-11411
Changes:
* Update codeql.yml to use @V3 due to v2 being deprecated on December 5th, 2024.
Pre-checks:
Review:
=> DOC-2589: Update codeql to use v3 for `tinymce/7` branch.

.github/workflows/codeql.yml
Ticket: DOC-2589
Support: TINY-11411
Changes:
* Update codeql.yml to use @V3 due to v2 being deprecated on December 5th, 2024.
Pre-checks:
Review:
=> DOC-2589: Update codeql to use v3 for `tinymce/6` branch.

.github/workflows/codeql.yml
Ticket: DOC-2589
Support: TINY-11411
Changes:
* Update codeql.yml to use @v3 due to v2 being deprecated on December 5th, 2024.
Pre-checks:
Review:
=> DOC-2589: Update codeql to use v3 for `tinymce/5` branch.

.github/workflows/codeql.yml
Ticket: DOC-2589
Support: TINY-11411
Changes:
* Update codeql.yml to use `@v3`  due to v2 being deprecated on December 5th, 2024.
Pre-checks:
Review:
=> DOC-2589: Update codeql to use v3 for `main` branch.

modules/ROOT/pages/7.6.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11391.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#tooltips-of-toolbar-groups-not-showing)
Changes:
* Documented a bug fix for TINY-11391.
Pre-checks:
Review:
=> DOC-2578: Tooltip would not show for group toolbar button.

modules/ROOT/pages/7.6.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11402.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#always-show-the-comment-input-field-in-the-viewport-when-pressing-the-reply-or-add-comment-button)
Changes:
* Documentation for the improvement in TINY-11402.
Pre-checks:
Review:
=> DOC-2578: Scroll to show action buttons when replying/editing a comment.

modules/ROOT/pages/7.6.0-release-notes.adoc, modules/ROOT/pages/editor-important-options.adoc, modules/ROOT/pages/events.adoc, modules/ROOT/partials/configuration/disabled.adoc
Ticket: DOC-2586
Site: [Staging branch](http://docs-feature-760-doc-2578doc-2586.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#new-disabled-option-for-disabling-all-user-interactions)
Site: [disabled option: editor important options](http://docs-feature-760-doc-2578doc-2586.staging.tiny.cloud/docs/tinymce/latest/editor-important-options/#disabled)
Site: [Event](http://docs-feature-760-doc-2578doc-2586.staging.tiny.cloud/docs/tinymce/latest/events/#:~:text=DisabledStateChange,mode%20state%20changes.)
Changes:
* Added new `disabled` option for disabling all user interactions to various sections within docs.
Pre-checks:
Review:
=> DOC-2586: New `disabled` option for disabling all user interactions

modules/ROOT/pages/7.6.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11504.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#allow-mentions-in-comments-dropdown-to-flow-freely-outside-of-the-editor-container)
Changes:
* Documented the improvement for TINY-11504.
Pre-checks:
Review:
=> DOC-2578: Allow mentions in comments dropdown to flow freely outside of the editor container

modules/ROOT/pages/7.6.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11558.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#fixed-css-bundling-for-skin-ui-content-css)
Changes:
* Fix documentation for TINY-11558
Pre-checks:
Review:
=> DOC-2578: Fixed CSS Bundling for Skin UI Content CSS.

modules/ROOT/pages/7.6.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11357.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#checklist-items-were-unresponsive-in-center-or-right-alignments)
Changes:
* add fix documentation for TINY-11357
Pre-checks:
Review:
=> DOC-2578: Checklist items were unresponsive in `center` or `right` alignments.

modules/ROOT/pages/7.6.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11592.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#adjust-tinycomments-ui-font-size-to-match-the-editor-ui-font-size)
Changes:
* Add improvement documentation for TINY-11592
Pre-checks:
Review:
=> DOC-2578: Adjust `tinycomments` UI font size to match the editor UI font size.

modules/ROOT/examples/live-demos/comments-callback/example.js, modules/ROOT/pages/7.6.0-release-notes.adoc, modules/ROOT/partials/configuration/tinycomments_reply.adoc, modules/ROOT/partials/plugin-apis/comments-apis.adoc
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11486.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#the-commentauthor-property-is-now-included-in-reply-events-of-the-event-log)
Site: [updated example](http://docs-feature-760-doc-2578tiny-11486.staging.tiny.cloud/docs/tinymce/latest/comments-commands-events-apis/#getEventLog:~:text=%7B%0A%20%20%22type%22%3A%20%22reply,%3A%20%22DEMO%20USER%22%0A%20%20%7D%0A%7D%2C)
Changes:
* add fix documentation for TINY-11486
Pre-checks:
Review:
=> DOC-2578: The `commentAuthor` property is now included in reply events for the event log.

modules/ROOT/pages/7.6.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11523.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#introduced-a-new-live-region-for-screen-readers-to-improve-accessibility-notifications)
Changes:
*  Added improvement documentation for TINY-11523
Pre-checks:
Review:
=> DOC-2578: Introduced a new live region for screen readers to improve accessibility notifications.

antora.yml
Ticket: DOC-2593
Site: [Staging branch](http://docs-hotfix-7-doc-2593v6.staging.tiny.cloud/docs/tinymce/6/ai/#interactive-example)
Changes:
* update `openai_proxy_token` for tinymce/6
Pre-checks:
Review:
=> DOC-2593: Update `openai_proxy_token` for tinymce/6.

antora.yml
Ticket: DOC-2593
Site: [Staging branch](http://docs-hotfix-7-doc-2593v7.staging.tiny.cloud/docs/tinymce/latest/ai/#interactive-example)
Changes:
* Update `openai_proxy_token` for tinymce/7
Pre-checks:
Review:
=> DOC-2593: Update `openai_proxy_token` for tinymce/7

antora.yml, modules/ROOT/examples/live-demos/context-toolbar-labels/index.html, modules/ROOT/examples/live-demos/context-toolbar-labels/index.js, modules/ROOT/pages/7.6.0-release-notes.adoc, modules/ROOT/pages/contexttoolbar.adoc
Ticket: DOC-2578 & DOC-2509
Site: [Release notes](http://docs-feature-760-doc-2578doc-2509.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#add-labels-and-groups-for-context-toolbar-buttons)
Site: [New: add label groups demo and context](http://docs-feature-760-doc-2578doc-2509.staging.tiny.cloud/docs/tinymce/latest/contexttoolbar/#add-labels-and-groups-for-context-toolbar-buttons)
Changes:
* Improvement documentation for TINY-11095
Pre-checks:
Review:
=> DOC-2578: Add Labels and Groups for Context Toolbar Buttons.

modules/ROOT/pages/7.6.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11459.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#added-placeholder-support-for-context-form-input-fields)
Changes:
* Added documentation for TINY-11459
Pre-checks:
Review:
=> DOC-2578: Added placeholder support for context form input fields.

modules/ROOT/pages/7.6.0-release-notes.adoc
Ticket: DOC-<num>
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11422.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#added-tooltips-to-conversation-and-comment-kebab-menus)
Changes:
* Documented the improvement for TINY-11422.
Pre-checks:
Review:
=> DOC-2578: Added tooltips to conversation and comment kebab menus.

modules/ROOT/pages/7.6.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11298.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#advanced-code-editor)
Changes:
* Documented the bug fix for TINY-11298.
Pre-checks:
Review:
=> DOC-2578: Spelling error in tooltip for  toggle button

modules/ROOT/pages/7.6.0-release-notes.adoc, modules/ROOT/pages/contextform.adoc
Site: [Release notes](http://docs-feature-760-doc-2578tiny-11494.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#new-onsetup-function-for-context-forms)
Site: [Add onSetup to Context Form](http://docs-feature-760-doc-2578tiny-11494.staging.tiny.cloud/docs/tinymce/latest/contextform/#form)
Changes:
* Addition documentation for TINY-11494
Pre-checks:
Review:
=> DOC-2578: New `onSetup` function for context forms.

modules/ROOT/pages/7.6.0-release-notes.adoc
Ticket: DOC-2578 & DOC-2572
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11399.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#new-quickbarinsertimage-command-that-is-executed-by-the-quickimage-button)
Changes:
*  Add new addition documentation for TINY-11399
Pre-checks:
Review:
=> DOC-2578: New `QuickbarInsertImage` command that is executed by the `quickimage` button.

modules/ROOT/pages/7.6.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-760-doc-2578tiny-11437.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/#image-selection-was-removed-when-calling-nodechanged-while-having-focus-inside-the-editor-ui)
Changes:
* add fix documentation for TINY-11437
Pre-checks:
Review:
=> DOC-2578: Image selection was removed when calling `nodeChanged` while having focus inside the editor UI.

antora.yml, modules/ROOT/examples/live-demos/comments-callback/example.js, modules/ROOT/examples/live-demos/context-toolbar-labels/index.html, modules/ROOT/examples/live-demos/context-toolbar-labels/index.js, modules/ROOT/nav.adoc, modules/ROOT/pages/7.6.0-release-notes.adoc, modules/ROOT/pages/changelog.adoc, modules/ROOT/pages/contextform.adoc, modules/ROOT/pages/contexttoolbar.adoc, modules/ROOT/pages/editor-important-options.adoc, modules/ROOT/pages/events.adoc, modules/ROOT/partials/configuration/disabled.adoc, modules/ROOT/partials/configuration/tinycomments_reply.adoc, modules/ROOT/partials/plugin-apis/comments-apis.adoc
Site: [Release Notes](http://docs-feature-760-doc-2578.staging.tiny.cloud/docs/tinymce/latest/7.6.0-release-notes/)
Site: [Changelog](http://docs-feature-760-doc-2578.staging.tiny.cloud/docs/tinymce/latest/changelog/)
Changes:
* TinyMCE 7.6.0 Release Documentation and Community Changelog.
Pre-checks:
Review:
=> DOC-2578: TinyMCE 7.6.0 Release Documentation and Community Changelog.

modules/ROOT/pages/security.adoc
Ticket: SEC-281
Site: [Staging branch](http://docs-hotfix-7-sec-281.staging.tiny.cloud/docs/tinymce/latest/security/#enforcing-https-with-hsts)
Changes:
* Include recommendation for HSTS to `security.adoc`.
Pre-checks:
Review:
=> SEC-281: Add awareness of HSTS to secutiry.adoc for strict transport security.

modules/ROOT/pages/7.6.1-release-notes.adoc
Ticket: DOC-2609
Site: [Staging branch](http://docs-feature-761-doc-2609tiny-11653.staging.tiny.cloud/docs/tinymce/latest/7.6.1-release-notes/#images-with-existing-srcset-were-not-handled-correctly)
Changes:
* Documented the bug fix for TINY-11653.
Pre-checks:
Review:
=> DOC-2609: Images with existing srcset were not handled correctly.

modules/ROOT/pages/7.6.1-release-notes.adoc
Ticket: DOC-2609
Site: [Staging branch](http://docs-feature-761-doc-2609tiny-11498.staging.tiny.cloud/docs/tinymce/latest/7.6.1-release-notes/#opening-a-notification-when-the-toolbar-is-at-the-bottom-threw-an-error)
Changes:
* Documented the bug fix for TINY-11498
Pre-checks:
Review:
=> DOC-2609: Opening a notification when the toolbar is at the bottom threw an error.

modules/ROOT/pages/7.6.1-release-notes.adoc
Ticket: DOC-2609
Site: [Staging branch](http://docs-feature-761-doc-2609tiny-11446.staging.tiny.cloud/docs/tinymce/latest/7.6.1-release-notes/#text-input-was-prevented-in-form-elements-in-the-contents-of-the-editor)
Changes:
* Documented the bug fix for TINY-11446
Pre-checks:
Review:
=> DOC-2609: Text input was prevented in form elements in the contents of the editor.

modules/ROOT/pages/7.6.1-release-notes.adoc
Ticket: DOC-2609
Site: [Staging branch](http://docs-feature-761-doc-2609tiny-11662.staging.tiny.cloud/docs/tinymce/latest/7.6.1-release-notes/#error-messages-were-not-rendered-correctly)
Changes:
* Documented the bug fix for TINY-11662
Pre-checks:
Review:
=> DOC-2609: Error messages were not rendered correctly

modules/ROOT/partials/configuration/tableofcontents_orderedlist.adoc
Ticket: DOC-3130
Site: [Staging branch](http://docs-hotfix-7-doc-3130.staging.tiny.cloud/docs/tinymce/latest/tableofcontents/#tableofcontents_orderedlist)
Changes:
* Fixed spelling and link in table of contents docs for ordered list configuration.
Pre-checks:
Review:
=> DOC-3130: Fixed spelling and link in table of contents plugin docs.

modules/ROOT/pages/7.7.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11740.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#preview-dialog-incorrectly-opened-anchor-links-in-a-new-tab)
Changes:
* Documented the bug fix for TINY-11740.
Pre-checks:
Review:
=> DOC-3132: Preview Dialog incorrectly opened anchor links in a new tab.

modules/ROOT/pages/7.7.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11713.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#serbian-and-ukrainian-languages-were-spelled-incorrectly)
Changes:
* Documented the bug fix for TINY-11713.
Pre-checks:
Review:
=> DOC-3132: Serbian and Ukrainian languages were spelled incorrectly.

modules/ROOT/pages/7.7.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11668.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#some-image-file-extensions-would-sometimes-be-incorrectly-considered-unsupported)
Changes:
* Documented the improvement for TINY-11668
Pre-checks:
Review:
=> DOC-3132: Some image file extensions would sometimes be incorrectly considered unsupported.

modules/ROOT/pages/7.7.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11321.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#pressing-keyboard-shorctut-cmdaltm-when-cursor-is-on-annotated-content-now-opens-and-focuses-the-reply-textarea)
Changes:
* Documented the bug fix for TINY-11321.
Pre-checks:
Review:
=> DOC-3132: Pressing Keyboard shorctut  when cursor is on annotated content now opens and focuses the reply textarea.

modules/ROOT/examples/live-demos/exportword/index.js, modules/ROOT/pages/7.7.0-release-notes.adoc, modules/ROOT/pages/exportword.adoc, modules/ROOT/partials/configuration/exportword_watermark.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11675.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#A-document-watermark-can-now-be-specified-for-the-exported-file)
New watermark option: [watermark](http://docs-feature-770-doc-3132tiny-11675.staging.tiny.cloud/docs/tinymce/latest/exportword/#watermark)
Changes:
* Documented the bug fix for TINY-11675.
Pre-checks:
Review:
=> DOC-3132: A document watermark can now be specified for the exported file

modules/ROOT/pages/cloud-quick-start.adoc, modules/ROOT/pages/getting-started.adoc, modules/ROOT/pages/invalid-api-key.adoc, modules/ROOT/pages/usage-based-billing.adoc, modules/ROOT/partials/install/basic-quickstart-base.adoc, modules/ROOT/partials/misc/admon-account-creation-and-social-option.adoc, modules/ROOT/partials/misc/admon-getting-started-with-tinymce.adoc, modules/ROOT/partials/what-is-tinymce.adoc
Ticket: DOC-2559
Site: [Usage Based Billing](http://docs-feature-7-doc-2559.staging.tiny.cloud/docs/tinymce/latest/usage-based-billing/)
Site: [Getting Started](http://docs-feature-7-doc-2559.staging.tiny.cloud/docs/tinymce/latest/getting-started/)
Site: [Cloud Quick Start](http://docs-feature-7-doc-2559.staging.tiny.cloud/docs/tinymce/latest/cloud-quick-start/)
Site: [Introduction to Tinymce](http://docs-feature-7-doc-2559.staging.tiny.cloud/docs/tinymce/latest/introduction-to-tinymce/)
Site: [Invalid API Key](http://docs-feature-7-doc-2559.staging.tiny.cloud/docs/tinymce/latest/invalid-api-key/)
Site: [Latest](http://docs-feature-7-doc-2559.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Add admonition for Cloud account creation and the social login options to various pages. …
=> Update key documentation pages with information about the Cloud account creation and the social login option.

modules/ROOT/pages/7.7.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11722.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#the-format-property-in-exportpdf_converter_options-now-accepts-lowercase)
Changes:
* added improvement documentation for TINY-11722
Pre-checks:
Review:
=> DOC-3132: The `format` property in `exportpdf_converter_options` now accepts lowercase

modules/ROOT/pages/7.7.0-release-notes.adoc
…ents was allowed.
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11755.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#the-semantics-element-in-mathml-was-not-properly-retained-when-annotation-elements-was-allowed)
Changes:
* Documented the bug fix for TINY-11755
Pre-checks:
Review:
=> DOC-3132: The `semantics` element in MathML was not properly retained when `annotation` elements was allowed.

modules/ROOT/pages/7.7.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11658.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#toolbar-text-field-was-properly-rendering-focus)
Changes:
* Documented the bug fix for TINY-11658
Pre-checks:
Review:
=> DOC-3132: Toolbar text field was not properly rendering focus.

modules/ROOT/pages/7.7.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11394.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#fixed-keyboard-navigation-for-size-inputs-in-context-forms)
Changes:
* Documented the bug fix for TINY-11394
Pre-checks:
Review:
=> DOC-3132:  Fixed keyboard navigation for size inputs in context forms.

modules/ROOT/pages/7.7.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11368.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#dialog-menu-dropdowns-now-close-when-a-dialog-is-moved)
Changes:
* add fix documentation for TINY-11368
Pre-checks:
Review:
=> DOC-3132: Dialog menu dropdowns now close when a dialog is moved.

modules/ROOT/pages/7.7.0-release-notes.adoc, modules/ROOT/pages/revisionhistory.adoc, modules/ROOT/partials/configuration/revisionhistory_allow_restore.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11746.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#new-revisionhistory_allow_restore-option-to-control-restoration-of-old-revisions)
Site: [revisionhistory_allow_restore](http://docs-feature-770-doc-3132tiny-11746.staging.tiny.cloud/docs/tinymce/latest/revisionhistory/#revisionhistory_allow_restore)
Changes:
* add new option to revisionhistory plugin for TINY-11746
Pre-checks:
Review:
=> DOC-3132: New `revisionhistory_allow_restore` option to control restoration of old revisions.

modules/ROOT/pages/7.7.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11304.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#expanding-selection-to-word-didnt-work-inside-inline-editing-host-elements)
Changes:
* Documented the bug fix for TINY-11304
Pre-checks:
Review:
=> DOC-3132: Expanding selection to word didn't work inside inline editing host elements.

modules/ROOT/pages/7.7.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11661.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#not-specifying-a-notification-type-or-specifying-incorrect-one-now-defaults-to-info)
Changes:
* Documented the improvement for TINY-11661
Pre-checks:
Review:
=> DOC-3132: Not specifying a notification type (or specifying incorrect one) now defaults to 'info'

modules/ROOT/pages/7.7.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11686.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#the-cursor-was-sometimes-incorrectly-placed-after-opening-source-code-editor)
Changes:
* Documented the bug fix for TINY-11686
Pre-checks:
Review:
=> DOC-3132: The cursor was sometimes incorrectly placed after opening the source code editor

modules/ROOT/pages/7.7.0-release-notes.adoc
Ticket: DOC-3142
Site: [Staging branch](http://docs-feature-770-doc-3132doc-3142.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#accompanying-premium-self-hosted-server-side-component-changes)
Changes:
* Add service bump for `tinymcespellchecker` to support [TCLOUD-4589](https://github.com/tinymce/tinymce-premium/pull/537)
Pre-checks:
Review:
[TCLOUD-4589]: https://ephocks.atlassian.net/browse/TCLOUD-4589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-2312: update services for `tinymcespellchecker` for TinyMCE 7.7.0.

modules/ROOT/pages/7.7.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11624.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#context-toolbar-inputs-had-incorrect-margins)
Changes:
* Documented the bug fix for TINY-11624
Pre-checks:
Review:
=> DOC-3132: Context toolbar inputs had incorrect margins.

modules/ROOT/pages/7.7.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132tiny-11690.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#part-of-the-placeholder-border-was-not-visible-during-loading)
Changes:
* Documented the bug fix for TINY-11690
Pre-checks:
Review:
=> DOC-3132: Part of the placeholder border was not visible during loading.

modules/ROOT/examples/live-demos/exportword/index.js, modules/ROOT/nav.adoc, modules/ROOT/pages/7.7.0-release-notes.adoc, modules/ROOT/pages/changelog.adoc, modules/ROOT/pages/cloud-troubleshooting.adoc, modules/ROOT/pages/exportword.adoc, modules/ROOT/pages/link.adoc, modules/ROOT/pages/revisionhistory.adoc, modules/ROOT/partials/configuration/exportword_watermark.adoc, modules/ROOT/partials/configuration/link_attributes_postprocess.adoc, modules/ROOT/partials/configuration/revisionhistory_allow_restore.adoc, modules/ROOT/partials/misc/supported-versions.adoc
Site: [Staging branch](http://docs-feature-770-doc-3132.staging.tiny.cloud/docs/tinymce/latest)
Changes:
* TinyMCE 7.7.0 Release Documentation and Community Changelog.
Pre-checks:
Review:
=> DOC-3132: TinyMCE 7.7.0 Release Documentation and Community Changelog.

modules/ROOT/pages/custom-dictionaries-for-tiny-spellchecker.adoc
Ticket: TCLOUD-4598
Site: [Staging branch](http://docs-feature-tcloud-4598.staging.tiny.cloud/docs/tinymce/latest/custom-dictionaries-for-tiny-spellchecker/#configuring-the-custom-dictionary-feature)
Changes:
* <placeholder-text>
Pre-checks:
Review:
=> TCLOUD-4598: Modify Spelling Custom Dictionaries docs to match current logs

modules/ROOT/pages/7.7.1-release-notes.adoc
Ticket: DOC-3150
Site: [Staging branch](http://docs-feature-771-doc-3150tiny-11875.staging.tiny.cloud/docs/tinymce/latest/7.7.1-release-notes/#bug-fixes)
Changes:
* Documented the bug fix for TINY-11875
Pre-checks:
Review:
=> DOC-3150: Skin UI content CSS was truncated when bundling, causing CSS styles to be missing.

modules/ROOT/pages/7.7.1-release-notes.adoc
Ticket: DOC-3150
Site: [Staging branch](http://docs-feature-771-doc-3150tiny-11890.staging.tiny.cloud/docs/tinymce/latest/7.7.1-release-notes/#context-forms-used-to-disappear-if-their-input-were-disabled-in-the-onsetup-api)
Changes:
* Documented the bug fix for TINY-11890
Pre-checks:
Review:
=> DOC-3150: Context forms used to disappear if their input were disabled in the `onSetup` API

modules/ROOT/nav.adoc, modules/ROOT/pages/7.7.1-release-notes.adoc, modules/ROOT/pages/changelog.adoc, modules/ROOT/pages/support.adoc, modules/ROOT/partials/misc/supported-application-servers.adoc
Ticket: DOC-3150
Site: [Staging branch](http://docs-feature-771-doc-3150.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* TinyMCE 7.7.1 Release Documentation and Community Changelog.
Pre-checks:
Review:
=> DOC-3150: TinyMCE 7.7.1 Release Documentation and Community Changelog.

modules/ROOT/nav.adoc, modules/ROOT/pages/7.7.1-release-notes.adoc, modules/ROOT/pages/changelog.adoc, modules/ROOT/pages/release-notes.adoc, modules/ROOT/pages/support.adoc, modules/ROOT/partials/misc/supported-application-servers.adoc
Ticket: DOC-3149
Site: [Staging branch](http://docs-release-771.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* TinyMCE 7.7.1 Release Documentation
Pre-checks:
Review:
=> DOC-3149: TinyMCE 7.7.1 Release Documentation.

modules/ROOT/pages/creating-a-skin.adoc, modules/ROOT/pages/customize-ui.adoc
Ticket: DOC-3156
Site: [Staging branch](http://docs-hotfix-5-doc-3156.staging.tiny.cloud/docs/tinymce/5/creating-a-skin/)
Changes:
* improve documentation for skin creation.
* removal of links to skin.tiny.cloud/5t
Pre-checks:
Review:
=> DOC-3156: Clarify skin creation instructions in UI customization documentation (TinyMCE v5).

modules/ROOT/pages/creating-a-skin.adoc, modules/ROOT/pages/customize-ui.adoc
Ticket: DOC-3154
Site: [Staging branch](http://docs-hotfix-7-doc-3154.staging.tiny.cloud/docs/tinymce/latest/creating-a-skin/)
Changes:
* improve documentation for skin creation.
* removal of links to skin.tiny.cloud/5t
Pre-checks:
Review:
=> DOC-3154: Clarify skin creation instructions in UI customization documentation (TinyMCE v7).

modules/ROOT/examples/live-demos/full-featured/example.js, modules/ROOT/examples/live-demos/full-featured/index.js, modules/ROOT/pages/7.7.0-release-notes.adoc
Ticket: DOC-3153
Site: [Staging branch](http://docs-hotfix-7-doc-3153.staging.tiny.cloud/docs/tinymce/latest/full-featured-premium-demo/)
Changes:
* Remove dark mode detection and set skin to `oxide-dark` in demo examples
* update release notes formatting issue from build `error`
Pre-checks:
Review:
=> DOC-3153: Remove dark mode detection and set skin to `oxide-dark` in demo examples; update release notes formatting issue.

modules/ROOT/examples/live-demos/full-featured/example.js, modules/ROOT/examples/live-demos/full-featured/index.js, modules/ROOT/pages/uploadcare.adoc
Ticket: DOC-3166
Site: [Staging branch](http://docs-hotfix-7-doc-3166.staging.tiny.cloud/docs/tinymce/latest/uploadcare)
Site: [Staging branch: fill feature demo](http://docs-hotfix-7-doc-3166.staging.tiny.cloud/docs/tinymce/latest/full-featured-premium-demo/)
Changes:
* minor copy edits to plugin documentation.
* Remove `skin: 'oxide-dark'` from full feature demo.
Pre-checks:
Review:
=> DOC-3166: Various copy edits and improvements.

modules/ROOT/pages/exportpdf.adoc, modules/ROOT/pages/exportword.adoc, modules/ROOT/pages/importword.adoc, modules/ROOT/partials/configuration/exportpdf_token_provider.adoc, modules/ROOT/partials/configuration/exportword_token_provider.adoc, modules/ROOT/partials/configuration/importword_token_provider.adoc, modules/ROOT/partials/misc/admon-document-converters-jwt-expected-data-structure.adoc, modules/ROOT/partials/misc/admon-jwt-authentication-requirements.adoc
Ticket: DOC-3143
Site: [Staging branch: exportword](http://docs-hotfix-7-doc-3143.staging.tiny.cloud/docs/tinymce/latest/exportword/)
Site: [Staging branch: exportpdf](http://docs-hotfix-7-doc-3143.staging.tiny.cloud/docs/tinymce/latest/exportpdf/)
Site: [Staging branch: importword](http://docs-hotfix-7-doc-3143.staging.tiny.cloud/docs/tinymce/latest/importword/)
Changes:
* Update `Basic setup using the Tiny Cloud service` for each service
* Improved JWT authentication details for the `{pluginname}` plugin, and trial behavior.
* Updated partials, and minor copy edits.
Pre-checks:
Review:
=> DOC-3143: Update key information about trial period behaviour for document converters on Tiny Cloud. 

modules/ROOT/pages/individual-spelling-container.adoc, modules/ROOT/partials/docker/spelling-service/spelling-service-installation.adoc, modules/ROOT/partials/docker/spelling-service/spelling-service-overview.adoc, modules/ROOT/partials/docker/spelling-service/spelling-service-requirements.adoc
Ticket: DOC-3136
Site: [Staging branch](http://docs-hotfix-7-doc-3136.staging.tiny.cloud/docs/tinymce/latest/individual-spelling-container/)
Changes:
* Updated documentation content for Spelling service using Docker (individually licensed) 
Pre-checks:
Review:
=> DOC-3136: Update documentation for Spelling service using Docker (individually licensed)

modules/ROOT/nav.adoc, modules/ROOT/pages/individual-image-proxy-container.adoc, modules/ROOT/partials/docker/image-proxy-service/image-proxy-service-installation.adoc, modules/ROOT/partials/docker/image-proxy-service/image-proxy-service-overview.adoc, modules/ROOT/partials/docker/image-proxy-service/image-proxy-service-requirements.adoc
Ticket: DOC-3135
Site: [Staging branch](http://docs-hotfix-7-doc-3135.staging.tiny.cloud/docs/tinymce/latest/individual-image-proxy-container/)
Changes:
* Added new page for Image Proxy service in the individually licensed plugins section 
* Updated nav.adoc to include a link to the new page 
* Updated documentation content to include new partials 
Pre-checks:
Review:
=> DOC-3135: Update documentation for Image Proxy service using Docker (Individually licensed)

modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-installation-on-premises.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-overview-on-premises.adoc
Ticket: DOC-3165
Site: [Staging branch](http://docs-hotfix-7-doc-3165.staging.tiny.cloud/docs/tinymce/latest/individual-import-from-word-and-export-to-word-on-premises/)
Changes:
* Update Overview section to include Docker login credentials requirement
* Add step for pulling the Docker image in the example scripts 
Pre-checks:
Review:
=> DOC-3165: Update documentation for Import from Word and Export to Word services using Docker (Individually licensed) 

modules/ROOT/partials/individually-licensed-components/export-to-pdf/export-to-pdf-installation.adoc, modules/ROOT/partials/individually-licensed-components/export-to-pdf/export-to-pdf-overview.adoc
Ticket: DOC-3164
Site: [Staging branch](http://docs-hotfix-7-doc-3164.staging.tiny.cloud/docs/tinymce/latest/individual-export-to-pdf-on-premises/)
Changes:
* Update Overview section to include Docker login credentials requirement
* Add step for pulling the Docker image in the example scripts
Pre-checks:
Review:
=> DOC-3164: Update documentation for Export to PDF service using Docker (Individually licensed)

modules/ROOT/pages/7.7.2-release-notes.adoc
Ticket: DOC-3163
Site: [Staging branch](http://docs-feature-772-doc-3163tiny-11763.staging.tiny.cloud/docs/tinymce/latest/7.7.2-release-notes/#deleting-an-empty-block-within-an-li-element-would-move-the-cursor-at-the-end-of-the-li-element)
Changes:
* Documented the bug fix for TINY-11763
Pre-checks:
Review:
=> DOC-3163: Deleting an empty block within `<li>` would move cursor at the end of the `<li>`.

modules/ROOT/pages/7.7.2-release-notes.adoc
Ticket: DOC-3163
Site: [Staging branch](http://docs-feature-772-doc-3163tiny-11797.staging.tiny.cloud/docs/tinymce/latest/7.7.2-release-notes/#exception-occurs-when-pressing-tab-in-the-last-cell-of-a-non-editable-table)
Changes:
* Documented the bug fix for TINY-11797
Pre-checks:
Review:
=> DOC-3163: Exception when pressing tab in the last cell of a non-editable table.

modules/ROOT/pages/7.7.2-release-notes.adoc
Ticket: DOC-3163
Site: [Staging branch](http://docs-feature-772-doc-3163tiny-11781.staging.tiny.cloud/docs/tinymce/latest/7.7.2-release-notes/#exception-was-thrown-when-trying-to-use-the-context-form-api-after-the-toolbar-was-detached)
Changes:
* Documented the bug fix for TINY-11781
Pre-checks:
Review:
=> DOC-3163: Exception was thrown when trying to use context form API after component was detached.

modules/ROOT/nav.adoc, modules/ROOT/pages/7.7.2-release-notes.adoc, modules/ROOT/pages/changelog.adoc
Ticket: DOC-3163
Site: [Staging branch](http://docs-feature-772-doc-3163.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* TinyMCE 7.7.2 Release Documentation and Community Changelog.
Pre-checks:
Review:
=> DOC-3163: TinyMCE 7.7.2 Release Documentation and Community Changelog.

modules/ROOT/nav.adoc, modules/ROOT/pages/7.7.2-release-notes.adoc, modules/ROOT/pages/changelog.adoc, modules/ROOT/pages/release-notes.adoc
Ticket: DOC-3162
Site: [Staging branch](http://docs-release-772.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* TinyMCE 7.7.2 Release Documentation
Pre-checks:
Review:
=> DOC-3162: TinyMCE 7.7.2 Release Documentation

modules/ROOT/partials/configuration/uploadcare_signed_upload_auth_provider.adoc, modules/ROOT/partials/configuration/uploadcare_store_type.adoc
Ticket: DOC-2597
Site: [uploadcare_signed_upload_auth_provider](http://docs-hotfix-7-doc-2597.staging.tiny.cloud/docs/tinymce/latest/uploadcare/#uploadcare-signed-upload-auth-provider)
Site: [uploadcare_store_type](http://docs-hotfix-7-doc-2597.staging.tiny.cloud/docs/tinymce/latest/uploadcare/#uploadcare-store-type)
Changes:
- DOC-2597: Add link to official Uploadcare documentation for Signed Uploads
- DOC-2597: Add admonition with link to Signed Uploads starter project
- DOC-2597: Update description for store type to be more accurate
Pre-checks:
- [-] If this is a minor release, updated `productminorversion` in `antora.yml` and added new supported …
=> DOC-2597: Provide demo for Image Optimizer Signed Uploads option

modules/ROOT/pages/editor-command-identifiers.adoc, modules/ROOT/pages/fullscreen.adoc, modules/ROOT/partials/commands/fullscreen-cmds.adoc, modules/ROOT/partials/configuration/fullscreen_native.adoc, modules/ROOT/partials/index-pages/opensource-plugins.adoc
Ticket: DOC-3172
Site: [Staging branch](http://docs-hotfix-7-doc-3172.staging.tiny.cloud/docs/tinymce/latest/fullscreen/#:~:text=This%20feature%20is%20supported%20only%20when%20TinyMCE%20is%20operating%20in%20classic%20mode.%20It%20is%20not%20supported%20in%20inline%20mode.%20For%20details%20on%20the%20differences%20between%20editing%20modes%2C%20refer%20to%20Classic%20editing%20mode.)
Site: [Opensource plugins](http://docs-hotfix-7-doc-3172.staging.tiny.cloud/docs/tinymce/latest/plugins/#:~:text=Expand%20TinyMCE%20to%20fill%20the%20entire%20screen%20when%20using%20classic%20mode.)
Site: [Fullscreen_native](http://docs-hotfix-7-doc-3172.staging.tiny.cloud/docs/tinymce/latest/fullscreen/#fullscreen_native:~:text=This%20option%20is%20only%20supported%20when%20TinyMCE%20is%20in%20classic%20mo …
=> DOC-3172: Update Full Screen plugin documentation to clarify classic mode requirement.

modules/ROOT/partials/individually-licensed-components/export-to-pdf/export-to-pdf-installation.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-installation-on-premises.adoc
Ticket: DOC-3185
Site: [Deploy the TinyMCE Import from Word and Export to Word service server-side component using Docker (individually licensed)](http://docs-hotfix-7-doc-3185.staging.tiny.cloud/docs/tinymce/latest/individual-import-from-word-and-export-to-word-on-premises/)
Site: [Deploy the TinyMCE Export to PDF service server-side component using Docker (individually licensed)](http://docs-hotfix-7-doc-3185.staging.tiny.cloud/docs/tinymce/latest/individual-export-to-pdf-on-premises/)
Changes:
* Add tip for viewing available Docker image versions and recommend using the `latest` tag in installation guides
Pre-checks:
Review:
=> DOC-3185: Add tips for viewing available Docker image versions and recommend using the `latest` tag in installation guides

modules/ROOT/examples/live-demos/comments-callback/index.js
Ticket: DOC-3188
Site: [Staging branch](http://docs-hotfix-7-doc-3188.staging.tiny.cloud/docs/tinymce/latest/comments-callback-mode/#comments-callback-live-demo/)
Changes:
* Update to use UMD for broader compatibility browser support as previous working URLs stopped working.
Pre-checks:
Review:
=> DOC-3188: Update Polly.js script imports to use UMD for broader browser compatibility

modules/ROOT/examples/live-demos/ai/example.js, modules/ROOT/examples/live-demos/ai/index.js, modules/ROOT/examples/live-demos/comments-callback/index.js, modules/ROOT/examples/live-demos/full-featured/example.js, modules/ROOT/examples/live-demos/full-featured/index.js, modules/ROOT/examples/live-demos/premiumskinsandicons-material-classic/index.html, modules/ROOT/examples/live-demos/premiumskinsandicons-material-outline/index.html, modules/ROOT/pages/ai-azure.adoc, modules/ROOT/pages/ai-gemini.adoc, modules/ROOT/pages/ai-openai.adoc
Ticket: DOC-3188
Site: [full-feature-demo](http://docs-hotfix-7-doc-3188.staging.tiny.cloud/docs/tinymce/latest/full-featured-premium-demo/)
Site: [material-outline-demo](http://docs-hotfix-7-doc-3188.staging.tiny.cloud/docs/tinymce/latest/material-outline-demo/)
Site: [AI-Assistant](http://docs-hotfix-7-doc-3188.staging.tiny.cloud/docs/tinymce/latest/ai/#interactive-example)
Site: [comments-callback-live-demo](http://docs-hotfix-7-doc-3188.staging.tiny.cloud/docs/tinymce/latest/comments-callback-mode/#comments-callback-live-demo)
Changes:
* [UNPKG](https://x.com/unpkg/status/1904454221614739820) now servers all traffic over HTTP/3
* Other [issues](https://github.com/unpkg/unpkg/issues/412)
* We should consider replacement for Pollyjs in the future.
* Update AI-Assistant, Material Outline …
=> DOC-3188: Update various script URLs in live-demos to use `cdn.skypack.dev` and `jsdelivr` for improved reliability.

modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-installation-on-premises.adoc
Ticket: DOC-3196
Site: [Staging branch](http://docs-hotfix-7-doc-3196.staging.tiny.cloud/docs/tinymce/latest/individual-import-from-word-and-export-to-word-on-premises/#:~:text=docker%20login%20%2Du%20tiny%20%2Dp%20%5Baccess%2Dtoken%5D%20registry.containers.tiny.cloud)
Changes:
* FIX duplication error.
Pre-checks:
Review:
=> DOC-3196: Fix typo in Docker pull command for import/export installation instructions.

modules/ROOT/pages/7.8.0-release-notes.adoc
Ticket: DOC-
Site: [Staging branch](http://docs-feature-780-doc-3131tiny-11324.staging.tiny.cloud/docs/tinymce/latest/7.8.0-release-notes/#a-confirmation-dialog-now-appears-when-resolving-conversation-to-match-the-ux-of-deleting-a-conversation)
Changes:
* added change for TINY-11324
Pre-checks:
Review:
=> DOC-3131: A confirmation dialog now appears when resolving conversation to match the UX of deleting a conversation.

modules/ROOT/pages/7.8.0-release-notes.adoc, modules/ROOT/partials/configuration/height.adoc
Site: [release notes](http://docs-feature-780-doc-3131tiny-11108.staging.tiny.cloud/docs/tinymce/latest/7.8.0-release-notes/#setting-editor-height-to-a-pt-or-em-value-was-ignoring-minmax-height-settings)
Site: [height](http://docs-feature-780-doc-3131tiny-11108.staging.tiny.cloud/docs/tinymce/latest/editor-size-options/#height)
Changes:
* add fix documentation for TINY-11108
Pre-checks:
Review:
=> DOC-3131: Setting editor height to a `pt` or `em` value was ignoring min/max height settings.

modules/ROOT/pages/7.8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-780-doc-3131tiny-11830.staging.tiny.cloud/docs/tinymce/latest/7.8.0-release-notes/#the-change-event-was-not-dispatched-when-deleting-a-comment-reply)
Changes:
* add fix documentation for TINY-11830
Pre-checks:
Review:
=> DOC-3131: The `change` event was not dispatched when deleting a comment reply.

modules/ROOT/pages/7.8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-780-doc-3131tiny-11329.staging.tiny.cloud/docs/tinymce/latest/7.8.0-release-notes/#the-focus-outline-was-misaligned-with-the-comment-card-border-after-saving-an-edited-comment)
Changes:
* Documented the improvement for TINY-11329
Pre-checks:
Review:
=> DOC-3131: Focus outline was misaligned with comment card border on saving an edit.

modules/ROOT/pages/7.8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-780-doc-3131tiny-11811.staging.tiny.cloud/docs/tinymce/latest/7.8.0-release-notes/#source-code-editor-was-not-scrolling-to-the-editors-caret-position-in-firefox/)
Changes:
* Documented the bug fix for TINY-11811
Pre-checks:
Review:
=> DOC-3131: Source Code editor was not scrolling to the editor's caret position in Firefox.

modules/ROOT/pages/7.8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-780-doc-3131tiny-11923.staging.tiny.cloud/docs/tinymce/latest/7.8.0-release-notes/#improved-handling-of-relative-urls-using-base_url-configuration-for-export-to-word)
Site: [Staging branch](http://docs-feature-780-doc-3131tiny-11923.staging.tiny.cloud/docs/tinymce/latest/7.8.0-release-notes/#improved-handling-of-relative-urls-using-base_url-configuration-for-export-to-pdf)
Changes:
* <placeholder-text>
Pre-checks:
Review:
=> DOC-11923: Add note on handling of relative URLs with base_url configuration option.

modules/ROOT/pages/7.8.0-release-notes.adoc, modules/ROOT/pages/math.adoc, modules/ROOT/partials/configuration/extended_mathml_attributes.adoc, modules/ROOT/partials/configuration/extended_mathml_elements.adoc
Site: [Staging branch-release notes](http://docs-feature-780-doc-3131tiny-11756.staging.tiny.cloud/docs/tinymce/latest/7.8.0-release-notes/#new-options-for-customizing-allowed-mathml-elements-and-attributes)
Site: [Staging branch-#extended-mathml-elements](http://docs-feature-780-doc-3131tiny-11756.staging.tiny.cloud/docs/tinymce/latest/math/#extended-mathml-elements)
Site: [Staging branch-#extended-mathml-attributes](http://docs-feature-780-doc-3131tiny-11756.staging.tiny.cloud/docs/tinymce/latest/math/#extended-mathml-attributes)
Changes:
* <placeholder-text>
Pre-checks:
Review:
=> DOC-3189: Add new options for preserving MathML elements and attributes in the Math plugin

modules/ROOT/nav.adoc, modules/ROOT/pages/initial-configuration.adoc, modules/ROOT/pages/promotions.adoc, modules/ROOT/partials/configuration/onboarding.adoc, modules/ROOT/partials/configuration/promotion.adoc, modules/ROOT/partials/misc/premium-upgrade-promotion-option.adoc
Site: [Staging branch](http://docs-feature-780-doc-3131doc-3191.staging.tiny.cloud/docs/tinymce/latest/promotions/)
Changes:
* Refactor promotion documentation and update references to new promotions page.
* Re-name previous page to align with changes.
Pre-checks:
Review:
=> DOC-3189: Refactor promotion documentation and update references to new promotions page

modules/ROOT/pages/7.8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-780-doc-3131tiny-11761.staging.tiny.cloud/docs/tinymce/latest/7.8.0-release-notes/#non-uploadcare-image-urls-would-be-altered-by-color-adjustments-even-when-they-failed-to-upload)
Changes:
* fix documentation for TINY-11761
Pre-checks:
Review:
=> DOC-3131: Non-uploadcare image URLs would be altered by color adjustments even when they failed to upload.

modules/ROOT/pages/7.8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-780-doc-3131tiny-11842.staging.tiny.cloud/docs/tinymce/latest/7.8.0-release-notes/#it-wasnt-possible-to-add-comments-to-selected-footnotes-elements)
Changes:
* added fix for TINY-11842
Pre-checks:
Review:
=> DOC-3131: It wasn't possible to add comments to selected footnotes elements.

modules/ROOT/pages/7.7.0-release-notes.adoc, modules/ROOT/pages/7.8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-780-doc-3131tiny-11732.staging.tiny.cloud/docs/tinymce/latest/7.8.0-release-notes/#the-tooltip-for-the-blockquote-button-was-not-translated-in-hebrew)
Changes:
* Documented the bug fix for TINY-11732
Pre-checks:
Review:
=> DOC-3131: The tooltip for the `blockquote` button was not translated in Hebrew.

modules/ROOT/pages/7.8.0-release-notes.adoc, modules/ROOT/partials/misc/premium-upgrade-promotion-option.adoc
Ticket: DOC-3198
Site: [promotions](http://docs-hotfix-7-doc-3198.staging.tiny.cloud/docs/tinymce/latest/promotions/)
Site: [content-appearance/#onboarding](http://docs-hotfix-7-doc-3198.staging.tiny.cloud/docs/tinymce/latest/content-appearance/#onboarding)
Site: [customize-ui/#onboarding](http://docs-hotfix-7-doc-3198.staging.tiny.cloud/docs/tinymce/latest/customize-ui/#onboarding)
Site: [7.8.0 Release notes](http://docs-hotfix-7-doc-3198.staging.tiny.cloud/docs/tinymce/latest/7.8.0-release-notes/#overview)
Changes:
* Hide inclusion of new `onboarding` UI until re-launch.
Pre-checks:
Review:
=> DOC-3198: Omit onboarding UI from promotions page.

modules/ROOT/examples/live-demos/uploadcare/index.js, modules/ROOT/partials/configuration/uploadcare_filters.adoc
Ticket: DOC-3199
Site: [Updated demo](http://docs-hotfix-7-doc-3199.staging.tiny.cloud/docs/tinymce/latest/uploadcare/#interactive-example)
Site: [{name: 'none'} explanation](http://docs-hotfix-7-doc-3199.staging.tiny.cloud/docs/tinymce/latest/uploadcare/#example-setting-uploadcare_filters) - The explanation is in the **Important** section.
Changes:
* Updated the demo to have 9 filter options including the `{name: 'none'}` option.
* Added an explanation about `{name: 'none'}` option and what happens if this option is not set during setup.
Pre-checks:
Review:
=> DOC-3199: Fixed Image Optimizer filters in the demo.

modules/ROOT/partials/integrations/blazor-tech-ref.adoc
Ticket: DOC-3205
Site: [Staging branch](http://docs-hotfix-7-doc-3205.staging.tiny.cloud/docs/tinymce/7/)
Changes:
* Adds docs for the new Readonly property and the change to how the Disable works.
Pre-checks:
Review:
=> DOC-3205: Update docs with Blazor changes

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-12061.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#spellchecking-with-a-language-that-does-not-match-the-content-no-longer-overloads-the-spelling-server)
Changes:
* Documentation fix for TINY-12061
Pre-checks:
Review:
=> DOC-3151: Spellchecking with a language that does not match the content no longer overloads the spelling server.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-11876.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#removed-deprecated-css-media-selector-ms-high-contrast)
Changes:
* fix documentation for TINY-11876
Pre-checks:
Review:
=> DOC-3151: Removed deprecated CSS media selector -ms-high-contrast.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-11676.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#pressing-enter-before-a-floating-image-sometimes-duplicated-the-image)
Changes:
* Documented the bug fix for TINY-11676.
Pre-checks:
Review:
=> DOC-3151: Pressing `enter` before a floating image sometimes duplicated the image.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-11997.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#tabbing-inside-a-figcaption-element-no-longer-shows-two-text-insertion-carets)
Changes:
* fix documentation for TINY-11997
Pre-checks:
Review:
=> DOC-3151: Tabbing inside a `figcaption` element no longer shows two text insertion carets.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-11963.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#aspect-ratio-was-not-properly-calculated-when-uploading-images-wider-than-the-editor)
Changes:
* fix documentation for TINY-11963
Pre-checks:
Review:
=> DOC-3151: Aspect ratio was not properly calculated when uploading images wider than the editor.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-11368.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#inline-dialog-dropdowns-reposition-when-the-dialog-is-dragged-or-the-window-is-scrolled)
Changes:
* Fix documentation for TINY-11368 including (TINY-11823 & TINY-11832) as child tickets.
Pre-checks:
Review:
=> DOC-3151: Inline dialog dropdowns reposition when the dialog is dragged or the window is scrolled.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-11560.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#changed-word-capture-regular-expression-for-abbreviations-to-allow-larger-abbreviations)
Changes:
* Documented the bug fix for TINY-11560.
Pre-checks:
Review:
=> DOC-3151: Changed word-capture regex for abbreviations to allow larger abbreviations.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-11549.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#the-toolbar-did-not-always-account-for-the-full-available-space-during-horizontal-scrolling)
Changes:
* Documented the bug fix for TINY-11549.
Pre-checks:
Review:
=> DOC-3151: the toolbar did not consider the entire space in some cases if there was a horizontal scroll.

modules/ROOT/images/icons/list-bull-circle.svg, modules/ROOT/images/icons/list-bull-default.svg, modules/ROOT/images/icons/list-bull-disc.svg, modules/ROOT/images/icons/list-bull-square.svg, modules/ROOT/partials/configuration/icon_list.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-12014.staging.tiny.cloud/docs/tinymce/latest/editor-icon-identifiers/#:~:text=list%2Dbull%2Ddefault,bull%2Ddisc.svg)
Changes:
* Update default list icons with new asset files to support TINY-12014 changes.
Pre-checks:
Review:
=> DOC-3151: Update default list icons with new asset files.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-12036.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#resize-cursor-is-now-the-correct-direction-for-each-resize-mode)
Changes:
* Improvement for TINY-12036 and GH-10189
Pre-checks:
Review:
=> DOC-3151: Resize cursor is now the correct direction for each resize mode.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-11916.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Add change documentation for TINY-11916
Pre-checks:
Review:
=> DOC-3151: `ContextFormSizeInput` lock button has been repositioned beteen the "width" and "height" inputs.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-12041.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#spelling-autocorrect)
Changes:
* Documentation improvement for TINY-12041
Pre-checks:
Review:
=> DOC-3151: Spelling Autocorrect no longer requires the spelling service.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-12005.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#if-style_formats-is-empty-the-button-is-now-disabled)
Changes:
* fix documentation for TINY-12005
Pre-checks:
Review:
=> DOC-3151: If `style_formats` is empty the button is now disabled.

modules/ROOT/pages/export.adoc
Ticket: DOC-3197
Site: [Staging branch](http://docs-feature-5-doc-3197.staging.tiny.cloud/docs/tinymce/5/)
Changes:
* DOC-3197
Pre-checks:
Review:
=> DOC-3197: mark export plugin as deprecated

modules/ROOT/pages/use-tinymce-inline.adoc
Ticket: DOC-2594
Changes:
* Remove admonition for `not supported on mobile devices`.
Pre-checks:
Review:
=> DOC-2594: Remove admonition statement in `tinymce/7` docs about inline editing mode not supported on mobile devices.

modules/ROOT/pages/use-tinymce-inline.adoc
Ticket: DOC-2594
Changes:
* Remove admonition for `not supported on mobile devices`.
Pre-checks:
Review:
=> DOC-2594: Remove admonition statement in `tinymce/6` about inline editing mode not supported on mobile devices.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-11363.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#japanese-keyboard-could-insert-content-while-the-editor-was-in-readonly-mode)
Changes:
* Documented the bug fix for TINY-11363.
Pre-checks:
Review:
=> DOC-3151: Japanese keyboard could insert content while the editor was in `readonly` mode

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-11836.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#autolink-behavior-updated-to-preserve-existing-links)
Changes:
* fix documentation for TINY-11836
Pre-checks:
Review:
=> DOC-3151: Autolink behavior updated to preserve existing links.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-12015.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Add addition and improvement for TINY-12015
* Note: updates to icons ext will be done in seperate PR.
Pre-checks:
Review:
=> DOC-3151: Added new disc style option for unordered lists.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-11981.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#table-resizers-are-now-visible-when-inline-editor-has-a-z-index-property)
Changes:
* add fix documentation for TINY-11981
Pre-checks:
Review:
=> DOC-3151: Table resizer's are now visible when inline editor has a `z-index` property

modules/ROOT/pages/7.7.0-release-notes.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-autorization-on-premises.adoc
Ticket: DOC-3152
Site: [7.7.0 Release Docs](http://docs-hotfix-7-doc-3152.staging.tiny.cloud/docs/tinymce/latest/7.7.0-release-notes/#known-issues)
Site: [Import From Word and Export to Word Docker docs](http://docs-hotfix-7-doc-3152.staging.tiny.cloud/docs/tinymce/latest/individual-import-from-word-and-export-to-word-on-premises/#authorization)
Changes:
* In the 7.7.0 docs known issues section, fixed the following typo: "There one known issue in TinyMCE 7.7.0." to "There **is** one known issue in TinyMCE 7.7.0.""
* In the Import from Word and Export to Word Docker docs authorization NOTE section, fixed the following typo: ""However, this it is not recommend to skip the authorization when running Import from Word and Export to Word On-Premises in a public network."" to ""However, **it is …
=> DOC-3152: Fixed typos in 7.7.0 release docs and import/export word docker setup docs.

modules/ROOT/pages/7.9.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-11953.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#the-mceinsertcontent-command-could-delete-the-parent-block-element-when-an-anchor-was-selected)
Changes:
* fix documentation for TINY-11953
Pre-checks:
Review:
=> DOC-3151: The `mceInsertContent` command could delete the parent block element when an anchor was selected.

antora.yml, modules/ROOT/partials/integrations/jquery-quick-start.adoc
Ticket: DOC-3183
Site: [Staging branch](http://docs-hotfix-7-doc-3183.staging.tiny.cloud/docs/tinymce/latest/jquery-cloud/)
Changes:
* Updated `jquery_url` attribute in the `antora.yml` file with the url that points to the latest stable version of `tinymce-jquery`.
* Included `license_key` and `api_key` in the examples
Pre-checks:
Review:
=> DOC-3183: Updated jQuery integration quick start documentation.

antora.yml, modules/ROOT/examples/live-demos/web-component/index.js, modules/ROOT/partials/integrations/webcomponent-quick-start.adoc, modules/ROOT/partials/integrations/webcomponent-tech-ref.adoc
Ticket: DOC-3180
Site: [Staging branch](http://docs-hotfix-7-doc-3180.staging.tiny.cloud/docs/tinymce/latest/)
Changes:
* Updated the web component integration docs
* Removed the version in the src url so the examples/demos always fetch the latest tinymce webcomponent
* Removed the live demos on self hosted pages because their example code is not correct
* Grouped powerpaste applicable settings
Pre-checks:
Review:
=> DOC-3180: Update the web component integration doc pages

modules/ROOT/partials/integrations/svelte-quick-start.adoc, modules/ROOT/partials/integrations/svelte-tech-ref.adoc
Ticket: DOC-3184
Support: TINY-11856
Site: [Staging branch](http://docs-hotfix-7-doc-3184.staging.tiny.cloud/docs/tinymce/latest/svelte-cloud/)
Site: [Staging branch](http://docs-hotfix-7-doc-3184.staging.tiny.cloud/docs/tinymce/latest/svelte-pm/)
Site: [Staging branch](http://docs-hotfix-7-doc-3184.staging.tiny.cloud/docs/tinymce/latest/svelte-zip/)
Changes:
Pre-checks:
Review:
=> DOC-3184: Update Svelte public documentation.

modules/ROOT/partials/integrations/blazor-postinstall.adoc, modules/ROOT/partials/integrations/blazor-quick-start.adoc, modules/ROOT/partials/integrations/blazor-tech-ref.adoc
Ticket: DOC-3186
Site: [Staging branch](http://docs-hotfix-7-doc-3186.staging.tiny.cloud/docs/tinymce/latest/)
Site: [blazor-cloud](http://docs-hotfix-7-doc-3186.staging.tiny.cloud/docs/tinymce/latest/blazor-cloud/)
Site: [blazor-pm](http://docs-hotfix-7-doc-3186.staging.tiny.cloud/docs/tinymce/latest/blazor-pm/)
Site: [blazor-zip](http://docs-hotfix-7-doc-3186.staging.tiny.cloud/docs/tinymce/latest/blazor-zip/)
Changes:
* Update installation instruction to use Blazor Web App template for .NET 8 
* Add VS Code installation instruction 
* Add instruction for including TinyMCE Zip in self-hosted guide 
Pre-checks:
Review:
=> DOC-3186: Update Blazor public documentation

modules/ROOT/partials/integrations/angular-quick-start.adoc, modules/ROOT/partials/integrations/angular-tech-ref.adoc
Ticket: DOC-3182
Site: [Staging branch](http://docs-hotfix-7-doc-3182.staging.tiny.cloud/docs/tinymce/latest/)
Site: [angular-cloud/](http://docs-hotfix-7-doc-3182.staging.tiny.cloud/docs/tinymce/latest/angular-cloud/)
Site: [angular-ref/](http://docs-hotfix-7-doc-3182.staging.tiny.cloud/docs/tinymce/latest/angular-ref/)
Site: [angular-pm](http://docs-hotfix-7-doc-3182.staging.tiny.cloud/docs/tinymce/latest/angular-pm/)
Site: [angular-zip/](http://docs-hotfix-7-doc-3182.staging.tiny.cloud/docs/tinymce/latest/angular-zip/)
Changes:
*  update angular integration docs
Pre-checks:
Review:
=> DOC-3182: update angular integration docs

modules/ROOT/pages/7.9.0-release-notes.adoc, modules/ROOT/pages/changelog.adoc
Site: [Staging branch](http://docs-feature-790-doc-3151tiny-12131.staging.tiny.cloud/docs/tinymce/latest/7.9.0-release-notes/#select-ui-elements-was-not-properly-styled-on-chrome-version-136)
Changes:
* added fix documentation for TINY-12131
* included changelog entry also.
Pre-checks:
Review:
=> DOC-3151: Select UI elements was not properly styled on Chrome version 136.

modules/ROOT/partials/integrations/angular-tech-ref.adoc
Ticket: TINY-11907
Site: [Staging branch](http://docs-hotfix-7-tiny-11907.staging.tiny.cloud/docs/tinymce/latest/angular-ref/#readonly)
Changes:
* update documentation to include new `readonly` prop for integrations wrapper.
Pre-checks:
Review:
=> TINY-11907: Add new `readonly` prop to Angular integration.

modules/ROOT/partials/integrations/vue-tech-ref.adoc
Ticket: TINY-11908
Site: [Staging branch](http://docs-hotfix-7-tiny-11908.staging.tiny.cloud/docs/tinymce/latest/vue-ref/#readonly)
Changes:
* Update documentation to include new `readonly` prop for integrations wrapper.
Pre-checks:
Review:
=> TINY-11908: Add new `readonly` prop to Vue integration.

antora-playbook.yml
Ticket: DOC-3218
Site: [Staging branch](http://docs-feature-5-doc-3218updatev8.staging.tiny.cloud/docs/tinymce/5/)
Changes:
* add `tinymce/8` to `antora-playbook.yml` file.
Pre-checks:
Review:
=> DOC-3218: Add `tinymce/8` to `antora-playbook.yml` file for v5

antora-playbook.yml, modules/ROOT/partials/integrations/blazor-quick-start.adoc, modules/ROOT/partials/integrations/vue-quick-start.adoc
Ticket: DOC-3218
Site: [Staging branch](http://docs-feature-8-doc-3218updatev8.staging.tiny.cloud/docs/tinymce/7/)
Changes:
* Update `antora-playbook.yml` to include `tinymce/8` branch.
* Fix console errors.
Pre-checks:
Review:
=> DOC-3218: Add `tinymce/8` to `antora-playbook.yml` file for v7

modules/ROOT/pages/exportpdf.adoc, modules/ROOT/pages/exportword.adoc, modules/ROOT/pages/importword.adoc, modules/ROOT/pages/migration-from-4x.adoc, modules/ROOT/pages/migration-from-5x.adoc, modules/ROOT/partials/misc/admon-jwt-authentication-requirements.adoc
Ticket: DOC-3227
Site: [Export Word](http://docs-hotfix-7-doc-3227.staging.tiny.cloud/docs/tinymce/7/exportword/)
Site: [Export PDF](http://docs-hotfix-7-doc-3227.staging.tiny.cloud/docs/tinymce/7/exportpdf/)
Site: [Import Word](http://docs-hotfix-7-doc-3227.staging.tiny.cloud/docs/tinymce/7/importword/)
Changes:
Behavioral Changes:
- Old behavior: JWT authentication caused errors during the trial and was not required.
- Updated to suite new behavior: JWT authentication is allowed and recommended during the trial for full functionality.
- Introduced a distinction between using the plugin with vs without JWT and with vs without a valid add-on entitlement.
New Additions:
- A clear instruction to create a JWT key via the Customer Portal.
- A direct link to the portal to simplify setup for …
=> DOC-3227: Update Document Converter JWT authentication requirements and plugin descriptions.

modules/ROOT/partials/individually-licensed-components/export-to-pdf/export-to-pdf-installation.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-installation-on-premises.adoc
Ticket: DOC-3240
Site: [Export to PDF](http://docs-hotfix-7-doc-3240.staging.tiny.cloud/docs/tinymce/7/individual-export-to-pdf-on-premises/#:~:text=docker%20pull%20registry.containers.tiny.cloud/pdf%2Dconverter%2Dtiny%3A%5Bversion%5D)
Site: [Import from word and Export to word](http://docs-hotfix-7-doc-3240.staging.tiny.cloud/docs/tinymce/7/individual-import-from-word-and-export-to-word-on-premises/#:~:text=docker%20pull%20registry.containers.tiny.cloud/docx%2Dconverter%2Dtiny%3A%5Bversion%5D)
Changes:
* Fix based on Slack Thread
Pre-checks:
Review:
=> DOC-3240: Remove registry URL from Docker pull commands in installation guides for export-to-pdf and import-from-word components.

modules/ROOT/pages/8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-800-doc-3147tiny-11912.staging.tiny.cloud/docs/tinymce/latest/8.0-release-notes/#decorative-images-would-lose-their-decorative-status-when-the-alt-subtoolbar-was-closed-when-using-the-apply-button)
Changes:
* Documented the bug fix for TINY-11912
Pre-checks:
Review:
=> DOC-3147: Decorative images would lose their decorative properties when the  subtoolbar was closed using the confirmation button.

modules/ROOT/pages/8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-800-doc-3147tiny-11893.staging.tiny.cloud/docs/tinymce/latest/8.0-release-notes/#word-import-of-lists-with-a-lighter-level-failed-parsing)
Changes:
* Added fix documentation for TINY-11893
Pre-checks:
Review:
=> DOC-3147: Word import of lists with a lighter level failed parsing.

modules/ROOT/pages/8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-800-doc-3147tiny-11982.staging.tiny.cloud/docs/tinymce/latest/8.0-release-notes/#it-was-not-possible-to-navigate-out-of-a-figcaption-using-the-left-and-right-arrow-keys-in-firefox)
Changes:
* Documented the bug fix for TINY-11982
Pre-checks:
Review:
=> DOC-3147: It wasn't possible to navigate out of a `figcaption` using the left and right arrow keys in Firefox.

modules/ROOT/pages/8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-800-doc-3147tiny-11421.staging.tiny.cloud/docs/tinymce/latest/8.0-release-notes/#resize-handles-are-more-accessible-with-role-and-aria-valuetext-attributes)
Changes:
* Documented the improvement for TINY-11421.
Pre-checks:
Review:
=> DOC-3147: Resize handles are more accessible with `role` and `aria-valuetext` attributes.

modules/ROOT/pages/8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-800-doc-3147tiny-12125.staging.tiny.cloud/docs/tinymce/latest/8.0-release-notes/#toolbar-drawer-now-closes-when-the-editor-loses-focus)
Changes:
* Documented the bug fix for TINY-12125.
Pre-checks:
Review:
=> DOC-3147: Toolbar drawer now closes when the editor loses focus.

modules/ROOT/pages/8.0-release-notes.adoc, modules/ROOT/partials/configuration/pagebreak_separator.adoc
* Release Note: [Release Note](http://docs-feature-800-doc-3147tiny-12013.staging.tiny.cloud/docs/tinymce/latest/8.0-release-notes/#changed-the-default-value-for-the-pagebreak_separator-option)
* Default value change: [Default Value](http://docs-feature-800-doc-3147tiny-12013.staging.tiny.cloud/docs/tinymce/latest/pagebreak/#pagebreak_separator)
Changes:
* Documented the change described in TINY-12013
Pre-checks:
Review:
=> DOC-3147: Default value for `pagebreak_separator` option to better suit modern standards.

modules/ROOT/pages/8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-800-doc-3147tiny-12118.staging.tiny.cloud/docs/tinymce/latest/8.0-release-notes/#in-inline-mode-pressing-the-back-button-dismissed-the-context-toolbar-and-moved-focus-from-the-selected-image-to-the-editor)
Changes:
* Documented the bug fix for TINY-12118
Pre-checks:
Review:
=> The `contextform` subtoolbar is no longer dismissed when using the back button in inline editors.

modules/ROOT/pages/8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-800-doc-3147tiny-12182.staging.tiny.cloud/docs/tinymce/latest/8.0-release-notes/#removed-undocumented-documentbaseurl-property-from-editor-instances-documentbaseuri-is-the-supported-property-now)
Changes:
* Removed undocumented `documentBaseUrl` property from Editor instances for TINY-12182
Pre-checks:
Review:
=> DOC-3147: Removed undocumented `documentBaseUrl` property from Editor instances. `documentBaseURI` is the supported property now.

modules/ROOT/pages/8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-800-doc-3147tiny-12004.staging.tiny.cloud/docs/tinymce/latest/8.0-release-notes/#strikethrough-format-could-be-added-outside-font-size-format-which-renders-incorrectly-in-some-browsers)
Changes:
* Fix documentation for TINY-12004
Pre-checks:
Review:
=> DOC-3147: Strikethrough format could be added outside font size format, which renders incorrectly in some browsers.

modules/ROOT/pages/8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-800-doc-3147tiny-11692.staging.tiny.cloud/docs/tinymce/latest/8.0-release-notes/#deprecated-editor-selection-setcontent-api)
Changes:
* Fix for TINY-11692
Pre-checks:
Review:
=> DOC-3147: Deprecated `editor.selection.setContent` API

modules/ROOT/pages/8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-800-doc-3147tiny-11884.staging.tiny.cloud/docs/tinymce/latest/8.0-release-notes/#long-tooltips-could-overflow-narrow-browser-windows)
Changes:
* Add fix documentation for TINY-11884
Pre-checks:
Review:
=> DOC-3147: Long tooltips could overflow narrow browser windows.

modules/ROOT/pages/8.0-release-notes.adoc
Site: [Staging branch](http://docs-feature-800-doc-3147tiny-12018.staging.tiny.cloud/docs/tinymce/latest/8.0-release-notes/#tab-to-create-a-new-row-in-tables-with-a-non-editable-final-row-would-freeze-the-editor)
Changes:
* Fix documentation for TINY-12018
Pre-checks:
Review:
=> DOC-3147: Tab to create a new row in tables with a non-editable final row would freeze the editor.

antora.yml, modules/ROOT/pages/exportpdf.adoc, modules/ROOT/pages/exportword.adoc, modules/ROOT/pages/importword.adoc, modules/ROOT/pages/understanding-editor-loads.adoc, modules/ROOT/partials/individually-licensed-components/export-to-pdf/export-to-pdf-installation.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-autorization-on-premises.adoc, modules/ROOT/partials/individually-licensed-components/import-from-word-and-export-to-word/import-from-word-and-export-to-word-installation-on-premises.adoc, modules/ROOT/partials/integrations/angular-tech-ref.adoc, modules/ROOT/partials/integrations/react-tech-ref.adoc, modules/ROOT/partials/integrations/svelte-tech-ref.adoc, modules/ROOT/partials/integrations/vue-tech-ref.adoc, modules/ROOT/partials/integrations/webcomponent-tech-ref.adoc, modules/ROOT/partials/misc/admon-jwt-authentication-requirements.adoc
Ticket: DOC-3228
Changes:
* using `git log tinymce/7 ^tinymce/8 --oneline` to compare branches for missing commits- less the ones we want to be omitted from the `v8` docs.
- [dc450da](https://github.com/tinymce/tinymce-docs/pull/3754/commits/dc450dabc701ad5473f64ca487cbc309031f931b)
- [af9b478](https://github.com/tinymce/tinymce-docs/pull/3754/commits/af9b4789c60a2df3ee188aea146c9312f0b6384b)
- [bfbf03f](https://github.com/tinymce/tinymce-docs/pull/3754/commits/bfbf03f9f71e6c72eed99827c46f5a0f69064a4e)
- [a76c253](https://github.com/tinymce/tinymce-docs/pull/3754/commits/a76c2533864dfe70ef3eacca656ef6900d3568c5)
- [bfc3a11](https://github.com/tinymce/tinymce-docs/pull/3754/commits/bfc3a1102e4d4a834bb83c4d30653afe6912996c)
- [ae55c31](https://github.com/tinymce/tinymce-docs/pull/3754/commit …
=> DOC-3228: Cherry pick `tinymce/7` latest changes into `tinymce/8 >> release/8.0.0` branch.

modules/ROOT/pages/8.0-release-notes.adoc, modules/ROOT/pages/license-key.adoc, modules/ROOT/pages/vite-es6-npm.adoc, modules/ROOT/partials/install/basic-quickstart-base.adoc, modules/ROOT/partials/integrations/angular-tech-ref.adoc, modules/ROOT/partials/integrations/blazor-postinstall.adoc, modules/ROOT/partials/integrations/blazor-tech-ref.adoc, modules/ROOT/partials/integrations/common/license-key-property.adoc, modules/ROOT/partials/integrations/jquery-quick-start.adoc, modules/ROOT/partials/integrations/react-bundling.adoc, modules/ROOT/partials/integrations/react-quick-start.adoc, modules/ROOT/partials/integrations/react-tech-ref.adoc, modules/ROOT/partials/integrations/svelte-quick-start.adoc, modules/ROOT/partials/integrations/svelte-tech-ref.adoc, modules/ROOT/partials/integrations/vue-quick-start.adoc, modules/ROOT/partials/integrations/vue-tech-ref.adoc, modules/ROOT/partials/integrations/webcomponent-quick-start.adoc, modules/ROOT/partials/integrations/webcomponent-tech-ref.adoc, modules/ROOT/partials/misc/setting-the-license.adoc, modules/ROOT/partials/module-loading/bundling-vite-es6-npm_editor.adoc
Ticket: DOC-3226
Parent: DOC-3147
Support: EPIC-225
Site: [Release notes-IMPORTANT](http://docs-feature-800-doc-3147doc-3226.staging.tiny.cloud/docs/tinymce/latest/8.0-release-notes/#overview:~:text=This%20release%20includes%20breaking%20changes%20to%20the%20license%20key%20system.%20All%20commercial%20self%2Dhosted%20deployments%20must%20update%20their%20license%20keys%20to%20use%20the%20new%20T8LK%3A%20prefix%20format.%20For%20details%20on%20this%20and%20other%20breaking%20changes%20when%20considering%20upgrading%2C%20see%20Migrating%20from%20TinyMCE%207%20to%20TinyMCE%208.0.0.)
Site: [Release notes- Changes](http://docs-feature-800-doc-3147doc-3226.staging.tiny.cloud/docs/tinymce/latest/8.0-release-notes/#enhanced-license-key-system-with-t8lk-prefix)
Site: …
=> DOC-3226: Update licensing information and examples for TinyMCE 8

CONTRIBUTING.md
Ticket: DOC-3221
Changes:
Pre-checks:
Review:
=> DOC-3221: Refine language and structure in `CONTRIBUTING.md` for clarity and consistency.

modules/ROOT/pages/license-key.adoc
Ticket: DOC-3248
Changes:
* Fix missing space in in license-key.adoc page.
Pre-checks:
Review:
=> DOC-3248: Fix missing space in in license-key.adoc page.
